# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: telegram
type: Opaque
stringData:
  BOT_TOKEN: ENC[AES256_GCM,data:BiPXZoUUa2a15+BlFYFkyiIrQDcp/Is5BA3zSkKpjUrvMxB5SxBcHS2FU0zU,iv:jSxP84ZRqsSS0lC3ZjNbw87LE8TNQBhHo9whOrwNWMA=,tag:lD8Xs31gyBDzDJH4ayOs5Q==,type:str]
sops:
  age:
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGl6a3ludDBV
        SDRzdzM2VFBGVHFYdGRjUXI3MVJBbnZBcldwY01TZEl0YktLNjhwaXBSSEpmR3lW
        czNXS3NUeDM3TTRNdi9MMUppM2IvRFNvcHBRTFhVbC94aEJIWHZ5K09QWVVDSnZS
        UzBTSFFpNE5QVUlZVWdGNVpDcnZRUjZ0eWJUSDAwY0IyR2tKSTJZNTVXMjJ3cVhk
        dGNzbzJlZjY3SmIvZ3BlbGxZMWp1S2dUTmp4RndreXB2NjRHTTN5dXFNOFR3QkJq
        WSt2RkdJWUIyYU9BYURpaUZXVWExcGdOSHpEUWVZR2p4TGw3KysvR0REekd5R0Rs
        TW1sVndOVW9XVXRmYnhtZWxMbThzVXpjd1pPQTUwcFd3QVFFdG43alhvekZaSzlT
        dURrZUJQWTFGbzlzKy9NbjRHYVNRYmNJaUJLRUpuT3dIR1VtZndrYVRLY0VpdEtF
        a0huT090RkJQUWhvNmw3R2tta09BbVlTcEVwWVdSOVdrblJ1M21xU2R6VmZXNG05
        SXM3YlBzanFha1JFamFuN3BWQkhTVUc0SEJrYXZUK29hajJ1TDZFMjdOQlBxTGNh
        dHJkLzljUmc4WVhxRVIvVGowYjNqa3YxaG10b1MrMC9sNmhFbUt3S0tBbmd1YnNt
        S3NyMTBCTDgrVUxJK3Voc0RuVGV6R2ZwUkk4cWlLKy9DRnUrOW54NzI3OVBUMGhX
        U21BYXB2YUhoTFY5VGVJTE5CNzMxYjRRNXRoRktEQkNwSlJFKzk2SWJSa2E2blNT
        MFBkUXdtdDEybWI2aTFNNTk2ckE0cHlVTmZLVnVDS2tBbllRbkMvN3k4WUczTXpY
        cFNyVXFUNThSUWJKVUNHeWR5ZUJZcndlT0ROcGMyQkU5QWt0RVRxdThPUnkyUmQr
        a0FldzF3UkhITEx5eEVWMW5LZTJuLzd1WGRPRXFkeThXeXZYV1prVVBob0NvQjV5
        dzNIa2Vod204M3dFeVBzcm5FZy8zVkltbnJvbzBzTENheTVFWnh0NTZEbFF3L25s
        cWhwZVNqaUJ2alBST2RnU0F0WWxsd3R0QjlqcFJUeUdjUFFPYnNNOUxLbk00Tk96
        eU5DY1hYRUtxU1Y4N1JWMFFGWStENjE1RGRTSXpYVDhpUFBnRzNhRkI1WStYdkU4
        U3VCREVKODNrWm9udjY1SzVkc3FFWTYzblhsenlpV3lTYW5QUThYVy81c3E4bG02
        WE5mNFlaMEJ5bzVRUTVIVHRxVHhMaFFaQ2F3L0YrWmlKcklRa3V2K1NONmJ3SmFQ
        R2liL0MxV2w0YzNtNlpOQjdydERGTFpSeFYyaTFIYVdsR3hJU2ZjbzBSbHAxRWsy
        Ni9qR2F3RVdXdVE4RFF6TmFWVEdGQlV4eVMwZ0xLUTRvZUp4bGhsNkhMaWFRTURq
        bUdpU2IxTWE0NFBVZmFEcjFTTFFiNWtVd0p6S2ZCRHR2Y1BHUDFWa252Y01ra3RH
        U2JqUjRHTktxQk9pZDJGTlBHN0Q4cjVCemFuK2tuQldGMkdTaFk2UGZmeWVTbng4
        RWlxT1phY1dKNlRIQXVGUUZ3OGZDaWEwaUE5NTczdU53R2FKem4xejNkeVI3WCsy
        VGc3clF1VnFFRUJvWFk1ckIzWTlqQXFlOVFWR2dqYzdhWlVqQVdvRk1SNC9CK3pW
        N0p5dXRBNWZBdlYvTkV1NFIxUlhmQUVyeTNJSWVYc2dUTndjSmxKaEtnM0pZdUUr
        d0V3bEswVklnYzFpZStRc3F6ZXo2dXJoTGhZNnNKK0ZPQlNNY1UvcUhjSkM1bWEy
        UmVTVDF4TC94SGFiVUsxVFZwSm8zZGRXZkE4MThmeTBsamRndzh2djZlWXNPZ2xN
        MXlrYkFCdHJlQVVqMkJhTE9zVFFQeStvcTN3ZHQ4MWYyYmQzblZ3QzRta200aGw0
        Z0M2Sm5OdEw3WU1HTFA4T3dBQjNVVmY0U1ZHalB6VlloZEllOXBwT1IvMFVmZwpS
        Rk5acWxpaUI5d2NERmdVRllXZ2VGZFhrb0s4am94VVRsN2VjU3ZSUFEwCi0tLSBm
        YWhkUFVWblVNVlBLTzZGY0llaU5kaXpib0RyRTJ3M1FYdTVOT1N5RFN3Ck+9RYit
        VmAjkx04KhOk/SUZeE2YGTyKC1zZDa5uzCHD2lh7vlFSl+zqtXNO5K0/8bvotoy5
        14hGRcf1PqNK5EU=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T20:44:49Z"
  mac: ENC[AES256_GCM,data:3DxgzsqPZx1Lt75mqiJogzeq+De6a5iypiAfhfcmumcOBY5neCJ4ZxG5CQIeMJstduZdyRigoZXpHINtzKQD941kQCRNbJsPQOw/SFwokfzRfNV+MUYtADH3uILllXGjKjO+QMxvnMUL/v7iRhqhKoCtf2QYuR5qGqWQXEpEDQw=,iv:LpMrD7dKlQjgsAjxFZ8LISk0bjLrOvi695w8OxwigEc=,tag:2jtM93/O9lLLMPU52uCGrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
