# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: telegram
type: Opaque
stringData:
  BOT_TOKEN: ENC[AES256_GCM,data:BiPXZoUUa2a15+BlFYFkyiIrQDcp/Is5BA3zSkKpjUrvMxB5SxBcHS2FU0zU,iv:jSxP84ZRqsSS0lC3ZjNbw87LE8TNQBhHo9whOrwNWMA=,tag:lD8Xs31gyBDzDJH4ayOs5Q==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cFIySmJuSVlzZjlTYTJP
        YUEzSkZoTmdmVUpMbHJsUGJOaXZUSmN1NFJRCm5wakdGSlBPWXdubXlDNkt6K0VD
        bnYrU0gzeEo2VUtVMVNuS2ZENGczbXcKLS0tIFRxMlBIWmNKaE1VUTUyRnF6N0dz
        SXM0Ynhia2ZsWmcwa0l5RTNnbFlhcEUK+2JSwZudF+Zvh3lowoj7q6mvUmOynO01
        V7VYtBJO5GQZhd9OubesXaTdqAsWngJGVSSIGIRno7YvDAohL9GecQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T20:44:49Z"
  mac: ENC[AES256_GCM,data:3DxgzsqPZx1Lt75mqiJogzeq+De6a5iypiAfhfcmumcOBY5neCJ4ZxG5CQIeMJstduZdyRigoZXpHINtzKQD941kQCRNbJsPQOw/SFwokfzRfNV+MUYtADH3uILllXGjKjO+QMxvnMUL/v7iRhqhKoCtf2QYuR5qGqWQXEpEDQw=,iv:LpMrD7dKlQjgsAjxFZ8LISk0bjLrOvi695w8OxwigEc=,tag:2jtM93/O9lLLMPU52uCGrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
