# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: telegram
type: Opaque
stringData:
  BOT_TOKEN: ENC[AES256_GCM,data:ElnBEXh+pXpbPOzWr8f911f1hOcfClv2smbEV5m0WPmBknD7OicJnLBsbwMM,iv:jSxP84ZRqsSS0lC3ZjNbw87LE8TNQBhHo9whOrwNWMA=,tag:WR5IlIy9Q8YYJdBavHCrAQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEc5b1M5R2hx
        bDNVdnJ5akJGRTl0cmlzU0dRS0Q1eGlBNXdzMEtHUTcvSDdZNzFMdFIvNENXak1L
        dVRFRWlwZ1J3Vm5JYkR5M3o2bkdtaWhzLzVaWkVCZi94Slh1LzAzczdRdXVWYTZP
        V0R1cnp2TDBSQ0J6Umg1QS9HSlFBOFd6b0IzODZrOE1MYk9FOTJaaUovZUJIV3Yx
        Z21BSytsUDVSUjI0cHBYVlYwUFdTeGdveGRCZWVSeVgrN0o3clp4OVBybXVHODVT
        RFNFUDlYYWFMM09veUVid1k5VEFTa2tYU1Q2MXJDNGJ3M2ppRWNnMzFNcUp6ekFq
        QUFxaG9wRUJuQnc3T0RTUmpvYUcyS2paYk45R0FtR09wNThUOTZ0MlRTWGVmZ01D
        SDQ3bGlYN3hXaGlpMVFtUEZUWnFNMmQ1aGNrTzYwVDVFRGlTRWxGY1dQcGVEbDky
        eisrQVNLZE8xYTJhazMwNkFtNHEwcEhvdHhRREV0SmF3RlNxeDBBOWRjUldkZTRy
        V3l0WCtncmZvRjB4dEQ3UDJrVHVnQzBJQnNEY01oVTZjTVlVVWJBY0xVY2pnaWNs
        emluYjU4YUpud3Foek1Fbm9SMmZQYXBHLzZKdU1MaWM1VlJ0VStHR0tWd1FEUUVp
        Wit3bFNMSXJqM0JKbVEyS1BwSmxkM2dCZy9jU2VXRGI1TmYvWFhSdVRjd1hNYmlP
        Z3B0bVE0Qy92WUY1ZlpjaUNpaTV4cGJ1NkxjT2ZRdUNmcDNaU0lpRmlBMlRlMVBN
        anJwZi9ncUo1WGFHbEJ4cVZQTy9CdEZlUE0wMjQxS1VVUlI4WkljU053MEFlZFRT
        L0o5L0NDRnJqd3BNRzRIY1A1elhrQ3ZIZHNCcVYwOUd0SWZIQjlQZmtsZmhsTVNu
        TWdwN1JKa2FNcjNUYzFYUGZGNGN5NVFUbUNsNVFRZXFsTWxGYW5NRS9pR2ZVb3dw
        OUJnamE4S0ZaU29UL0ZKTTFDVElZUUFOVm5qQnhXUXpNRVZLN0NxbWFjc29mU0I0
        R1g4L2lGSFhlL1pyL0kra3NkVGFwRnEwQnR1dFVwSVJERWsyY01HUjRibmNvRVZ3
        NGM0WGJ4RUJQQUdGUFFJNHBlZVJBZlFDL3ltdGx3ZUJjSlN6em90NjFjV1FKcHRi
        Z0NQZ2V3VG5nSW1GNXdxdXBYRGJLMStIUFB6T1pxWTgvbitIM3pzVldXcG5kdllD
        WHI3N1RZYkF1VklocVNydExIcnFBUnlyaUZtaHdUcktUeVVYWDJKSmtyVVZjcC9W
        RTQwVDM0N3dsaktETEtneEJUNW1janh2NXZySnRMbmhFbEZoT1kxL1psNmhiZmdQ
        K1RDL1A0RkF5TEF6WW13WGxma0ZRdlBPZ3hDa3R4VkdmMzJhZ0VXYkdkWEFJRWlQ
        Um5aQ2prb1hqU2V0VXIxYTNMQUF5QkdCM3FUM2FNTWJiN1VkT2ZmbFUvNXN5Y2JT
        RzQycmFaL1NVV1c1N0svcDN4Y3l4Y0g2UXBPc2dNR3ZoWFBvcjdtN1J4dExCbFUv
        bEUzVTM0bnVqUHdUZUhSL2JLaXphN0xzTmlZRHVEMUEzVXRzSGhSS05zRW9zYVRQ
        ZS94VFZsWjZYbkZuWCsvT2YwZG1VV085dGdoT0JvZFM1MnVxUHJUSG1BVEJDR1Nz
        VmpJZU5lcUwxcnovVnJRVUltV2RaUHZFMFR1UXpFMytyYWtUcnRWQXlSZnBLQ1dy
        TkJOeExuOURnQUVlY1hGM0xyNFg3MXVIdDNwMUFMVmpQS0lZMUIzQkpaeVRuemZx
        MDZDVkVDTXU2WURMQXFyaU4zV2pWUlpXcHVoQ3p6WXBCam5iSUVLRkpGekZJaHBk
        SGNlaW4zK0MySmxKdi9Ua0MwVWlTRU40QlAwL21ERndBM2M3dkZTSmRyemVQK3dM
        a0ZjejhJcmQxRjNsakxFZlBuWFhyOHBCcXQwUG5leTdQaytxNlQrbFhKbEtOUQp1
        OVdsRTBuc01KRkN0ZVFMeElBTTJxMGhkamxXazE5WmVZeW9CQWZmNUZ3Ci0tLSAx
        bVVUOHBGcXY1ZmtVdHdBRGVWUVM0NmsrYzhYbjE0TXBINHdEN3RNZkVJCvW3y2b+
        0aLS+R2vf7VcJLzYikCwsTkhJjloVDFHs9a497SE8TzYULr504p1rxhOaStowtVv
        IEooyXbG0V3mwgc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:2RxWwd5GBlaoIfCHf5wPXvQ9zcXzN4b6RK1au+us3TermYOeC0PjuFmGwoGG7zBIc5uMgGzNJjuiYAXG6xgvxJNv6SrzEpWH2lyawO3HXDJpHFPrNXLYJkUDmr7ayygTDQEELx1xeXoVo/OgzHCMJ62oLcsfCDRERtGCWglKB4Q=,iv:wcnFW0ZpgkpejowH8cOv21752TMI+izCOc72TgVny2E=,tag:oXtGTO4TRZ0drmI83LSnXg==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
