apiVersion: v1
kind: Secret
metadata:
  name: apoci
type: Opaque
stringData:
  APOCI_REGISTRY_TOKEN: ENC[AES256_GCM,data:IevhBnoDs++JVE2jYLCFiBJV0EXrjrDANgOxtMUdzFvfyTdepfsH7DuECiuEkft448fFF/3FU071FZmbhwtGn9B+jEWVeHEceBfrPSfnRcg8TzgC5aWqnZsVvrMowWauljMJQKG4mPdBMbiVxUUpDrs94qOL5jAB6X15VuPS5NA=,iv:tr702AkSTnUeAhr4pYjrcoOaFPkTFRhlI8x+BOMm2Y8=,tag:IDnckLEbnmATfCyOFbi6fQ==,type:str]
  APOCI_ADMIN_TOKEN: ENC[AES256_GCM,data:hy0khd0VVPt09U9EU+yYde5G0BUrhh9XKx6Cc1Sx/rIBnuscIZx/Jck5DihVgVPpRit82W/tv13CYSuQdeK5JmbYhHRanE6YLeLEc0jANRTNucYSfCgy8go/SYcDKUnXGoA9RHTENddZZwN9zsiF/1uKUxPRswEoBwPK5ZVs5/Y=,iv:s2QBVtlnBmZzTtiTFDfYf3fAWIc2OQQMiOHMio3vtSM=,tag:v/eg9caoS0ASm4etMRvJ+Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFYwaC9ia01i
        bm5ubzE0cjErZWM5MTFoVjZNc0duMmpiQjFySS91WHc1K0I5V2dEUllkcFIyZTlT
        Sm5JOEdyRDFZNkRmN2lWZHFmVUJWck84YkxQNEtyeXBKOXFiT0JKTFR2R0J1bFBr
        VllGM3gvM2cxdkkzajNEMHlKRUZySnZBaml4Y1FKTnFPZC9XallCZmV6R3Z4dE5L
        SDgrdk9ucE9GOHAwSktzc3REVm9uNm5mWU1Lekh5N0lCS1dzRU1ZdWdWUU00djBY
        RVRCVjVZS0swTVVUb28wUndjQlpsYWZ0K2lpUVFGdmZ2U0hUaCtXWnhmbXM2UXFK
        c2RlYjdsSWg2NWIxR0Z2dmNqMHRIVVNTMVRQaWQ4bGJ4RUNwL3JvdDM4em1CdzJG
        ZXEvcE52ODdQY3VBUDlMRUN6OU50WHdxN2xUUmh3UTJWQ2NSVjNmalNiMzl5cFZu
        SGNyUTVDNWVPQitsOWhXUHBZeVBZQkV5cW4vUEZ2YTdPcVlCN0lYd0ZzRVpURWUv
        RVpBRTZ6SldOL2w1SEc5YVNsd0FzWnMxTUMrMTEvaE1OdTYzOElzWHdqOHVjNnds
        WGdGVXFYRDBjdENWemlsbzE1Q284cG01TDJvV0NCRUM4b2R4ZHBUUzFtTXk3SDBK
        SkFob2Q5T3kxMmRjSkZqUkJZK0VHMjRQY2FwNlBHd2hXdi9RVEZmT2trQ1JiZS9n
        Yjkrd1JyTzZYVERoYnBIekE1YllkZTlwMmZnMkdZdDFmOE1HRm1BaHVRY3lNTXh1
        SWJlcU1DQTcrQjRRT01JT2ttNmpKLzBPT3dRVXkzbyt6Q0c3THNzNEwzWWVVcDlK
        V0VvRE9sL1EzVm5qek1zOXF3T1V2QWZabVplWGRibTJGbHV2ZE5xdVp2V05WZUlq
        REY3MHFldzNnMTBMaVUyTmh1WFk4Ym80SXBoQU04bWhtSU9Xb05kR0lNTFdDNkN6
        VVhIZGgwVGRzN250bisxdGVsSXhBMU9jMDl6RjFvcUk0d1BId2tEWkNJODlrcEVp
        NlpuVldScmhyL0cxbXpFRENnZEp2dXlxTVllZmljQ3h5eDVuaGRIWUtGcXJOWEYz
        U2dsYVdkVkFlazZydG44MnpGRGo3ODRKN2JhbmxUZi9vSm1vYVpoQTdoeTVpTzdL
        enhkVFdUN0J3bkl6bXEwdVo2a3R2UzYyNFJnVzFTTGVoeG9UcmVlRjRSOUhNMlQ2
        Y3hWVlc0SWR3MjZEKzlpbHVIVGlJSlN2TXpCdmhkdXl1SGQwTSttTkJXZUt6d2M2
        UnJneVcvb0ozTVhscTdaV2JyK2NYbktpVlFXMWhDMGR4UTdrRmUvdmN4NWlLWTlQ
        c213RWJkcnF3QWEzak1aQU9HTHNSQmRqVkVVbkJGaGpjMmV6RjJZcEpxVjVab1gv
        d1FBYmxpMWlpR01mY3UrcnpoZ093dHpmUVJNcjJHTkpsNlVRdWMyQnJjMi8xQUtF
        dUdmeVppdzI0b2ZHQzM5VTk3THJMdk9NRldrK3lqMVJMRmFqMFc1VTRlT24xTkI2
        bldhR2NCZUJmdHVWT1JHRDNzcnJ5eHlLTFpkcGpPQjZLYndNSzBxYTR2Y1JsZks5
        cHpod1VWbkUyMkF0bTN0ZVQ4b3NrdmJSN1R6TTh4d0NEbVp5SUo4NExBVW51TmRM
        SVN6cUZ3TEpIa25URXNaT0J0eTVHbHRpSld4ZlJHdk5kSzIvZVFXRHZqNmV1NVQ3
        NDJCS1BSTXRPWlgvOXJmTmxWTjh0ZEREMy9FTXVJT2NQaTJHcDJqTEhhL2RYeEZr
        YUl4ZTB3M0dCU3VQd0pNZS92RDJucm9idkFBa1lJRFBReVhGM25uZ0xxR0lSUk1w
        UXUxUTNrT25FZ1BDYmU5MDRLZ2ZBdXlnR3IzUWZiVk5wNEowSjhLRXRHaWxveGgx
        MDlQMzI0QU5EVmI4SDh3YVUvOWk0SUhPT1JwTUJBbGoyUGd3OWJuViszdlJVUQpv
        cE5ZTTZoZTBtNVNnOHdoRklGa0xmNnArb1VlUVc3V2lGWmZTWXhTbXA4Ci0tLSBz
        cGpudnhlUlZtNUdYcVYwUWNza1RZNTRJNXRiUXliOGNBWkZqRlNTMFhZCvpcs1Mr
        ZIjXLRuV+r6azttKU10907vljOlfnHn0CuEryHfKZxrrmSyfgQHVyMOt8SBJKqCE
        75xjnWHkJgWF4M0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T21:52:14Z"
  mac: ENC[AES256_GCM,data:QJ9vTq7pDqwzBjLb6ipO94npOnyX2OjMeb9EBVb1nwItpv81sQLm/TA2zVJG3f4kCXxb0XbdyNFZ0U94NxxmFnQdk59QLJ70MbmZ4bX0oaZeY/Iq3JDfiJRnu7ORwqB5fDMtdMe3mE3Abog+2MLjxhGF9A8bElQRDdJavvQqGl8=,iv:3kRQ1BtPgR14dz8T2e+Erlkxm2XtgDl51rJZz1/nwcc=,tag:DYQbvbw6cjpP0Vp4UnfVvg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
