# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:DpT/Kf4imDLtbg6qPISnG4irZASb1purngZxRt4vQeOP5D04,iv:5Odfj1M8JMhbXrsL5dJYe0hFdlZnXIXsShOkXwArUpk=,tag:tOm6goOcNpTYC8T01HkRLw==,type:str]
  credentials.json: ENC[AES256_GCM,data:ORFh4U8TOyiJP19WkeBjJYOEmVGzHjgG+jsFkxSFMzVDkrw4rhTK6pQe0TK+seJ3bsgQCLvlpxJuNbDlEY7xL7JI/hgEIMWgr/sPHk/weLkmYqQSf8yW+4AhhjbYKUbZN1Y1ZXiGCIryhdfaLTNeqLgdzmfVnO+QyguDows+vLdO8rdGZ1ARnGs3zZYxlAVMNYqgF7eR6/Pnt4ehWo2ufP8Au3FmZ3xOj1fC8uQPEw==,iv:7leRQqoyakMEqsRLOJQlyFX9vjqzFwYYjyvH32AGqok=,tag:a8JtKcVotVabyDc/IDuFug==,type:str]
sops:
  age:
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGhhcy84TGF3
        a29YSHJkRlhTRkx1M2VPTHh3UzF5ai9yNkRHbkRDSlMvT0RRRVFWNG1YZG91TGFt
        dVlIb0ViQkFjVlFUN0JsTWdldURUY1R6TFJNTmZpbktQYU5EVWZRN3V1Lzl1cjlZ
        bkpPV0ZKVEY5eDE2Uno2RmIyekpyK2pkWFZ3cDZoTWY2YnNlSjJmNDB6RForbzcr
        MEFoczF4bFhIRjV2VkIxUnNVZkVzVzk2WklPODMzdW92QkdESE9DTThWT0QyclRJ
        NzJLa29MQUJ4SlN0NU1ZdkdkZThZTWFqUURVVmlOeHAzZ2g0a2RUZGZ0TDZmT0xK
        OHRoL05oVEVzdnBxMEMzenVsS3huUVpVWHZYK3c2b0ZHK0YzcXlzUHFyQ0xFWWpn
        WlQ2ZWduU2hmVlJrb3VCSkJadlV2d3JVaWl2QitWVjYrYnE0cGJDb3NZdlRzZ0Fm
        UXlZVldNaEtwVEY2VXU1d2NBVzl4NllNSWthUUdERFZyZHdjclBVU3RIcFBUaHBa
        LzhZNGNBNWtUNEFtQk1aYTFuUWNnWndCZG5PNVdKYXowdEtSSzRidlgxQ21XaGFM
        VHZ5SU1IR2RJUGtsVVlEcW1CRThXd0tGNUZKOU12U0ExdHpqZFZIaU5DZHVtaDl1
        QzBPU1dvQXU1UVRIaDVOcDlYNFlBMW1WRkE1bnM3TWZ2Z2Q2TkRlRzlXZHlSVHRv
        S29SOE9VcGpxL1U3bTFmM1YrVzFTZnBib3NwYkVPNmlOU01IMmc1TlphbkVXRDlE
        RnBtYlVxc3NLaEtYeWswamhJbHFWUVVSS3pIc01Pem51UERDUGdneXhKelUvMUFD
        T1UxeExvNGc1L3Rmd0VwY0NQMGhwY3Y2OGdXM2FVNnFYcmZHQXBqQWNVVGxadjlF
        N3ZlWituQUxaYlNicGJjdmU0QmFPZzc5Y0JaZXBwaWRNdDZPd08zcU1BaHVmQ2xR
        NWFvOUJpeUZrdGZYYThtK1BWZmF4OTV3b1lsd284RzlrVlNLZGtmZndZaVJWbUR2
        dU8vQnJ2NWVML0o0dVJGUlZpMkFvMDJEYUd1SDdPV2VwNk5MclRob245TjFTR2xH
        V2EzY1lDNjVQZGN5bGRYeFk2Wm9YcnVIMUUvdXhlbEVsOTJ5KzFVeitvTnpGWmVD
        SGQ3N29xM0hWcjZQQ0JWOXZQK1hnM1g2d3JqbHNpOGxENXBQdDRwRXVLTU04azhh
        M3czbVZDQ3U0QkVxZTRiZlR5M3VpYmcrZmN2NUhhZ0ptWFozVzFsQitVT2dFMlYv
        dzVuUzR1M2lSTnExclJRb082aHczK2M5ZEVVOGpTSy81dlNFWWNlT0cyNkh2RHF5
        RVdHdVpBdnkvWGM4Mm5oVkhsY01aWDF4cWRMOE11R250R1FHdjlybXR4RVdoQVhQ
        Rk1iM1lLYytlemxmakRHTjl3R1VxaEdmNHBZNGVKcFZYdXovd1VnNHR6aW00N0Iw
        UVc0RWJDbnJJbWxJTW9hQm5Nd2lORGc3ckVBOWdGQ2dGU1JYNEVGc3R3TjUzQXJY
        V0hoUDV2amZiNU84QnR3eWpSMHJzQkcyMSt5dmZYelZzTXRRV0NhdHJCMUh4VXN5
        R3dtbU5KK1d4NWl6L3JtQmgxN1JuVVVrZWdQMjFYcVpVajkzMHZ3QjJWMm9SRGxI
        NnZncFp5ckpLVEhNVldqcmo4eG9QejNKRjRIMkZXcUJjcDlobzdvaHRSV01vUjNu
        VUpvaWRyZGRpVk15azdHMHpxYnhlb3Nua1FFSFJoeHlKckQ3OFJnVEtiUzdKUkRa
        OTcyZ3lSVTBBWjVmYUQ5dmcrR3NIYys5TSttUTdGWCs4NmIvYS9MRmxZSzJGL0Nx
        OUljUU5HUHk4LzRtV29rV013MGNYTzZyZmFyQ1k1UWh4ZHVtRC84dUpjazdkdFNG
        b2xSRk51QmNWdWhlRVNuYTlranQ5dk5IUWMyREhRUXBPbFVtRTZrN3I2bGdPZwoy
        RU1udXplN2RpU01kVkoyM0tRME1ueXV4RFhNb3ZCbVUyV3h4OC9udy9RCi0tLSBQ
        WVY0MHdkb1p6eW1OVy91VGIzL3RTZmg2TDBjYnF1RHE0dVFMSmd3c1kwCoJgDRaG
        VoPGU4P5L5wvIldMDqEERb08ijXhV1UQmNWrsdTXBNbBHpTxR1B22LCLx3g7gozk
        Aw5fZEZ+xQxIkSY=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T13:53:50Z"
  mac: ENC[AES256_GCM,data:wm5D8uximP8tD2xQNb2gdYxO4RmSysYm0zHRMWXGq94V/KxE6yzQE0qKQVoosZgyuVn8XgmhZAtca+ZTrpR9V4vOM3Th0hxZaAc8k2yRzjNrS2ii3m5lzktChq5k5wS2w60NIyFs54R3vsQbabjjD20fZX79XszJcQRb2CCuL/M=,iv:pizPVzqUZ7WSNQko0cL68bNSZtR851DPwihgXAeRzo4=,tag:yFh1ZobetnGy5DTtYZ6T8g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
