# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:DpT/Kf4imDLtbg6qPISnG4irZASb1purngZxRt4vQeOP5D04,iv:5Odfj1M8JMhbXrsL5dJYe0hFdlZnXIXsShOkXwArUpk=,tag:tOm6goOcNpTYC8T01HkRLw==,type:str]
  credentials.json: ENC[AES256_GCM,data:ORFh4U8TOyiJP19WkeBjJYOEmVGzHjgG+jsFkxSFMzVDkrw4rhTK6pQe0TK+seJ3bsgQCLvlpxJuNbDlEY7xL7JI/hgEIMWgr/sPHk/weLkmYqQSf8yW+4AhhjbYKUbZN1Y1ZXiGCIryhdfaLTNeqLgdzmfVnO+QyguDows+vLdO8rdGZ1ARnGs3zZYxlAVMNYqgF7eR6/Pnt4ehWo2ufP8Au3FmZ3xOj1fC8uQPEw==,iv:7leRQqoyakMEqsRLOJQlyFX9vjqzFwYYjyvH32AGqok=,tag:a8JtKcVotVabyDc/IDuFug==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TDY3RlYvQVF4WFRCbTFG
        QTJOUTJCdkZTS3BFSnFnNmZ3bFdoandPamlvCmpQTGtVQVRhamRCUXFubllOaity
        VVhvbmNrMjdjYndwWnB4VlAzTUJoa1kKLS0tIC9YOUk3QUdobHZITlh6RzI3bEFP
        OTlMS0hZZktObGoxcFNMSmZwa1FqZXcKgp1jvZyY8K99qIGxeyO8bIfKoatv8F4c
        xxS1M7S3Snh+XyN8e9ilno8bQ9DVIdWKjUKXN9NigDBr18xi+cr6bg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFhsbEMyS3FT
        MUVwbXMyNklJNFhwbVZjUWk4VlBPMmNHdEZNUmlaMXJlWStZdFkvYUR3MzZERklH
        cGxwUDVwQXFPSkoxYkFQYmp2Vk1OQUF4Vy9yL1kyVnRzbUNESWxwcHZlb2Y2U1NB
        TjhVTEhnd1JvdjBzSVZ2bzI3RmIwb3VOV0dIcENNeEFwcFdTcnRQTC9CYXBkTHNG
        dGp0V0NUSEpXL0FWbjg1Q0hXQlpTaHRmUGxTM2VsUno1T1VkdlF1ekdBUEhrMnd2
        ZGpSNlhINGJFMmNBeHBSTmVrMzcrNUtYQ1lqOUdZR05WOWZWWExUcmJpcW1peTJk
        WUNZME9WS1I2L1BRMndEbFhLb1B3dksrbmVzdXdsa3Q2UmwxZnYyQnpiNUJNc0o3
        VCtYRG1mb2Y0OWJVbTlzVSs2QXlOaGc3UFNWSzFCN0ZGZjg1UWJFODd1ci9Qb28v
        Z2NxWlBEMFo1WWtiR0FsU0tqZTJnakR1RndOZGpvUDhVT1lHck1kWXNYSExuSFpH
        bVpIckJTb1FWMmdkRDhybDJaRlhsdzZ6ZDVuVzIreUxTamlhTnhHL2QrUVVNcEdT
        cXNFUjh0MWRRTnNuQnIvWEdvVUpEKzhpQUlRWUloVXY2REd3YjFvVjVVOTJ5TjJ1
        VTFJZEF2T0FzV1lncDFiQlFPMENuSVB1WDl0UkRxY0NTODdUNU5GUVFQT3BCdzNj
        ZGd6c1NOc25YRnY4ekhpclpkK1piN3B6UWs2L2M5aEVqK3lhamFnd0ZEcCtwWWMw
        RWdJV25yVzc2aWc0b3BVck9LRUpJR3dDU1ovMm5hTXhDV3RZdWVsMG9KTGZBL2p1
        eG9nYUFiZytVWE9HRmpHbXpUdGlWMG0vMnZqWXduUm5yUnAvUmlndDB6N3lzTE5R
        QW9scmJQRkcwVHEvemlyMkdUQlJiVUdER3krandOM09GTGhlVEZMVk5UMnpRMDI0
        RGUzcHljQ3BuWXl2bGJscnN2dUF2M3gzK2xZVXllSlV1WVFoaWdSSTVnckF4VkJx
        S0xJZVNSOWNzU2J2eVd0L3lDL2MvUWdNdjBXd3N0WDJidW5IalBLa0VtQXdqWklt
        Um5sTWpkRlE0ZlprajFWT3p2UnlGdHY5WHNVYmVnZkpNNDYrR3Y3K21iWkJ0RHVr
        Y1Q1V29sZTUyZXd6YXZEOXQxTVR1aFN5NlQwV3U5cm5sUEt2aHkxKzVhbVNWcUxT
        aklHQXFVYkgxeDV1N0M5UHdiQ1JwZEpsNmgxOTl4RE5YcjQ1dkhQOU5DMEs5bmMy
        N2pjdndVS016YU11Tlp5WjBGMEhraTBPNXFYUzZWbGYxNjBDOEptRE5uR0J1VWVl
        cFZLQVJySzVkdFBOU281dE1udFd2MkxOZ0xGc2E5NCtNdzdvdWdlZWFZK1JWMk84
        UzFINGxUeDZyMXk2VkhvMjZ3SWFpT1BITGFweFFCN3BrMHdKQStndWNrcTNQNjRi
        UU9VMEExK0dEVnNta1BWQjhPSlcydVJrdktqNnhndHNZMEZTa3BOZENHdFVBMEVw
        NFhGODRYazE4cEtaRG1rRzVrUTNpZkF2K1pkVGtFSG9aeXRGMSsrY1lJSFlyNTJ3
        d3Z3cmZTenlmeDk2WTc1ZW1CV2RrTm9yaXNNT29QZ3psUU9LTTdCbGJ1VUxjdHNq
        RXFlWHYwSmQvbHdBRTNhYjRhTWhwZWVxajk5dlExR21wV2ZrTTlSbTRvanppcGxs
        NVFKVGNRay9JdmpZT2JZVWkvK3J0QU0vOFNtVkpOS0pzamNrOG1vVmg5Y3hYQ21Q
        N1N0Sk4zRGtSUStIWFNRczN5MDkzeUdrbElKNTF6dGdXUUhZMjh5S1NKUnZKbHhX
        a3ljbGNGeDdncjNuZXNZUGJ2ZktwakNZM0lHaG9IMDFmYjAxWmx2UlJ6SDU3ZWFj
        SlpZdDN4QktVV3BYU05yREZQVVFOa1lCc3RDeWNVbVkxaUw5ckVub0N1VVNTdwpL
        MktYTncrb0pLcmpBQlczRnZtU0JqMW1wa2crTnJhb0tpSUpwbUR2QjFvCi0tLSBJ
        eVQ3LytYaWRaMm1sK1ExWWthQkNzdHQza3F4SXl2VjJydUZzdEo4UDkwCuDfMsdG
        EkzlmONo/qzEDLS7PeIY59P8SEOV97fW90nNHhCSESF6I1oj5XBGc8/tM9CsUOkQ
        qzV8WfHsMqbf3EA=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T13:53:50Z"
  mac: ENC[AES256_GCM,data:wm5D8uximP8tD2xQNb2gdYxO4RmSysYm0zHRMWXGq94V/KxE6yzQE0qKQVoosZgyuVn8XgmhZAtca+ZTrpR9V4vOM3Th0hxZaAc8k2yRzjNrS2ii3m5lzktChq5k5wS2w60NIyFs54R3vsQbabjjD20fZX79XszJcQRb2CCuL/M=,iv:pizPVzqUZ7WSNQko0cL68bNSZtR851DPwihgXAeRzo4=,tag:yFh1ZobetnGy5DTtYZ6T8g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
