# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:H+6L/S+MsClqSJF6eq9rJhJnx2ybc/+PZU6alNrOYm9pEEYN,iv:WrHeO+tNfhGoEep7PeqHyynSlr5OaBtrR/tvAWwrANs=,tag:clGZ1rTIVYjyi+eooJ9vhQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:LMovP21iibebcEo5tCQOV87FK+GNo5xF3sPHLHshv0eh/Bm5ZMne2rI26K5Qz1hyCHPRY7dOmbmL9PweZgUY8/eoS7i7D+9X3vrzbK1NLMPikWYa1ILA+VfPxrB17Dg3Q28wCAqZSacBPgKqY8E+sbyq/QsxUeORGB8PpoOBw8TRxlXX2u/CxBStPwWl9d0Og5faPFoknqXZb+l58Kc6hez+lraCe6zzidNVjsiQMw==,iv:oiqzlzxsnDhpbrVo/ZZP47DO84gfmoI/ZohHz35nXH8=,tag:JP1fn9aoCXLZ+g5LAKxQBw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4L1RKV0YvRmlpUTZzSXFF
        MWh4c0ZnS2NHMGZoaEcrQ0RUTTROWVgvY3k4CjZDMVl4NFUySjBBYzNWcFBnZTNH
        OW43aWF5WTl5eWtEYlZFNTIxQmoxTjAKLS0tIG4vTDl2d2h4OVYrT0RzMHZOdXUv
        TjZobUtoeWN3aklNMlBxTDRYM1RSdWMKLx7xz8QyLKuzclIH+hwHUFMV/Bq2w7BP
        SkkDw0K/WbvprZshl4HvYEqrrcPUHRAt95oxZArl2vcW+vGXSMCB/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T13:38:34Z"
  mac: ENC[AES256_GCM,data:Vl4x/nu5wedmUIx0GgxPhbvnFwBA83+4KYXyZeXsF6DphQDRHYZlqLjzn8D59stB4wasKA9ksdkqkOhW5aWjU6bi/w0eL+Cjq3MipQgAYvVW9YwjQgH0CIFGbyHkfCbz4BFSo6KM0DMvOuYNVI4NBcqJtIqFtkQLhMTBVY+Lv1g=,iv:1PVl+09XE3JaUP8/VWU7m84QZrFTPlMIjwHMO2NYZxI=,tag:HkfweHqqmTc5kb0fansang==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
