# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pSjofSK23afBeeFHZckz0T0JeJnPJ9zjqjzHgqMrqjI=,iv:dm1HL1NCAD8ulh1L8+L1wC8S9pnES7t5/lzFsq3IiQo=,tag:Az5TwC7jMKRLow8tLk3wGA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN0RlOW1SN0dzaWF4Sy9O
        QmVVU0JuTVo4YjRmUHZpaE5meEFwdndBb244ClBHbFhTb096UEQrbWFSdXByeXpF
        QXFSc0xURWg1QjJpQ1Q2blJkMTVwVWMKLS0tIERtdDFCenhkNjNxSEFCVUt6UUdU
        VTcxUVNOUk1VYm9ZcG1nM0t6bkZiOWsK45Iec1u5pHQxWkF2rM2U3opZrRzQiMUv
        dFUHHGMNsiKLneazQcJR6TW7M2wY0lDVKjXdiLiqp2Mh7M0stf4Uhg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T13:38:34Z"
  mac: ENC[AES256_GCM,data:1X0OXQauaMsT9PRYIZKFFMB9N5eB60C1Co0102B32aH4YUTa6rnEZ0uKt4YkCdVk8aFEk5WbnQ+NxCz09zpj8c6A37CBb1RobSxYVDSK4NiF4NavOqSRu+lM27W+o8Kj4sOcwWvLdvvo/FwCbPUWIAYLtFbmntMZCr0tNDMzeTw=,iv:3cmwPKLw1tX5s6H4oQCgAP7Ok/wTto21ji4e1T+TPaE=,tag:km1etOjJSxQIVLVYvaQCag==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
