# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:TGjBLbJsqzdMyA9SAuA1Za4QfxiO7mh1G3/8g1UMND8=,iv:6VwyMARf5gI7W8UTpkxhafcGnq10ivU8rdc7gmS36ws=,tag:D9jcHd/T4ocbMHvhU3Xnzw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcDJkNS9MZVk2TThaelBW
        QVZjY3ExdDVIQ25FRlVvMXZlUUFPbGROVTJZCmlTZGpxZm1jTDFuZDlGT2xYOU1V
        STlrNEVTMGFJM094VkxKckxDbG8wSEkKLS0tIHRBSHdLeE1sVm10dlNwUVZtY3V5
        UFZ6L0NEYmpnc0NuYkh4aFVDZUF4R2sKfHlm3JMeWbKKuthutc8151y0euxgXYtr
        WpcIAnEgvUqlD9P9Q9mZ8mXtgfnrMGYI+Gh3GYAsrYQ/eHHIaN176g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T13:53:50Z"
  mac: ENC[AES256_GCM,data:1qbetJ2ZVas0Zo/6+ayAAKYmrnooQ3Bi2NASW4BPtLBslE9bL9UV0ov+yyBEBj/eKY3e1J8wakAk79xRdnVKt03v3ar5Fy7bPVbHf4zYFB2HIKBDLuJjgf/BgL/6jzM0uIXdzy0lzscucdiawdRojvER4lZvs5h9lUfKwEP5k2M=,iv:YZwRcySBoYkCvjkSI7g0jA72zSVxrYjE38wU7z3NfMg=,tag:qf5vcv0BMKcAXxBLf7tQ7Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
