# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:TGjBLbJsqzdMyA9SAuA1Za4QfxiO7mh1G3/8g1UMND8=,iv:6VwyMARf5gI7W8UTpkxhafcGnq10ivU8rdc7gmS36ws=,tag:D9jcHd/T4ocbMHvhU3Xnzw==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZzUvOWFUL0EremY5RWwz
        YjZLUFVtdWFZM2NlREJ4LzVRUk4zYklMQzJRCnM3UXFXZ3B1S2NFeEFQaG80NDkw
        cUNDc29iaE5MQWxEaHNINDUvLzJHNUUKLS0tIHdGSVRjWW84elRBK3VGd0t6MmdV
        NHh3RnJIelBQZUpjRzc2emhjRUF4VUkKhj4pZyhJ6uggs0Gpy/idIibQCvr0SVtZ
        zuucHgHSxyu+As4Q6jhdFGA/EpQZJQ8dt1m2VrE213XXmmfkEkPVag==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG9EQzZIcXYr
        ZE9kanQvTi90ZWduNUhzSFBCODdtNXQwVmZuTzhHZ05xZFE1eGtld1lZbnRtVkZl
        VGdmT0w1dUFwSzM4MnhMSkVnTzJOZTl2WTZ1d05DODlER1JZU0VhODNwRDdvQS9p
        MlNjNDRrZURpYjRnNXNaQk1RR3JqMnVPSVdUVk5SeW02Uk4zcGV3YnNUYjdZRWFG
        SFBaZGd1QlI1V3VIK0hiVmdMOUJyNmhNQysxN3VzQmR1OXhaTHJsZXEwZTVmMEhk
        eDN6SWdhYkxnckMwb0RhcW0yay95eDlhVm9JZkxNTmFBaHd1WHpGaFRHVEl6NFFt
        ekJpV3I4QXBoemxoVVJLVUhjV0ZVYVpjQk5iNHQxY3BYVGxMSVZMalIyUURBT2Mv
        MTh4bkgvSWhBc0dVQ1Y5TE11d3BJS0t5TGJTL0VOUzFvY0UvZ1ZnR0ZYTmN6ZDZ2
        UFQ0ZStYMTJGYi9yWm9OZDZLd0lsdmJlUTlpWHNzeTMySmNWS21aMTVNSktMeEtO
        MGY4OERmOEhmdEVnbWVUdzZjTGw5K2FsY29DWXU1SEFhOGwvbWpvYnZxdFVxYlA2
        TFU1MVNzdnZzczBvaU5JNmFjMGxuaTZLS0VJRkpWWTRuZXJhU1hndCtlUlE1TlRo
        bUhEa3JQUXlqZ1kxREF3dzhwWjM3SnhmM20zenZMdE5hT2MrNTJjSHhDZTZtazFl
        MnNvQ0NIZGp2WUhwUGEzZTMzSGFObkJ1b29xU0Zrc0NHQm5nckhzeGd4M1dNUWlK
        SVV3aXNZOWRBc3dWQmRYYUNMSnZMcVN6Q0FTbGJuUkRwTFZYeEY5L2YxMTNsdk5I
        bDMxbkFRV01TT0JVQkxxMktsVyt3Z3EzQUpodjNLaTV2K2hXcjlQcFhsbGIrMnN0
        NzFKYlhhSVgrQkw2aXhIbUhTa0ZSRjRlZXVaUWtwRE1IWjFwWkRyMkYrSnJDS1k3
        SlMzc05NZXgxUW1lT050eXdKK21pU284N0NSeEpGWkhaZ2UxMGpuL2dJcnkwenBa
        eWZMSmNEaGxMMzFBVUh2dVQvMmU0bFFpN0x3NHpwU1JXTXN1Ly9MTElOamZSM2tP
        UGRjSmRWREwzZDFiSWNzOTlnWGlyNzVnRWtMSzJqRjFDMEZFd3lNVVY3RGplU3o2
        ejduR2VpWFJsK1haMXpveC9hdm10Y3gxVElLM0xwTzVZOVdGRmtaSWZKVElXejhM
        bkFGU2NOMmtvWWJhekNCU2VDQjB4RnNIM0hPVjc2T1doVG41bzhERkN4ZHVicWtw
        NTM3TlJQVWs0UzgrVjduWEZJS1hqQTV0bkNsMUR0Uk9RMkRQV0xvcmhxWTBYK0Vt
        azduczEybnJPNWV0cmRYUm91a1V3NmlTRVR1UjlyVytkVFhYUWUxNEc0MGxUcW1I
        WHZIcnphdFphdmpCK0VPMytsU3ZTbEdJdVFmNHcwUU9pS2V6ZGFSTUw0SDJrc2h2
        NndDaGNGTm9aYXBYUzlEQ1VtMWY1QW10TU9rZk5IWldCYlI1U3QyZzVQYnh4WTJI
        cVd6V2dBbGNqY3pVTXlVNUtaUnc4TUl5WFRMcXAwM0FlR2tSNEVwdENVVmVpSDVH
        T3oxZjBtWDhqVFpvV1M2ZEZaT01VdEhJUzEzVEh6SFE0ZmZLazdvelljNWVvZVRB
        MlE5UEFLekV2TkdaaE5qYnlFOWk2ZUtWTVc3TFZpYmxUTjVHQmxsYW9EZWlMWXJs
        ZlhvZS92dXR2K2JIalhZb0pCbVdsSzdWdzh0VDc2ZWJWSVZwaDdQblY1RnpVTHpO
        WVlTUE9NWHkzbXVxZmdsWHlCSjFXbU5mcW1kVUI3SUN2TExrcDNYOG0xL2pmZEZY
        YkJWSGtjekNveXZGaXkwanZYMWt6SndLL0FSNjF1SjFLcFhuOU5IVndiMnc0dFR6
        RGRlcVBUaHQ3Q0E3ZnRmaG1BSGl0c2NMV3d6Z0twUHVDNHN2b1E2eVg0TTVHZwpC
        SjByTmJSenJQV01uZmZjZ1NzRXZsYlNmVEdzbXRoU05aVEFNZmxCK1FFCi0tLSA0
        ZUtTYUh1OHgyOWtFQ1c5a3NNREtyNzFnQ0J2R3Y0YXpnUTJhVkJSMTRnCvanYaUH
        Yj0lkL+ymBJwULxMF10oWV6o7FsnWEReOKxmkBS/4ikODxByBanelO/+PR4AkvzZ
        2+IkVjuclgnYVL8=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T13:53:50Z"
  mac: ENC[AES256_GCM,data:1qbetJ2ZVas0Zo/6+ayAAKYmrnooQ3Bi2NASW4BPtLBslE9bL9UV0ov+yyBEBj/eKY3e1J8wakAk79xRdnVKt03v3ar5Fy7bPVbHf4zYFB2HIKBDLuJjgf/BgL/6jzM0uIXdzy0lzscucdiawdRojvER4lZvs5h9lUfKwEP5k2M=,iv:YZwRcySBoYkCvjkSI7g0jA72zSVxrYjE38wU7z3NfMg=,tag:qf5vcv0BMKcAXxBLf7tQ7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
