# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:TGjBLbJsqzdMyA9SAuA1Za4QfxiO7mh1G3/8g1UMND8=,iv:6VwyMARf5gI7W8UTpkxhafcGnq10ivU8rdc7gmS36ws=,tag:D9jcHd/T4ocbMHvhU3Xnzw==,type:str]
sops:
  age:
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE1XQXZGbFF2
        MCtuOXdHdk96TFY1dENFMTBwQ1pBemkvRVp2eVEvaEhDZHZPSFcvRm5SbEQ5U3Rr
        eTgzZWVQcWZSOHdOaFBUZ0VJazhVNS90dWZpRG5IM3JpbmY2NHBhdndFdURqQlFT
        VUtOMkg0aW1rSWpFbWkyMTRneE1yVk1uRHlKS1hqbFZKZDBuMERYT1k3ZVRDMVBU
        c3RnZGtCNnU1bHJlaU5yL1pxYXZOOWV5Sm0yTjVpcklaRDJwRm93Z0t6ck4rMlg5
        aVBoWDEzWms2dSs5VXNhTjBseUVwNWNUOHBqaFRCRXN4NEt4Y0daKzZ5VUlVVkZ5
        WXFpZ00xMDJuZGdSdURiNVFnN1EzT2FET3NuQ2Zpblo5bWxTU2xIYiszdGFTWXlB
        RTkvck1ySklEemltSnl5dTBoUnlSS2E4OHRpdTB3d3ZWeUdRMjBUTWU2NFVxdmNI
        SWlJSmJHV20yeERMVXlIL3oxMnQxcitiL3FoYWgzUFJBR2FKMXlLeWF0NktFeVd2
        VnNrRW40dmVUZjFGckpJRy9tazdHRGI2RDF0QjZxSXhwRGNHRnNWcitEV3FBM0ZP
        dHQrU2NFeVlQKzM2dVNnSXJhR3hCQzY4NnByQVBHSlpZRitabEk4T09zZFNDdm1r
        SmVDTjFlU0NuYUh0eDMwemcvWmE5cTBIRDJyOTJodFhRNzBqRm5tYitqeW5zNUJ2
        L2FHcVRHNU04cnlZTHFRZnVncHJUUnVnUHU2RDViSE9sVEk1dEJOd3p6eUlQT2VN
        WThiZDdPeER5YmRmVVZKMWF4Q1hlRGNFL1gxOFhxTXA1T0wwRG54UWFBdUhJNjRY
        VElBOXo2RUI0TGZUUWxEK3FXcGc0RlN1czBRMXNQUzk3UmVtTUxsZ1JzWlNXYkFW
        THJnNW1ROEs4VXN6SXEwR0tzWWdyQ0VES2RGQUxweXRnV3owSnlsbDEvVm45NGhH
        eE5PYTV2TVFtVnBTNkgzM2ZodFpKU1VxM0V1Tmg0dlJNS25xajg0MmI3KzVOdXh4
        clFQS3dWMFZpV2k2am5nTHdRTDIyc0xDZk5CY2N2NWZaOXFwaE94cnpyYWZZK1Rm
        Z0NTR2pOelBmZ3FTOVFRekE5STNBaGlEajhwS01ienF6eEoxUWhyRzRYbU1KNE1H
        RFkxOFhFMmxOZ3RObW5xT1NobU9uLzQ2aVV6NWFVRERSMmFGRXl2ZzFGS2hDZWRz
        T2NoL3doN09tU0FhVTV1ZFRpSGp0SkVCcW1ndUZpS1VZS0p4SjkrQjQwQkNpTkpp
        UU04UnlIem5QdHFFN0poL3gvM3YvZEl6dlllUyt2YnZ0OTVyTU1JY2tQT3U0Z0pB
        Wi9iNUFCMUF2RXJyZW1PTlhMTHNINDNubUdIUTI2MEhEc2RJbnArUG8zemtSa3Fm
        ZVFsM2oyUllhaWVZYU5UWHdUSTZDRm9KYWYzeWpJaVBkNm9jQTBsTVR2WDJEakRY
        bmZycm8rNUZRbGpVd2hmalB2WUJRNW1yRkRTWThwZDdFWlROVGxicWhWdUtRT2Qx
        Wmxyc3p3Q3UzOStPdG9uNjg1WVlUaktQbjh1ZnpIQ3ZyS0RIN25ZTkliaCtzNXFx
        Z0syc2hBS28wVnlIV1U5b0hENHZielFvaFBaellkNzBaS3dOTy9Sek1DMHlvblll
        aThBa2xnbWpzLzZNTk1CblNRYW91VHpMUXVRR05ITzZKc01kSFRNdDRMVzFVWDdR
        aTVIMzM0UnFzZ3hRL0lKK3FIU3ppVFNrTUxpaFVXN0xJQmhFUGlRM05XQ1orSG01
        VlVLWVMvR1c4OWNTcFJaSUg4TVRzdHBnK1gzVzRkZFpFS1N2TU80OUJzTmJZOVpG
        NmlSa2Z6dFRib0tLK3hFRmszUzdtNGZudkJzQVJHaWlaTHIxa2o2OWQ5UFh2SGUx
        ay9xQm9qa1JCYjFTYWg0MlFJRVZCSnVJWm40NGt3YzQ2aFVQOHBDcEFkWkJBdwpp
        aXNpS0xDNjkyTC9QbHBNQ2Fpd0ZmSW50b0VEODdLRUtJU2dST1U1RHNnCi0tLSBN
        U0hyNU4vam9sa3kvMzlSRCt3SFlrc1RGdGp5NnMzS3dieDF0emMxdmVRCkqDd7+r
        DtI0tnXEta3Y8HKbKQkc7l/92KF/4BsKU8WVa6oQse4nMm46mYGS6dqGGhODu0Q0
        NH76dCurRfRAR88=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T13:53:50Z"
  mac: ENC[AES256_GCM,data:1qbetJ2ZVas0Zo/6+ayAAKYmrnooQ3Bi2NASW4BPtLBslE9bL9UV0ov+yyBEBj/eKY3e1J8wakAk79xRdnVKt03v3ar5Fy7bPVbHf4zYFB2HIKBDLuJjgf/BgL/6jzM0uIXdzy0lzscucdiawdRojvER4lZvs5h9lUfKwEP5k2M=,iv:YZwRcySBoYkCvjkSI7g0jA72zSVxrYjE38wU7z3NfMg=,tag:qf5vcv0BMKcAXxBLf7tQ7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
