apiVersion: v1
kind: Secret
metadata:
  name: foundryvtt-secret-stijn
stringData:
  FOUNDRY_USERNAME: ENC[AES256_GCM,data:8/2gpWs=,iv:tZx1zp49JnmlOlBP3NlgCUtxPdy2sXBxJxMSDLGbAhY=,tag:Cnu5W/jC3ZxIOVYjaR4wOw==,type:str]
  FOUNDRY_PASSWORD: ENC[AES256_GCM,data:Jz4UFlUYl4ofQ5ZMRFbp,iv:8UYP9XeGp/gVEEe2GCxWX0sFvQhi2M5WmPpsdAUsADs=,tag:BR60OAjAV+hqj/hn3CcxTA==,type:str]
  FOUNDRY_ADMIN_KEY: ENC[AES256_GCM,data:XD6JaLBnAD/u8P6D2j5pPevOrpQ=,iv:QUFVhwtBoGn9avUS3cb508EhThQqBemk8zy5JC6myiw=,tag:6UMUKZmijBbLgR1jujAomQ==,type:str]
  FOUNDRY_PASSWORD_SALT: ENC[AES256_GCM,data:of7shkFsqKBiiZmyNvnGKwOiy5ns45SKz/lQmwgTLACM,iv:OHoz1pN5wo/9Edy9/FSMHDz/cj/6aL6t+UW01dh/mj4=,tag:baRqGfDe2ARxwmQ1fRtvQA==,type:str]
  FOUNDRY_LICENSE_KEY: ENC[AES256_GCM,data:L2ywTn6Un0n5JbvVqAIAJt3XxW6DNanvrosh2P8=,iv:RAE2+M6xsuTV/SoK9eCzD/Jl+PQJDaSuZmfTqfyDRwY=,tag:JG/3PZqrAlx/ZROLCNrkJw==,type:str]
sops:
  age:
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDAvVk5nNzhL
        QW9yYmxkYkt5bHNHc29kZzBBcXJpcE9MSklqNmpPUENOL2tkVDN0L0lxZ1EzaUdt
        YjM1aUQvMzZ4V1Z4eldmQlFGZDlXRjE1OHFaaFcwZ0JNV1V2WGlTOXdtQ1BVOXRJ
        by9JNGZVeExUVTMxQm1wejEyeG9BMmw1SXlXWXVDRjQraUNWek1lN29meTErODlE
        UkdzbTM0OGhkc0Y0Y1ZvR085NVROU0N0R0t2M1FsdEFncG5qNGw2Zjh0VFFpejNa
        cENTOE16NWx0aWUycUZUNVErWHEzSUFoR05VdVdYTWtvd2hMeHQreGZwL21LWWVB
        WWk1aHJMK1U3Zm1EVm1VUjNwWk5oYllURmFTR2dwWStvR1RQQTRkR0VsWFY3bmRr
        U05JSlEvMVdyYXV5U0IvK3F1V05DSk9ZTFFTMjc5c2VlZnROdlB5NDI0MTVtRGRK
        VTg4c2lUanFJT001MlU4UHZUTUtSeklqbThOeW5RVmw3anFjazMvU2kva29xUWZ1
        d2hsdDdmdXVHYWdrbGM3dnlNT2VjeGxGcnY5T0FDSUk3cWpnZHgza3NDU2ltblBQ
        Z1NGOEtaTkF5aVc3VWsxczh0aWlNKzlneEVSS3BFaFBZSys3NHU2aUFqYjU5c2U0
        MHREenRySmJCUWsxZUJ2SUZGNlZVSTloMVBLWVZFS0N1SUdvbWZGWFBPeG9scW1u
        VVZVR2NFbFNKMjF2cTdKNzhkcXJnVUtrbHdPNzZrVVRzd3J3Ti9UWjNtaW51Wm9P
        QndYZnhUZ2poZjJnS3JJbXNRUENEYXR5b3kxOE1Jei80UWFicnFMSkFYSytmQ00r
        OFloRUhGWjlHNTFNcXpGZmg4SUNtb3ZIOXlUUGFuZkVHQmJETS9GK1RuekdsZnpU
        SGxkVGZGOVF1NGZJWU5nbGI4bnhFQW8vZTZiZnFuaEdFNENlV3RrN0VnZkpZSEJI
        U3NpbUVTamU2bEV2TnF4TGdDcmFDS2ZGNG5FOXBnTjFzRnZ6VkM4OEc4Yll0SkQ5
        L2lydWo5TTdQcHRtbkZNa0JkcHg3OHRPd1VjQ2x5Z1FOT0kwYTJ1UVdwd1ovTHlE
        b2xJbDhCai9jTzE1STVzQW1MS084dFlhbjM1b2hMMlRNMDhWUHQwTk1HaHZZVEVs
        Y3pYMTNMdkUwdGVlKy8vVUcwMmMraTBjWHdWaDZObHA4YWR1Lzh6STZSdVplQlpl
        VGVIZHZuVnNFaGFTdmNENHRSN0NzYkhPMWhqdnEvT3FuUU1jNkpyT3RyM1ZWR2x2
        aUU1OGFLWHB1bTlMSU1sZmtKYmxjWEYyT2JXN2dhNExZSmlpVkQ0SmdJQ1dQUzBB
        TTBDemt6NTYweDBWZ2tXb3Q1b2JnQnBwVFNYME5kaE9Dc3E3cElOZXZoUzRPdUli
        Y1M4Q3FiQ3R4a2c2R1BxQy9ML1pRdnlxQzNSM1ZMOHZQZlY1dHJ1VXdDMmphMjk2
        VTlSNGI3aEhYUzVUc3dYcnpvSVFpZ2lMOERjeEdCVHVQMzMxZ3FtRkdEZEkzbTE3
        RWdkMHdZNUxOSU5YbFROVzVOY3crc2RrSGl3bzE1OFdvNlF4U2hhNUZKejBnNklQ
        VjZzT1NQenhjcHVWY2tEV1VReEE3L3lFVlV4VWJFQmR1ellPVjBXRU1QYml4Rmd4
        RGoyWHpTbDhqZVl4MmRpK2JzdU5BNDJ4K0hpZm12OWNuc0hJSloxdDBzdEw0dkxy
        dnJDdlNFMlpXbnU4ckVSR01Gczg1Q2tVVkZ6Y2E2c2h2TTRYR1RGRUViTHJIdmM0
        TUF6TXV6dWtWYzBPQW9teGF2Z3NtNWFNNCt1QXNVTTJobGF0NHZHWlRqczJkNmMy
        ZHFMcW42aFlYOHZrSHMxWmp0emovaGlxK3lwc0ZEUWcySExITmcxRXdtYW9ob2FY
        SDlhWEFsQWo3UlAreFJvR0JpeitLQ1MwWmZueVRwSFgxSEFaWi9RbkRzNmxXUQpv
        ZUdTbjN2Uk9tNEozQTNhYWI2Z2xaU3pOaENSL1NNaGFRU0NrR05WYWNjCi0tLSA1
        T1J5c2U5T2R6MXgvNEEvaGlWVXJySEN2S3oybnovK3ZnMUJCSWh6RzVRCsvVISXo
        2zDRSl3lan8qjZnXUWUBSK2vBkpvjrg6ghrmUG0bbo9Ul1y4EvE8Uz/q2VkTBIx0
        gjdwHscguXLb6tw=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-24T17:01:26Z"
  mac: ENC[AES256_GCM,data:E/xAemw63XRv91ETQSpe5CuuqCI47PREDsvKIrcfwfWS8PatBjRJxAwiD2A0l3Kj+Fg7fxMtFYvMATMFfPdEqCDgtZ3ntb51XRY/cHR+g4fPoxqvr/7Mr3VCYbGbtDxXIUKTdRSnRlTsrknEfoIsF0g7dkVN2WTPqxmo2P1N/50=,iv:VrVuTTVh9PeYVY/emsV1a2bN2cxRFFu1kM1++/suVSM=,tag:iSkfKow0D+qz3iDCK39kcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
