apiVersion: v1
kind: Secret
metadata:
  name: foundryvtt-secret-stijn
stringData:
  FOUNDRY_USERNAME: ENC[AES256_GCM,data:8/2gpWs=,iv:tZx1zp49JnmlOlBP3NlgCUtxPdy2sXBxJxMSDLGbAhY=,tag:Cnu5W/jC3ZxIOVYjaR4wOw==,type:str]
  FOUNDRY_PASSWORD: ENC[AES256_GCM,data:Jz4UFlUYl4ofQ5ZMRFbp,iv:8UYP9XeGp/gVEEe2GCxWX0sFvQhi2M5WmPpsdAUsADs=,tag:BR60OAjAV+hqj/hn3CcxTA==,type:str]
  FOUNDRY_ADMIN_KEY: ENC[AES256_GCM,data:XD6JaLBnAD/u8P6D2j5pPevOrpQ=,iv:QUFVhwtBoGn9avUS3cb508EhThQqBemk8zy5JC6myiw=,tag:6UMUKZmijBbLgR1jujAomQ==,type:str]
  FOUNDRY_PASSWORD_SALT: ENC[AES256_GCM,data:of7shkFsqKBiiZmyNvnGKwOiy5ns45SKz/lQmwgTLACM,iv:OHoz1pN5wo/9Edy9/FSMHDz/cj/6aL6t+UW01dh/mj4=,tag:baRqGfDe2ARxwmQ1fRtvQA==,type:str]
  FOUNDRY_LICENSE_KEY: ENC[AES256_GCM,data:L2ywTn6Un0n5JbvVqAIAJt3XxW6DNanvrosh2P8=,iv:RAE2+M6xsuTV/SoK9eCzD/Jl+PQJDaSuZmfTqfyDRwY=,tag:JG/3PZqrAlx/ZROLCNrkJw==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpamd3UWdXTGYrNStVTFBF
        UjRpSDFudEJuL2oxeGlVa2Zkckp3eTJCMGxBCk9wZDZFcTJTNllkUlUrM1NzWWNt
        N3A3ckpJYkl3ZCt2ZWFvSm9oak9qVjgKLS0tIG4ySTdZVElpc0hIQXcrUVZxVkV5
        T2ZYdWRMb2Fsa3ZCN2QrR0NXV1Y5UGsKeK5t0M1h9mc+fRLLUsKDHh0vNozL9ch4
        5gW4+5hJmGZbeuIYnKXeODzh4CKT5VAxrmhdoaTaSSXoZiyvdSvhuQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGFOWlJPbzBY
        Uzh2U2l2QTFENzZqQmduazFQbUFWVk1NZFF0RzFhRk1tVm9ZMkJrZUVyTi9NeE5v
        QVNySnBpSG0wL3BuREx1ZW9IUW5SaDlmc2tyUFhBSUJQMFRaS1RUblZOUldvd2N0
        Vy9qRkxyLytVUWovcnhkelFoNWVQRDNWcnd3K1dMUVFHZU9ReVppWGJwVW5YVVFX
        ZTdwckdqc3crVXdUOVh2Nm01NStLZDlXVEc2bU9qc1dJMDB6UXJhWWVlbmcvUXla
        elErUG91dDN4NFVqSFdVdHVPdkNrSnB6Z2djMjgzT3VSUU9vVndrTERYMjdhM25k
        NkVWSGFmWWlqQndVZC9RNWhSLyswS1ZjaWgzOHIyNVN5Wm9sc0dzWUZtRHV6dVR0
        Vk4rd2J5RVJERGxkdStabWRqL2FRQ3BublJnK3RsdWNiNGdsOXgySElvalJOdHFJ
        QzJHcjg2Q3liOU5vZnBOQXlIY3RYd05iL2ZlYjBkQThJRmdvZHhVV1FWc0xoSWZy
        ZmJlRW5xK0RKTUdmWVBEUWFiQ2FpZG5TNWJSRmNtd0pMRU5GRE1HQ280cFlFSVVm
        RTFxOVBqbmNhSUhPRGdVQzU2U2g2ZWtvcHdJNEk4bEZVb2NKVVJBZlY1c1FJL0Fo
        NnpyM2NOQXlJQXdQQmRqdmN4S1lqbzVUMGd0U1VQTWJTanAvN1VzbUZoS0tWT25E
        aEpyWXltdHBYdFA3UFZ2WEJpSVRGUFlsem5NRUZPSGxPOEtyVXZucDdOUEwzY2lI
        SDk2WS9UOXh6Zm5oaFZGei90N2Y5UVYvLzJMOFQ2MndORWwxSDV4OFMxZXJxcXpH
        TXd5WmEyNnFTTStkUXp1em0zbTJWbWRmeGRDeWhIM2dqenVOdVNRMWxkYTJqZWJh
        K2tLb3VMUFNKblFQZ2lhOEN5OFh3R3dXRGRVMjhKc2N4U0RyRHFwdk5OeWxaaFZY
        U2lHSnYxWk1YR3VrU0lrQzM2Kzd0WEpxQnNHODh5cTFjOVU2RGlJY0Vrbm9WN2U5
        UWRjSG9jSmx2WTF5VUROQXo5aUdBZ3F3SkZiczczOGVPeThrU1NITVFyQTY0VDRw
        c1pwcVV2ditabDBQMWh4eHdKdjFWMlQyN21RVURuYkZkM3FjYm5QQzhpRUUzbG0z
        OVhrQUxCT3B2VHJUTTJRYzJ3aU9YZU1ZTmZkRlEwbzZzUUpaMHV5aTJmSHF1aTRM
        ZUtEZmlvZzRydFM0K2tlZHVyaDc4OHBQdEU2c0h3OHZBVGtsWHhmekFZOUZFNnhq
        WThCTEZKMmM2ZmJwUG1wMEFnUDlVSHorTlp3SnJDUFBHQUhwaC9ldTBnclNDeGFk
        dXl2Z0dFVnNmUmJrS1ByeEhVbkd5VDl3WC9pelcxbkNGSU5FVGRKZzRvajlFaWNV
        dlRDRmhBdG1HT3lnVmwwZ1NDWUpNc1FKa1JKdmo5cnJIYzU4U25KN0d1WUROZU1t
        OWNxeHFLMTJLV2xqMXpWdTB1RUJHaDJ5NE1LcTlieUF2V012amRoZEpvTzRiejBS
        V1JrTlBaWjJsTHozZGoxSHd4SXJ2enVHRjVadCtwemQzQlhnUng0Nmp4dFV6Nlll
        a2pVbVBnVUMrK3BTWks5RnNDS2lmTEdPY3NjeDU2SGhaZ1Nheng3SXN1YlNmcEMv
        aTRJSnZGbCtqcVV2VWdUL0tTYzB0NnUwYXVMc2o3RmpSRFFnbitMSWRmYWJ2ckd3
        WGlRa3NqaHRQZnZHeDZOWnFzQ0NTdFZseW44cS9RRzYxV1hLamlodURQQVl5Mnh4
        MTZzU0VRNUxyUDU0dVgvd2VGWm12MW9UVWFVSnVWcFBWR0pHWTRvKzA3MStLT2c4
        L2Q0bjZiTUgvZS80TmFuM1BYTjJQOHlrRE1TNGJxZFM3a3JXbUlLR1hnM3BIU1lv
        OEtUU1F2dFhvc2J4UXVueFRTZEdnUnBmWE5Pdys3WGY5OU53Zk1Ba3hjNGVIdwpJ
        d2Jlck9VcGttdGJPRDNtWVhDSytZY21TM25uNjZBR3dEaWlaZm1BSjFRCi0tLSBj
        YzhFczBPRnlVTWRJYUFiYU5LaGp1ZHFVdS9nbkVBbENyYVF6VEs5ZVlNCqyS40HT
        qKITNOQJvGnWa4xlulDRClSFSpfldUY9inQsto3WQVp4/nW65TqmNDYTCtN7vFGo
        eV7sDWBmrv4/9e4=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-24T17:01:26Z"
  mac: ENC[AES256_GCM,data:E/xAemw63XRv91ETQSpe5CuuqCI47PREDsvKIrcfwfWS8PatBjRJxAwiD2A0l3Kj+Fg7fxMtFYvMATMFfPdEqCDgtZ3ntb51XRY/cHR+g4fPoxqvr/7Mr3VCYbGbtDxXIUKTdRSnRlTsrknEfoIsF0g7dkVN2WTPqxmo2P1N/50=,iv:VrVuTTVh9PeYVY/emsV1a2bN2cxRFFu1kM1++/suVSM=,tag:iSkfKow0D+qz3iDCK39kcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
