apiVersion: v1
kind: Secret
metadata:
  name: foundryvtt-secret-stijn
stringData:
  FOUNDRY_USERNAME: ENC[AES256_GCM,data:0PHyv44=,iv:tZx1zp49JnmlOlBP3NlgCUtxPdy2sXBxJxMSDLGbAhY=,tag:YmT3g0y/Hzr80NgkrpKk3w==,type:str]
  FOUNDRY_PASSWORD: ENC[AES256_GCM,data:BWlOUcBL90yL2SYTUe4y,iv:8UYP9XeGp/gVEEe2GCxWX0sFvQhi2M5WmPpsdAUsADs=,tag:Owl6qNeDoIakoO4lg0RV1w==,type:str]
  FOUNDRY_ADMIN_KEY: ENC[AES256_GCM,data:qiVJF9pO/88MSXSIQPI0MCeCuGU=,iv:QUFVhwtBoGn9avUS3cb508EhThQqBemk8zy5JC6myiw=,tag:yX003EBdOMrzlyZNLK1J/g==,type:str]
  FOUNDRY_PASSWORD_SALT: ENC[AES256_GCM,data:9jisldNFwZvRxlvGrVhMwWQMcRKSZIojEuRqwH0hUHbb,iv:OHoz1pN5wo/9Edy9/FSMHDz/cj/6aL6t+UW01dh/mj4=,tag:Md6d3Wo0SKe6no7D/rSsRw==,type:str]
  FOUNDRY_LICENSE_KEY: ENC[AES256_GCM,data:z5oIHaOlCuCW2Fgs2KIilXQI9TzHV5q1xFujwgI=,iv:RAE2+M6xsuTV/SoK9eCzD/Jl+PQJDaSuZmfTqfyDRwY=,tag:T+hsMrn3pqvkPVBYM/IkJA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGVwMjdDODRq
        emlqTGpldDM4Q09kUVE2bmhCTjFVV1paYzFwd1plYlp4NEdYSUwvWWdGTFJFQkFn
        VnZJeE5uL1ExbU83YkVBcUVSOFQ3c0wydERlQ0dvOGV4bkdSMGRnYkYzNDhNdldX
        cFBIRCtOK0dyRmF5S3NqVjJMempjRG5QdE5TSnpsR0hiRC9URWIwVC9LbjNYbDRa
        MXR6UTlhL2tGblJ1cWFZdElVekIzaUF1Q0VPRUVOSVFOakxjT0RQYWNRamFzRDdD
        S2hpY1BVOHdnYVVac3ZtdzA4ZlpjejlSTTZaTXZpaE9yZDFCVnhhZEVnVFpENU80
        bmdvVmhmOUxMQkJhWkFpaDl3bkpXTG55dkVRK3lvTGgwUFpBOU0rUVpROW1wM1Q2
        SlJadEFhMzFJKzgvYnRwN3JDb29qcG5oU0RaOW9MRHlNN21JeVNPRmpFZm9sUmYw
        UkdDSHdZNE9iMmo3TC9wWEFQVDZ0WmZqOU1SM1g5ZEZDZGh6S3V4RDNxemZ1Ly9a
        WkZlV1JGN1pqWHlJSTkwWXBzUXlrYlN6UWhvOStDK3FtVkJsdHpSMXl4bXRwS0Ns
        dG01WkxmdTV1Q2QzVVRLZGZ1UWxEUmM3QWZ2UzJ1cVRwSXRveCtiYnVucVg3Y2lB
        cmhyUHJrano1aVd2aklGM3NlWWd2YUpreU91eVBTZTFmZ1RXSS9QbVlMRDdrRElv
        SVdPZWdXUzdzVUtxOGFNY2ErUVZVTVNMWDVWSVJHaG5QVUE3M2kxaFBxZ0syalRL
        aVFlbm5YZk9UVFBqOEhiS292U2ZoL1FoMVpucFg0VDBmODZ4Z2dJcEVFa2pCQUtX
        YUFNd0l3b1p6b2FYVDhDUW1YcEtRaXJvMnY0ZVZMYmd6eUcvSURwOHF6RExqRndn
        L2hjbUczMjFBY1JiZWdsa1ZLdERmOXZPZ1JIZStKUDhDNWlsSUc4ZzkrcU5EWThl
        OVpTTHU2UTBhMFVRU2xhNzhUZXBBR1NuODJHZVp0eEtyMFNJMVZjWTZZaUY0Yy9L
        bEFaY2hiZWJha2NRdkdiSXJrU0k1OVNkRFEvayt5blZTVUhkOVZJT2JWcXFGR1cw
        WlM3OWFQR1NiT0E2MzdwNHBueDVHOW43UkdXcTJ5b2FGOXBoUGUzVXB2K1F3Ulcy
        bWNkWlNkWVdPMDljOVl3ZHlKTDlXd2l1MXkycW8rb05oMUk0V0tUQ1hLWWdRTVc0
        cVZKVk8zWC9Ic2VnT04zMm9TaGcvQmpyV0o2Zmx0cmFNS09KVFdDT2RHdWdiaGVG
        bEY4eGdVOW9SM3ZxNGo2cldtV1FIcnB4TzNsN0puNWdkMWRQN2tOT3FLdXZjRkk0
        dG9RcUxwc2JYNW0yKzJaczQ1Qit4Nk56ZWdHQzNkWUpmY2JuZmZRNjluczViSWwv
        ampzK1RNRHdMaG54aWpBNzEweDJ0bERORWpJWTVjdSs3U0pzejEzdm5JRkd3ODFo
        WTFQa05TMVVMQjNJdGszNmNVVUZKUk9wbzk0bFRqTlMzRzMrenErOUtLaDIrKzNT
        WXVoVXJjcGt0SDMzSytKUHRzdlAwTUJ6OEJsalZHTzhGTkt3ZFhjRWp1OVMrdVhF
        djlCQkVud0prYVlETXd6MlRmRG1zQ1k5ZmovT2lTeWx6ZTJRREY4dkN5dkdRelda
        dVZQS00zQUZZQktrdGRHUVRhdnhnbEFzSG1OQjEvVVhhbHpXOGlCLzF3S1RIdVo4
        OTRnMTBBSVVHcWpQelVWczcyamFLRUxDVzd5UVRzT25sSHdXbTlEK2hkQ0xlSVJN
        S1gwbmNYUERkRmpqSXdkcFJsVVJra0pMNm1qazNkZW81aDBDMHFod2VLb1pnNmFo
        VnVFS25rWlI3eVowb1BUYytwNjUvL2JJVjlGcU1VVjVFUi8vM3NScXo5VjZqWUJZ
        T014WUZBR0lzUGIrOE9HdUt5MFFGc2dZSzBsbGtYdUJlTlZDNE5GUnllSWxRUQo1
        c0h3K3ZOZzBQVk9yWFRXcVhNelhzaXd0R3VHZHhsVE5Xallrd2lXRGswCi0tLSBG
        Vlk1VFQ3Y2EybXAzaTRzdHhzS0d3K1huMWo5MkJNbzBoUXI2RDlUQ1VjCqQcR2hh
        VRTzjO6FxsBdYVbnQg99lzrkNkrfIul1PJ2DBclyOaHrSnblCuo6gql/R51iOhgm
        ZaJsxS1z/DAFBww=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:35Z"
  mac: ENC[AES256_GCM,data:uhL1DRGB9WnN93RGGgGAhCM9zX5OgNz1UprTuTWAfr2r7azDwkgnIaqQseN6wjl0GLyMhRSDDhvrJenp51WBRa4eq+YOrTLXZSBpirpXg1F67JN1K6ryW9Q2xw8+9Ra78WQ+FUEdsa3zUOg51lNj1XEDUYeOAg0OjDHX31MxonA=,iv:eLEU7VCj1WTdyLWmrB3gdEA3jUnUFTNFLZJKPN+8gi4=,tag:oV0+irNmri6BVUV86NBsCg==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
