---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./jwk-certs.yaml
  - ./clients-secrets-base.yaml

configMapGenerator:
  - name: authelia-clients-config
    files:
      - configuration.yaml=./config/client-config.yaml
generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: ./clients/gotosocial.sops.yaml
  - path: ./clients/continuwuity.sops.yaml
