---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#   - ./block-local-eg-netpol.yaml
  - ./secret.sops.yaml
  - ./app-template-repo.yaml
