apiVersion: v1
kind: Secret
metadata:
  name: restic-backup-secrets
  namespace: default
type: Opaque
stringData:
  RESTIC_PASSWORD: ENC[AES256_GCM,data:n0gl0kYC0GN6dSpsDddxHtXSZ3lZ8N7rZWrfwIAIE6IkWyRoROokXW7GiR0s,iv:vxXgSI0XBuDAVmOGxTDpLTx35CJyi8KeREhoNlsjwQs=,tag:Bn1xrQKbnIj+XfYDTxp88w==,type:str]
  AWS_USER: ENC[AES256_GCM,data:su4L54964IMn1fNv5emzMOo=,iv:te4PDlfJuh7htFoYe4sHqN2JcknPHege6UirhSrv6ao=,tag:hacSZn3P3Tq8620DgJzYMg==,type:str]
  AWS_USER_DESCRIPTION: ENC[AES256_GCM,data:H5YCheFh,iv:wsr4n5mVe+KGMqbfHNHhYpjQAM+vGQh7vv1IGUdYNxw=,tag:p7AtEqxYr+tXy0Y7OOvWZg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:g8PmJ8Xbmffj+vEeMqzG+O9VoTwQ0uzidfDsSgjDBXc=,iv:tOFvn0Ba5yPx5linCpxWxLsus5EhFEvLt7K6nR91cvo=,tag:tAc+9eImlehb4C6rTHdvQw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ntHylQ+yZRwUx06JnWl4Caa/NLqm4tX7eQKx0+owvLI=,iv:QNFcVGsikwGyG8jVxch5MpNDn8Z0Fu9QAJJ2TgYV1Go=,tag:8iZb3q9b4ln4OXfxnRqE3A==,type:str]
  RESTIC_REPOSITORY_BASE: ENC[AES256_GCM,data:F3AN91wglgLmHTDAzqTUeDdADLtMrv3LP2C2lM393tf7aOtTw/4Y831F21M/wChdAnSxm3fZRVkj5TDv,iv:AjA9FDybqlKwBGYgHtZyv7bfXl36ei0cQ/MRfLU4C6A=,tag:Ub4yQRxxlkhTgXOOsAHF7g==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcktaUWVjUHVTdVZ4cmpW
        bE9zV1FETGJyMUFabkUrYXE5NjFvd1NnbTBRClFjT2xERGlkUUtRQlM1TStldGV5
        WFhXeTJ3K0d6dzZFN2Nnc2tSenB2SDQKLS0tIHppbyt3aHJoYmRNR1VVRCttUFd2
        RzNqa0cvN0g3RTVaZDlDWWZRcXFMOU0KndbGWvgDBDl4cyPPF2hABJgfrkOudwPJ
        ptyLiakIlgMSU7NSV2tzzsPI2sN2YYu37o0hFPuwJcRPjH2vUcyIEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-08T15:17:32Z"
  mac: ENC[AES256_GCM,data:NOYZSohQ8CcgTFa4X0qJwfE8Wrjh9dy1ApibqWTG2juCaYQdGMmrKPgtmMuq3W0lr2WcsQWrhk+1m1Z0MmXNFEZoolyT+MEG2ynvsOB3QrZSlJ7DoWOYog7I6fK5KUaJGoiCn3aMose0jQgo4jNJGeEmz32SFf89n2k4I9INLsc=,iv:VP0vUEQquYXGiCbuwOt2Bp19Vkefz7EA1RXRUTFQZ8o=,tag:kBgQ6euIWiBzP5pXMV2hFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
