apiVersion: v1
kind: Secret
metadata:
  name: restic-backup-secrets
  namespace: default
type: Opaque
stringData:
  RESTIC_PASSWORD: ENC[AES256_GCM,data:n0gl0kYC0GN6dSpsDddxHtXSZ3lZ8N7rZWrfwIAIE6IkWyRoROokXW7GiR0s,iv:vxXgSI0XBuDAVmOGxTDpLTx35CJyi8KeREhoNlsjwQs=,tag:Bn1xrQKbnIj+XfYDTxp88w==,type:str]
  AWS_USER: ENC[AES256_GCM,data:su4L54964IMn1fNv5emzMOo=,iv:te4PDlfJuh7htFoYe4sHqN2JcknPHege6UirhSrv6ao=,tag:hacSZn3P3Tq8620DgJzYMg==,type:str]
  AWS_USER_DESCRIPTION: ENC[AES256_GCM,data:H5YCheFh,iv:wsr4n5mVe+KGMqbfHNHhYpjQAM+vGQh7vv1IGUdYNxw=,tag:p7AtEqxYr+tXy0Y7OOvWZg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:g8PmJ8Xbmffj+vEeMqzG+O9VoTwQ0uzidfDsSgjDBXc=,iv:tOFvn0Ba5yPx5linCpxWxLsus5EhFEvLt7K6nR91cvo=,tag:tAc+9eImlehb4C6rTHdvQw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ntHylQ+yZRwUx06JnWl4Caa/NLqm4tX7eQKx0+owvLI=,iv:QNFcVGsikwGyG8jVxch5MpNDn8Z0Fu9QAJJ2TgYV1Go=,tag:8iZb3q9b4ln4OXfxnRqE3A==,type:str]
  RESTIC_REPOSITORY_BASE: ENC[AES256_GCM,data:F3AN91wglgLmHTDAzqTUeDdADLtMrv3LP2C2lM393tf7aOtTw/4Y831F21M/wChdAnSxm3fZRVkj5TDv,iv:AjA9FDybqlKwBGYgHtZyv7bfXl36ei0cQ/MRfLU4C6A=,tag:Ub4yQRxxlkhTgXOOsAHF7g==,type:str]
sops:
  age:
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGFsNDlEM2s3
        SWRvblJ5dmh2aEI0clhQbUcyL1dxem82bHNJVTkySjAxdDBkVmRLOGIyVGJiWDU1
        bnIwL2oyNS94eEtRcmhCRjFqM3cwQWZiUHBjdy9GZEllY3VhdWlRQkNVS2lpZ01p
        VHVVOC9NZW9PbjF3UE9KVjhzZFE0d2pDUllUUnI0OVpjSUNzWTV2R1gwTDhzYUd2
        TWx2cEYzRGg2NWxXbDV1MmFodU9IdkRpQWdLOFpRSXFBOVVGNTJ4b3RmU0YySWV5
        TENQby9jbnhxSDA4cndFaThJTVJJOVFNK2ZVRXJlTHllZ1F4cnFHeCtFRlhnbEcv
        NW5HaFpaZWl2blF3SzF4bnhQS0d0Y1B0V1h3WUN3TjBFQkxsdlg5dFdJYXlsZWFq
        WUhwRVdrWm16bmNycGgxOVNrTVJrNzBrYVpxaFlUTzlnMXMzYjZ2a3JBYWJJdHhz
        d0ludm9lYnJxMFNFTHlsOGNJdjVPYXozWDRQbFAzZFFaOXVaWWlNemJraWNjSm1x
        MUE4dmZVMXBVVm1OcWhvaE9TWGtzL1BHeW1tTkRoMDhkRWYwczE1UjZGNkc1Y0s0
        MXMreFNQaHVpNStXb0RvYnpRVllmcWp2VHNLbGROYVF5VlVFdFBUbTB3SlpBSHlt
        WmdIYjJCd0VOYkw2QStQdWJrOUVzUGpWd3dnamJlakxTQ0RZblVQOUZ0WjNTa3N6
        RXlwNFcxOEs2RFcwZjQyUDFSbldQSmpuSWphZzF4RmpNNjduZ1RoTlR5QWYwa2dV
        eDFEbnE0YkwxQjdBcU80TUlrVmhWR1Bnd0hsZ1NnL2dVNDM2UHlGdVcySldUSmNM
        MEpRazlIczhPYVBkck9nOVllWEhER28rYkVITWNIOUNxWTY4RUxDUGRNMHpTamg4
        cm03R1luTFRQQm9PN1ZSUlFhWGxVK0g1Y2FjeUg1MDM1SGNQcS82azRtenVmY1Ir
        L3hMbVpTQ1FJYWFUT2tDd2xjT1RkK2FRSm9meDZ6bzFhVUM1amlrYmJ4ZjNjZWpK
        NjBueXlFTGpja0szOEhLMEhndTlUZm5ZQmxwTWdmSTVqMkpBSmtsTnZsQjZlTnRl
        Nkx0RXpFeU1HMzE4cVNicTlNSW44ZTBNVldHVmJEK3dSbG4zd0FGYmRrbzdvNVJ2
        MmtIbXhlN3ZMSWUxQ09IRHZndGl5SVA0ZFpZVHBlcDhpSnpCYjlNSVp5OUFFdDI4
        VW9neVBweHFwQUx0dmJ5MDhmcU1ZS1lKU0hBM1NvSWhLR3I1Q29KTDk4WUhBR3B0
        Q2ZqcWZKU21qMjFETnVGRkptYkpXdzJXSVJFdURDMUpqVW5lVUMza2JDVzhRYUJl
        clhubUpabGlUTk5PZ25tTnZ5a2k4Q1dGWUdmL1J0dFV2Qi9RS29rUFNPUW1CODYz
        RE50RGw4OTkzZ0IrSzJvdXRFVFhNd3lRNWJlZFN5d2ozOTNtdXZINWFNZnBTSzVi
        VnlNVU16SGh0S0dGcHpoeDdScHZRVnRjSm5iZWhLMTh5TUxvUXRVQXdMUThISjJ2
        cE1CcEhCNkxpelZyK1k3VEcwazVSTjhqSDBsMkY0RmlsM1hrU0hsL3Q1T3dES1ZE
        UDEzN3J2WlpzMmplTk9yYTdiK1JCOU5sdHhmMkZnS0FsV3FFSjVxWmN3aUlNOER1
        SThZYUVzNDROTzdxM3ROemJrZ0xZWkdacU9ZVDdPd3ZXdE8wVXpaVjcrZE9pb2ly
        SDNHRFNGT09Cc2F0Y0xKd3hlUjhKSGF5ZjdoeS8renpzc1pBMTUzTXhtR1VmWjZR
        alZUL1hCQy9QbXVyc1kzbTF3V3paRlhTU2wzV2RscytKODhacnc5WG5vS3B1YjBO
        S0VCMFYzVlBRWklRQUdHWk9qdU1UdXF0L2VXcTU5RXNZd25kMnFXRG93YjBnQi9V
        dDRUWG9BQ3NUckRnejYxZjlPWWNyNXNTYzdyM0lISWVaT2I5OFU3ZEFLb3pQdwov
        eGFESlVXbFh5alZZZy9kaEkzK0pZVWhNTy92Y2dYMWRPRDhtaXJCc2g4Ci0tLSA1
        Nm8yVmZ6VXduU2Naam5ISUlHQWpSWGZjb3h0eDBBQk1TS0RtdnNaR0Q0CpbiguFx
        JzY2TW0//KXYMeUkrSIl4I4ODcjglE+/DZgm4zXctJbFRMU5whs1BpoxjPHaDVlF
        uAM9p7C+ptYzsj8=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-08T15:17:32Z"
  mac: ENC[AES256_GCM,data:NOYZSohQ8CcgTFa4X0qJwfE8Wrjh9dy1ApibqWTG2juCaYQdGMmrKPgtmMuq3W0lr2WcsQWrhk+1m1Z0MmXNFEZoolyT+MEG2ynvsOB3QrZSlJ7DoWOYog7I6fK5KUaJGoiCn3aMose0jQgo4jNJGeEmz32SFf89n2k4I9INLsc=,iv:VP0vUEQquYXGiCbuwOt2Bp19Vkefz7EA1RXRUTFQZ8o=,tag:kBgQ6euIWiBzP5pXMV2hFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
