# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:vZV3hObDIJSAHXJLoIlK0SzuDhCnIdnScnAMg6zGjm9cPXpjwUcGdA==,iv:X52E3Dbcg+5h5YQiUJ28a3VZvJwfsJ/ASQXK1/0gU5I=,tag:Rtxj33zSZh1sY0dAX8VmMw==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNGc0VDlVNm9zM3NtNjYr
        cmEyVlBiK09pWE96YStJc29Lek4rM2VXcWtJCld2QU50UlY3M0F0SEtMTitOMmF1
        eHVxTjNpL2dKNE1nVVltS1l1cG9kQUkKLS0tIDcydnRtYnYxNEJVbnpGN3JsUjVY
        eEZMRmd5SWdDU2dVYk5XMUpZSVl5cUEKEiNijs1Hggl+Ix3/A7duxoWaobTJZgnr
        3Q79CVyHSpKLTPwLanxIYwL9xUp4Kq28Xcn8zk25bG6XfoDvJ7F2ww==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEVOSGU5ZzRw
        cWNwVGVINDVYRjNZVTdOV0F0ak5pWkN2MGtrTExIZEwyanpTVGVRUTRZamthL2xB
        WDYxbG1iVTJ5ZlNJU1R3aWl3U3BKRWJaLzdJeExBU3VXMGRxWEROWi9EWmkzbzh2
        NXRveURBOGNWU0ZXMFp2bEpDWjludzR4ald2aVU0OExJUkZET1lWNGxmRzUwYWEz
        TzBuNmp5ZkI3cnFIWUVkQ3BwUkhuRzhEWDlMYVViQmY2OW12OEp4U0pmYjNlK3FF
        YWhCdjBRWWJlRVZ4SW5CYk85THFoR1QyR1NQcG1nMUZCY2VQVU9Cd0Q4d296bzZ1
        dHF0ZEpKWUJHaVBtcXdWNm5oYzFIMzJ2dlFUbzhyUjdRRkJtU2o4dVlxOUhLYTho
        M3MwU0RmeW9ncFhkdnVaVGY4cHkxVnJCQ0JPdWhPa2xvYkZhbTVqdFhIdHZWVnBG
        VGxkOFdWMzhDZFVwZ0t3QXYvQjFaemwxQnNNbTF2MjVSZWJvS2JWUzhaVVQreEhW
        Z2hMM0JOUHoxdEhZU0tndUROdTQwT3Z1VVplbjFzdUYyTzlsNFpRTUNnbU1oNTRO
        N3o2dXhGMkVaTFdaUytqemwxd21MQlFWbFVWVzhobHVXclFzNkVHQzUxRGFwWUJ5
        d1V4OXkzQzU5QTBHM3dWYU5rQUM2ZGNmQzd4ME85M29qdzZuVVR4a1lqUnliM1J0
        d3VjY1hZSkJTOU1ZTkJxVnFjN0VCSEJ2dW43dDBFTWxOOEpjWURzWDkxd0xFWjFs
        S1dMOEg5aWZ1VW1IMU92SGpBM1BrbDBPeDlwUFpNdmRhQjErSjZlRWMwNVBzZTV1
        cmdGMGpsaDN4bmV4R3NZTk1DRzJ3YUdsU05VRkhVZEFYck1aZHdybWtoSmkvdXBR
        dHNDNTJTYytTaWg4d01jS3RraXlPRE5vUWV6bGZKUlAvZkJKZ2JNK0hFQ3J3UHhT
        WExmc0hDNkhYaFk2TzkwUTdMZlhtQktnbW90UHphcjlQN3R5Y1ZnTlFQYSs1b0hr
        MmVZVGZHM0lLb0doOERhSjFBaHltSm5GU09VVTUwTGVGR1FxTEs5VHFjanF1Zy9W
        amZiNk5yUzJjZDMzUTVxY091THBLQXRUTlNURGltWVVXNzZIcng2NmZzZmlHdmdi
        dE5EaVF0MjhQWGFWejVvbktodVpSV3dHSXA3eEpIUDZnb1lacHdGZE5uQjMzTHkx
        cEtrOEc0WEk4SnRDYTBoM0poMjM2VlBQQW12RE15RG4rbzkrWXRmVVBXNUJIeERY
        cWM3RHJuUHJORFdieGlHRTNqd01nMjV4LzNQM2thMzBSQzczM3lPUHdnd2prSFdU
        OVBtcmpST1RTcXVoSVRJTFVjNGR5MDJScEpnbnpldTNrVXhnc1c0SHRrZDBjNmVh
        Q3N4NU9tWWtDQWloZ05PMHNHb05VTUdZWVB6SXpaVldRM1VrL21GUklaSE1YYm9q
        d1prWXJCdC9ub3UvcG9RcHBDSjhWa0ZFdnU2SVBaNHYrT3ZNOUZKcm1DOWFpbHo3
        U2pSRnRFNGE0ZmFOd2NrcEtJakRQdUhGUmwzbmdZK1EwMyttZVVVWEhBVVZaaHk0
        VDJ0c2F1TmVRem9hbndlcjZmbW5ocWRtQXdSRXhDUzg5YUlzSFhKdy9tbCsxSjdi
        by9JdFVuL013MDVtYkt2NGZMaWI0QVAzVy9rWXpOeXhuWnRXU0pEVmxUNE0xaFhu
        YTJGZWdTYy9BeEpMcmw2UDZKSVI4SXkyVjNOaTRQNkgwWnl4SDk0c3g3MGVvSUhv
        WGxKSXJnRUNqck5aUWdEbW5vVHBRMVBsWnhwK2h4Nm1uTTZpdmZ1OWJvNFhiYUpD
        bU02TE1aVFlOb3JrL0EyS0NNY2pQUTdIYm4xNU9GM0lWVXlxazlpRzhRSDlRT1Ex
        NC95YVppVGQ2TThwZWIvTjFzcGt5Yi9LY1dQeVByT1cyazhicjE3cnJ1N05lUQpZ
        TnZESW9sL2w5azUrWHFDT1phV2o1eWcwaUdtSXRnRHRFRnBjZEh6R0VRCi0tLSAz
        ODhzM1pWS3JsdzRyRjFiZUt6dGZ6RnNwUkpVSkdTZWJCa2p0eVp2OHRFCkVU18zZ
        JQfdp0dS9QGh6kcrITUVfKJfwtxL6ZQsSLtZcnSUJe8CceiDDTVaUqDt63lMzkbT
        i7ScifRdE2bonCg=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T13:53:50Z"
  mac: ENC[AES256_GCM,data:aqCytG77zZ/M7mzRaJi4ESlku6Tv/tNA0Li0q8MDgNIwnhFW7gePirERmlRKPCvvHK7mHdlzIVNLysUGNa+FG4Ja8EplWIbi0jF09p8UAtVqo809gO9Yku4XLEq4sdD/Hnqs0xZalB+t8cFZH6YO/T6bOtTeeTN+7/01myTp5aU=,iv:od28eztZ5UFeARGA2nXgeCCohCvLhyxdZJuhMtbDijg=,tag:Sjtz6VhQdnLbZEAWIuDAqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
