# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:c4/BggrmE9Fa2kKprWJ0vaVt+G1/gMeT41MNmcWM1K0KTEHgU/AOXA==,iv:p6q+14NO5Rrmn5A98sHoKvZ4zFyfToxOqbInCugZjIc=,tag:nbStiuYWABiCVRdrVOS0Gw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Y0hkdCtweFY0aG5lS2Z6
        cStYUCtybTlZL1hvbys0WkhPeUVyL3NRY0ZRCmQrVlVGZlJWR3Fva3JrK0l2eElp
        dklkQVZmRTZnUE9YMSsvaFh5Q3BhVmsKLS0tIEdQSkhHZDV6aE1HZ2NielpkWHlK
        MmNYVHhZb2ZMWkRORWpHYlBLRi8xTVUKLqYI989h+YqfUr0+jR/tcGjyrsEZeYO2
        2tXn0VoW/cqqYhIbBE+VCDvtlKkbmF3B6lDJ61wUaAMsiPI6fr720Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-08T10:02:50Z"
  mac: ENC[AES256_GCM,data:jdtqBKF7tFV6YUeINt4zKxJgvKfMSm3GA2PWxne9vtWyYykGCBVglcykDErB43SQ1c7KVM6lvmL6dAfQMr8MCWY2DbZUosRynI472qLQl9ocNOxp2FJoWlgJmPGsnJzNEXYgmNEnKjq/fejbSNbvgZdXciutNjDuJtrw3eNg5Po=,iv:COyRej//OwI89eR1kZNCgbM4sI9oCa8z9IJkljyfvqM=,tag:VHxy0KXnGvdIS6n5dYQlZg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
