# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:vZV3hObDIJSAHXJLoIlK0SzuDhCnIdnScnAMg6zGjm9cPXpjwUcGdA==,iv:X52E3Dbcg+5h5YQiUJ28a3VZvJwfsJ/ASQXK1/0gU5I=,tag:Rtxj33zSZh1sY0dAX8VmMw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M3k0b09CWm1Yc1ZreTZz
        eFk3YjIzYytZUU1oZHpnMndxYTd2dzdNMjJJCkN2dXNXK3laNzRBOWl5R0hpcStu
        dFFSemQzSVJHOVBKOHBBSzJpZzVMbk0KLS0tIGo5QzZOUW1sVlNkSE5hVlpmYStu
        cGdlTTdaTzVYY2RsbXhMZnByOHdOUjAKRwmZHOr9vB8JZA+FwVdPGwgGwfpp3h1p
        qPEnoXu+mCdudK+M8ixcFVtOfuH5+H6naBE0d85cBLRmvXZcltnLCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T13:53:50Z"
  mac: ENC[AES256_GCM,data:aqCytG77zZ/M7mzRaJi4ESlku6Tv/tNA0Li0q8MDgNIwnhFW7gePirERmlRKPCvvHK7mHdlzIVNLysUGNa+FG4Ja8EplWIbi0jF09p8UAtVqo809gO9Yku4XLEq4sdD/Hnqs0xZalB+t8cFZH6YO/T6bOtTeeTN+7/01myTp5aU=,iv:od28eztZ5UFeARGA2nXgeCCohCvLhyxdZJuhMtbDijg=,tag:Sjtz6VhQdnLbZEAWIuDAqQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
