# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:JHsAlfO+svkHG7R3BSiJi2u/vpjFya+xbZMUml0dw/DSBoF0xK0rdw==,iv:JCXuY6+e7qtTG/dEAZ0n8JkSy9oKwhqK/I41j6qBvmo=,tag:ivAOTJrrnOTQNK4Htok0CA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaS9mRGtaT2Y1WXFmdTdj
        MURNQWx3N0o1aUJiVzlPbTEyTDVRSVBJRTJnCk5zd3VvTms5bGhyOGQxcGRKY3M3
        NytKU0VTVy9iN1pLNkFHNE94cGhJN0kKLS0tIFN0aWhyR1dza3lBZEZzenlqcnE5
        aGFJYVEzcytidkRpOUhTQ1RiaGVVcmsKQ78AFXJ0VJYiEjFGPCSWddmmEvvtbuZn
        MWUib4z9u+4JeCtzTzvuOFA3CK/Q9DCZ5tzMMO42C+yuzrg9qVwNqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T13:38:34Z"
  mac: ENC[AES256_GCM,data:FGW3W7ttKL07NYjiS0HhHK4GtU1JQR8VWyXvKxPsxLiSctJ/dhNtz89bopBGQ7DQuSau9tJLXaqGuhhYzZuZjuDAlA/T+hdaYPPFTxl5RczAJNZ+8Xh9ULtyKAfEQuCOsTZAgmHWWzoLkTjCYr5VK4AEM5jJO3TLOcnamYJf1Gk=,iv:7rbilP5hH7mQMeVzmMpUOCjIwbKI8TUcaq7Y7YMJFzs=,tag:sK+Npb6FMNFQY7/r7dw6FQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
