apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:OsNEbA==,iv:w5MG3rzT/oGBNjagSgBsWOs5S6yPJd90zpoVfZrFG7M=,tag:QtR6lfdwjcKkXW9tCfYDDA==,type:comment]
  LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:q12wdnqJqL7QW5VvuSRRBwtE,iv:DMdDn9f72uhsOgv9TjF98t+89dolPF1pMjJ8mFLLh20=,tag:ri+xjjkKcPj20rFiKBHOyA==,type:str]
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:nKi7h0/LP23IXg6GW7euZx1pFScCOVZ79kM/drwLtvo=,iv:YTvmm1QG4hE0mzPLfjZijo1+PLaYtv5sgt+orALno+Q=,tag:MzBQmwCiMbcmq+7GoowMyg==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:INbiOpNvhPGRkjwmi2e2q5NISbbITBb/94bgMkrBaYs=,iv:p7+xoa6WL/FIWVOhDOiLdtjzZlcTVtiAfejuoxb7xHY=,tag:hwIDRqSqi2cqBPrT+lmQkQ==,type:str]
  LLDAP_USER_DN: ENC[AES256_GCM,data:CkDvQF0=,iv:pbSfGV6k3jgikCM8TfI7GZIAjCl1qsH674SkPmQrFiM=,tag:w7Sb8BkZdQVVJJz7UJ/UwA==,type:str]
  LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:g0/vFKaL6QbHKDTRZgtDTMTlF9eVKp3Npfvev+o=,iv:BikIg6LbCuo79nMEMXMrK/RYEs6rK7HhTVRKn/+Gg4M=,tag:f/cEELhi0oNP2AoponlX9Q==,type:str]
  LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:YS1tXiIa/5tBCwB3xhSAD0N0idU8lJScXbH/FUbh8KA=,iv:Ia24/XPZd4onKie761HSdxflM5GO6+FHHPRhT47u9xc=,tag:8Fb1KPRssjhBUA37Js/s4Q==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:DzCHfv1g4ODqX1mMKRlFr5BYCSSAaequVDTn3hOmz0DKZT5arX86C4ykS07weWhvrtAhF2ZyVEIVqH4RKwYc64mJZoKucbbTjQA9tP2cmC2NXLrB7NsnJqc19f4Czu69,iv:O+2rMR0tefKs0NRRFJY97oIs5bZPDPNvMH2izhSuLrs=,tag:derI/oR8++faV+mN5AKlsg==,type:str]
  #ENC[AES256_GCM,data:z7Wm0CvHzvQC/f/U6vM=,iv:0WVi+171S2t7ksybqWmUcGe4HHbo/SA93/oFMbPdEQs=,tag:V3KsXte1yahCUl3DqHr7QQ==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:TiL3T8I=,iv:IfLoHNSxHvmGL6uLlq3FmfiAwjwTLFEW1644zWo6xYE=,tag:mcmgyu6FZKHPz+hXVAed1g==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:eK6argrv5fFHffRwMqBL9cZ1QAkUcfMXtiWeNjSJMsrITKui0/LHSA==,iv:7bGPWIsOqpjoiUt090GP2cZ3KqCFIRJtN0JizsOmXJg=,tag:vzYn+/ISsmqqm2qWd6nyHA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:2ksZo5c=,iv:ypZIqCUIJfALuebbfVXT3Cux+yg696jx4c/4opkAfQs=,tag:XH9pMACQtfrw4C0/Tin7MQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:99LVgGsshx8YkegZ6pCGjnEsPd7YTqXxB9OXOSobcuY=,iv:iv11DOSVOhAaTsL7a0/rjYmrXjcqeWLGCIOm088bK5E=,tag:fR/fPjhWtAKdaZagx3yG1A==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:tHNnLMt0gsixnssZbjOKTdVWVak5ZHxIuE3P7rU2Gas=,iv:eeoNe4djC2LpY9N3U1v7A7rEuQP9A2Fgh4MHG8hKbVo=,tag:I1qcIckNi3hIlUg1xzayEA==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSjNrUW9KSG9hNWw4Mytz
        cmlQVWVsSEZRUCtOdzROSFNRV0dRZmU2VENFCldPTkl3TTJDbCtRdE9uT0lXTVd5
        UE9UaUtEei9waXNKTDM4WktuckJReDAKLS0tIFJldGFiSWttQmliNi85V2o0cmJx
        ckZKb2o5WmtUZ2pmd1ZxRklMSFZsU1EKJn/Pzf0UA3qsXS3MNPbW0sHFYsbYHdNG
        Nk+a6EVAVWMw79NcZfbIz5/Zqc/vopj8nWeBYOToOtatPBHr7V5PrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-06T10:29:02Z"
  mac: ENC[AES256_GCM,data:okr5y8mGMbockV8ZbqTf7AXzHGat5bYVRGJFrNrqtRHzpyrFFlRnXjsp7Le49yR+mJN6baMvCtwLWqLzhJFhWBtzQUe7Pe0gCyFA8ocGEhLaMYgY9BqBEDV4OniZhTOD2mfIREkWSbQ9WJ0k8b0MhpLGkFrxtNWl8gZCv1SkMf4=,iv:V7QRO5l+GMGTpwfRHJLUCen5/5H0E9GVdUOv/6qC6r4=,tag:pssIvBu90+23XWnRIjhHyg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
