apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:xxrPGg==,iv:w5MG3rzT/oGBNjagSgBsWOs5S6yPJd90zpoVfZrFG7M=,tag:NQnfQOej9uwnB8N2dq9AFg==,type:comment]
  LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:u7H8mRcqcnA1I6obT9Bh1nBN,iv:DMdDn9f72uhsOgv9TjF98t+89dolPF1pMjJ8mFLLh20=,tag:zZfU267aKE0/wrD6x2OArw==,type:str]
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:eUVc4o/ofxBkUAGQQpMG/vKpzKrlf/aOL+TbYH1Y/QY=,iv:YTvmm1QG4hE0mzPLfjZijo1+PLaYtv5sgt+orALno+Q=,tag:gPxVY4Dhsog4eGpyzhMHOw==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:sZBasOFGtCoZlCqfryOB472S+sGbqhNzAwZ2Dkd3Gbk=,iv:p7+xoa6WL/FIWVOhDOiLdtjzZlcTVtiAfejuoxb7xHY=,tag:8PK9XqJAZ9C7nl451hD7MA==,type:str]
  LLDAP_USER_DN: ENC[AES256_GCM,data:V/6P5Po=,iv:pbSfGV6k3jgikCM8TfI7GZIAjCl1qsH674SkPmQrFiM=,tag:FkEnsPP05KVexxxvDEKjvw==,type:str]
  LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:WNVQqJpF5aQXUhCEUIQZRV69FTt5suwR8aowsxc=,iv:BikIg6LbCuo79nMEMXMrK/RYEs6rK7HhTVRKn/+Gg4M=,tag:Pl7NPJimlzurxmy7P2W/uA==,type:str]
  LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:E/xmNkXbnr3+naeYfcPOvElrok0nGobyn0lWwDzfUII=,iv:Ia24/XPZd4onKie761HSdxflM5GO6+FHHPRhT47u9xc=,tag:kkxD0dzAj4hDlgcKwxtVig==,type:str]
  #ENC[AES256_GCM,data:IPXBAUDJ2wM6YawMHU0=,iv:VgSBHV/S6Vwm10DgfDcvTeacy27cZ88yEfFgV8BynjI=,tag:xLY9AVDddHhTyxhWCf86gQ==,type:comment]
  LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: ENC[AES256_GCM,data:M8LpuQ==,iv:tMxe0syIHIZicwChLalUow4c7AJ07DAsEy3O1IIuThU=,tag:p3SNaAV+M4bPcASY9NfxsA==,type:str]
  LLDAP_SMTP_OPTIONS__SERVER: ENC[AES256_GCM,data:TbCxrE2dEPJWCqn7FH9zE2Cg2SI=,iv:0lyusHFmdc8wB4vjVnuuD8XBDzDMDHzNUWlFRMxvBtI=,tag:Q+TfAMJAR5xNKaLS7hvF6Q==,type:str]
  LLDAP_SMTP_OPTIONS__PORT: ENC[AES256_GCM,data:hqPs,iv:akPFXyJu13wmdyZABgr+LRb6Wfx+z4k46HWmB7y9UHs=,tag:74tJWm7qG1AARf0dikoe6w==,type:str]
  LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: ENC[AES256_GCM,data:BBJ/yHXBGG0=,iv:uxW3s+Nk1QpvQ5HFBj2DSSGhy7NuZcsl1nxtV/gVIWM=,tag:ZIH7JoTzkN+6vvn1d+g3vQ==,type:str]
  LLDAP_SMTP_OPTIONS__USER: ENC[AES256_GCM,data:LPsLpkyvEhaLWh7aERq0ASI45Blh0bIQ,iv:RpuKySKoeJBgtLi7Tl3SkrZ+/6PuAk7lKkLwMqU5Vco=,tag:kz+006IQjCAbJKV8TZk2mw==,type:str]
  LLDAP_SMTP_OPTIONS__PASSWORD: ENC[AES256_GCM,data:jv0hblQfG9v+yUiNy5NqzQ==,iv:NM21Q35d5i+mYAQrZbOrUUAnNO3Lgas8H7KZnXdTy00=,tag:oGb3U6JGUe71SpPNVV9+9A==,type:str]
  LLDAP_SMTP_OPTIONS__FROM: ENC[AES256_GCM,data:EcCXRkO2eUpfdjV51dQHFOfHEqVP,iv:rAYQTqe7ejSUJF0wACqX/L8auOk7DRJvxZNEk9LhxoI=,tag:I11eaFCdz80sPr7Myt0+lw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHNHU2tCT0ND
        SlpRNnR5bzJZWmhveERKS2pGODFIcnh2d1Y1UlorMzhlOEQ0a2wyaDFrMGVPTndy
        cEZKT2twM0xkVkhsY3RVNkpSOS9CZU02M3kxbnJybVAxQnloN2NUOVcyWExmZmx3
        WFVRd3UvTWVuT0d1d05LdTV3bXJTK3FadDhmN3ZaSTNkV3pqRFV5MVZBV1RhM1NK
        MVdTRWhkZk9wV1RXK1FFeTBxc1hQcE0wMCs0R2pNZUlsdStpczBIZFRsUW5NNlpQ
        K2tnNTFSWm81R2V1L0VQemtIU1RnVi9Mb3BtdCtKZytRUk1sVjRxMERuRlJrZXJS
        bjlkbTBRZWtraVI3U0ZwYlcvM2lVUXQvL2Jxd1NmSEZXcTg3aCtONXd4M25yQW1h
        V3I0b3hIS3N1eWw4TkNGYStldHo0a1NRbDByRzlzSEx3UjRhcUNucmYyaDZWVFZV
        RjFIU2k1OXhLMXhKaGkyL21QYVR2MGJXd2pUY24wS3hCdG1jM3A5YnVlZlpYWUxQ
        dDZ1ZEVZcVZvcTE2UzM0NmxvSWdFYjFiYnMrZzJQZ0ZKWWdKWEZwQk9FUGJpcVdj
        NkxHZGdQdVRrNVppQ0pzS1gzRGppWjlNNzBNUGN3R3ZGakx1bjRvY1YwS1lVMWN6
        MFpkV01XcVVlaXFOWUtqdHhrSGkyeFZGUTIyRjJFRGhqTFRyREpaN3NLazhtdFhV
        OWR0Smx3MDBFeHhwdW1XR2hMNmJDR09SRG9GRzBXRlA3dVdRVzFrLzlsUnFkK21I
        VDJCVldLUzBCK0pyL2o5LzlIQlo3WlJlcUNiTm50c2IvUlZXOXdaTjcxK3dkeWgz
        U2UyWU9wa2RDUE1rZzN3WlBURTJhNmVCakVrd1BqQTRFb0dLMThicHNCaHByZCtv
        S0RDaGhGZDhRK24rU2YzTHF5QlJVS0pYVGZxdHNSYzlROTRGRnNHZURRcytDclZV
        YmhMbkYrWVpkTVBjaTl2aHRXbG5GR2lLNjduem01T0U2ZGVVOFVmOGRUNDBzeFhl
        OFNaMEdKbnhnUldVNk5xbDV4MUlnTk1YMjFhSWEzL0doSFE1dE9FWTA3S0JkaXRa
        cUFMaUJDU0Y1eVdyL2VtRTZSc0FqMURNTENnVytVait6dVNVSmo2VW4wSmpBUk9l
        UkxsUVdwK1dLc2RsNjkxWUt3S0J2MENudDR3S205TE82WGFnTm0yazB5YnhXRUNx
        R283YkdZbjdUcUtMVWNtUEVkYUNJVDN2ME44aTgyZ0V3V0UyNjNCT0Q3eUpITnM1
        RHRIV0J5TGYzQmtja2pHd2Z1SFROOVQ2WncveC9zc2lidWVQcURtOUNNT25wTDlT
        NldyZTlqQnpaWXA1cjN0ekxwU1pVZWxXVTJPdXhXZ3lYNjF6bzJSaTJBbHV3eEs2
        SlNqVkNrTVlZSG5wUUtEbE85KzdYQzM0MEhtVGhBcXFQVGxjQUZVTHphRmd3ZDV1
        Skxva1VvaVczYzhuTmZUWDh6TWdidzNJenZNb2wzTFcxSTRjUWRMS2I3clFGSG9t
        amhGMExrSTROdHdYWTNNQ2xFZDZ5QmRsby9sdzFqQ2NsY3oyRlV4aU43eHJSODl0
        TjhBMlc1NnJRVVVPR2FmS3NwcmV5aXQrUDM4eVJCM3VHa2ZseUwrN1JrSlpZQmtE
        aG9pTFl3c1dERk1oVFJ5T04wWENKempuOXJ6WnlET29Pc1JDMWlNZVJYMmdvYjJI
        a2Vxb3dTMDEzOGYrN3ZYQmQ5NlVPVHFmOVpHZjV6ZGxUS0RwU0RwUmt2NmUybU1K
        dlh5eGpLc1VOQ3lpWmZnMTM0NXdTT1JCQzd4WG9udW8rN1VGYjVTVDhhTFNhVTZl
        bGhrVWZ3VHhuWEVEVktPNXdzVlM2eDNva1pFeGNic2xLWTlaNmRxRHo5Rjl1M1pX
        cllHNEw3d2VncllHSHFoMEkxQVpFU3NhQklXMDcrTStNazM3Wm5jTDMxQnJJZwpr
        NXBNeUxrUVZNWUNMNHN6TENBVFFLMkVFZGd3Y2dOVVN6b0lBeEJBdE1nCi0tLSA2
        azVJVFovUDNLeGUzL0RwU1RlcStDSmcxZWZQTnltS3Z1ZGxIOWErMGh3Ci+oE+9B
        0RB4BgqP7kMZD/O60+FzmamSxkiBIqwO+lnOwkzSOrnlSJh9WHUfLpsgjrDCJ1j8
        mwdp7zleS3UvbT0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:10:55Z"
  mac: ENC[AES256_GCM,data:1wSP7a9THFa3LHrN7xIyH3B2Bol6x/CmTvd6K4aecL5ZPbZIxRvQ5JQOXCiUS3jbCP5uZEqhu9JA1yc0i0YZtrtvvnkGGobbKI0Pk+EBPZ96HGryRDqmTdIR1f8DoEmIxv1bfWKqenw6xlVOPde2nsfXpWik7AiHkUDBhYFfXho=,iv:Zyvk7w750yr0FoVZ5OR7Z8SlqhR3C1kH9ZpgjQwNb48=,tag:6e8DFbh8UOXxGsDAJPZdzg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
