apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:OsNEbA==,iv:w5MG3rzT/oGBNjagSgBsWOs5S6yPJd90zpoVfZrFG7M=,tag:QtR6lfdwjcKkXW9tCfYDDA==,type:comment]
  LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:q12wdnqJqL7QW5VvuSRRBwtE,iv:DMdDn9f72uhsOgv9TjF98t+89dolPF1pMjJ8mFLLh20=,tag:ri+xjjkKcPj20rFiKBHOyA==,type:str]
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:nKi7h0/LP23IXg6GW7euZx1pFScCOVZ79kM/drwLtvo=,iv:YTvmm1QG4hE0mzPLfjZijo1+PLaYtv5sgt+orALno+Q=,tag:MzBQmwCiMbcmq+7GoowMyg==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:INbiOpNvhPGRkjwmi2e2q5NISbbITBb/94bgMkrBaYs=,iv:p7+xoa6WL/FIWVOhDOiLdtjzZlcTVtiAfejuoxb7xHY=,tag:hwIDRqSqi2cqBPrT+lmQkQ==,type:str]
  LLDAP_USER_DN: ENC[AES256_GCM,data:CkDvQF0=,iv:pbSfGV6k3jgikCM8TfI7GZIAjCl1qsH674SkPmQrFiM=,tag:w7Sb8BkZdQVVJJz7UJ/UwA==,type:str]
  LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:g0/vFKaL6QbHKDTRZgtDTMTlF9eVKp3Npfvev+o=,iv:BikIg6LbCuo79nMEMXMrK/RYEs6rK7HhTVRKn/+Gg4M=,tag:f/cEELhi0oNP2AoponlX9Q==,type:str]
  LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:YS1tXiIa/5tBCwB3xhSAD0N0idU8lJScXbH/FUbh8KA=,iv:Ia24/XPZd4onKie761HSdxflM5GO6+FHHPRhT47u9xc=,tag:8Fb1KPRssjhBUA37Js/s4Q==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:DzCHfv1g4ODqX1mMKRlFr5BYCSSAaequVDTn3hOmz0DKZT5arX86C4ykS07weWhvrtAhF2ZyVEIVqH4RKwYc64mJZoKucbbTjQA9tP2cmC2NXLrB7NsnJqc19f4Czu69,iv:O+2rMR0tefKs0NRRFJY97oIs5bZPDPNvMH2izhSuLrs=,tag:derI/oR8++faV+mN5AKlsg==,type:str]
  #ENC[AES256_GCM,data:z7Wm0CvHzvQC/f/U6vM=,iv:0WVi+171S2t7ksybqWmUcGe4HHbo/SA93/oFMbPdEQs=,tag:V3KsXte1yahCUl3DqHr7QQ==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:TiL3T8I=,iv:IfLoHNSxHvmGL6uLlq3FmfiAwjwTLFEW1644zWo6xYE=,tag:mcmgyu6FZKHPz+hXVAed1g==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:eK6argrv5fFHffRwMqBL9cZ1QAkUcfMXtiWeNjSJMsrITKui0/LHSA==,iv:7bGPWIsOqpjoiUt090GP2cZ3KqCFIRJtN0JizsOmXJg=,tag:vzYn+/ISsmqqm2qWd6nyHA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:2ksZo5c=,iv:ypZIqCUIJfALuebbfVXT3Cux+yg696jx4c/4opkAfQs=,tag:XH9pMACQtfrw4C0/Tin7MQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:99LVgGsshx8YkegZ6pCGjnEsPd7YTqXxB9OXOSobcuY=,iv:iv11DOSVOhAaTsL7a0/rjYmrXjcqeWLGCIOm088bK5E=,tag:fR/fPjhWtAKdaZagx3yG1A==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:tHNnLMt0gsixnssZbjOKTdVWVak5ZHxIuE3P7rU2Gas=,iv:eeoNe4djC2LpY9N3U1v7A7rEuQP9A2Fgh4MHG8hKbVo=,tag:I1qcIckNi3hIlUg1xzayEA==,type:str]
  #ENC[AES256_GCM,data:Cg4WP5ksSMOfGycOg6s=,iv:VgSBHV/S6Vwm10DgfDcvTeacy27cZ88yEfFgV8BynjI=,tag:QKRBVGxmjsN7y92D/ld2Nw==,type:comment]
  LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: ENC[AES256_GCM,data:lwR3KQ==,iv:tMxe0syIHIZicwChLalUow4c7AJ07DAsEy3O1IIuThU=,tag:Qbcm6IQNleS9/wCfGgjc4Q==,type:str]
  LLDAP_SMTP_OPTIONS__SERVER: ENC[AES256_GCM,data:lF/Yf58TEiCFinrR/dmJCMY0/d0=,iv:0lyusHFmdc8wB4vjVnuuD8XBDzDMDHzNUWlFRMxvBtI=,tag:YqKBpbotiEquKV8KnE3DAg==,type:str]
  LLDAP_SMTP_OPTIONS__PORT: ENC[AES256_GCM,data:FZg2,iv:akPFXyJu13wmdyZABgr+LRb6Wfx+z4k46HWmB7y9UHs=,tag:RGEXKNyjx4MJIpzY+SW+0g==,type:str]
  LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: ENC[AES256_GCM,data:ywutof9n8GY=,iv:uxW3s+Nk1QpvQ5HFBj2DSSGhy7NuZcsl1nxtV/gVIWM=,tag:fIjN1wDPnmdAXmK5KKaRvQ==,type:str]
  LLDAP_SMTP_OPTIONS__USER: ENC[AES256_GCM,data:wGSkEql2csuk5jCcARYfW+r+bj05VjqW,iv:RpuKySKoeJBgtLi7Tl3SkrZ+/6PuAk7lKkLwMqU5Vco=,tag:8Xs05VLWAgGSAVt+PHIjlA==,type:str]
  LLDAP_SMTP_OPTIONS__PASSWORD: ENC[AES256_GCM,data:4ED4MS9bejoLydPRPvKU6A==,iv:NM21Q35d5i+mYAQrZbOrUUAnNO3Lgas8H7KZnXdTy00=,tag:OSvDiDhik/k3gKkd8VMdIQ==,type:str]
  LLDAP_SMTP_OPTIONS__FROM: ENC[AES256_GCM,data:8gzuqCBTQwmttaT7gNKXIbz5LIov,iv:rAYQTqe7ejSUJF0wACqX/L8auOk7DRJvxZNEk9LhxoI=,tag:8kGWnOq6x/NN3wAhXLTSQA==,type:str]
sops:
  age:
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDlwayt5ZVpZ
        T2ZlM3YyOTN0dXpTRTlwaFdLTEVRaHF0Y3JKaEdPM3dNSFcxcUhMbm9BNTJrQ0lr
        VXhKMTRRTWd5TjdOUGUyZndjUHI5K0RuZlB6b0hocm8xVzBuNHROYTR6Q2FZVzZh
        aDlqT1E2bEEwdFJsdS84ZjJRM2RFUGQwUHBaUlc4dlVlRk81SDNvaGtnbUxvQm96
        cXA2WFdRVG5VZ253N1NGcXRSdTF6cnpwQURxK3JVbE4wWkpjNHh5N2pCY3orYk1Y
        a1FTZTRhUXNVN0NvdDVIV3l4OVlXbE90Mm1KR3c1RUh4NStPYjBlMjNzWlFFRnhv
        VEllWHBkdTdkcTNIb1dIT2dNVkZ4aGlMYXZkdDhPVFN4dlBmbFhnYXNHZHZGSDdO
        Zmg2SWpWQ0lvNnArWTNZYmRPK0RlU3lXWlJjZ2hBSXVKYkRtOVMxTnl2bFNkVlZV
        VDhKTUNDRDlLZXBLY2kyeDIrRW0vR3FLUzdwS296QldSbjRpTGFjOGp4S1dRWW9B
        U2lCZXVKK2F3SlVuYzFwNGs0UDRFWU1wWFRtOHVHYzRXWHBobnRHRTlPTXVEdG0w
        ZWk4ZXpFRFg2WExJUmtXVWpuc0N4bDJIU296OFliSXdlYVFXR2FZVS9pRktRdXBP
        eE9uWEFUV2pQSUoycVhkOXZPcHZRaXpqTldYM0MrWmZuc0lPV0pjdUhURjJJanhl
        Sm1WaTNGdkRzUEtyL2NlbTloM1NleVJmU1VQTTdPVTNIT3YvT0JHek5yc0l2VnBE
        dTlwb1JpaW1HN0g5VU55Q0w1bVA0WVE3WFlQSEU1UDZpakYrZnM3NmRTK3hQTkVZ
        RWRIWUZmS2xyMTkwWSthbFJJUis4VTYveHQ2dTNUNnJvckJPd09STTVHeE5kOXAv
        TUIxL05qSnN5dXBzem1yV2Q0eUtvWHZCRkkzUlpHWHZMN3BNL3RmbmxKcHNVRGx5
        dFNUVG5OSys4V3IxZjRWL3R4OTZZaTRwbTVpRXN6TVZuK1NzaGdrc1h0MlN0MGF3
        VnRYY2F1bUttckJjTGJFNGVqd2F4aXJpZWRWMXZiRnNPVEwrOGhFWVFHSjdPU2Jx
        QVk2SjFLd1dzZEdGOGNkcktiRWRlV2FZZDFHZ0RaY3F1ckd0WG5IV0dFU01rYVM3
        RGxHc1BXUG9oQlZmbGwvNzFTNUYzczZJR2NQeXJlL0xFUlZMd2VhVGlicWRuMzJK
        UUdxRmNqZCtUeXJMZjlTZW1KTnViWlFEWjJzbExBMjNmckI3amJxSStTSTRsQUFD
        T2ZwL1JGNmNVOFdxdzZzZWtJT0VFb29DbVkvK2NBeU5nNmY1WENDN2pKalh1Z2dN
        TityWkpHNDBKdUNIZG0rOTk2NDJsbjY4YVZPcHAwd01DRjJVb0pNdVdjUjNwQkRy
        eWF6eC9TbDFQelJ0V1ZVY3lSL1RERnU5NkRrelBnVURkcWdSYXZ5TjJYZi9kZHRW
        QW5Kczl3bW5rR0sxeHVLUElEVTBYb1V1REpKNjZUUEUyOVFJWnRUV25KZUVFTEh3
        aTZkbFBDK2wxNmZYd253ZjJ5UTNwUStEcmpoOTlDVkZ2RHNGbXJxeSt5VVFHbVBM
        MFg0d2R1L0s1dUl6bldmTjZTbkdYYWphVGhlb0JobDdxM0NTeTU5cTBBb0M3eEdh
        VjYycmkxYmJKbFYyV0ZaRkdobUpqSHFFN1VPUHhjOFBZdWZPd0RYV2JFWGpoY0FF
        Rzl5aFBuWEsxT25Qd3FJUm01cUlFMHJ0SGVNYmlWWnd4Q0VYbjJOakE4Y0hnaWpx
        ank5RUpkN3F6NXNLaURvUldRMXpqc3N6RG03azZJSVd1T0xLbW1UNEt5K1NMeVlx
        czRabDZqVTJadGRKV0lRK1NWVmR5d2kxMW95WGJGWmRFZ0UyU3FsSC9GUFB4K0FK
        WStTcW1TR0pqVkY3TWFNdW16TzdBUndHdkhJMkV3N1BLM0NTRXlvRVo1dFBjQQpm
        Q2tmVzJQeFJrdlZ2aTMzN1ZOeFI0RzdZbUNzaVpJcGxTdnorL3luNFRzCi0tLSBZ
        WkcvUXhKRGNrN200Rkhjd2tWVFJDUVE4cFQrYUJCWDlSdHVxSHJxck5rCtiQwiR/
        WbDZGQTKrtBmcqUptddxGZ9rIg39E2VlnXfKnd4FdQrjt0sv8jQ/fuF5t3//+IIN
        XVIUcvCLcVvVFbs=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-06T13:16:08Z"
  mac: ENC[AES256_GCM,data:Vla34sXB2VoJncvGZXz/7gAsNytpzwAtlmUjxv33MbzKhD4sudkRqUwFfwLwueqXxzzOkIi3JdyZEm+833eGTprLIwq/FEP8k8hVPN59faP0KoHwJSZFsqYVV6BlPCaehiuLZEGbPeIuRFpIMDUD+GkxyJbpSBRCfJqq1WlVjTM=,iv:6d8YVbgw2jyiglrHhiJUDfMsPgLmDuu/El7EtxmpRTc=,tag:BoAmuIjhto5ygvFzoR9UPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
