# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:hv9v93AM8IwKHUe+TrI1qf3zHaI4XaVoKAMGVA==,iv:ya8ZRDlu0xpGQaDlh1c7iWULfMjWGWi9buxKptP9oBo=,tag:JIp/OeAMEUYR6RaRO0ylQQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:WJs47UV1x4OxRctzN37jAQj3tPC/9fHPeobkKFHkhz3koVfH5y2hax9y0J9Z,iv:UlE7sMz2lccF8ToK5MuFOPrRFP3nR7bKZTGcG/9iRHc=,tag:7FhjhqXnuFnhthtIT6eiAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGw2Unl6d0t1
        Ym9QaCtSNVF3SXFXWkFJc0EyZjIxTjA0SGlkSVZxNUJ6dVZzVWhySFdTcDVMRzJE
        T0pUZ0xjQVkzREF1QUI3K3FMV3VtWVRETWtWTlVOalV2WkNuNFV3dHZDRzNYcW4y
        VXF0Nm9NcWs1WUNoaTVpODFkT3llTlVuZW5UREp3L1pkYWRJWm1sdjF3Q2xqZTRG
        TGF2UkdGejNya1BHcmk3TmlQRjRVekNqVmNLcFhORHNTa3hUR2ZxVUFLcXpKWUt1
        RWx6eWhmOGtwcDRLRmdreWZaMEtQeFErWkxya2FLNDQveGxJbkFHRlZrVUZkVDdM
        V3dBZ3VaQ2N0T25WVklMV1JpUGpMSTVDOFhxeEpiWEJDT2cydzl5eFlrRHBUb3c1
        MmxibU5hYkZsQ21aSWhabG1qeThJQzFaa2JnYWltTXNoTEkwcnU2WEg4aDFJblhK
        UWZNQjNLR2VBdWk4QWxuZnpGdXpzd1AyOU02Z0tmWUNUSEx0a0NDTWFxTFpYSDlZ
        ZW5jQ0syYmlkR1NvMjNHSGhTYS9wVDhzZFBBdjI4MWRZcEVLVlA3anoxQ1QvUjBh
        YlNORDhRaFg0NWNMM055YzM3OHJSbWo5aWF5aVR1Z0ZHRElpby9DbnIzRXJXczhV
        L09LdE5PVEJCNk9YRHVOOUQ2ZlhHd0kwdktpakU5dXVUZ2t4bUxzdnB6SDBrVTk2
        TVhmNEJ0dVE4Rjl2UDFCeGlqdmd1c3Z2eFNqdm5HRjZxTkNSN2JtTTZnYlc3d1Ez
        SVVFT0lrUHpBQmgxTXUwbzhaVHI1S3g5dGgxRmRTdERzMG5OUllFdWYzeUErV3VK
        RlJwbi9xZHI5Vk11bmdyRG54eDM5VUNWR2NHOWlkcHk3aWJscGo1WFJsV2JFR01N
        ek5WRFUvMWxVTmZURjVjYTBoSldKZFd6aGh1QzcvSW85TVJkN1o5dzdhazJORUNR
        YjZVUXFZOGhkTlZyRnhvWlU5ZzgyeERRMk9lazNaQVkvY3ZKRUNYT1NOYUtFVmps
        SzJOSGdRUlV2Mmc5cGU2L003MHYwQlFvdVRSMFgycTZSRXZFb0RFSTFQKzNZcjNy
        OUZ6cGM1NWpaNnpIRFdjV21IVzA5TFNtMzQ1TGFHVmlPTlRhZ2RZUjQvTkVSUSsw
        eDhnVEtWZmdmdFZVNzZ1WWpIdkczdkc5amRvbjZFbTUrSHlBS1pFNWhrNHpDNEow
        ZVZKS3dHYlNXWVMrWkcwaFVWbWVxTE9QN1VlOGcwNXVEYzBQMUVWSlhQbFFKdTlC
        U2U3TXhuN0RBK3VoK3k3Lzd6YlBkM0lJSnV1WXNhdE03b3I5TUZOSm8zUVhFNEFV
        RzEra1JqODVhdWdlcmVGaWVXT0g4UHdxa3B4eVBYcTFUR3Y1aXZwd0hXOE5sZXhC
        czlFVklZQW5ZTDN3WFFqMFNSR1Y3TlNIaGtEMm14eXJBTDFoSWlickM5TzBMQkk5
        OGFRUHE4TlhsRi9lV3dOWXN0Y294V29CSVZOTmlaUHJzVSt1UlNQcmdlS3RadlF4
        OVhBSk91QnVLd1JQbnQ2KzJsNCtEMzNhMWVzdDg4aXhzV2tYRDU3SEdud3dOVmZt
        OTNYdkJadWVMRHh0Z0o4QUJtQWpCY0FoZSsvZmJPYkhJN0RFSW96emZteUsrZlhL
        c3MwZWtmeEZVQUI2cTk2b0NwMTZTSkEzTlhROWVZTjZKdEtjdldlbndQSHRjMWRm
        YjEwdnNBTnJkOWozOXBVR3BqdGFHTWJ3K29QTnNaT3FxR0JuTnJWdlJJSTcxRzN3
        QVdCMFhmYkRNcXI4M0pEcHQrTDkwMHhBVlBsTWtObVY0aWE0V1ozeURYNUdwcW1D
        TTJrUVN2a2wydENVNjFMcWZReXh5U1RkSVRTTERYZW1tUGtCbHpBcEprOUJER3V2
        MDM5SXBORGRQeGMza0NMbkRZbEt0ZllaQ3RyR1BUSlZUbllEYmkvNTJPejBCdwpi
        UzR2Q01CS3RnSzd5ZTdPbnJUMmpLQmxTUWZNbWtoWEtpSFpXM3dUcUlrCi0tLSA1
        Slg3bFhXSzJEbkViMmp1dUhWMWcyVnJobmpQWkdPTFVRZ1kyR3hJMmtNCgbIwarq
        SmZQzLUlvbW4vBjCZb/gP2bUCiAuK9AGo++sodj8nwukN7m5yvR96h3iDEhpYCPk
        H7QCUplB3qoJ6WA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:35Z"
  mac: ENC[AES256_GCM,data:wcjSJBWI3St6OGnN8iBytT0mYKw0OV3gYYICyfFH3Oew4KS/DLg8d+FHxxp4hiwydy4/DXDR//lXURBqp0Cmv1SSY1zBeVkNtr5PTib7kJiVIzZsxw4qyiLUJAU81S2zYcrmxP9PW0Rsyx/ric5jHMChTWrvLXfQvVboRcLEwFw=,iv:imOabHWnZQL7aywd8pzugN7eW3/FufQvHUGNe2YGyPE=,tag:M1ekWhodoaIQozRkyAVpkA==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
