---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.0/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nfs
  namespace: default
  labels:
    app: test-nfs
spec:
  storageClassName: nfs-local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---

