---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-agent
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.2.2
  url: oci://codeberg.org/towonel/charts/towonel-agent
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: towonel-agent
spec:
  chartRef:
    kind: OCIRepository
    name: towonel-agent
  interval: 30m
  values:
    controllers:
      main:
        replicas: 2
        annotations:
          reloader.stakater.com/auto: "true"
    agent:
      logLevel: info
      healthPort: 9090
      services:
        - hostname: "*.kubes.cloud"
          origin: envoy-external.network.svc.cluster.local:443
        - hostname: "kubes.cloud"
          origin: envoy-external.network.svc.cluster.local:443
      tcpServices:
        - name: stunner-turns-tls
          origin: stunner.network.svc.cluster.local:15349
          listen_port: 15349
        # - name: forgejo-ssh
        #   origin: envoy-external.network.svc.cluster.local:2222
        #   listen_port: 2222
      udpServices:
        - name: stunner-turn-udp
          origin: stunner.network.svc.cluster.local:13478
          listen_port: 13478
      inviteTokenSecret:
        name: towonel-agent-secret
        key: TOWONEL_INVITE_TOKEN
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
            interval: 1m
            scrapeTimeout: 10s
            path: /metrics
    monitoring:
      prometheusRule:
        enabled: true
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          allowCrossNamespaceImport: true
          matchLabels:
            dashboards: grafana
