---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-agent
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.13.0
    digest: sha256:22f40cf9e02dd922078b82b74ac80ff8dd4993fe828a07dd5e5d6592ce2065c2
  url: oci://git.ow-ops.eu/towonel/charts/towonel-agent
