---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-agent
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.11.0
    digest: sha256:d88087db3d00ff9c43ce755ebddc76815ed93ee306cdaa888df662c5e41eabdb
  url: oci://registry.erwanleboucher.dev/eleboucher/charts/towonel-agent
