---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-agent
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.5.3
    digest: sha256:6f8792e3edc89096b764ec791ee2dca4e4c2b8a5e1eef4da695edb53542284db
  url: oci://codeberg.org/towonel/charts/towonel-agent
