# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: towonel-agent-secret
type: Opaque
stringData:
  TOWONEL_INVITE_TOKEN: ENC[AES256_GCM,data:3l6ZOwOtpS0gjHsJWk43zGIUaa9xatNBCqIYVzth0zPDjeYbB0jRs88cFTjaiH+uOXsgTTg45+qGNuwWwPYhI4DvwBjuAxB3BDVEkkyDOUdM+z5U/CS8JpJRYx6thFSwaR5p3OWPKTgG7UJxoOIQ9SuoSOesxjkjUjqdbQ/GROOgWd2+XitbXjfavAL1vsDwDU/n59uoEQ==,iv:YdWzTLONR/5P3EyJw8kWqgPbbWOiVLz3DihZ1qappd8=,tag:frukfoT5iC3yCMN99FIrsg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDB1angvT2ZJ
        RnJmWkJXQk14bURhTVBqN1lwQXYrUVhja0lLT2FqSHZndWp0M3R2VksvOEhtSmE1
        cEpMK2dWTDMzUkFVYlFYR000WUtqK1pKZ0U3STMvVGhQOThWTWZOYlVMeXZyaWZS
        QVdRTDE0cjNBbkN6WjA3NGxKZmZVM28xeUVid1pKd0dzZWNoSUZvOUEzZXFPQjE2
        czVvMGRrZE5DRnJEVG94NGowdExaNE80Q2tZRnV3bi93L1ppcTFqYWplLzFMRWlk
        QlVNSERNZndkRlZBSlFhWmRNVHh5V0ZjaS9qTGpqYThWM2xKSHdTbmU0VWNwaHd4
        YjlGZTFVUU05OVQrSWtzeFdDT3prbjlqSXNJWWVBNFNhRHBPMHh4ZWpRcnYrSTZI
        STRPNVVuUm1HcjlaM1ZaRFd6TXQyKy9YVHB1RUpycSt5VHJET0RVM0hFeFZ2dFdz
        eTYrUldSckdTZks4U3NOODhmSWNMTlFDQXNNNzNFUnRQYlhCOStiZTRUVHRpQnlm
        MmkvZkxaalpjTzBGaGM0VFVFQUx3R3lNdlh6RU91RFNDQUdrYWtEY0YzT21NRXdL
        TnJDd1ZFUmlicmpUVER0TWUyWnhmZ0NTalQ5NEl0RUI1R0ZiNURCbnMwSnpQekFn
        SER0dGs5L2x2V1JJRWNMd3VlR1dKck5KeHFyTi9YTXVBKzh0OXBmUDE4MkdjT2lu
        T2l5UGZPalpJU3NjOUZaTzJtc2hFeis0azl6VEpDR3VFWXdiMjlyeEJDZlQwbS8x
        K29hY0U4U2pBQWFBaTYvU2VNV05QVmlnTTVVaXltdHhGelp1T2tTL0N3UVhxRjRD
        YUZNMXFWM3UzaW9lMHRHQjZMNldwRGtSSFMyK2tLN0NuaUMzVmQ5YUgzQW5nYVlJ
        TXNvc1hkOXdWMGk2cHhYZWZ6Y0JpWlVvNFRhYVhkdGxLYnRTcDh4TFhWMGZ6UGx2
        RTVnQkRkdFAyVDNhNFUrNFZSeHczem5PQ29GWEdXRVYvTFVnSnlMYVFKUGtIQlpj
        cTRmdVRrUmhqdi95ajF6SUJTUTNTZlRtY1dkSzZMaFVXNVhURWN0amlYNVBnbDJh
        dHFrbGlFZW9uaEZWbGNidVRrVTBrV3liOENPTnhMb2E1U05IYlBpUlZsbEFOZ09T
        Nm9DMGdrZkthb252blNQcWxiOFdvajFSekxiYmhZcDBodjFGbUJYTXRmQm5sRWhX
        UGZKeklLdmE5Uzl1ZUx4YW5GSXBkTkJPV2lyUmZ3YzJnWDZTdlRhaTFsaEI0S3Jv
        OS94TXVHV3BFWHgveDM2V25LQllqdmw0emMzdVpKZGd0U1ZYQmxIZDRjVExhVWlG
        VEpETGdtTk5DR0ZKSHMxbkppMTRMUGpCeExoVjF4bEFnUFJ1a3poQU41bUFXbjZh
        UXhIRk4zemZTckJCWnNiNkRLK3JvYUcvN25TNnhPVmZWNHQzSG0vNkpoQ2xiVnIv
        SVlyQmRjY1d0V1NFWUlSM3A0c3VoTEhGSTJ6RWFRMGNoV3kzQUdiTmdoZVNCVFlZ
        aG1kMFVFampPZG4yWDNxN1lDWXErMkk4QzlDeDFtNWpFZFd4bkxnZTE1Y1JnajUz
        RDl1SENhSzRWaHhHeVRrQzNTOHg2U0JVTkJuTm9HOWlNbUNUVGplNVhJM0J6bHVJ
        R2t2dW5pVysxcWc2WVZrd2E3L01sd2lWeFlMK0ZzMnJZYUU5c2FuNTFzdW83dHE1
        dXpKSW9kYUxkTFU0TnluRzdncWdCWFVMem9JcmN1RjliN1FhcE5RRUZRTlV1Vm9K
        Ti9KUUxWUHlkUnBjQkJmeTdTSC95TFVqV041VHJTdytMbThjTU1oelhXODRxY0hP
        Q21JOEhnSXgwSDhLanZqdjdBTU55S3pkcnJlMFBSSWg5dHZDbVBpcjU0bDVxUGY4
        R3NvclRpSHB4KzR4K2Joc0hjaENJZEJjRVIrdVNGQW9HUlppbUVnSSswWUJNUQov
        eWN4Mk1XWTdSWDUwclJRcExqY1kvVldITFRSS1hmYTZSdDYzT0tTaEpRCi0tLSB1
        ZTlsL2dwL0RjMFhVLy84VXM2VjhZL3RqSnczempSV3VGUlJqYythbldZCpDnJzQx
        d9yC9cazFYLf10W7gd3ciKyoFMWQ+DgBxVa262DxujcvxVkKwymaSiHvsf7ILoDw
        7RgI4Mj70dEIER0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:miLXcQnFg0rhF5X3M9nySaeIn0YIj/fXi/BBzlQ7c+/GEha6fG1fIUnQPDXCGhUr5jzpcp+ENix6+8p2n5HA0zrVmpa3sIxr80tr6s47SImatwuOjj/syy6v5qjA3Tv3+JoW4pKXOfyhiZd8d0HzST1Rb5Z1+umnw77t+YsmmRk=,iv:Bcb6NKenviOJXugTeObrzpYA3CMeIBHSJyl0/YGx3rM=,tag:ATFp1AwSAyYSCDa3KJeiMg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
