# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: towonel-agent-secret
type: Opaque
stringData:
  TOWONEL_INVITE_TOKEN: ENC[AES256_GCM,data:veZLE03MMug5LCmX9/7syWYRqCVP6MhRg6Lx1mqG2I6ps8NvFj4GIOJJyx6M8gRiWGlinX5ZUxKSFiEGMSQL5uskPWC9t7T+s+Ds3wNHpMrBEX1oWXedLNCo+cJj9j9GeNStIPdaZmWPFeWNftMFnbzo9Ujp8x1ZuK32bylcKot9dfzmBBlOj1b8wLRDcOSBdRJjD6uepEyF0Vu4IGwJN33chlJehg==,iv:IOoZ9DUyI3kjJuIluHShiY+sGxuA3ILr+DmWSZO1g+8=,tag:Ixv/uwmE0aeimxs0BcSfkA==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WEdESWwwb0g2eDhaR1ZI
        dXNhcWFRZGNhamtuRzN1K2F1T2Z0N1ZDNlMwCjJETkFFZ1VsRTZUelVYNkZ3aENu
        dUJMSEk1RGczZ0xKOUM3WjlGUVQ4dW8KLS0tIHlYMlptcUZRc2N6L3ljcVVRRmww
        TXQwUGUrRkRUL0Jmdm9zR3hYbXMraG8K2ZR2bFE+z4KVnOzJ/J8OHzQ/wpfcCsNF
        I1o/kSk/avfqGJj5jPkrwunQBsz86wZytPzZcs+QaZQqXR3fS9aKUA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGJPV3pHYzVK
        MUhhY2NhRTE4WDhwRE1zZUVxWkczRWhjamdhVU5kbzNIRTJaN21adE50QzZWQ2t0
        dGJSRXBuam1ZNWZLS3lDUWpXUmlpaGlTcjBRTXZCK2ZCdEVZSmtGZGJZTit6NEF6
        R2ZWUDBXbms2YzZJRXpyQnBRRWNBd2V5eUZjVFNpd0Zna3drTEliVG96Qi9wdXg4
        c0NoOUlJeTg4NGRjMGFnZDFacmtzeHZ2Q055b1RDVlhGNFh3T0JKK0s1eVdOdmFW
        QjY2bEhRMEsxQUZuVVBJcnZweFNBbEJTV3pNZjJmOWVDSjdnMEo3OUpnazZUZjQz
        MlpxTU5aei93S1g0UU9wTFdrNTIvSGY2dEJRQUdxQS9lMERJQldWb0paSzZjek9t
        N2dDQ2FMditDcENmNEJleUhCZnpEcWovRjB6aVdXQVQ1SWxIc0EyL3BmRFJCemx1
        SmtFdXgweGdVR2QvYWZCMnpiaExFSHZYb0tmUDFGSGRiMW1sY2FHZ0JNMVUya1pn
        QWFpc3grVEVKS1dVd1lTT21KSkJDd1NLMzBZU0JrNjIvYXhKbDJ6NjZGVFZEbGtu
        bDNKRlgzSXVUTHdGZFBJeGxQU0F4U0QvRTQ5U2s5R0NYMmhHRUdqdGFpeTh2YjR3
        d3NxOEhEeWpvMzVUcEhKb1pqWWRTdDF1ckZaR3RscmNRcGhtaG9UTmowMDg2REYz
        SlZ0eGFWaXVkUDNodktvUGN1cVBVYW1yVlVrY3REZTlFclV1N2dDYmMrT0xmY2ZE
        NzNKWllOdUdWOFlIL2VZREFiVSt6VmdUT3lXOG54Y3VXQndUNklzd01sTlFVMDhR
        dXA5R2ZkRm9iNXBYTWtOREpuNTlQTzVTdFNxMnV1VmZrVURmV2JOdGR5dVZ1eDRo
        bllZQ2oybVM0NGFiTXhMcWtFMkMySmt2YVpNck1MTTBOcndMR1lDalpHYjJoYmhr
        Wm8vSFZPMnBpbnBCUVlKalUrMUNMU21YOVNndWhIV2owY1M3Y3FUN1Q2MWZZYmFp
        U290SWIxbncrOGpNN084Wm5ueWJET0M5OGZNamFUV3VYVHRNNGQ2MWRLTHpJSDNK
        QXRqcmRta21GU0FtYndwQ0Foc1FJUWFzbXJCa1VzQ0NwTFZLa1I5STFTa3lxbmdE
        bitDK0dRNDBmZGpaTnQ5dWh2enhyeVhZU2xvMXlGMnRIUjdkVWRHYU55V1h4TTNY
        M0V1SnVUeDkwbnhLQ3JFWW5IalhuMDQ2UXl0SDNtemIrdW9ObzNVblFYblFtaXlX
        YUhJNjZia25IN1hLazl6dTJMbFdYemFtdEk4NWxUS04zdzVWSU53ZURmSys0elZl
        TEVBQ2h6R2lZcTJyM2ZZN1lhV25sMzdoNHFUbTZjRkRPMWVFOGU1QWgxWXN4MTZZ
        WjNDYVBzdnpYMWc2VzJPVm16Wm0rS3ltUDUrSnRwdDhzL2QyZS91TFdHbHdyLzEx
        bUN6R3VSamZmZTlNN3Zpd1RhT2NDZ3BGeUVSMjFzNFZEU0VqbXBXSXFvTFQ2K2xj
        aGpGWUYzbU9LZG1rNE5EcC9DNUlFWVBZMTdTUnZUQmRMRzloTmI4YUN5cmt3K29p
        dGVpRG02VGhpYktYMW9FSEJOdTBoMjhCMnA0cTBxY1Q3RHhWaThsOVRTVXA0Z2Nl
        enBOT1VPRldZZ2UxQVVrc2JxdmVxLzhHcXBHYzdMRmRwVENIMDAwNytjQnNMNkVJ
        UEdEM1pzdXVMQjdCSTlla2FMQnAxWW5pVWRLQ3pVK3hhNWdaTElDbkV4WCsreEFB
        eWNKcUNZQUFDbExjNXRUYytZbC9rZGppeitQYkk2amtTSUd2WjFudXgzMjdDOUZt
        cVBnbWxJUnhqT2dMNS8zckxKaUNmR0xYamFjcGUyMUdwaENLVGhrMkV3a3NIZlFr
        RHRlUFpNa0N2VXdBTmw4RWhrNDJOc1NmTWdZSDgwZXFiNmprbHNMd290SVhlZwpS
        d2JUenNUN0I3U2JDUVV3VDBjc1U1ZEU5eGhicjFYTDhvS3pNWHhJMjhzCi0tLSBN
        d1YvSVNxU1p2QjZyMTRFVFNZbmlIdk1peVFYc0toLzFkdlFvMFd6ZkRFCuCwRJ/7
        vYKd8a3iGgzGaGyEmcVRMjKkuNJ3uWtjecpK5D3uZTMgqkwbjnblLlkGNjJDA2ly
        F0/VBI8aqV5mHtA=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T10:34:30Z"
  mac: ENC[AES256_GCM,data:aej7x+rJOxdAaYYgXApYiPI8oZtpKhai89pbOCiRbIlhZK1WLOiAVwh3C40rK8NLLaobmGq0wXJ+AHpVwuLEUeMUazoOTz7n6fHfwMHirCrety2IP+A30oDa8RyQOH2MvPuOnPUFoGNOOvddSyxT2sLB5AQNw8rK1RE125YDiOY=,iv:nu6At1J8DzrdKwmj+leCGZF8Jq/B1hztMtIIqFO2At0=,tag:3Q1bYxmZA2Wd9+2ALVrQ3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
