# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:z7M4FzFyAxDnIFKXY8Zk+DBhfLgnVw+mV9ZROZ+XQf8wiIyEYmj30Q==,iv:th7KKpZM9w/Py8mrjsF68ff6Q1gRi6C6ya/bs7jbqpc=,tag:9FSjK1ZTzRqQWM6kazzAAQ==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieXFFM3F1L3Z1T0tZc0dH
        bVVwMm9seVFxM1NGKy9HSDZnbEtuY2pVMmtFCllhZnkwcVZrM0JuUWVYUk5JdGhJ
        RzlzUG9zV05VdzM2NHc0V3kyb3QvQTQKLS0tIGMrd0hLK3F5amxYRi9QaHpjRks5
        akprbS9KRlh1S2ZEc01mcVc1U1J2clkK43SANTu2jLj/EeHY9hiyraV9Gts9ziwN
        wXfFtf1If8bf+yPuy5kNcSpNKOcYsM/ezGJthNGZ/ryrH8IUKmnhiQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDkyMVcyYnNH
        d0pJWWRBSkZWWEdaeVEwdkppVVpnWUtsaTMzRG9Tc2J3WFhkMmJqbkluUzJubEtM
        b011ekQwT2lpSGVVZmNKVjJoTHVmUWNXSHZaamlNU1lEaXNSQTR3d3AyZ3pvc05m
        Ujk2amxzSVlHYlJ1NFk1TWR5bzJnS0U3TndoVnpnSmdKV1ZwM3VNR3VyaXZpZkNS
        VU42dXNDSm1SZElKZHZLMmZ6VG4rdktEeUthcElPVG5LYlBaT0w2bkg1VnBWOHF5
        UHV5djNZTmdla0p6c0phNURnZEZqaGV4VlBXbzhmRndNaEQwUU54MVVoelpMZ05M
        aVpaU05jc2orYWQyYVkxS0VjbFRDVVRBQVk3aHQ0cWVNNE5VU3p0d3FnbVg5QWpH
        MHRVMHp1OHRPVmY3TExBUDAyb0lQZ2k5WFdtSGxERXovRXcxa3FaRUZUTytFQVpD
        bUNSWVB1dmRhRWlDN09CU1NTUHZvVFlGclhEazlCTFRQeWxYZ0ZwZ05KMEhEZDN3
        ekRrTitBN05mNG5vV09haTF5R2RJcitsZUhGaE1WM1AxeWVTR0E0Vll4ckpYdFFs
        YzI5bWJIYlJQOWpaa0hiWDE4VUlXN0xxN3kxbmExbWl6WTF4NVlNcUdnZkpXNDhy
        ZHpCRDhXOXZQWWdjVjNpN3FjRFUvNExzbVl3UXYya1FRdWxRSy84UE1TZUt6djlU
        QWlCSmtsM0hxek54RUZBM21sc25XVnlqdW1pOU5uZ24ySW5tTHdaQTZhYlBCK25t
        T1cveWEwL1lHbi9MdVN5bHZrbWZDRHArUkFxYWwwTWNDWlVqYjR4L2h4M28yT3Fx
        RXhPb3RhRTE1YXVwZHBUdEFlekk5dytOVmorVkRWNEFZWUZMbXBOMVZuRGpDRi94
        L2lMaFpOL2h4NUpIaERRamg3LzVxYUJNQzNYRzBzUWtBSUc2d2hYK0NadFZaRWVD
        RnY1SlNOQTVPb1VZYXM1citjYjRKSlh1YWZkdW0venZLNEVKa0NoZ0o1MnhURWVI
        YXFtNGlSOFRNMmFtbHBaT3BBemg1djRtLzRWWFNNejFRdE1UcE9iTGduRERlR3JT
        bnRVc1VSQ3FEZTM4dnIwZ2x4UzFiWnllSEJQVUJlaVlkTXJHVVFzeXJldUNYNXEz
        TjhxazF6M2lDN002OGM1bGxkaGt3Z2d2bnZTeDdyNEp2aTBVNjQ5RUN2TnJVUjVU
        S21MVWNzNVVYcmR1OElwMG5WcEI3VU80OW56UEhxUGVsdTlIYjVGb3RkV3hSdEFl
        QlhkaFdaRWhUaVFuOGwxOG5ZWHlFZmNSc2M1T1p2akhpbjhmaENrUlk5dVc3bVI4
        Zm9pbjg2OTlpZFNRVGpOd1JqOGt3NFQ2RGQ0VEh6clNrTmd5TkNucmtkU2dRcFJl
        ak1aQnlrWWRyMTN3V1Y5Q0Mwa1ovam9BMkpLOXc4R2ZYR1QxWEhFU0QyYzdjY2F1
        Kzdnd2c2cDNCY3BsMjQzM285TStDVndHVEZ0a0tBR3JBVlY5MEZ0ZE90QUlJVkdP
        WlZZY1kwU2xaenNyS3o4eW5HQlI2VFUrVGdkczlMU1I0V3E0UHQ3MEcrVy9hR01y
        MHY2QjlScStJd1lDSk9Sa09ETzFUbHg1c042a3gzdm9YbndkalJoTVVGS0xkaDdN
        RHkvSEhTYXNxd3h5SkxUWnJaeGJraWtTWWMwWE1sZ05ldUx0UVF0eFJrUXVnN3NR
        dDdXUmpkaEZmWlR6RzBuZjI1OC9qM25IU250a3laUW9zbGVJOFBiTVNVdlpwQzg5
        djc1dVRuRGlMaTUwY2ZXQUY2am9CZFJuRTZGMXdRdE9yVlVCNDVwR3IvcUkzclVG
        Tlk3UlNoZjlPM1UwYWV5MzB1TlJBakhYU1pVb29WS1BUTFlqVVRiOVBxeFZObmdR
        RzRCclZ2OFBtU3QrbDRRRFk0cklRV1FzMzdNaVFrK2wreW1Cb3RUQ0xoRnVWdwpm
        RCtuV0ZDUTQxRzdaQU16RGY1K0Y5Ykp3QkdkRFhlYjF0TWVUNHVVUUZjCi0tLSA3
        MGlPcm9qQTkvQXh1WnhMQitZcGxDc2xkakppd0JyWU9qb1RWaXJjbVBNCuIVv3Kt
        JJstOUuiluthXeIQjmkDhi4fFuMZ1DEndH/HBssXNA6N0uoItCtexaPqCeQE4shc
        NC2UmsHlXRTjL0U=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T13:53:50Z"
  mac: ENC[AES256_GCM,data:coEqX0v2n45w4B0agbPPmitG64E5x72jso1sFkdgl9cGP03HY9Ls3pzGAF2dB2zc7wcAbdr5jx8UsqrpCOm9S7kqKP5BDPWjTiRooXi0GjaIJ52M1RxROIN7tJMa9zNdoxTZzDd+3ZAJotylEL4fUiBCDyvNThoDTDzlSOVGcSE=,iv:BVvonbRg2Wspa+2L0UWOn00bQKdYF+AG5YvJpEbwS8M=,tag:hTbOSSkxcQk9fSe93mBuCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
