---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.0/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${CLAIM:=${APP}}"
  labels:
    app.kubernetes.io/name: "${APP}"
spec:
  accessModes: ["${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "${APP}-bootstrap"
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY:=2Gi}"
  storageClassName: "${PVC_VOLSYNC_STORAGECLASS:=local-hostpath}"
