# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: restic-password
  namespace: default
type: Opaque
data:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:R0Yafk6HbK7ls2eGQ/blx0vy,iv:b/aycSwx2Z8gUqCTSu4JQHmY88uAsRWqeusKWpMcclE=,tag:i8zs3mCJwyCaxLosS+Mmjw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:6YOXj/knQmaVr9n5usxeE8oqoRz05lLY8yIdch4bEWkXywwI+JgIlSsZas2Q,iv:SKyR6P/ct911oXHP1YREUBV8wc1ahFCi6gAHSTk1Ois=,tag:E+DfP1BjtptzJy1yOCG2NA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ0lBUTZCMjZ1cmFZa0dQ
        dnVjK0hjeG02VGtYeEErVlp6elV2b0JIbHc0CnhZMldGcStOcmpsZFp4WjgwWDlV
        SjNBUCtxbGd6U0FaN05QWEd5ZEVidkUKLS0tIDdIRDdNbkRHaGg0V1lnMFg0N3Zy
        R3VPQUVEb3dnbzN5aloxcnNmbTRzVTgK/WiD9QDzmJp8PuwDe8cYQNmFHsE75EKz
        k8Ipdxxv2FLcFPO2vOt2kRztQeL1k1Azfovd0vAXiaBlRAafOmaPYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-23T09:10:41Z"
  mac: ENC[AES256_GCM,data:hNHqomRB5WOeM+bAFMk+0hofc1hbK0CYT1a7iYVKrKQ4Wv6MGNvFAS6cmbfHgcGHmeWn+/nzIB5Mjtuygf8M9L1u9PAogJRjr4DJdmBUjkBcg+LpYF5gkoAuJ94XITtOHsY1Le1Sd32QISmdwHFP+HlVwEF3Kpc376uzIkmhPVY=,iv:e5QNJNMYJKVkiVVs2Ubv40pDgAeTmE1dhuJO8VAdYlc=,tag:a1ubE3aqRXOXQdyYre2rOw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
