# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync
  namespace: default
type: Opaque
data:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:9H4HlYo4luT6YRAYNVU+AQH1,iv:n03wuuMMsDc7C5gURwq/QIC7f7Mb8Xtu9Sqx9r3hs6I=,tag:84oshI8IC570x9+4uyLCig==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:EE5sRuz2sIoSvH4eyimW12wJmPgab75JiirNIMbwjyiwssIXYvYeJIXWMoQQ,iv:ILFP1V+h3xBujw4dgJAzfW77qkBRtn3OPOToLSAHEuw=,tag:Vlzq82rWZmX97QeMiME1gg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VDJhQ3VjZ2NldXI4U0Y1
        bzV6bmFIWU1EZ2ZPVVExTnpBTFZybmpQeWc4CktVMTg4YzRjb21xRTBVRWFOdmFu
        UldnM01qeG8rbzFWTFFOTUNZbzFTdHMKLS0tIFI3QjQ3cVl3ZmJiZEN1eGpvWlY3
        eEQwL2xOb0xYeW9QREZQbFhyNk1vZmsKiftl03WdWUVdGkso8cGHXAlHC1gANA2P
        iF8GToqIwoPqn49CSd9fOJlfyxb2JhvnQIPZLU+ugZvfTt35yFUbQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-23T11:20:58Z"
  mac: ENC[AES256_GCM,data:tVaQKdYb/BvwvqkFESmPOj9PUQs2cdtOzqLS/B5BPlqEF/bDeQq83MeOjSn+Xpxqj2RvP5fICbtScR/D5roH+YtmPh7VSY+XfRk8xsnpLK5F8hZ1QNRLlsqgjqv0dk51ZXwg8qykrqORYdUbMWDdsul7scCyN/1/xVppgjME2p8=,iv:R484NB70FLJEoZ3M87WHWekXkl0ezEMNt7WoJ+sD3mY=,tag:JQvTxC2s1SPRU+dlvTMllQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
