# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:eLKIRoj1dA+HqKDm71t+IsZ7,iv:f0ZzSOdM+cpEdp7RnjmFlOGHAL/gg0742P3o/Im4RxQ=,tag:NHqICJAA7dWsmEwwUscK2A==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:1Rzi+z3jVjE8+Axy2Gs65qC8d6z66tBwsxaaaSfNoIeRBh8JwXpXlPaACkgy,iv:UlE7sMz2lccF8ToK5MuFOPrRFP3nR7bKZTGcG/9iRHc=,tag:NcuPKPCGO/sJNXOeO2vvTA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeTZYakgyZGwweWkzd0ZT
        SEVuVjBmWTVTdVUrdUlQLzNsb24zRDREd3dJCm81elRvYVZBRExyWnp1TTZud1Bz
        Y3AzVnI2NnZlWGFGRUtCQ2tUUUF5bzAKLS0tIEFqV3FGWEVwczVIMm5rR0Y5UXU1
        cTgyY1NYYTJ1QVo0YmlxVDNuU2cxbTgKj6fZACWYgb25ZD8miA3WJ8OXWyEdEFzI
        gH6ie5tSTSGuFdoDMAF/MKTUcgxNbr90EL1EPP8//4MItBtJhs1M1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-25T08:24:48Z"
  mac: ENC[AES256_GCM,data:x76ErrvMhyuLqyPBBw0SBl8HW0fvaB5RWUxjCJHPEWFrc6hZhqznQ244GTe1MRtAH7doVJnsxtjHg5YeyV3d0Xrl8i/BzQ2NEyx1CaNMeErgRtbPPocLq+Pi5Lg3T7n4/GKzMW2BYsY7rlUo5QtBd23yrMiLty8JE0UFjIB6MYA=,iv:dr57WxOLNb5Q+pY/kVUwZtUm+v3IF4r48vYaRyeWeyw=,tag:gNogoXQFhuTkhM4uR9pEvQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
