# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:c4tTTBQfyj212pGPMWyHhlofE80krZMbb7XlnnrTRXBBvok=,iv:YwVxlTw+6r/GOBfYgidDoptG0VguLN9409z1XM32M7c=,tag:P1UBvn4nDQ8uRMloc6SoWQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:1Rzi+z3jVjE8+Axy2Gs65qC8d6z66tBwsxaaaSfNoIeRBh8JwXpXlPaACkgy,iv:UlE7sMz2lccF8ToK5MuFOPrRFP3nR7bKZTGcG/9iRHc=,tag:NcuPKPCGO/sJNXOeO2vvTA==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeTZYakgyZGwweWkzd0ZT
        SEVuVjBmWTVTdVUrdUlQLzNsb24zRDREd3dJCm81elRvYVZBRExyWnp1TTZud1Bz
        Y3AzVnI2NnZlWGFGRUtCQ2tUUUF5bzAKLS0tIEFqV3FGWEVwczVIMm5rR0Y5UXU1
        cTgyY1NYYTJ1QVo0YmlxVDNuU2cxbTgKj6fZACWYgb25ZD8miA3WJ8OXWyEdEFzI
        gH6ie5tSTSGuFdoDMAF/MKTUcgxNbr90EL1EPP8//4MItBtJhs1M1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T12:28:35Z"
  mac: ENC[AES256_GCM,data:LJk9wZo9qqPZjchXBsWm5fpFg3uepxgA9C72mR7VC4nOzcDIqOYlAAz92BCJ9Y1Mc1oYp6mF80gMBBEad93vnNxuUKCHX+e3eTlGASDMXD8/XRciLl9akkg7sy4O/P5JFFFFSA9Tm0Vq2qwISYlknCiIz1wjV5kVctaXDJOQXx4=,iv:9BkojMQzecfKrAYxcyH71kvbL5wI/21ATxR3NfHkjAM=,tag:fdNdh6jPCGFqZT1A/a4iSQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
