apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
type: Opaque
stringData:
  meilisearch_master_key: ENC[AES256_GCM,data:yCyP/3laQ0S7te+SuO+B3ZwlZNSXbESERilA+eQY7jJMxqEy,iv:LavBJGy+g0Fc4YNCWksPArsdsmPzm3M8CDA3BbWxgJ8=,tag:snYw9dVpRgRXgA48262QDA==,type:str]
  nextauth_secret: ENC[AES256_GCM,data:YRlToSndsuA5EvhGfj4okAGwI+t9m/fjjeeJfaqsmtSx/QEFQZFo+RkKr4k=,iv:sqBD9HScDsvwK10/cbB6N/1iI02uSdtn/3hERSe1l74=,tag:R/M29gZErldYrX9Q3P2TuA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFkzU0xTdkor
        bWV2S0FMSGJpdjRWckQ3Vk9tM1NKbjg5ZVVyb2J3SVVCd3ZYOHNVdkszVTU1Z3px
        cTFZZkJsQ00yQktzUmI4NzZPN0NodkU5aE9YcTRIQ3ZPblhWNG4xaDh1bzZTenB6
        cFlSVlYvUDhqTkRQdUVBT1FZNWN4L2JqdEpCUU8zMW0valF0RU9mbXM2Z2VQZ1By
        dWVYdlJJdUtwYThpUVc1S1pEcWNuYTFoemVhRHk1NU5DTTd4ZnZhVHNSbkdBM05q
        QXpla2lvWXZTQnZMYURQTURMcTVpOWNQWVJSRi9HSVpPN2d3NHNiYXg3Q1FZTDdS
        VXlLS0FaaVZDSGN4M1NndVlRbm9UWWgxSjJGcE13S2Rzd1VLK1BVbnhRaStnTTh4
        RmZ3bmpGTFhTK3JhcW4xSlBvSkJCL0RMQnRRUUxRZUZ0UTRXdUlmdlpGVGtieGx1
        elpKajFQbTZwZFh2L3RERnMxbkl0RUYwbWJDZWFSdlhUbFhGSG9qNkVvdUtPTEN4
        Q3l3Z3M1TGo0SzF6VWo4UCs1UG10eVZoYmVSTDhwS2hNT1pSaVNHOTcvNDdUWEt2
        cVVjaUZTR1YvaWJKUUd3d1o1Rm15TG5TTzlnV3c3bEJwaHM2dXhFNmlKNklBeEVw
        VUFNRXNJbE9oYzJWS3RRcmtSQTRyM0FHMzRHTWFRU09oYnJyOXpFb1VDQ0R6Q0xR
        eU1KZUtjRjJlNjlGUHBnUDlTSEZnYUZDbVl2ZlQ4Y0x6aTkrcy9adVRhVHVzOXk2
        eDRTQUVVb3lnNjdjSDFtTU5VdnhjQ1NMTlpSaVBtTnJxM2x5UGFDVUN0UjNrS1JM
        eUpLMmxkVWZFWkcxcEVGU1ZwdkhJazVjaEVMTWV2eDNieVFwQVVSYTNLQndVMVF1
        OUlIWWRKemxXWWJUa09LQUljelJ6emNHdndZMXJjU01kSHVsNWE3RUZWN1dJaGJi
        SWN6WEpmR0U3RDM2L1R4Nmw5clQzbW5IWVZheENBZFRzNDdONWdXTGZTNkgydTNT
        ZzJFamFlNVM1UHVSTjJ2ZGpZV0lVNzRiS2hwZ1E1OUFVSGxXajlyamNVd25VSVRj
        bE9rUThmdEh4Tk5hTjBPMjJnT1JNRHFBZVg2OUVPR2V2eUlhdGpVNGpoUEJzVC8r
        SFM4M1ZjTHZzUFVpR0hOV0pwMVV2WExHQUZsWUZCbGowWFkxTHpaTUFtV0Z4SUI3
        YS9CM3pYU1liVHFRcWp5ZThoZ3pHekpIaG8zUEV4MkhGU0huUGUrMlAzaFU4M1o0
        dWdMN1piMnpUZ0ExdFRBc1FHVWdDUzVBS0d6aGI4UTBKS09XYnRxaUl0d1J1K3dG
        emZSY1J0YXZJOU1FbU8raGxQTm9sVnMvc1R6L3JSeDhQSVhBaUxvV2RVb2hQZ1ZG
        L1hqWkQvVnlORUZlRllZWVIwMGk1K1h0V05QYlpoL0RWdjV6ZFFyYjJXRXBaUHNh
        Yko2SWZ3ZlQ2WkxoSy9wVzJtZUZDQmNRQ1NOSUJQWHhNTktFRFErTHZuYUd0V3di
        ejlSbE5ESHZPWUhaU0c5THpiMnBZK3J4aExOVTVzNjUyNktSWEN6c0s1cU9CRU5N
        RXdsa1M0K2F4QnBnRmhrQi8yV0gzbVhJTW5BVnJvZnRlSmJwZmNodjYwaHBTNUlz
        RFBEOGxuc05oQ2VlZWJxdzQrbjJlRnZOZHJrWWFRUGVJY0R3aENoOW1OSEdDUTBH
        cGEvOW9tU3NOdHRFcHFBT0h4dHVzdk1CLzRsUjhFRDRzYU9TOXdSVG5ITGlMRmRN
        SnoxWk1Idmp4VUNIV2JzSGRLemp4WDV2SStlYnVmdDB3S0lTSVQ2NTBFTTQ5VnRn
        eEt5SlI3aG9jdlU5VkdHQzlueUhMSGFyeXdhUUhtSUFBaEx1NC9FSkYrV2VXQVE5
        aGJFSGdxd2tLSU5yVE40eWk5cHQ0TVAvNTRoY0RJcm9yb1FiYUNRN05ndmlKZwpY
        elFtVitwZ2ZWSjJ1dzdkaHVjUXY2dWkzcUFsOTZYbW5kR2dGcGRRQThBCi0tLSA0
        Y0dWM3JZalorZFRIbjJ1WUdUUFlsUjI3ME44RHRHaHBFS21NZFJxUjNJCnWOkSVm
        3zkkFXanji/CtJNT2TaiCHRdvPc9ioEc6MUuvcYG/TWQiYjCfqL2IIdAK5e4rImP
        9EsRCg8G0RSLk5w=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:crx1snKMu/Q3+awEeJDgzooXlJ48kmy9SwgjpsJVwdw5q9c1W4xJC1QRVEJsuuG8roFfWJ4u93Z/XzVUSHgV5tbS+eZiukRv8Q3Mypss0WT1V2pH5C+STxzPP9u+Ei11pfsawfGjPe6bQvjHllzSVGkrkZ3lN9rwHzOa79xy3LI=,iv:VrIfCXi0BzFSZIH4CydWMFH0WfeiEt8FUgGIfPJKi+4=,tag:GqOiWAbv7nElpz8AFKl42Q==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
