apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
type: Opaque
stringData:
  meilisearch_master_key: ENC[AES256_GCM,data:YUZONFugeWd68MsClHBZL4y7y9M8okddKwJP6QZYUhwWdCSQ,iv:LavBJGy+g0Fc4YNCWksPArsdsmPzm3M8CDA3BbWxgJ8=,tag:dKqr5biq5Vmmwizzt4W77g==,type:str]
  nextauth_secret: ENC[AES256_GCM,data:HOax5wClyrwTgy3e74hc5xRTI9xcqMpx13fKVvHjyAJ3wtxFJ3pXo+1MSNo=,iv:sqBD9HScDsvwK10/cbB6N/1iI02uSdtn/3hERSe1l74=,tag:l4K/8XVGRKxNP3ynKViP7Q==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3L0tkaCsrczlUenVMZlN2
        R1JYaUwxMzVpRUJPT1dNRkRYbE9rUlhpRDM4CkJzSTBSN09nMGY0RUVUaFNvc1F1
        blJ0c0d2b2p0YXBxUVA2dTBJbElTVG8KLS0tIGFaa2tUQUIwSmFYUkVYRE1uTVBr
        MXNkd0dwdUU2eFFrY0xseS9LWERnQWsKlyOsv+ENrXwV52B8rQDbVV9WEl4NNbJ/
        NSD0gxHdxZicFiW17ckQ6nnKgHuXhpNxBfAI2YTEIUk21eB81a/S8Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFJMK3NIR0ty
        cFJ1NlA1b2cyWk1wS0F0cXpseWovOWFJRjBCV0RoVmhWRnFkVWRsQlN4K05nTi83
        a3VPQ1R3bWI5S2Z6aXRuQjlSUlI2SUVzYXNuV0R0YTl3ZVE4Ulo4cndTRExlbEQ2
        VVFTTXFiN3BmUFg4dWRxSG82N1J1OEhXYnpGUGdjT1ljNGJsNUw2T1VkT3ZlbThG
        VVFGVkZuNXF4MVlLZnlhYlk4V3FsTDhEbkUxOG15SnNjd1B4OTc3cnpLRDROZWZm
        aU5zYzRxNGJxUEM1QWpwWEZiempqTWV5cjN5VU1NQ1RqVUpQT1p1UmYrL1dacVY5
        VThSb2ZWbHdDQ2hHdldrWGowOVIxTnNBM0luM3NrQnV4NWpLYU5mdXRXSVNEcnkr
        bGJtR3VpaE1jbTU3ZUFyTGFjbC94YkZQamZOSm9tcUljVUhxVmlrQjdyS3lCcU1L
        VFZ0c1NOYlpjQ0FMTDhlaWRTd1dwd25JeU4reE9wQ1Uwam5VQ1BGMmMwV2tybUZS
        RlY3RXcxcGs4a0s1MDlpS1M5RlJsYXl2STcySDgxYVNYQ1FneUMwZkJwbmdoMENT
        SlVIUm9zRUdyNjM0ekJETVZGYnVtSVYwK0pMM2s1WVNlNDhiS0xKbzVUMzVNZDFR
        alF4SlVPaEo1ejMyWjUvTWNEYzR6emFRY2tycnFoTnpQZ2wxMEhGdURyZTFkNm01
        ei9xY2owWGdUMHdPeTkwVDMyYjFJNzFadUJuNndRY1ZKTnRCRGlFMVJSY3QyREgy
        WGlMaEtucURiaEFnb3k1T0ZrbXdWc2RBQUFlSFlaZExEdElKVE80L3UxenJlcXdx
        WVorT05ubnZ1cm5mSHp3eUJHaVUvZXlOUjFQbnBxQU9UQ1RJcGlNQkNXWm96MGIw
        d3FKOFZrcER6SFllQ01QNnUxY0pDRnFYbWEvUDV2VHoyakpxdUlFc1RjaWF4WGJU
        SW40bDMxRGh4cXZ6b2hsUzZORzNsTkE0ZUdMYjdaK0VzSGxqSkZ2M2kyVnpvaGhh
        bjhZRjhQeGNCK2NLckp3TldORjFFUmlWTTJOMEJ6a2RUNWpVYnBoQXlTa1VqeG4z
        c2ZkT0JEVm1FZkVSZTB5REhYTDJHa2pQTjBMaGwzYzZ0OFFQcVVIN2F4dEt0SkhR
        dVlIc1d6ZjZpVnplWmpKUFVvUGN2aVZXUFpvSktJSThBbG9OamxlZ21XK1lDTVRQ
        eUcxVnlFL1FXaFdUdHl3OVJya2FnRndmWnkwSFZHWThiZjBjVVpzRzlYeEJWVjZU
        R2ZGQk9ETHpPOUYrVFRZS05QZ3g4c0JyUnc5bEhVZVVFT1c3aTltWGlwQk1tOVI3
        cTA1Q2V5ZCt2ZWpiT2s5SHM3UjlLa3FFeUpuMGdRb3VpaWIzdFNrZHROUVFiSnpt
        TXZUK3hsVHFPaVFvYTQ1VVUvYllBQ3VBMStLS09kOXhQb1ZmTnM5SzZhS0pFK2Fu
        aS9UcFhFZmQ1YmVock03Q0hMbkFBQVNMRDFoOTBuRjZMQk1wSk5xUnBqK2pnWGc5
        MlJ5a3VtMDhzbzVhWTV4UTFIQkcwU3o0TjFpQmdpdTh2OXhZSHNabG1UbjB0Z2pO
        ODBnZjJpM2cyUThodks3b1d1cUc5VEtQN0llaDZFaDhTYzJobzNxeWlZdFYrZ3dO
        NUNMU3FRa2tmNmVRMEVIdjNTN1VKRDd1dzBTM2FaSSs4c2lTdHN6dHNWVjhJYkJV
        TkMraDVIY2xWcEY4TEg3ZDUvY2IvejdCOHBVbkIxb1pnVjIrRlp3Q2lvb3h6cU1s
        RC9tQkluK0JJZ2V2S2VaYkRiZitiMDAvZHlUL3pVamdFK2JTZ3hLRXRWU3JCVlhu
        NlJJdzdLVENNQVViZ1FldG9DVUU1KzdaOTQ3T2tUMTQ1Smg4VnN5aENsT2FCL0Fy
        bEJlOUNvNzErNzRKSDJDRVIzSHNhbC9qTldCRnRmWEduQ3pEQm13UXE2T3pIZwpN
        M1J0SkhuRWdwRGNBWDBPZGc1dk4vZUdsSWhQKzFwVktuWHBqaU1tZGtnCi0tLSBU
        bU5RMG5GK2JEMEZadzFXeEEvVTd1UlJML0pCT1grZ2pZS050emx5clg0CiEv9bGk
        MjSH8a51zc1terWkZdRGVFifFLL0aa2/lY9zRZlS0brkHKl8TCYH/oXJMGwZwqX1
        DHXESwklIGFffOk=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T20:57:43Z"
  mac: ENC[AES256_GCM,data:ubFGTd1JLI3feQbI/2XraxyEsaYTdudRX0HXSu4OG1qvmT5ckUZYPP3i0vDi2SCvd41Vmch3BrWeOTCU7eyKRlShEC6aYanMDu30Cm8wKlZlBmfFaWx2knMEWpsAf8pgNa1urkL5qHfkv9RxgFSF3vx2vpafpL3X7SK9RQo6i1Y=,iv:l7ZdN1QJkyJTGOy4ylwHJ+K6/3vLV7uDDYqFhvSXYFo=,tag:5pUqDK1NRJawAKVzg022Bg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
