apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
type: Opaque
stringData:
  meilisearch_master_key: ENC[AES256_GCM,data:YUZONFugeWd68MsClHBZL4y7y9M8okddKwJP6QZYUhwWdCSQ,iv:LavBJGy+g0Fc4YNCWksPArsdsmPzm3M8CDA3BbWxgJ8=,tag:dKqr5biq5Vmmwizzt4W77g==,type:str]
  nextauth_secret: ENC[AES256_GCM,data:HOax5wClyrwTgy3e74hc5xRTI9xcqMpx13fKVvHjyAJ3wtxFJ3pXo+1MSNo=,iv:sqBD9HScDsvwK10/cbB6N/1iI02uSdtn/3hERSe1l74=,tag:l4K/8XVGRKxNP3ynKViP7Q==,type:str]
sops:
  age:
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFpCb2tpQTJH
        N21XeE8wcmVKc2xBUkFGcU1NdkJkd1R6a1NTcmVjbUtFU0JmRjlzWVB2YVZWSnJI
        MnNvcHJBU2NGNGxWN0htQzhOVjJKSUdmSExnOXVMNHZ6cldEU3ZFRXJGc0xqb2or
        UnIyL0xsd2ZyN0tEcUtZUDJlajBvK28vMTJWSW9kZVdvNkd4dXNZUUhzeDFDK2d5
        bjBld0M4Sk9WZlhIN3JmeXNCSFhXUHV1NmQwcXFoRmtpZmUyZzlEampCWXlzNDVk
        MW5BNHZ4ZzRNa2lOL3BkeVpwbjh5U3hKYkVjQTU4ZzRnaVF4S3cvc0ZCMTZOYzJK
        VnBwb01ZYi8vR2RjS2hlS05LMVhURTFzeC9YSmpTb3Z0ekhiTUxiTC85d0c3TWxQ
        anoyR3Q1R2FZK3BPblV0bGJXNm1wdm1pdU1IZVVMK0U4VmgyRXJITWVvM21YS0xy
        NTNZL3dnWWZBbDI4MDBpWTJMWDExckpMYUYwYTlhN1JwYzZQQjdiZnFRVzQ1Wm4z
        Y2FUTkpmeUMvT05qVmhBWUZwR0tvZi9EY3kxZEdYQTMxOTdUSkJ4Zk5FMVQ2YUZq
        VXhxRVhISXBaRWtxS21YbmJjL05XZ0hmOU96NnFtNXhRdEJhckVEZzF2YlBoa0tn
        M2VEVDNQRlJtYUd6dkxGS2lTS0pMbU5XZGNtMVBaZy9qWHpZbTNMMXZRS2lrQStx
        akx5UVRnbE9CR3dMbVdBRTZUdXVPdmlIQUxsbUxYNXRyUU5iaDg1dnoyekI2V29i
        dXAzeHB0elVUU2RJUnVYR0JBWW52QUt6R04rbzBEcFI4SkxuLzM0b0g2SU5wWVNz
        OHFpZzUxTVJJaHJPWStBQjdaRTVMcEk3alF0VnlyRFVYZmVzc3FSU3VyRC81dVJW
        SzJUb1J0OTZ3V3BPMjdzYVE3a1JHbXZlYXphclFpWkRqTUlxYXArTWFQc2JpZ0dI
        VGtzaGxCMkNUZUVEY2dBcS9ZeEV5bWE0ZEF6cXNYL1pQdUNUU3ZwYkUwa1BlbFFz
        bHZWWFA4Tk9CeDNTQWh0czNWbjdZMjB6NmEwRTMxa2cwbUZrUXV4ZUx6S2ZuZXNH
        M2prUDVtQThwYnFTTFRnY3FydndSWlR4dU5RdmlwcXp5N2NEUEF2Y2ZsbzBNQXVJ
        Z2gveElMdkxoTzU2UUpULzVTb1c4b0haSFAxM2hXU3NPWDFqNXJvZTVjaUhhZTAx
        RUpKM3BrcE1TanJhdmVqVlpSMll5S2tnRUp2SkQ1SE96aUJ5c2VYVFh2VlZXa2JZ
        UWZBU0F3RXBJcmozbG12U25CSzhIUjVDam5Vdi8zOW0zK0hWRjh6cXQ4cXBxSHpv
        UHhkWGhQbC9Jdlo5SmxRNzczeHJmR3JOZmRkZmlzejFiek4wMUVRZ2dWQkRmSllh
        ZHN1VTllelZmTzVpdmtqM0FUZWMzRGVVeVkySERqbkJtOGRGeGxYV2NPL1dSUk9B
        emZrT3FxUWppVEYzd2p6MlZWWDVmZGk3bjExUlMzTkIzODg0QTBiaVNRVGVWdDNK
        SDBjTnVHOTZMM0JhVFI3UXExUnEyMkZBUXAvKzcwb3FVbVNyWVBtWmlpTWdYdGto
        VkZlbU9WSXlHQnlhYlJWdTZiaHlRaXh1cXpWTzNuQlFDQm0rRm51NS81VEhhSVlm
        SmI4VDd4bVJrNTg1dVNwSko4aytiTEhaaDI4d0hnSmhIQmFEMVF2YWJMTVNvOTZh
        U2NmVE44RVVCWVFackhybEFwSU1uRnpzOFlIMk5mRURZbVIwYk1JYmtGNTc5cVVO
        eStQV3dmbGIxVXpMWU11Q1B0NW8wUmVySVBNb1hNVlA5dVZubWloN1g0SVhadU1y
        cGxybUdBZ0lqbFBBVzl6SXBMOGRsdW1URlpuKzlYbUtobE8vSGEyWkxoK25hK1Ru
        alBySW9sSVk0aTVnV1hrbDJGRms0bDVIMGMwdnNJYmg5b3FjNExodnR1bnZUQQpF
        LzNSajJJalpqcXVOSkF3VWdocDF6TnMzWVlwRVV3SGdOSk1GOGFQdmxNCi0tLSBz
        V2lrZGhiY0RsdytPRUZyNk5xMGRJamtuZllCWStTK3FOdE82SU14TlZVCjb8X7PT
        dkf7RJ9jEMlMVpAiR4HjM1xztRAVt1VIkVVtJJeVNZGj3GKgsl3y+Eg0wREbsoL+
        0GT+NghV5X5nxkE=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T20:57:43Z"
  mac: ENC[AES256_GCM,data:ubFGTd1JLI3feQbI/2XraxyEsaYTdudRX0HXSu4OG1qvmT5ckUZYPP3i0vDi2SCvd41Vmch3BrWeOTCU7eyKRlShEC6aYanMDu30Cm8wKlZlBmfFaWx2knMEWpsAf8pgNa1urkL5qHfkv9RxgFSF3vx2vpafpL3X7SK9RQo6i1Y=,iv:l7ZdN1QJkyJTGOy4ylwHJ+K6/3vLV7uDDYqFhvSXYFo=,tag:5pUqDK1NRJawAKVzg022Bg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
