---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-snapshot
reclaimPolicy: Delete
provisioner: driver.longhorn.io
parameters:
  # used for volsync to copy from.
  dataLocality: disabled
  numberOfReplicas: "1"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-cache
reclaimPolicy: Delete
provisioner: driver.longhorn.io
parameters:
  dataLocality: disabled
  numberOfReplicas: "1"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
