# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: livekit-config
stringData:
  livekit.yaml: ENC[AES256_GCM,data:CK+sUla8y0KRphQQvqE/vNLWtXjHwXCRfwYCtCOZodVxUce9Yz57n6y+Pf1Bfr5zyUZXMNvhkVRKczcIlAooZnPePX0kBjnZD5W+XbZFnsR77GY6lt5w5Q+GW4dx34KuQTNyauYtceoVOGAKtH/5Isr9SMRJjThHWzowFmaHpCFzupgff8M/EOViSR59w6SYGdHnWI7Ts8Za29HYBDoGCploI8lUSkPYnFOzVV6ifO4TLtZ4PMK/df2Nzmpe0C8S9SPfNnwWVYlqJ94ASdf+NOeBt/NJdwPNgWzik6HYwDO86T8FYlJdtkl7/6+MaUTb99odE7YrHgh9G8/xM0LCvBNINOSGZiyQc2yB8VFhHLoCVGYy4HVf0yz5TQf6SXPE5mc45b2RU7Sf608hWgt/m7V0ukQXO0PWkefXlAps8i2yzoqD3sNmJoPpRsxqp7spcCsOGkWv5RGICkCGaHF+A7GMSGFSYGoqBonmFRfMzq2gijtcn/rSIBjPxVvktsI7UkSiJ38qMP/gYSl3zcCYnda5YW2zrzDHAEe8RZdt0r0OCKE4fU+bEMrkOIWrYN8oJiZp4j5yE8Eq7gJsBk7cj8rlU6ozEjF3XPy5PGyEC5dxpc1fA+XqqNEJYlReqbKG7rjdS/dcFD2tnGZers77GawHtziXbInSF0jEYe+/bxhNq8oYPep5M3e7AdWBn7CGqCIWypDwvEFGoWKnKPTqG8TpoAvg9W00Ok941nWMdz1CzSz/pLzovlHoIXAvTUf4Bleka9H0AF/i6oicOjkxjoniclujC2ZDbhz3FyMZiJVoVkS9M6dXEforBtjX9ZJBwfoFVpbOpJ78JZph1tHoI2/rSph+oWdo2lBbAAMgK3pMurH+LtVukoFv+E3n5zzTN7wrb3U4ejw/B3GbcIr+Kh9R4Fe/U2eFfsZIIxVYOT97zXG4FEDZaqWKbpuwI9DYj/4TXyebHQ8xMa5jWV2dLJC8kWyRUmvQNNCqV6xFdFQ9z1JBKnCIFVlGjZO6X0YE/0S59Ij8F0dYGYJZAdEimc9lnHkBPMj4wryArK3Kz2uk+YqXFLPSTn4ffPmNpyEpgI/d1iw8Rxr+S0AaAwPYJ/8kXJa0PRO+QGs/WlFKfWZsh6rcnp/zSQF7oEBp4pW5i4PeiW9cVIZBkSzvDen0rDjB1+P8mvIq21++oZo+aolyoiWStDsowsG/gGnosFjdlTSnsA27NwOVMivV1y7x8of6MCpMLwFib0SoRuV0pPNG8+Ma+ObL2vxbbvYvrMMPp5iJJPoOhj6hZ0mal3n8+L0A1VYPx4Nyk93AgdcMa+cQOFnsbvPH0EBccudi9tZboMQej6wlu35ppdr0AjADbGzs/WbKZKyY,iv:p+YCvtSw6E6oWRLyAd//PuYR12/pbzxqgaDcL0DO6jo=,tag:5s6MvmpyJ1uY3JOcFlP4tw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNElxYktSWkdDTjZwcjM1
        OTM4ZWptNmVvQ2dIUkY3WXdsdVlCUFJqM25ZCmtwN0FkNkdZdkY3UzAzb2gxYWFB
        eXkrdWtiRVFVNmFYam5zUW5JazEvSEEKLS0tIHlzT2pTOU5ReVBUOXkwaW0zWXJl
        ZzdtemRGZFhvZlhlK1phNjNSbjAvVFUKrRHFv2KdK539MFCCuYrVdWXC6jiUgTSb
        a+s5dkxz6ZBeaRyz7VUktaI5hX2zwEtS+f2FUAB45rdYBGzeJoZ+8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGYxQ2RmYjUy
        RzZlb2JWcHh5dUErenVtZGxMdlAra2hiWXErYk43VmE2SXN6YmdyaGYyTi9Kc2R6
        dUVCM0hzbUdWazI1R0xKR2RTc3piVHVNekpvc0d2eFUwemdRTGlQYUlZaFpDVjQy
        a1hkVmpZSkNZMnRZWFRoNnlDdXhqb0RwU2VuYnVmMHhEMHhWRkJjc2RMbWp2bnZ3
        TVRkSm9UUjZ1eThuLzRocnUyT050dGhxVEVsM3NVYU1wZ2M2eG1nYjdLR2xzcnp3
        eHBXb2QrVGhybWRMVklXMzFDY0wraUlldS9qNktuV2FKSkxyUE5Zc2FleEFTKzRr
        eG83YkZCdWNncTNYRTBHVC90R0JWK3k1cklxb2x6bDA5b2RzL1FiQ3NPZENYK20w
        eWRBV1QyalRidlFnV1BEZGJwN2pLMktDQ0VIakZHZTYwZXVCL2xvRExDeU45dVNu
        elA4L0ZsZW5OUUVESTFoTWovYVBuTC9mTWg5d3ZqY240MGhYUU9IeDBxSm9Rclly
        NDNJRVh2UnA0U05JbUZZMkZaZFZ0Q2JlOGpVcHhXaC9uSW9tMFhTNXdVTkhaaklk
        dVFrYTFORWlMdDhYYjVyZlg2U2pyTjJIWm1PU1RwemlxS0pFMEl3RDVkRkZoK1pG
        bGVtS3RFRFVNZEx0TE1nWEV0SzJMcVJkNXVKMFkreW9UT01JMnlNbUhxbHVNeHRG
        TnMrclBLUHlidnFWUnlvK3NQUTMrR1h3a0MwMTUybGpVdythQ3BaNHBjam15K1Fw
        N3hKL2RqRHV6dVFiOTJCZy9mZkRPd1I1Z3Bna2gwUTExTG9ETURGODQzR1N3c2JV
        cDE5dHgyWTdEeFVGK1R6bFhCMTNhZXRybG9tRnhUdU50aUN6SGJtMzNlcUNTd2U5
        Vm1BU3h0QzNyd3J3VkY4YlFnSGNQblJoSDg0aGVabC9uUk8zSVJpTkFxaHRKcC8y
        bHdzemtsNmpUVFVqYlFGa2JXWDI1S3lYUENqSDBxZ3h0YmpmV0FvU1RtUVFvL0RK
        Um5QdkQ5bWJyekQ5KzdMSGdVRWVqUXA0MlprYkxkUlV3dGdwWWNLNnUzL2pvb2w1
        MWNnY2xNSlFET0lqMmFDRWRwZSt3WC80dko4MTBXa2xzTy9nUU0wV1Vpam9kNEFX
        MzFtT2pxV2orR0lJTnF2dmxBR0FHbUd6dkw0YzlLNS9hSzVROXBheEF4Sy90aERC
        cmE2RUg3ak1PdUNDczk4alZ3Q0xLUGRUU1ZSdkYrS1FwWnRORmM3U1hBaW10UlBC
        em94NmFaY1dhRDlpdkJxUytuS292UE8ySnJnNVpLQVloNUJEUFNJVkY1Z0lMOVFF
        Q2VERGhWQS94ZkdzZVR1M1FNZmRYTDBRclN4dnZDVmNRZVlGSmlvNzBvTHBIT2Vl
        UEZsQTRla2Jtd3k2T0pZNDhhb2FnSkU1UVJWT0RTay9KQnI2MnhFdTlCaUNDeXRi
        ajFncXJMMmtBeS9XbGpUSzhxYUIxMGVKTlVxSlpHakpOTlF2cCtBNXYwWG1BeFU2
        bmNId1Z0TUVFTVFNL0NTVzFDd3libUd3NVBIQ1JDNzBZMlZyQlZvMWdITldpWVFo
        Qkg5U29BQ2hSUGhlMHhjN05NVXNBWG8rTmk4Z1lwZUgvWnV3b3p1K2RmMkVpaEti
        aWp0ZU1YYlNsR1VNcnMzT2Evblh3dTBpTCtuVy91UCsvUWJaL2Y2ZFU2YU1ZZ0RP
        TUovQkhVQWpBVmNMNm5NSk5WUEUwL21SNmEvYUxleUNrRXppQ3hYeEN3Q0EzSXVX
        a09sNnZ1V1Y0Ym00QjhqalhiZW11MkJtVUtmQWpsb3V5Tk44bTVubEI4ZGFqWDV1
        bDloNUh0dDFwc0xYRXRJWTdXRWxkYlhKR0cySkhaK1ZOUlRZRElkWUlLcFdPM2JX
        K1ZaT2c0a3U5SUtGQjAyU2RSYm1qWEQzSTF4amtaT2dJSlo5UXV6U0lTSUhHdwpS
        R3NQNFV6TjNjd1E0aXVNVGV6ZWhtRWt6TlA3TVI1UDltajlQL3ViSGQ4Ci0tLSBk
        dWlHdmVITE92WWM3VldZUzBDUjBwNFVDWVp0aVBtNE5NZDh5QWhIUjhVClzpIcuT
        tQLQdFsaht18dqsnnZQ5ybvWd7+fmx5wjIxk1YPseLRqIysS7XSaKHcxMkEmE1G6
        BrI/XcGayRd64C8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-14T13:40:29Z"
  mac: ENC[AES256_GCM,data:E1/8Bw1skBZJkYWQtbVUy0mHBM5KdaIo6//fnbAlbUuOKAfdiSe1Od7sszfi5Nkcgyb86yHoSJ3BSgYoYP/BZG+FgSxvbHoelUP4vaMOHN+Vf0zG1txIFU+6ZxV0dFHyh8uE2Gg1r2ZUI8Yt7n4UXwz+Ue4AH87ucYB/TiJFMrs=,iv:/erMj/uQ1gyEWNDp4nxA5Q6i8cFU37zeLbB06SStYE8=,tag:COCoOlQdQ6WyQB2PjFpKTA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
