apiVersion: v1
kind: Secret
metadata:
  name: gts-pg-secret
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:McuR20bAxXCArA==,iv:WLgLnLpJKQMOhk900e8W+bPXilrNGCmZhsA4OXNka14=,tag:E4iOU70BjwRnxXU/pYaS8w==,type:str]
  password: ENC[AES256_GCM,data:KBdmI/RIkeHPKFFgsu9ghpp+rK+rvz5f1G7Pk3ucNY4=,iv:lx7fxhDuLdwTlD8/stgWKFVFkXpsxDsElZnb9JijTn4=,tag:tJWVc2IEygL2idpUKKuLyg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEdsSllkU2hP
        K2ZHbFlrOTkzMmtCOEg4TU0vc0o4TUMvemt0QUExYTEvNHNOOS9hN2VTbFh1d0Jm
        b2FsbzJRd3ljVDhsTE1YaHYzZUhvdk1TamNDTU5aUGpMNUdNNkVZL00vMmZBWUhK
        aGMrV2c5b0JBa3RVVStZOXRoTm9aTUNwbXk1T08ydHVXazBPK1cyQWJoMjliRWE5
        ZVZia3NUcHdtbEFKcCtKSHdldk4yRVFFbTUwTytHZ25SYmU5dkZBNWkvOXlvaWMr
        VlpVV0R5RlRMK3N6M1Z6RUF0R1JVaER6clBnQ01QcVZUVDVaWmR1czFLS0dWZVVj
        WkVYblFGYnBXSUU3Q2IrV3RBK0xjUFlzMTd6YmN3aDdZR0pSdzlNeldhR1RDMnla
        anQ1OXYwcGFhWjZIamVTNWliQUY5L01reExQMks1dmoyc09PaUFJcDhYTW1PaC8y
        S1JlSzBFOER1NG5zck5qYmdTaXIxcnZ1aDVCdkJsNDdoVE9vK1RqWUhabW5SL2VP
        Qnhla3BjWDdnb1duRmtyd0hQeUMvS0dRY1lpSnY2cHpzMnFHdGwxelZGQmFqMmR0
        YWREQmRTbjZ3dk9BazliUGRjeGpka0krUnpEU0lKY0laMnExUUcybFN0blVOMzZk
        aDZvS0hBOHJ0Mk85UlFKY0wxcWRtUnk2NXRCcHRWNXltdTNvRXVMc01QZTBDY3BS
        NUJ6ZFYwLzdjdGpoczcvME9zQVVjUUJrUHVkUUtGU1FYckk1amFhRmVqdmlVYlJU
        YjQyWG9CZ3cxUG9McVE3L0xQYWpWZVNUcnN0R3d1RWtxYytyTUgyV3VkYXk4Smhr
        djBod1lEekRlVUtEeGVJTlY1b3ZiRmppYytleWtwNktZY2kzRUZkdnEyYmJ1dVE3
        ZmM0ZExXcEtFSU9mek1zbHAzdlo0UkJSZkRNL0lDakFxendNUFlHQ2tzV3hEd0tL
        bUJRcE9VMTNXY3MxQkdnNFdXTEk3cmEySXM3d01RSkNxV1hzdm5wN1NEanlKaG8z
        SjFmWFBubCtGWXpEL1paS0ZoTk5tR2d2UVBuWnlOTjROdmt2NmVzQVN0MmxqY3Yx
        UnpKd3JDRS9YOFRtQzBrU0w0aXVZckFtNmdEYVJTT3E4T2w2M2pPWld5Wm9VNGRN
        TXd1OWF2SG5ETHdXT1huQkhNQXlaRnllcU5iNDJCT2NXOFdoeVZYWTA0UVZ3WFpr
        Nm9OaEFBcWp3eDE4VEI1aGxseFVkd0lId2lZemVvRVJPUE9leTBTU0IyaEtJb3pJ
        Y21LWTNkaCtVNWNMcVRuaUpZT2tId1hidWd2M1E1K1RndWNFUG1XelRIZHJmWjFP
        SkxqK3JmQ1V5QlRTandTSkQvMkxKajh4K1pIRnlKSzV0N04rQnltcGNBRFJsN3F5
        Z09jWWpyRFR1V0g4QVBYNXpCREFmZ0VPK1FSVEFEYlQvcVZqVDdjdjhLcUNVd2Er
        TzJsNDZKSkhCT3laL1loRjgxOTN0NnlFTm1jdndsNWRKZWxJWElRTlFCb1JkU3Zj
        ZjZqOVlNbDlxTTRRWUhJOFFsNDlvRXNXYlpWdGhzRmRjWk1vWXZ2Z0hPdWxvVzlo
        VURqbEh5VUdrK09TcVljaE82WkNUd3dTemVvMGdtOEozUnRocUVqTGNjV2JXTDVa
        MDBpL2o0eUdyb3dMRzNCUGFHdmZrMTdHSU9XMlNONjgwbWhURDN0eCtCemNlU2ZQ
        eW5QNTVoOHhQamo1VUkyVUwwY3FpZUlZNExWQUVMVlB0NjNRZVd0MHE5T24yRCth
        YkZZTU1OZDZrc0hLM2gybXFtbm94SSs1NnVUQndieU9XcStwbStySVpiME9CQmlS
        NFNEakFINmhLWDFiK0ZvN2hvdFl6TzdlRDRDbVJ1RFNmT3Rib3hnRkxpdm5WTWsr
        am45UW5ocXh0YkZBRDBKNjVjeTRwbXF2VU9nZnZpVWVvbVF5L2NDVlAzbXBTZwor
        Wm1PVW4xREkySFh1c0ovc24wOEJUNGxMazFhdW9WVGVpTkR2UStvNmJrCi0tLSBN
        dHNMVEhzK0tqYko3WGw1SW1jMnhEUzY3bDBQSnlTKyt4NGo1SzNMdEd3CnYPmznm
        P9p4CF8Mts869dbMJHTMJCXy4nAOpQIt3xbhaslnJc/LvCSFd/u9x9otve0v4BwV
        JDlU+iXfljhyEDU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:35Z"
  mac: ENC[AES256_GCM,data:LDL05SwoOnyCh1dINEKOyl3qkNJMqQMSz4syvs15ghR/1WWrcpMpZl4wPSuexJU3yZNsjvtw1Qlt2+MvXoWQaBcpgfRoJk0AgXQHeCg6dpkFsibhnH01kWQyQOSYTw4KvbyHsv97onsCIlJiwatZIa6IdOEESDh+rE2pQ0N+hqQ=,iv:UUuDW37V7X6zVT9PAP6WU4QBxjbCdnGBxd/g2MR5w7c=,tag:/f81ufTqXUgm8v8H/HWQGA==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:kBc2akr2iE2y/eWlejNGp6Vz3uez+A==,iv:0+xHaWZ+DFBOzTilA0ch3y16xLkxN07yj4duiZ8XRHQ=,tag:Er9P2flGfPQTcR3tLrLrfg==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:4J4HO0A2ix2WyfTbT2VGL/HHh33fFspjTbubmwIsWFY1vD3s4TLVI5PHi77yaYBN,iv:OkrUUaOiMme+Xh3dXNzZytsEq9D6+78zDfLPvlXzUHg=,tag:3CVqBr1sQmmW6ACBfoa7lQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEdsSllkU2hP
        K2ZHbFlrOTkzMmtCOEg4TU0vc0o4TUMvemt0QUExYTEvNHNOOS9hN2VTbFh1d0Jm
        b2FsbzJRd3ljVDhsTE1YaHYzZUhvdk1TamNDTU5aUGpMNUdNNkVZL00vMmZBWUhK
        aGMrV2c5b0JBa3RVVStZOXRoTm9aTUNwbXk1T08ydHVXazBPK1cyQWJoMjliRWE5
        ZVZia3NUcHdtbEFKcCtKSHdldk4yRVFFbTUwTytHZ25SYmU5dkZBNWkvOXlvaWMr
        VlpVV0R5RlRMK3N6M1Z6RUF0R1JVaER6clBnQ01QcVZUVDVaWmR1czFLS0dWZVVj
        WkVYblFGYnBXSUU3Q2IrV3RBK0xjUFlzMTd6YmN3aDdZR0pSdzlNeldhR1RDMnla
        anQ1OXYwcGFhWjZIamVTNWliQUY5L01reExQMks1dmoyc09PaUFJcDhYTW1PaC8y
        S1JlSzBFOER1NG5zck5qYmdTaXIxcnZ1aDVCdkJsNDdoVE9vK1RqWUhabW5SL2VP
        Qnhla3BjWDdnb1duRmtyd0hQeUMvS0dRY1lpSnY2cHpzMnFHdGwxelZGQmFqMmR0
        YWREQmRTbjZ3dk9BazliUGRjeGpka0krUnpEU0lKY0laMnExUUcybFN0blVOMzZk
        aDZvS0hBOHJ0Mk85UlFKY0wxcWRtUnk2NXRCcHRWNXltdTNvRXVMc01QZTBDY3BS
        NUJ6ZFYwLzdjdGpoczcvME9zQVVjUUJrUHVkUUtGU1FYckk1amFhRmVqdmlVYlJU
        YjQyWG9CZ3cxUG9McVE3L0xQYWpWZVNUcnN0R3d1RWtxYytyTUgyV3VkYXk4Smhr
        djBod1lEekRlVUtEeGVJTlY1b3ZiRmppYytleWtwNktZY2kzRUZkdnEyYmJ1dVE3
        ZmM0ZExXcEtFSU9mek1zbHAzdlo0UkJSZkRNL0lDakFxendNUFlHQ2tzV3hEd0tL
        bUJRcE9VMTNXY3MxQkdnNFdXTEk3cmEySXM3d01RSkNxV1hzdm5wN1NEanlKaG8z
        SjFmWFBubCtGWXpEL1paS0ZoTk5tR2d2UVBuWnlOTjROdmt2NmVzQVN0MmxqY3Yx
        UnpKd3JDRS9YOFRtQzBrU0w0aXVZckFtNmdEYVJTT3E4T2w2M2pPWld5Wm9VNGRN
        TXd1OWF2SG5ETHdXT1huQkhNQXlaRnllcU5iNDJCT2NXOFdoeVZYWTA0UVZ3WFpr
        Nm9OaEFBcWp3eDE4VEI1aGxseFVkd0lId2lZemVvRVJPUE9leTBTU0IyaEtJb3pJ
        Y21LWTNkaCtVNWNMcVRuaUpZT2tId1hidWd2M1E1K1RndWNFUG1XelRIZHJmWjFP
        SkxqK3JmQ1V5QlRTandTSkQvMkxKajh4K1pIRnlKSzV0N04rQnltcGNBRFJsN3F5
        Z09jWWpyRFR1V0g4QVBYNXpCREFmZ0VPK1FSVEFEYlQvcVZqVDdjdjhLcUNVd2Er
        TzJsNDZKSkhCT3laL1loRjgxOTN0NnlFTm1jdndsNWRKZWxJWElRTlFCb1JkU3Zj
        ZjZqOVlNbDlxTTRRWUhJOFFsNDlvRXNXYlpWdGhzRmRjWk1vWXZ2Z0hPdWxvVzlo
        VURqbEh5VUdrK09TcVljaE82WkNUd3dTemVvMGdtOEozUnRocUVqTGNjV2JXTDVa
        MDBpL2o0eUdyb3dMRzNCUGFHdmZrMTdHSU9XMlNONjgwbWhURDN0eCtCemNlU2ZQ
        eW5QNTVoOHhQamo1VUkyVUwwY3FpZUlZNExWQUVMVlB0NjNRZVd0MHE5T24yRCth
        YkZZTU1OZDZrc0hLM2gybXFtbm94SSs1NnVUQndieU9XcStwbStySVpiME9CQmlS
        NFNEakFINmhLWDFiK0ZvN2hvdFl6TzdlRDRDbVJ1RFNmT3Rib3hnRkxpdm5WTWsr
        am45UW5ocXh0YkZBRDBKNjVjeTRwbXF2VU9nZnZpVWVvbVF5L2NDVlAzbXBTZwor
        Wm1PVW4xREkySFh1c0ovc24wOEJUNGxMazFhdW9WVGVpTkR2UStvNmJrCi0tLSBN
        dHNMVEhzK0tqYko3WGw1SW1jMnhEUzY3bDBQSnlTKyt4NGo1SzNMdEd3CnYPmznm
        P9p4CF8Mts869dbMJHTMJCXy4nAOpQIt3xbhaslnJc/LvCSFd/u9x9otve0v4BwV
        JDlU+iXfljhyEDU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:35Z"
  mac: ENC[AES256_GCM,data:LDL05SwoOnyCh1dINEKOyl3qkNJMqQMSz4syvs15ghR/1WWrcpMpZl4wPSuexJU3yZNsjvtw1Qlt2+MvXoWQaBcpgfRoJk0AgXQHeCg6dpkFsibhnH01kWQyQOSYTw4KvbyHsv97onsCIlJiwatZIa6IdOEESDh+rE2pQ0N+hqQ=,iv:UUuDW37V7X6zVT9PAP6WU4QBxjbCdnGBxd/g2MR5w7c=,tag:/f81ufTqXUgm8v8H/HWQGA==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
