apiVersion: v1
kind: Secret
metadata:
  name: gts-pg-secret
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:PHktK9NWuK5gzQ==,iv:WLgLnLpJKQMOhk900e8W+bPXilrNGCmZhsA4OXNka14=,tag:JMIpWlRBCRha57qq4vDXwg==,type:str]
  password: ENC[AES256_GCM,data:LU7LhHctEeeCcoU+fHz/IHMI59SR/pnIIYrzzp5HDKo=,iv:lx7fxhDuLdwTlD8/stgWKFVFkXpsxDsElZnb9JijTn4=,tag:85kc8l5L2Hx21HlGHk3PBg==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ajVHSytoNUgrUC9WRXRy
        RmFKU2t1QllEakZMenpVVC9UcEF4cjNRT2hZCnVBbThOTk5wUkl5cDBTQmFoL3VB
        RUxnamlISjF2VjJxTXg1ZlNGbno2V1EKLS0tIEw3Wk9lVVhkOVlndGFGU2NvNnVv
        T29JZE8zMGZUOTNWS21pbUFuaExJUEkKA9Xq3Z58rbX1IQPZvz274tIgcvAPh6zs
        ahAiEDmcn/HILlnMU2szhjsI3EQ5c9Q4UaTliDVrYvDCBigEViZfIg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDJ4eGVSSHgw
        Mnd6dXgvOC9sVVZhWGZhV0ZGMmh5TUtZbjdCd0g5WkZXR2NKR0thTmJsRVhSZmNL
        cjdscDlFT01mcXdTNlpNeW8yYmdWTTBIaE9VbXE3Uk53WHZsRkJQNXFWWDR0aE9Z
        VlFNbEFtZmVJWUxsdy9MaTEyQm5EbTJwenZWcCtVNVJSMEViMGN5c3pPY1hTWTFx
        dVFGRklwYjdQdzNCWkdQazFVWDg2OElaZ2RUV2pmVUJPalhTdXhXV2NuNmxZcXdn
        bHJ6OE9sc3Y2TmF1dUZodFZEdC92RnZZRlhFa2tuYTFGeTV0WEp4MlNtem1ZcVZI
        eFQxMkwwU1d3UnNvVXNWWnRmNlNlUUI5VlJ1MkdjSHpBK1dJTmpPWG9SRXRHcHBh
        WkZLRjU2eURhaW5yYjZiclNieDN3RSs1QUh5Vmd4a2RaQklvN3BQc2txMG9HZ3pX
        UGVFU2pOMC9PUDI3TEFKaXkwaDFKd0pKSG9BTlVWR1ZXZXZDeGtkbXdVRS9EYkp1
        Z1o4dEw3THBpOFpzOGM3K3AxZXdnUmFpQ2JTbGUrZEFic1E1ZU5aWFE3QzZMaHUv
        MENYazYrZFZFcmlTeW9mU0Z6aGVGdjIxUTNQM1Q3QmtKUktlSmk5YzlGUGNNMFJW
        Tm1FenJJTW9KRE1Jd0JnVGJxQml4bFVvc01CaTVqZjgwL1p4NFphZWVkcmx6VGtp
        SEh0Y2JHc2paUVpSWHNvL3VBd0loV2o5eTBvTkZKbkhnS1k5Z2RiVlJ6bHJHamhJ
        SW1LbGQwOE9oaGlxbzV1aXhTS0ppcGlmRVZ1NUMzeGNISlhZY1BSb0VCQkUxNmtq
        dUtMT1BaVTREUFVXWnh5QnNGVFpCdGpIOURwVWY3K2x5QzN2WE9qeS9TWHB1UTBn
        VEZZN2JrUCtXclUvUHR5SXkweHFhSis4ckJ1NnBIMFhpcm91SG1SL0JCQlJMQzVD
        V2tWbW5QZmtvak1GRk16NFBSNnJiRXlZUFpjc3JaZlVsTFRhWE8xdllYQ0VHWWRa
        MDRiMHdQTXZjajNzdzhhNHNUa3Z6L1R4VVNiSk1rU1I2SFNxck5GTUk1cTZVUEtP
        ZjBXRU9SNVZOWXA1aldXWnFGL2RuVk50MEpzb1lwL0orWE1yTlRQNi9rYU4vRzlQ
        RTYyby9VNmk5b0RSanlFMWhqNjNvTTlwaUk1Y0doMU5JVmxPVFQ1SFU3MmZKUnZ2
        cUZKYWpNVmhORXp3dUMwdW8xTjBlREpXVHJIZllpcGRsRXlZTHJvR0t2U0FPYXF5
        RGswVFZNQms2MVF1VkUvUmxxKzN4MFdXajFCZzZtUUlxMmxMU3Y5UkhjK3N2a3NJ
        VnFNVmNkVGxBNTBXZlg4N0Y2NDgxODgyUVVHcGkvVWhHVjhJbWtlREE1QnpGNjVn
        dXVsYzdVS1hkYVZzc245OFk1S1F3OXR2WWtPTCtZckZ4SlRxV21DZEJXWmdaRlE1
        b3VwQWNRRXY3Wkp2MVBheVg0TTlpbCszamtxZ0lIWmZUOEsxdVZubWpodFhTRnJr
        UVRMRUdJdXVNQWVCL1M0VmxwRkNBbUZPcml3azllWjhWM3NiTnZsZXl1VnpoYU5p
        U0VBVk1xYTZUODFOZnB5M3duck9ReTd6ZktQbzlpNkdJZzNHMXUreHZDdUxIU3VC
        TEtlNmpwRkI1S05UdjRja0kydnFBcHJpanFyTmhzMUFENWxodnNWY2lRQVh4SklY
        TFNaUTVGMllwMHVlbnpVWXk4bWJmdTRJNjZRVGxZaUoyTS9IL0pWTXgrd0VSa21K
        WE1sd0dKZFEzNFJ6Umk0Tk5mQ3dQempSNEdMc0VLcHlVRGc5SFFWRWVFRHk5M1lt
        WGEyZUdxejIvU1VFRE5YT1cyQmdZdGZxSGZhVjNMcVJqWlpnUGxnUUVHZmNTSjVD
        UThtcnlxZFNMQjhVM2NUWE91REpXOTBZbTgyc0lJZG50dTdaYWRiL3dZTytFZwpE
        WEtQM2l0VWkvVDUySTBvWCthbGthU1JCNzFwUW9YV3NIN01DWXFTVVNjCi0tLSA3
        SDhsQkpQVjZHUEJDc3ZtTmdjcVE5aVp4MUF5U0U5OWFoMGhhL1dEU21BCllj4KeT
        TPzU0YhuIDHz0v7Nnt2Bqt03qS8KHC5AoDJng/9ygSUqnvwetAFX1N1Oe+svSrmp
        aBZrO1Ved2fWe2s=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T21:32:22Z"
  mac: ENC[AES256_GCM,data:VYlVOISAIxRQbAu+p4CAV6ZcrKj1gg3iS/7dgfi03JHIRyan9yL4xvhOLjdjNvZ+r9ZuwUhMupvOGkyJyz/dEyxzje2Jwfj6WZi6fUBaesSIc49/t0NlzCCgOgrBw0vmhTyrbmwsqUbKwZEIMxyhyk0lo7P8QjjDHg0dV/kGkrA=,iv:ng0x2vzR6aW0TvFvqE0h48QjWMmhR/C8JnVhZky7myA=,tag:bNpQ+7F1I/G0T8dRG+2qqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:34ekthpMHMM+a67HKWNnRorwIfNUcQ==,iv:0+xHaWZ+DFBOzTilA0ch3y16xLkxN07yj4duiZ8XRHQ=,tag:QMnZCRcDXCP7pIIavWgdgA==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:HKJCF4O8XI+DnO1opYiRtCHDU8BdlBJLWqZAmkjrIP6ConSo/E2R9/3fjZeUnI3t,iv:OkrUUaOiMme+Xh3dXNzZytsEq9D6+78zDfLPvlXzUHg=,tag:05beFxMu9DG7i+XjukYv2A==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ajVHSytoNUgrUC9WRXRy
        RmFKU2t1QllEakZMenpVVC9UcEF4cjNRT2hZCnVBbThOTk5wUkl5cDBTQmFoL3VB
        RUxnamlISjF2VjJxTXg1ZlNGbno2V1EKLS0tIEw3Wk9lVVhkOVlndGFGU2NvNnVv
        T29JZE8zMGZUOTNWS21pbUFuaExJUEkKA9Xq3Z58rbX1IQPZvz274tIgcvAPh6zs
        ahAiEDmcn/HILlnMU2szhjsI3EQ5c9Q4UaTliDVrYvDCBigEViZfIg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDJ4eGVSSHgw
        Mnd6dXgvOC9sVVZhWGZhV0ZGMmh5TUtZbjdCd0g5WkZXR2NKR0thTmJsRVhSZmNL
        cjdscDlFT01mcXdTNlpNeW8yYmdWTTBIaE9VbXE3Uk53WHZsRkJQNXFWWDR0aE9Z
        VlFNbEFtZmVJWUxsdy9MaTEyQm5EbTJwenZWcCtVNVJSMEViMGN5c3pPY1hTWTFx
        dVFGRklwYjdQdzNCWkdQazFVWDg2OElaZ2RUV2pmVUJPalhTdXhXV2NuNmxZcXdn
        bHJ6OE9sc3Y2TmF1dUZodFZEdC92RnZZRlhFa2tuYTFGeTV0WEp4MlNtem1ZcVZI
        eFQxMkwwU1d3UnNvVXNWWnRmNlNlUUI5VlJ1MkdjSHpBK1dJTmpPWG9SRXRHcHBh
        WkZLRjU2eURhaW5yYjZiclNieDN3RSs1QUh5Vmd4a2RaQklvN3BQc2txMG9HZ3pX
        UGVFU2pOMC9PUDI3TEFKaXkwaDFKd0pKSG9BTlVWR1ZXZXZDeGtkbXdVRS9EYkp1
        Z1o4dEw3THBpOFpzOGM3K3AxZXdnUmFpQ2JTbGUrZEFic1E1ZU5aWFE3QzZMaHUv
        MENYazYrZFZFcmlTeW9mU0Z6aGVGdjIxUTNQM1Q3QmtKUktlSmk5YzlGUGNNMFJW
        Tm1FenJJTW9KRE1Jd0JnVGJxQml4bFVvc01CaTVqZjgwL1p4NFphZWVkcmx6VGtp
        SEh0Y2JHc2paUVpSWHNvL3VBd0loV2o5eTBvTkZKbkhnS1k5Z2RiVlJ6bHJHamhJ
        SW1LbGQwOE9oaGlxbzV1aXhTS0ppcGlmRVZ1NUMzeGNISlhZY1BSb0VCQkUxNmtq
        dUtMT1BaVTREUFVXWnh5QnNGVFpCdGpIOURwVWY3K2x5QzN2WE9qeS9TWHB1UTBn
        VEZZN2JrUCtXclUvUHR5SXkweHFhSis4ckJ1NnBIMFhpcm91SG1SL0JCQlJMQzVD
        V2tWbW5QZmtvak1GRk16NFBSNnJiRXlZUFpjc3JaZlVsTFRhWE8xdllYQ0VHWWRa
        MDRiMHdQTXZjajNzdzhhNHNUa3Z6L1R4VVNiSk1rU1I2SFNxck5GTUk1cTZVUEtP
        ZjBXRU9SNVZOWXA1aldXWnFGL2RuVk50MEpzb1lwL0orWE1yTlRQNi9rYU4vRzlQ
        RTYyby9VNmk5b0RSanlFMWhqNjNvTTlwaUk1Y0doMU5JVmxPVFQ1SFU3MmZKUnZ2
        cUZKYWpNVmhORXp3dUMwdW8xTjBlREpXVHJIZllpcGRsRXlZTHJvR0t2U0FPYXF5
        RGswVFZNQms2MVF1VkUvUmxxKzN4MFdXajFCZzZtUUlxMmxMU3Y5UkhjK3N2a3NJ
        VnFNVmNkVGxBNTBXZlg4N0Y2NDgxODgyUVVHcGkvVWhHVjhJbWtlREE1QnpGNjVn
        dXVsYzdVS1hkYVZzc245OFk1S1F3OXR2WWtPTCtZckZ4SlRxV21DZEJXWmdaRlE1
        b3VwQWNRRXY3Wkp2MVBheVg0TTlpbCszamtxZ0lIWmZUOEsxdVZubWpodFhTRnJr
        UVRMRUdJdXVNQWVCL1M0VmxwRkNBbUZPcml3azllWjhWM3NiTnZsZXl1VnpoYU5p
        U0VBVk1xYTZUODFOZnB5M3duck9ReTd6ZktQbzlpNkdJZzNHMXUreHZDdUxIU3VC
        TEtlNmpwRkI1S05UdjRja0kydnFBcHJpanFyTmhzMUFENWxodnNWY2lRQVh4SklY
        TFNaUTVGMllwMHVlbnpVWXk4bWJmdTRJNjZRVGxZaUoyTS9IL0pWTXgrd0VSa21K
        WE1sd0dKZFEzNFJ6Umk0Tk5mQ3dQempSNEdMc0VLcHlVRGc5SFFWRWVFRHk5M1lt
        WGEyZUdxejIvU1VFRE5YT1cyQmdZdGZxSGZhVjNMcVJqWlpnUGxnUUVHZmNTSjVD
        UThtcnlxZFNMQjhVM2NUWE91REpXOTBZbTgyc0lJZG50dTdaYWRiL3dZTytFZwpE
        WEtQM2l0VWkvVDUySTBvWCthbGthU1JCNzFwUW9YV3NIN01DWXFTVVNjCi0tLSA3
        SDhsQkpQVjZHUEJDc3ZtTmdjcVE5aVp4MUF5U0U5OWFoMGhhL1dEU21BCllj4KeT
        TPzU0YhuIDHz0v7Nnt2Bqt03qS8KHC5AoDJng/9ygSUqnvwetAFX1N1Oe+svSrmp
        aBZrO1Ved2fWe2s=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T21:32:22Z"
  mac: ENC[AES256_GCM,data:VYlVOISAIxRQbAu+p4CAV6ZcrKj1gg3iS/7dgfi03JHIRyan9yL4xvhOLjdjNvZ+r9ZuwUhMupvOGkyJyz/dEyxzje2Jwfj6WZi6fUBaesSIc49/t0NlzCCgOgrBw0vmhTyrbmwsqUbKwZEIMxyhyk0lo7P8QjjDHg0dV/kGkrA=,iv:ng0x2vzR6aW0TvFvqE0h48QjWMmhR/C8JnVhZky7myA=,tag:bNpQ+7F1I/G0T8dRG+2qqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
