---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: externaldns-ovh
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.20.0
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-ovh
spec:
  chartRef:
    kind: OCIRepository
    name: externaldns-ovh
  interval: 30m
  values:
    fullnameOverride: externaldns-ovh
    logLevel: info
    domainFilters:
      - ${NEW_CLUSTER_DOMAIN}
    env:
      - name: OVH_APPLICATION_KEY
        valueFrom:
          secretKeyRef:
            name: externaldns-ovh-secret
            key: ovh_application_key
      - name: OVH_APPLICATION_SECRET
        valueFrom:
          secretKeyRef:
            name: externaldns-ovh-secret
            key: ovh_application_secret
      - name: OVH_CONSUMER_KEY
        valueFrom:
          secretKeyRef:
            name: externaldns-ovh-secret
            key: ovh_consumer_key
    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-name=envoy-external-kubes
    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-ovh-secret
    policy: sync
    provider:
      name: ovh
    resources:
      requests:
        cpu: 13m
        memory: 42M
      limits:
        memory: 42M
    serviceMonitor:
      enabled: true
    sources:
      - crd
      - gateway-httproute
    triggerLoopOnEvent: true
    txtOwnerId: main
    txtPrefix: "k8s."
