# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: externaldns-ovh-secret
stringData:
  #ENC[AES256_GCM,data:XdnsqUcuFFLGEaeN+C8TC9oNmZ8FmQRgPqn7dfLVgacbievTjcpzT09WcSJpEeXjy1tNGX52ldBGeD5T3JORwQEnmn4fzWPL2Qpqj4fM2sLfqoQYrPS5Wn3y0UGY+21MhYPWggUj315DWbt/86oa/gUwz/3vwl5uOR5DweNF/uBZQUzvc9/3eC7kQNpiTFMd+6cN7gIJPJnXWnPv3qcPlDrGtxYYtNvS0Af9B3M3LmUczB6y/6apQSENXi7kZxzIX7NlzX/HgK8bkMns/+DsVbWyd+mbjCW7PV5lLJzbKqjgn9iqAMckwzRc3Z6H+wACzr0VYyyOwBpaTrID2JwugIM0UxVeZ+mxA3xHg+g=,iv:HvPKLInxmtiW+GaJCDLWAYyGw18FG3ldLJn6WYfkJV0=,tag:nErNuZEA0yr58j5yAglW4g==,type:comment]
  ovh_application_key: ENC[AES256_GCM,data:JSR9QkwyK+7tJ3f3elxmGQ==,iv:o4i1MmEz217bcMOvTxWGUrHL345rEBwPmOslJFC8xcs=,tag:gzbXIVb7JDYzY8R0tUNNYQ==,type:str]
  ovh_application_secret: ENC[AES256_GCM,data:FqCLUkjwlKwzKmgQ9XAgWwI8LyqcQmVN2Bzl9lvJ7+A=,iv:QpfvwxoBXA7Fi7T2UDwo+Erb26ALV0npIkfWKPkcel0=,tag:wcDOEcDbe9AiRq96dqcKlw==,type:str]
  ovh_consumer_key: ENC[AES256_GCM,data:bR5wvaBwoT2gNL3ehG+att3x7rP69qkVeiuJ6jsT78U=,iv:FC23Oe7cgtNAz7Xqv3mJpygFALOBxbJN9l/EE4dS2pY=,tag:eWJQninVG/jc+auuSWwRqg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbFUva3U1WENjWDlOWmd0
        MzNMVDJ1Q2IxbzM0Y1VxRTVjYml0Zk5QbVdNCmdJYlF6NnFrR1l1WEpFQUJmZ29p
        V0xmYnBOUGF2akg1MVdDdlQ2Qi8xdWMKLS0tIFM4cmRTNjZKSHloUjBoaldNenV4
        RldQVnhmcUhCOWhyQTlJWUhLMUU3MU0KGPv6MzgQ6+ttovMUmcspsENAHh8JNSv0
        xjM+ndLX1b2eRcJ5Jws9bVrB3JpmBO5yQJ1J5I3VOA+ywuadj6y6eg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFpBOVoyMjUv
        bEtJYjRyT3oxcDNOb3UxR0VDRDdxd3JBZGM0S1ljd3NRd0JBNjljRVpINHZpT0pm
        WGt6MG1WNjlxQlZtZWR4L3d1YjNieHVBUkxZb0RCRGRQQVd0TjdCWkkwcDZsU2VS
        cmkzdUxpSDhBUjI1b0lyM3V2eThOSisyOW5zU0JUUCtHd01ibC82eDhOeFJpSVV0
        WnJZSjZOSXdOVWFUb28rRk9mSmY3eXQvY2MvS0JZa21NVW1SaGhrVUs2NUREdHox
        Wi9sUml3ckhPVUFUSDBSWm1qNFJQSWJjYWNZaFJYSG4rTVJrM2dFZXBIeU9jaGNF
        MU1PL3ByNjVHZTB5Y1AwZklVbzV4emVZSWRneTB5NURDT2VKL1hnTGo2SW9ycURW
        WUlnU0pyTDRvcURqS2Y0NTlRcmtwVHNrRmlTamhHNDlNVG9vRWtWbFpXZnYvTnVQ
        SkJWNzk2c0ZUY2ZHVFNGNWlzaVdFTk9WVU1acmQxV1NUcG1Ua3RjeDRrTk9FMDhC
        MERIcmFqWUh0Ni9FWGZYejM0a3pvMFIycXhNWSt2NnJyd2d0K0xieHlpYVFCdHNX
        K3JpQXFUanFZcmR2L2lZbGIzSEVwSWNieWRWZkwyblFRanlhVWZRZzdvVVc5S2ND
        RlhaM3FGcmc4RjZKU0Fyc2Y3WXN2SEh6ZDg4cWpmL0xCSVh5R2FpSEcwSS9tN3Mw
        dGtTeTk5dVkxQ3ZzQnlHYUFhSTA3d0YwRUJJSjRxRWpzbVJXd2grTFBuQmloSUZB
        SVFpcGtBek5STlVIOFA2ajdpYlBIZitZTVlVNFpMTXM5R3pHL1NObTFXNm8zaEdJ
        MTZ2RkxSNXJBZm8vWEI5TGZzTzIvSGRpQmlTQVFxcmNnT0FzbTJSNW5GS0U5Zkd2
        SEdFeE1zNXlzYm5tdFhtL2ZUZTNWb2JXTlNNQ0xXNStVVzZCTVU3YSt4dGV6Y0V1
        cUc4ZlRqVHh4blVLNzJmTEQvenlWalI1dThRWHROcWdNM2RDNElETU1jeGxJZzh6
        V3lkdkhxMjVMcmxFWnUyN3JCdkcrNzJxWEQ0MXc3OTZoS1ZiTGVYR2FMb0ZrV0Jy
        ZUs3K0NNcGhONnppUk1ldjdEclJjMDhFK2dNZHRTZnp0eGRBNlNnNGh4S0NMM0d5
        NUF0MjV3MlBRejZQZFZtMHNhZWNBZ1E3c0xncFYzYXFINHJBT1JXUEZxM1ZkbDU4
        ZXN5cnNIaUdmNG9pVG53T09uMU51YkdQdkI5bi9aOStzbTdNaTVJWGJ1a0RmWnFs
        ejdYQzF6MFRmK080dTZpejJZejZ3RUFVMXNDa0JKZzU1bnNaalp3NlY0alRMWW5Z
        Skl5dzB5eDhMU1FxYk1wTjJSN1RwMjlzS1EwR0dxYlhURS9MVGN1bTRZNDRURlp6
        ako3YiszVGJySzNVamVGRjR6WXl5OUsyZFdPcEJ6K2k2TEY5VnZzRE9LYllSUXJ0
        cUVBbFdqNTdzWTc0cDdIVndMdDR4RVM2SnJvQndxNnQxVFNtRXp3WkdPOE9SMTht
        K1JTM0prQ3htSCt1eUpEcUtJamlHOFQ0SlVsT3pVenJhNTVoTlFUQm9ScERJSXFX
        NDBZeE9TbzdzT29SUnVBUEladnUxODJUdFRydDlyRlFBYm5XQUw4SlZBcFlYU0pQ
        RTFaTjZwMERyNmJXWEhnbGUrWndWZENNZ0xySFFaV1NHQ3dmK3pramxZai9VNHZa
        THAzRkppQU5Bd3hCcHdnR25hTG9SbnpyZTFmYUJTYVU5b1dlZ3p6WnBYSjBXNFN0
        NkFUM1h1NGpyYUR0QnRjUmpEU1pVREVsWnh6dG5hNnhqUU5tOHVPaFRQM0RNa281
        K3R5UERlM3JVWjRPOG1NRXN4Tzk0MEwyY1BnQzJXVFdDUGloeVZKSnRRVUpRZFla
        Wng5cmpHMi9XcU5qWnRjSjZSTUpXSzRZaDFjMjhFajNRcGpHRXB5aWlZaVZZQQpO
        aHF3SWpvS0U3dG9rM1R2TCtiQTBKWVVJVld4MEZRbDJPdjJUQStRbmpZCi0tLSBr
        MHJXU3NWdEtvaFJHdXJTeE1ENm1YSXZJYnJ1Y0NLdi9jV0hWQUtYSEVrCnNSRAfY
        5Jllz9pwWmgd/Mr1fU3+8HSnHLlzJ/k9j63ZKdOQkGP4Fddl01FYMLWQ1rZadwlX
        EnaSu1iyIlNAsjE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-19T08:35:56Z"
  mac: ENC[AES256_GCM,data:rkKLfzN73KdmBVSLMnZZREcQoF3Hi2SLmI/DI3oU8tJwGxKvK+1qO9+9ktyiHv29qyZm55t61Mb3+3X16QZhoyc6Eo578FQ5bPVUa6Dyxp9+EJAQUjvvXj7iTxbjiO6OiKFLx+QHYCeefJNL7IT+7TTjvWPrGEpvHmHtlneyF4M=,iv:1vWvZGmwVa9f0TIdgQK6Hy9n2IPr9kaMnvJ3spV4dnw=,tag:k6a3Pdhw4o/tiqJFn05DAQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
