# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: externaldns-ovh-secret
stringData:
  #ENC[AES256_GCM,data:M4IB7dXaSrOcPo53iLObBHS57RJdKHSUGkH5WH8izSN+B609JTpiiusy8F5yF7+DSz+3Y9l6qsQiGqgiu6tXMXdUrOTN0QevSFSVLPggttrSMwju/SFOkWq8nzGEhgjB2ZAj0rJaMtRmMWmVRGsKE+wb16lYQCgONKL7tfKcJg9+zb41auLBV9T8RlPqwh6YVQ0PHznOnB6/6t7GVoWREF+DpKmFq3ttnLg0jbIbEfpJFjxVvLbVCv/g32rXs6mG3cbgbYjg43G/Jk5lGm3ZnYh6TxX3dTxXGifkjvWz0t63IxXtUt536yQUA488+6pVvloF9ooIzfEhPoj57OcDvqrOTbccyDyiDm71kLI=,iv:HvPKLInxmtiW+GaJCDLWAYyGw18FG3ldLJn6WYfkJV0=,tag:SFUoKG/Jd8vNwF7yNWCISg==,type:comment]
  ovh_application_key: ENC[AES256_GCM,data:EQYw4ut2rtucipA7Q93oYg==,iv:o4i1MmEz217bcMOvTxWGUrHL345rEBwPmOslJFC8xcs=,tag:Lhy9J+OLSV6882I5MziQ1A==,type:str]
  ovh_application_secret: ENC[AES256_GCM,data:DW3c4yATANcYtZPWuQgrOaWSifmlnGVZkB04yrG8PyU=,iv:QpfvwxoBXA7Fi7T2UDwo+Erb26ALV0npIkfWKPkcel0=,tag:B6QUGyW9CYmP++RqXJ5NRQ==,type:str]
  ovh_consumer_key: ENC[AES256_GCM,data:Sj3SoF9aOlijvmBdCPfhtHqTEyjK9aLMbtRng8k48Pw=,iv:FC23Oe7cgtNAz7Xqv3mJpygFALOBxbJN9l/EE4dS2pY=,tag:C063wYvXtuKtXyfpVCJqjA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDBZUFlqN3Zr
        UjFqMHFoejRqZnBxdEdSTnNqRFp4NnVMT2V0WTVqQUlpbUZCc1o3RktSZy9Fb25V
        UVR2OEgzYUVaR3AwM0JXbkVyN0FjYWZoN2RHN1RVZW1jY0k4cUZmYjJXeUNqcXJw
        dlIwbzZXUHZ5TS8vazMrWlJ5dWN1aG1TWVZodHFGRnpKL2hJcVhoRzREVWNFeWti
        emRtbFZCVU9tYTJoVXAyVE81cGt0ZnRJRnAvdGZWOWhkMjM2UUJpSnp1UTlvN3FS
        RlRscXp0YWtpR2F5RW51Q2tqbDVZc0lGWGhnRXovclpSODBud3M1THNEV2hqTUJi
        dDBEampXN3ZZK1BuNlMwYkZHVG5ZMXAvMjd6TVZPMXdKRFhqZEg4UXVxQ0ZaVnNh
        ajFrdzFxY3EzUnE0ampsK0Q2UDhVbFFoQjB4MjBLK0JvUEZzeTVOWFBYWm4zcW9p
        Znc4ZTBmUEdsMU51VXlVVkRVcE5HWkpuQ0x3Z1RJMW1POVE1OEluNTJrdEx5YkVp
        TEtaQkRXSEovVGY1M2k1N3c2a3VzS0tPdDladlI0aFZUSVBObWFxRDRleGJqOWFM
        aURJbUVyQlJjVnNOTVhQbUREdXhvbWgwc1pUcWl6bXFBWWFmektkYWRJTllMV2hT
        WGEyL0pJTzJMVXlIakpXSXNPNzdYeEpSK08waHlaQVNxYngzbWIwb1pMdjVkT2FN
        ZlovRFE4cEZscno2NXIwTVJVV3hlYzhJOThlaUE0M2l4cUpzWFU0L3JNV3A0SWFT
        US9jdk84cTM1Z3dyckNnQ1VsQmZJQVhRUzdSNUp5eFFNSnZvNGJTME0vVTBzblRK
        T3VDZHZQcjJMZjMzditjQ09HcnEzZ2pkcnJ0VHJrSlR5bFg4bUF2eWxtZ1pVaTRT
        NXBGWGRkRE82UHIwc2hvY25Ia2xVVzg5VjQ3YXA5aDFYWnFZUzQ4YXRNUVZMbnFp
        eUhRbFpSeHQ4YlVlUkVCd0JsVlF2T3Z2RW9RaWtKRGVDNStFZGk3VjVVU3BhS3NT
        MFprNElkUUNXeWhrTzZoNUpQd3E3S1pRZmZTZU5JVGlxOEhKTW5LY1daRDNLajAy
        SW5ocXRsYUV6cjJKdmgwNGFvbVZJMVJrNHNzeUZjM281dXpkbENYYm8xcCtZQStu
        cWZTRWdlYUlLL0Y0UmpPc3JUWXRwQjNqdGlXbG1WS0tmR0c5WlVPY0VZVFpHc1M2
        YmNsdi85TzJmRUg5TmxnUnJFNm9pcTRreDc1K21Ld2dUQ0hXQkg4bmZWYU52Z1B5
        d1RURVdvMVlmeXRmWWg0VlRST3FxUlQxcDU2T1hkaHhxanNCUDJvOTZFc3BLS3JK
        V0hSeVBTR1pBc2RnZG1JbWxpK3ZOcnoxbWJzMFJJRjN3OE9JeEhCUE5VYUVsdUNX
        TW96YXgxbDJ2YUZSM05XbitaY1g4NU1SMTV3YUFVVlF4UnF2OG05ZEVoYjVOQ3Jz
        ZHMxRDdxWGp3cERvQXZtQllKRE5wNCtTbnRWRGxHMzlLa0tMaWQray9yQ09DSWFs
        VnhmL200aUxlUm9LRHZvLzlmUEpGN1ZWVjRTVWxTRG90Vjhyd3BqOXVCV29wckZn
        UGcrb3hDNW9HYU03RjhYb1ZEWk5uRjFZZlBrRTlWZUxYSW9UVDRuUWZlLzVRSVJS
        MzA2N1lEU2R0ZmN3c3pLczEwK0tWLzJRWmRpT0pZTFF6TWpNVnFxNHhFNzhueVBJ
        YnFXeGpOaVB6OUNhN2s3Y3czODBOQXlMdW5OamZVVUx2NVI2YzJVNUxGY2xqMHpo
        YVpiN3pFazBMSldiamxOQnBoais4UStKTXVFckkwMzNtVnZFVFJ5R3ZzWVE3Vmw5
        Y3RNODZ3TEhSaFdFc0QyVEpvNks2cmRoVlRSYkFuTnFHazBWcTNxYXc0RElNbjNB
        cmROaGEvd0Z4Yzl4RXYyQkVkaTNWUGVxY2xoMERuVWJ6emZ5OXk2R3FlaklUdwph
        bzd1ZVpITHZrLytBNlg3YXBnUlVFMzVRVVZkbVFsczA2RlRvc1NOUnM4Ci0tLSAz
        MTZMNUhLV0ZhdDVvVGwxL3NYbncyR2JoemdIVUZWZ21uRm9qK2ZQNHBzCntnExiw
        czCNg3gXRZDJ+V/itHVLR0yX20Zziap4fKDf8Lr7GUbOj3DiXyT96Pph0VaeMs1s
        PFvuna9CKLgYQgk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:9JiajLeqKDnnKIG3jxVZlVIoBa+D+4R9ycS4k/ly8FTd0LBO/N9Fm9sycEqHSyGd8MVL7B3hOA5teJm7AbwqGrtxHucCjZuFM7wGZXCNFWDhtbWYgTX9nN7x/45H0ePROevVOYlyOC8/ReIKnwmt4Y9/yRhWmEZZCfLdBhJ0/jU=,iv:UjJyCFf0DA9WxIf/fG0GRkpi9QoGZunHJhq6wqjebJQ=,tag:V+uX5k7osXUBkB3JHejQQA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
