---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ../base
  - ./cronjob-restart-app.yaml
  - ./rbac-app-restart.yaml
configMapGenerator:
  - name: volsync-cold-snapshot-${APP}-script
    files:
      - scripts/cold-snapshot.sh
    options:
      disableNameSuffixHash: true
patches:
  - path: ./pvc-annotation-patch.yaml
