# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: stunner-auth
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: social
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: social
stringData:
  type: ENC[AES256_GCM,data:gsYJ4+PXWkNg,iv:PqT2RPHUlr3zJ5tAaIOPVLyzD75SGCTbi57Ftu1qwuk=,tag:/UgGDp/RU8CXD64028YrjQ==,type:str]
  secret: ENC[AES256_GCM,data:Tf+fvlO5DMXyTrP6obRbb3CFauREdVwoko3PCkHiD9sulz/7sv5YO9NQC1Z98SxDyRhU58HbcoEIioewqvtPUzFvMOODxccpc9hnlZUJkpvTtlUinkoXTfLCDTIT92rsLZhmKHSdTttWH8ewwJ6A6i6MTx9zIU00p2BNAp/8Moo=,iv:fR6IsoYF6L2yA6b5yKXq0nSGSd9vEX7GQd/IQXxGAGw=,tag:FJ6qndOLpeoVU7A3dCovXw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cEx5SE8wS040NXJRbjEv
        NU9iRm40Znd2bUM3WTQ2TGE3Q2Q2R2FyV0MwCjlMV2puRENJUDh5NGR5NXEvZHJt
        R2UyOFNmZUQ3M3lWNU1PUXVDemVwQncKLS0tIHhBNlFOZGFqYzNPN2sxMjJXeEE4
        aGJHMlJacDBJbjEvYXhXa2Y5RW12REUK2bp/px2cY027/0BeIi9Q+UJJBlFQwWyi
        BbhWBxiVxQRu7IQ/RBqxpzuk7DJnx1tP6Onikiy9R75Z3GnLTpaFNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEpRTkt4YndO
        TVNpb3hGVXJUcVdUUStVWHJTcXRoUEVTc1oyRnZYV2YwM3UrQXJac2JiTTlVVHVN
        OWpYeDhMOEJXYVBicWZyOUdVMUVVTTVOcUlFWHBVcWk2YlVvMTV4bEE4bUp0bWhi
        N3hiRUpFUEluaGJnM09CRkRzMFVzSjVLWUlyQWdiam5paWpOTGQ4dHhRYnhFYXVt
        NHdxd0kwRVBlM3YxenF3TEF4L25mUWVUZVFZQW9odkphQWFKZjU5cEYzUGlsd3p1
        eEV3bzBXK0dtaDc4Tk92Znh3OU9nMVVPeDhEMHdxSnJYYVhzVDB0eVRpMUZMeDBM
        alo4ZG1JSXZ4WW1XZ3gwTjhQaW5HN1F6NExIL09vK0lQZzNxd0RXck5OSExSNXNV
        dVh4VEVaa2RpbjZYcnVxN2ZlRGFEcllkdmxLYk5XaHhIYjVkVjRab0dsYmxkcVpz
        c3VvVFQ5VWlsOVJYUzgwbldHVnFGRHE4cW1oZ3dRMVJMUVJXRU5KZmVUTnhRaVM2
        ZWQ1ZjYxTDcvbTE3OWpDS3NIVkNQY0U3eGlFSmNKY2RaQ3lhQjBKM3c4M2RTaHZs
        UnNrd0JOKzNEZzhFRk9nWnQxUE5ibWd2UURySWZjckRobEhmN1BTbDRmSm9NT2h5
        OHJmbHpKSHM5QWhqWkdoQ1doNXF5RCtFbVRJQWhVbjZGN3hKUHcvcWptRXM3ZGNN
        OGdOdyt3c2puVlVaSFpjcmQzUTJLOUFjb2x0cHJSWDdSeWwxeExxOEgzVTNVY1Bt
        YjlBUXF2S3pQcUFObTkremFhQkFtVXJhZ3pIN1l3MlNNaGtURGxtRGRucjB4bm5J
        dUt6N3FQdlMwMVlvRFFNTlc3L0w2dVJCYTh0OFNCV0p3TnBjall2MEpSS1pieGl3
        M0lYMzc1SHA5Qkp4T2VhVW1WUERvWmtpYnZOQ0cyaTBBakVDaHBUbmZlSzREZmhZ
        MG1mMC9welpIa24rS0xiQ2poSktsc1hSYTdoS1U5UURzZHJmbXhjaEVUWXI5elBW
        WkhMTURQN010cFJ2MzdiRS9oN2k5MHlzOTFXek5KQkYwZkxOSDVyN3p2aTROZS8w
        Z2FON1IxS0xQRmlTaTRjTjlUSnpjU0VrSGlMb0FjWmVHVmt0d0FKY1c3TVM4TUkx
        SDRaVDIvZE9tc0NXY2xxVERKM0kyS1o4bzk0UzlDdy96VnltKzNITzVXRDBreFpn
        alJwc1lFNTk2cHhQckRqSk93NnVwUVYrRjR3R0xkeEluN29Qb2dFZXhKOThubnlW
        cTdBVHB0STdiMFRFeENtc2J2djhZYTJQQXZ2VGwwRFpvQlJDN1hRQWN1eDcyUmRq
        cW5Bek12V1lkRTJxajczcnd5WkVLNkYyM0tFcml0cVl6WDZ6SVdJNzlhTldPL2Nw
        ZU50L01sOG15TkttN3pBdDFzaGpFWjR5SXM2VEJNeXZXVUVRZktUMHIvc3pxYlR3
        cnMyeHdtb0t0aXREVjJPWFhaNDQvT2orSDZEMUJGNDJydnRWTEp6WFdiWTJ3NndG
        VW84VUQzSUkrOUZ5OERVY0xFYlZFQVk2eHhCQkc2N2FDTUd5N3J5NlU2NG9uNWJQ
        UGtKUHRsR0tHa0NlMzAvRUYrUXhCbjNTdnNmOXE3aUpkMTlOYjF0bEJ3TlhDSTRP
        TDByZmpqOGhLSXdWeGRTcXRsdzFhNVBlS0ZjY0tFVFdTdXp1VnEwMzJNNVRrczVy
        WEh3MEk0NTdUMTRtdmlLWDJRaHlsVUlDTGc2NURUVHBydi9YeExpNG9nZ05WQ2g5
        a0VrcnNUb2NmUUR0c1pxUDdDYzd6alB1ODlhNTI0YjRyNlFiZm9icTFDRWR6bG5z
        T2tUOGVVUTFJdGxPcUFmUDlOL3N4WVFQOEk4U2xUR0tuN0hIQXp4alVEdFFhR2l5
        Ri94YmhaRGl0UkxzSCtPT0ZPS1FkS3ZZcWpKVWZERWViSVhFaTI0ZkZ4ZHNaZwo0
        Z1p1ZTBHeGV0S21oSjlCYVhsNXNEaFd2NnFadVdmOGdGV3pFVWI0aWxRCi0tLSBz
        cGNnSWVvQU1pcmJXWlBRRWtBMzEwNmVYK3VxdUFzam83MFdYUXQ1VHJzCvvzAZ9Q
        gZHHbyGjhsGncGiaIK7c5Xv450cyr/CqggphO9TUqZXZJAvYmTpAeFJVZPdNwh7Y
        gxAiI/qdVLgd8Qc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-06T07:00:28Z"
  mac: ENC[AES256_GCM,data:/wLl7dENlUXziVRtqykoBzVz4bl1TSJlJ3JtAi4gtvjJIDH3KHOxapJW+Aaq7AE4NvTzhKaTC/xX7D/YIJGzDdG+Z4XkNcHC0Rbz+Tv7b8GzRxp7RUU0NZDoc9oK7w39m69JrK2N5+bPGBHHWd9lQxlLUx26+vEkUha5OFMUyrI=,iv:Ej5ELJf+6pO8R48CyQMZGF5vNX/mdimxIu6cSYGfcyE=,tag:fBWtRqneCxV6ICj3SlVf/A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
