# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: authelia-secret
# Authelia env vars. See: https://www.authelia.com/configuration/methods/secrets/#environment-variables
stringData:
  AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:sJCd0mgHFaju8PW3EMInkT71CvUxHf5zpy04rCcudhmufZwsWPKamKYi63/zcYrA00AQCnjM/sG6wmlb/5fZdA==,iv:8d7aORL5JKvcPXaAdRfEn+47JZO/VRira8EjlQWK4d8=,tag:krKpuLKMkRCseQpandtOrw==,type:str]
  AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:vNUclRFHFALycB+HS1vsMAQIL/Ue7FilZHbbrKAEbI/v/9WMGirUUo0ZrhCv4+tgrrEgQOx6xDOj06h/LZIUOQ==,iv:VoAtecG822ITU6Fx42p6o0nXrl0BkJ2Enw3OKJOY2pk=,tag:pv6FB7/A1adH2PRfhs8S9A==,type:str]
  AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:JA05fSj0Xi00EmiGuf0MIah5SGUGhVd+DYuHfHArDgFaHsbCSEVIN4hesyjXnFPTpkpB//nM1uRza7GSmiXYsA==,iv:tQrDWzSRObhF8hGvWJRwVSeqMaScdo26q+X9aDXpXs0=,tag:cFT/MXvekKNVY7aNEXAY/A==,type:str]
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:eoA588YnmUbjUyoewJef6Om6yQ9SYPoG8DwQCGcIpAl0WzQpDJqJn/sk,iv:od2SBn/NVt0vG2Z5QviBiVB1T1cTd0hvjfo8dxUvrxw=,tag:EOd4oCovb/7ZFlx9Q4aiSw==,type:str]
  AUTHELIA_NOTIFIER_SMTP_PASSWORD: ENC[AES256_GCM,data:hZpmpDtKoW2+Np4ihpbJpw==,iv:nI+xsHMudv9r3seLRFutVug5wEd+9bZ2hqJHc1fBqTM=,tag:iyvMwG9csc0znawsSmztjQ==,type:str]
  #ENC[AES256_GCM,data:+X++qem2BrUe,iv:Ld6mdOsZYPk5TeqFmHN90bstAoz7R5XhZXO9Eppl/HY=,tag:F8XdxmCAokGU0SFiCBoQkQ==,type:comment]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IERJOVI1L284
        bWI1TTdKYXYyY1JDSEVlWUZIRlprcGxhSXpGRTlKeElZN3V0V3FNa0xuMHlHd3hM
        LzEwT0QxUG0zdnI3K1JDVElOeDBralJpZjU1Um9zK0JYRG9SSWthQXZIQzdJQTQr
        V0huNU43eERGSFVtUmZ5elpLVE5ncTV6TFVldThoY1BVdWZHQklSeHJya3BWU2Vn
        MWMyNnNlWkRGbXlabXBhNVlzWFY2aW1ramxRQzQyQ2czL1NxNXNmT3pQL1UxOTYy
        RCtxYm04M2dCVThYeEc2YkQxZ05NREVtL2JsbitpY2M5bDVGUzBmaGxwUmp1U1Vj
        OEgxNlFSaDAwbkVjUzFJZXkvTEZpT1RNNlFwc2h1UXR3b1BWVGR3UWVSNmhCQ2dH
        VGh3RU1rSDJTVndBb0pqWGlZdzBFRHZEYWZFdCtBd0x2ZjZRVlNzbmZ4V1VLdkgx
        Q0lka3d0NXJob3NUWFNVVTdTOG5QcnNWODBrdEFoenllSWJjdnFHQkY5SkpKWmhK
        VmkxdVpnVEZCMmFFNFlEaEx1ekpsMVJoYk1RaDdjK05vdmFOTmN2OWQ4K1lydzlt
        anVzNDFFeTA0bXVkaWFIT0tDTkJHcHIwNVk3WW5KVEZwTnhSVUVxRTZMT0I3TWUr
        eTRMNVUvNkh4UVJZbVFJaVY4MG5kckp4VjY1dnVIRFZFS3prOXBWYituVjBUbS9l
        Y2pQTjV2S0QraGtpOHQrRUxkYll2TmZBbVJOdFg1RzlvTVl4YmxKMFcxWnkxSCti
        TW41UWNqZnZDOERtd3NqRDNZcWQrczVjSFFya3BMMWgwVy9sUFZXVTFjY0FjallL
        TWVBU25UTFpGSWtuc2RvaDdVU1U1LzAwb2VWVXIxVjJJWWQ3S3JuK2s3TlhDOW1v
        bFhHMkcxSk8yMDJKUE9SSlBIVndFczJhZFdSRU5EcVV1bFJ4NUZkSzlRVG5pT003
        RXNxSnJUajFDVDA2b09WVUZYUlZSWFpub3BaZFBIbFEveXBoUENkM3Q4U2k1MW53
        NFJGM3dlYWZ4QzQyU3JFdGgzb3ZQQjdLYTlLOUJXeDFIenVTRnpIVWxwQnc5b1dr
        RDl1UkJUdXZKTnlBV2JhUUxwdWI3VmY4RmJxekJBYXNtem9ULzE1NHBDUkMzamZ2
        SGRQMWVhTTRtcnY5czZYWEdQTUV2SDBNYXN0TXVaMkRYME9YL3BSV1hORmVLQVJK
        MVFlVGNCT1JXTmFJOGZJVDZpaXNsYlZTMlpsVjVhWjFpdE9Gdm4vN01LSFhSNEY0
        TmR6dnRzL3JoUWpMM3JDV3djZ2VZemhPWDRXV09SdmRDSHIrbVRlMkYzVnNWZ3hv
        S01mTDZaTndjNENWNlpiN3pvYlN4dXFIczlKenRHN1FHaGVjWFdxaEUySkgxVWc1
        MHB3cFdvd2wxdHljKzg5dFNIcFVWVUV0WnZlMkwrMFJhOWFKQ05HUnFMWk1tQ0hS
        b0R5T0FjTCt0MFFEOHF0d28yOGNBRjhiaWtpWTBmL0s1bXkySlRqekNMQWw1YWYy
        Ny82UE9tZitVYXM1VG5RcXFNMkhoS1V4R29CWC9VNUVHNWxxNkFIbEF2RVh6VDBQ
        R3hPTUYvWW16Y0lxNGF4WjE0NHNtV3pCQTlpeGc5WFNia2wyYnI0dmloalYzYzNJ
        a3VJelBrbXhUR1REOS9HRmliRlBncTh1LzVnaGVGTGNvMjlRVWZlaE1MWS8rSHpO
        R0tmVVJhcW85ZGFoMzhCc3BIYzlFOUMxNVVtQ3hnYjUvMEVSSXRaOWkxYklxczN5
        RnNOSlZ0SWZmczdpdmZIcnNiT2ZnaFVqQndHVTcrMnBIOEFoeTNBSEorNVYxU2d6
        akI1ZGFNSjl4UG9rYTVhbjRvNjFGSDJwN2N2SUZFT0lxaDhiemVBRzRQYlp6eXoz
        YjYrL1kxRytib0pjbU5PNHhTVGZRTGo3eFZRemczYkZLVC9MUWJsVXBRUjdiQQpu
        ZlgyS0tMdW5wOWQ5OEFWN29lSXdYM0duTWhiSVcvVklTS3k2REtvK3VBCi0tLSBX
        aUU0Nkd5b3NtQWhQOWpTVENLcTJ3VG15SzF0L09IbWNsVEZRMHY5SUFFCm+VF7Ks
        fgToQhdgprzewhoi6EEZ2bGhWZKmNPq5O3qtsC7/l3ECLBMyTYS7hBBZ28Cr7igs
        ilG4WE7GGBiAm3g=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:ea6JWSWZvwWE1KHzKC100VlPLFXJ/ZaqQwOgNBtO0q29wo9nrZwke1wpZYtJ0WS88RyknTXqw8RvYVysQCQZ/4rp3JPUOhFGE+ZOIqrXP6eYeD5e+XcRGnQxMLgPRKUuP/8Kg/h8GFjwh0sLl8u7fX37165CCwB76NuLMsS2Q0A=,iv:FtCndzja4g0UJLTlZ5OapD+TvN7BefFcfHURUOwXE0g=,tag:ZEHGq97FSdHXc/+LHwI5hQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: anubis-key-authelia
data:
  ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:V/Su080YmQ/N3TZSWoL/bJL+UxluxY+VJxT5VNwLj5XIcnuR72gk0i231NhgOrl6R1WGCTploVUk9VDOrxE6+eT5z9LXajHoGRCrf7XX/3Li7bjoeJiaTw==,iv:OvOAMR0r3WYPHvh6ngLz4Y8v8kap1sVgON1zbRYiIlE=,tag:NpFODHlu108eBKae2w+i9A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IERJOVI1L284
        bWI1TTdKYXYyY1JDSEVlWUZIRlprcGxhSXpGRTlKeElZN3V0V3FNa0xuMHlHd3hM
        LzEwT0QxUG0zdnI3K1JDVElOeDBralJpZjU1Um9zK0JYRG9SSWthQXZIQzdJQTQr
        V0huNU43eERGSFVtUmZ5elpLVE5ncTV6TFVldThoY1BVdWZHQklSeHJya3BWU2Vn
        MWMyNnNlWkRGbXlabXBhNVlzWFY2aW1ramxRQzQyQ2czL1NxNXNmT3pQL1UxOTYy
        RCtxYm04M2dCVThYeEc2YkQxZ05NREVtL2JsbitpY2M5bDVGUzBmaGxwUmp1U1Vj
        OEgxNlFSaDAwbkVjUzFJZXkvTEZpT1RNNlFwc2h1UXR3b1BWVGR3UWVSNmhCQ2dH
        VGh3RU1rSDJTVndBb0pqWGlZdzBFRHZEYWZFdCtBd0x2ZjZRVlNzbmZ4V1VLdkgx
        Q0lka3d0NXJob3NUWFNVVTdTOG5QcnNWODBrdEFoenllSWJjdnFHQkY5SkpKWmhK
        VmkxdVpnVEZCMmFFNFlEaEx1ekpsMVJoYk1RaDdjK05vdmFOTmN2OWQ4K1lydzlt
        anVzNDFFeTA0bXVkaWFIT0tDTkJHcHIwNVk3WW5KVEZwTnhSVUVxRTZMT0I3TWUr
        eTRMNVUvNkh4UVJZbVFJaVY4MG5kckp4VjY1dnVIRFZFS3prOXBWYituVjBUbS9l
        Y2pQTjV2S0QraGtpOHQrRUxkYll2TmZBbVJOdFg1RzlvTVl4YmxKMFcxWnkxSCti
        TW41UWNqZnZDOERtd3NqRDNZcWQrczVjSFFya3BMMWgwVy9sUFZXVTFjY0FjallL
        TWVBU25UTFpGSWtuc2RvaDdVU1U1LzAwb2VWVXIxVjJJWWQ3S3JuK2s3TlhDOW1v
        bFhHMkcxSk8yMDJKUE9SSlBIVndFczJhZFdSRU5EcVV1bFJ4NUZkSzlRVG5pT003
        RXNxSnJUajFDVDA2b09WVUZYUlZSWFpub3BaZFBIbFEveXBoUENkM3Q4U2k1MW53
        NFJGM3dlYWZ4QzQyU3JFdGgzb3ZQQjdLYTlLOUJXeDFIenVTRnpIVWxwQnc5b1dr
        RDl1UkJUdXZKTnlBV2JhUUxwdWI3VmY4RmJxekJBYXNtem9ULzE1NHBDUkMzamZ2
        SGRQMWVhTTRtcnY5czZYWEdQTUV2SDBNYXN0TXVaMkRYME9YL3BSV1hORmVLQVJK
        MVFlVGNCT1JXTmFJOGZJVDZpaXNsYlZTMlpsVjVhWjFpdE9Gdm4vN01LSFhSNEY0
        TmR6dnRzL3JoUWpMM3JDV3djZ2VZemhPWDRXV09SdmRDSHIrbVRlMkYzVnNWZ3hv
        S01mTDZaTndjNENWNlpiN3pvYlN4dXFIczlKenRHN1FHaGVjWFdxaEUySkgxVWc1
        MHB3cFdvd2wxdHljKzg5dFNIcFVWVUV0WnZlMkwrMFJhOWFKQ05HUnFMWk1tQ0hS
        b0R5T0FjTCt0MFFEOHF0d28yOGNBRjhiaWtpWTBmL0s1bXkySlRqekNMQWw1YWYy
        Ny82UE9tZitVYXM1VG5RcXFNMkhoS1V4R29CWC9VNUVHNWxxNkFIbEF2RVh6VDBQ
        R3hPTUYvWW16Y0lxNGF4WjE0NHNtV3pCQTlpeGc5WFNia2wyYnI0dmloalYzYzNJ
        a3VJelBrbXhUR1REOS9HRmliRlBncTh1LzVnaGVGTGNvMjlRVWZlaE1MWS8rSHpO
        R0tmVVJhcW85ZGFoMzhCc3BIYzlFOUMxNVVtQ3hnYjUvMEVSSXRaOWkxYklxczN5
        RnNOSlZ0SWZmczdpdmZIcnNiT2ZnaFVqQndHVTcrMnBIOEFoeTNBSEorNVYxU2d6
        akI1ZGFNSjl4UG9rYTVhbjRvNjFGSDJwN2N2SUZFT0lxaDhiemVBRzRQYlp6eXoz
        YjYrL1kxRytib0pjbU5PNHhTVGZRTGo3eFZRemczYkZLVC9MUWJsVXBRUjdiQQpu
        ZlgyS0tMdW5wOWQ5OEFWN29lSXdYM0duTWhiSVcvVklTS3k2REtvK3VBCi0tLSBX
        aUU0Nkd5b3NtQWhQOWpTVENLcTJ3VG15SzF0L09IbWNsVEZRMHY5SUFFCm+VF7Ks
        fgToQhdgprzewhoi6EEZ2bGhWZKmNPq5O3qtsC7/l3ECLBMyTYS7hBBZ28Cr7igs
        ilG4WE7GGBiAm3g=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:ea6JWSWZvwWE1KHzKC100VlPLFXJ/ZaqQwOgNBtO0q29wo9nrZwke1wpZYtJ0WS88RyknTXqw8RvYVysQCQZ/4rp3JPUOhFGE+ZOIqrXP6eYeD5e+XcRGnQxMLgPRKUuP/8Kg/h8GFjwh0sLl8u7fX37165CCwB76NuLMsS2Q0A=,iv:FtCndzja4g0UJLTlZ5OapD+TvN7BefFcfHURUOwXE0g=,tag:ZEHGq97FSdHXc/+LHwI5hQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
