apiVersion: v1
kind: Secret
metadata:
  name: authelia-secret
type: Opaque
# Authelia env vars. See: https://www.authelia.com/configuration/methods/secrets/#environment-variables
stringData:
  AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:Yg0YR8O6EYra7NwwZtNS+9TU0JXWBU2ZJCRYT6trrc/BmRdPWG8b32Wuok2oG6n+U8o3EpQ7pVD0VscIs/ypWQ==,iv:8d7aORL5JKvcPXaAdRfEn+47JZO/VRira8EjlQWK4d8=,tag:JBY8bc9cZ8R1uI6PI6sxUw==,type:str]
  AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:m4Vjcbw3hiYyhet/nfh1Oy1H2xX/Bj1cuVq4mMND9PR5S0ZNkfoKAx+OfeXy9KTnbUuai0zjRHnp/u2Yb/uAeA==,iv:VoAtecG822ITU6Fx42p6o0nXrl0BkJ2Enw3OKJOY2pk=,tag:P4xSmDVE2tzj/7A5xdtMqg==,type:str]
  AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:DAXgFc3nTCtczHE1dkIOUF03Q6yQJuKsT4ArG+iiXRuW/LSrOtDnZ4a7WhkbUHI1mbxx55uRf7oaDQ3wqgLeWg==,iv:tQrDWzSRObhF8hGvWJRwVSeqMaScdo26q+X9aDXpXs0=,tag:BQculqIcNWmsI0Nxq8pZkg==,type:str]
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:TH8NyPvj4deikN4pgoeUGoLJpDs+tyyT02GPrZun3gy+JPUYlfDi/Jee,iv:od2SBn/NVt0vG2Z5QviBiVB1T1cTd0hvjfo8dxUvrxw=,tag:5wPOJa3lRT69nJ1xDYdAjQ==,type:str]
  AUTHELIA_NOTIFIER_SMTP_PASSWORD: ENC[AES256_GCM,data:81UE/92Y3dJ9hdb2RatZUw==,iv:nI+xsHMudv9r3seLRFutVug5wEd+9bZ2hqJHc1fBqTM=,tag:eXy88icpAtilkAtV51ZVew==,type:str]
  AUTHELIA_STORAGE_POSTGRES_DATABASE: ENC[AES256_GCM,data:xj8uYkRgNxc=,iv:Sx5CV36fFgFJdXYvE76TYfz2zShXTUS0JfmQXffmh1Q=,tag:aP9+7EkgTQYwC4ZA0vuxbw==,type:str]
  AUTHELIA_STORAGE_POSTGRES_ADDRESS: ENC[AES256_GCM,data:1uKCgHExvxgr3noNT7WcKd22NCy+V51M1wZwqtDchbw+SUs+t4fCAA==,iv:X6nOozqFmfkORm+COr8AO1vlMoMVFgpfzforbdln5vA=,tag:BqucIFlhSFFCy9Msb7J5Tg==,type:str]
  AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:QtAIaP3h65g=,iv:0vehZCZ02apotK3xT2a3WL7E4HI2aqCtvHgmKyLDF6w=,tag:m7Emm452XRun66mFVHoYEA==,type:str]
  AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:IdCG2E73kUYt0te+Rn8reF5B8IBK85SckHRUd2AzGIfwAPxlM7oWBPNQ,iv:vzT5+QBIsml+5g6SV4119G7PoMCpAAYpMI6aMHX4LSk=,tag:n+AaiZ7eyUpsEKnhrzpHCw==,type:str]
  #ENC[AES256_GCM,data:fBGKFDly7vEmoeWsAaE=,iv:aZutZJLkKeefb9TCkAXT1eGZqEwv+ZYhpXq/JBawTzk=,tag:EH1DXHr8Bj6Ve5ARFv7BAQ==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:4fAJ9QtN2Ec=,iv:WqvSmiBVzFiCQoYWxvv3nDy3SRE1viirZP05vCvsybc=,tag:sEvtbblBpvWSUUPEki/KXw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4bVPP/NiWaIt8Yi1Tol9a0jdFVqxHN2NmSd9QUOqy6llCSvf7uNceA==,iv:4jN2Fh7d4ldDaBAJaSUkuUfktaGEjJlbJc5ys05Apyg=,tag:/yKjh0PsjKJ7ZoEkL6wucg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Pxs/uou7mrY=,iv:whTjGW4fnVqR4akC3ZLBSWdEIeb556xEoxGEhAbF+KE=,tag:0PdoqdjGN7LKbVrog0hvQw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:SQxfKBqnvyQ75WZEdiu6gP0azuhND18LH1jy/f7hLB6Q0KOyWDVW1FwS,iv:eRUc2gnkiVn8xfiJFzsx6NCAyg3zHafBmkrKYXt7KmE=,tag:zV0Hurgfi4kwxyoi/U4l8Q==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:bEt8NkOaWQL1AHLk2JsxczNKvix/4bYsMwaqIc19cHE=,iv:DuKotGMFEsMdOO2SCwF6x1EilxHVlfgu93mfVut9+6g=,tag:bxTPjxBQEzHQ4E4u3ybHCg==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK1BVUnFrR3Nwb3BpeGNX
        MFV0T1RMa1JYL2laZW1lSEFYTkZ0c0F0YWhrCjNhZUNPeGs2Qy9lNUVMYng1RldJ
        Wm1iYUMvaFRIYkJUWG5YUENaT0V6NVkKLS0tIFB0KzFLV2R0WW9IaE5YZUVXUUFy
        L0hkSkMzZC9GNDkvb3l4aVEzNU45UWMKSoU9ikI+BfGZymjamHoKWGQfxOiQ8m6r
        tk0dnrnxA8I49aRhRyLH2wjlykuYiiddiwpPMbrWRKEwbaqHjFRW5w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE82K1pSbU16
        aXJvZ3VENEJ0dUg5Z3VRVGgvb2N3UnFGNzNkeUgyeUVhcDdNUEgwQk5ka0I5T0hn
        eEcwdXNLRXlsQ3BpMTJDVURwbnVqU1MydnNtTk40Z0FKSzIvdkhaU2NKcEJlR05i
        b1BtQ0JiZUQ4M0lha0RXOHQ0d0NickdsYndhOEhVSWQ2K0hYWmtudE9Jb3dVbXRY
        TFJRYlp0L2pFL0Q1U3NFemU5SExmV1pUY2VoczB0YkJMSDhickt4cExiNHJNaDVY
        dzJ3MFV0RUhDUGE1cE9oRXh6YWlYdytSdmkzRGJBcGVhdDVVOVZndWhxaElVUWJ3
        b1R0am9SV0JGem1PVzN4REtVS1JBY1phTUZKajFHSTh5QzVUcnVBdzliVzF1ci8z
        NkR6R1R6R0g2enBEQWlvdHgzV21HY0RQLzBQcFVSRlM2eitTT0lhRSt0dDNkRnB2
        NlBhZlJOVlhJMDB2NCtUbEoxR0tIUE5Jc0ovbjRGYVZsSjlTNDc0WS9vRGZYNmtW
        VmVMWTd5V2d5bUl6WWEyc3BUWXZmb2pNYVlkbUdIaW1Lb2ZURGNNSkZLbm9ia1J3
        d2YvSHJwb2gvRTI1MEV1aWhoVmxqbVFLSWRXcFFHNjdIWDdCblZHbGR1VkhwKzRo
        N1I3aE42ekJpVnA3Ym94OFQySVNzZjFCbWdOTm9NSytwYlJOeGRuKzhvaVB6S1BX
        M3VjZEhnMFo2U0VyN1lmQnNQVGo0M1NDK0w1amRWOWRBWmRGeHFEM0Jnd2RZWUJw
        cWc3bHJleUQ5ejk3bk1vMHNNSExpcXBUMGhiRUVmSWNyNkhpL3RsSU1IWmJLUDIy
        RkRDZE9nWExnSElINmNzWHA4OVM2QThhVTc4TFY3QjdocDkxRmovOWJTdU1ab3E1
        bms4YzJ3WFVTUGowU2FodXg2SFJDMGJlVkpocmprdGFIYUpIR0ZlZ3JwTiszL1pl
        WkhBbGRSTTBJZmZCVEc0N0xnTlpKUGpYV1U0WlBFVU5XQmIxOXMxaUFxZVBjM3Yx
        NEEvU1lQcXZHUHU0eGNhdndsWmY5aGZOdG1ONUcwWU54bTlYK0Zmc3JpdFdEQ2ly
        amhtZXE5bjN6bk8rYnlNSDZKMUlkSkNkYklmZk9BMWZIUzYwNUs1M2p1dThuNTMx
        d21SWlBDeGNFOTl4anJMc2tOYUZDcGpRQVBUc3Z2c2FTTjBvMHo5WmRpeEd3OEI3
        MjhDbEhNajhJa3hHVUZlUzJ5V1RDREJIOThNYjhkdFRNSG9VRmRyai9UaUdRa2tT
        Z2ZBc29kQTlZUFh0VDFxK2w0UklldXNBYnNYQ2RxSGxISE1UKzNLV09kRGN5MmpY
        RHRJUDJwUmcycWFWQitvYktFQ2tKRDFmSjQ1VW13cG03bUU0Y3JJdS9Id2NqSEZl
        ckFCeE5vR3RSZjlZWDcxL1hIVmVTT0xvcDhTUSt1V3doUyttb2U0K0VBSGpSUDQ1
        R1ZCTThlOGN6NWZmTHpIbkkxelh0anV2bEhsL0R0bzUrQnBtbGZROFN1K1ZKajNB
        SlhrNS9tdU8zWFNpUXRBWEc5QWN4enRtOTJoY3IrMndkZnNvcDRRVmY4R1RGWlhM
        M01SbGRuN2Z2WUlSN0E0Uk9peE0raGVGeHRMRXJLbis4RDJOZ0FVaDArbUU3ekZr
        a1U2b3NxN3lzMVVuaExZQmNUc2FSNG4zYXl0UmxGcVJwV3pqRVVjNUh1SzhFbWYw
        SU5ZQ29GNVFpR2V5UnpCV1ZISmVkK1oxZzBqTWNxU3E4bXdEbms3MVJiMVR6Umds
        WTF5U3N1dFp5cDBGMFAvZXRWZ3hFVWY3WGI4UnVZQ3IvTHlMTGlhKytIQ3RrOGJ5
        eWtsZWdaMjVZKzMzbVBGNnFmZlFGcGVmbm42SGZCREkwclYwT2tka2I3OUxUNVAz
        K1pSQUd1Z2gyNjhrZWFmVWJrc2lKclF5NFdxVElRcnRIcW8wU0tUZmkrME1WUQpG
        SnlrT0J0V0JLOVZzOHFwQVY5SnBTNFB5eEw3Z2FEYzlpdWI3OE9EZFo4Ci0tLSBQ
        Ty82ZnVva0pPdlBQV0d2bElVYUI2WWtIMUNRc2VLWEhMS0NodDJoa3lBCi37vkLc
        dCq66/7ctdS1IQVnEVhjZtG0U1z2veM+HFTtkmED41e3gjjrmiwTHU1GG1yJPhYH
        0jL6DZx+ihLjCSk=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-07T10:20:46Z"
  mac: ENC[AES256_GCM,data:c1KoL+8kZE6oKoSo4bUWlvfZe9Nx93fP5tQUKFr+gRGpVJoaotLwOtAr5CeBBejaZSvPpb41PN/XuGc43p1Wt9iMr1eOvQYx6/1XjcJIzItJvUx5iQMkAZzeEwBLph24M8TMc5DSmf4775MUHxj244LXyVnhkZaPZ+Gug2oH4PY=,iv:BsmHBOkdDxyQs/5bhL8jW2FWe1+Wg2ybcEl8cWCSfyg=,tag:6SzGPWhX/YIN/KxmB4I+zw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: anubis-key-authelia
data:
  ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:hwmB9Jp0h9wxdh3gpyxwoeFpbxKMEg6oUWbcPrY6wz3wIHx02K512kIrYKI8drHr3pmK6no3YuJDwL2qc+LY5NGbR89VI6hb5dnhjsy1crCagVl9R64hGA==,iv:OvOAMR0r3WYPHvh6ngLz4Y8v8kap1sVgON1zbRYiIlE=,tag:Dl05LAVerOcPAVu3xZsk4A==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK1BVUnFrR3Nwb3BpeGNX
        MFV0T1RMa1JYL2laZW1lSEFYTkZ0c0F0YWhrCjNhZUNPeGs2Qy9lNUVMYng1RldJ
        Wm1iYUMvaFRIYkJUWG5YUENaT0V6NVkKLS0tIFB0KzFLV2R0WW9IaE5YZUVXUUFy
        L0hkSkMzZC9GNDkvb3l4aVEzNU45UWMKSoU9ikI+BfGZymjamHoKWGQfxOiQ8m6r
        tk0dnrnxA8I49aRhRyLH2wjlykuYiiddiwpPMbrWRKEwbaqHjFRW5w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE82K1pSbU16
        aXJvZ3VENEJ0dUg5Z3VRVGgvb2N3UnFGNzNkeUgyeUVhcDdNUEgwQk5ka0I5T0hn
        eEcwdXNLRXlsQ3BpMTJDVURwbnVqU1MydnNtTk40Z0FKSzIvdkhaU2NKcEJlR05i
        b1BtQ0JiZUQ4M0lha0RXOHQ0d0NickdsYndhOEhVSWQ2K0hYWmtudE9Jb3dVbXRY
        TFJRYlp0L2pFL0Q1U3NFemU5SExmV1pUY2VoczB0YkJMSDhickt4cExiNHJNaDVY
        dzJ3MFV0RUhDUGE1cE9oRXh6YWlYdytSdmkzRGJBcGVhdDVVOVZndWhxaElVUWJ3
        b1R0am9SV0JGem1PVzN4REtVS1JBY1phTUZKajFHSTh5QzVUcnVBdzliVzF1ci8z
        NkR6R1R6R0g2enBEQWlvdHgzV21HY0RQLzBQcFVSRlM2eitTT0lhRSt0dDNkRnB2
        NlBhZlJOVlhJMDB2NCtUbEoxR0tIUE5Jc0ovbjRGYVZsSjlTNDc0WS9vRGZYNmtW
        VmVMWTd5V2d5bUl6WWEyc3BUWXZmb2pNYVlkbUdIaW1Lb2ZURGNNSkZLbm9ia1J3
        d2YvSHJwb2gvRTI1MEV1aWhoVmxqbVFLSWRXcFFHNjdIWDdCblZHbGR1VkhwKzRo
        N1I3aE42ekJpVnA3Ym94OFQySVNzZjFCbWdOTm9NSytwYlJOeGRuKzhvaVB6S1BX
        M3VjZEhnMFo2U0VyN1lmQnNQVGo0M1NDK0w1amRWOWRBWmRGeHFEM0Jnd2RZWUJw
        cWc3bHJleUQ5ejk3bk1vMHNNSExpcXBUMGhiRUVmSWNyNkhpL3RsSU1IWmJLUDIy
        RkRDZE9nWExnSElINmNzWHA4OVM2QThhVTc4TFY3QjdocDkxRmovOWJTdU1ab3E1
        bms4YzJ3WFVTUGowU2FodXg2SFJDMGJlVkpocmprdGFIYUpIR0ZlZ3JwTiszL1pl
        WkhBbGRSTTBJZmZCVEc0N0xnTlpKUGpYV1U0WlBFVU5XQmIxOXMxaUFxZVBjM3Yx
        NEEvU1lQcXZHUHU0eGNhdndsWmY5aGZOdG1ONUcwWU54bTlYK0Zmc3JpdFdEQ2ly
        amhtZXE5bjN6bk8rYnlNSDZKMUlkSkNkYklmZk9BMWZIUzYwNUs1M2p1dThuNTMx
        d21SWlBDeGNFOTl4anJMc2tOYUZDcGpRQVBUc3Z2c2FTTjBvMHo5WmRpeEd3OEI3
        MjhDbEhNajhJa3hHVUZlUzJ5V1RDREJIOThNYjhkdFRNSG9VRmRyai9UaUdRa2tT
        Z2ZBc29kQTlZUFh0VDFxK2w0UklldXNBYnNYQ2RxSGxISE1UKzNLV09kRGN5MmpY
        RHRJUDJwUmcycWFWQitvYktFQ2tKRDFmSjQ1VW13cG03bUU0Y3JJdS9Id2NqSEZl
        ckFCeE5vR3RSZjlZWDcxL1hIVmVTT0xvcDhTUSt1V3doUyttb2U0K0VBSGpSUDQ1
        R1ZCTThlOGN6NWZmTHpIbkkxelh0anV2bEhsL0R0bzUrQnBtbGZROFN1K1ZKajNB
        SlhrNS9tdU8zWFNpUXRBWEc5QWN4enRtOTJoY3IrMndkZnNvcDRRVmY4R1RGWlhM
        M01SbGRuN2Z2WUlSN0E0Uk9peE0raGVGeHRMRXJLbis4RDJOZ0FVaDArbUU3ekZr
        a1U2b3NxN3lzMVVuaExZQmNUc2FSNG4zYXl0UmxGcVJwV3pqRVVjNUh1SzhFbWYw
        SU5ZQ29GNVFpR2V5UnpCV1ZISmVkK1oxZzBqTWNxU3E4bXdEbms3MVJiMVR6Umds
        WTF5U3N1dFp5cDBGMFAvZXRWZ3hFVWY3WGI4UnVZQ3IvTHlMTGlhKytIQ3RrOGJ5
        eWtsZWdaMjVZKzMzbVBGNnFmZlFGcGVmbm42SGZCREkwclYwT2tka2I3OUxUNVAz
        K1pSQUd1Z2gyNjhrZWFmVWJrc2lKclF5NFdxVElRcnRIcW8wU0tUZmkrME1WUQpG
        SnlrT0J0V0JLOVZzOHFwQVY5SnBTNFB5eEw3Z2FEYzlpdWI3OE9EZFo4Ci0tLSBQ
        Ty82ZnVva0pPdlBQV0d2bElVYUI2WWtIMUNRc2VLWEhMS0NodDJoa3lBCi37vkLc
        dCq66/7ctdS1IQVnEVhjZtG0U1z2veM+HFTtkmED41e3gjjrmiwTHU1GG1yJPhYH
        0jL6DZx+ihLjCSk=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-07T10:20:46Z"
  mac: ENC[AES256_GCM,data:c1KoL+8kZE6oKoSo4bUWlvfZe9Nx93fP5tQUKFr+gRGpVJoaotLwOtAr5CeBBejaZSvPpb41PN/XuGc43p1Wt9iMr1eOvQYx6/1XjcJIzItJvUx5iQMkAZzeEwBLph24M8TMc5DSmf4775MUHxj244LXyVnhkZaPZ+Gug2oH4PY=,iv:BsmHBOkdDxyQs/5bhL8jW2FWe1+Wg2ybcEl8cWCSfyg=,tag:6SzGPWhX/YIN/KxmB4I+zw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
