# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:Hd9fZBLIzWtLBbxrQEfiytHKzJLdf69CBWybtuyRiBw=,iv:IX+ocSwmNGKQQRCUH0lyI+LzepsGFm79vQyklClUGHk=,tag:z9TDSFkIyk1TW42P2Sj7Jw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFNZOEVHbStt
        ZlVkTjNIa1JDSkROMmp3QmhsdXdleCs5ZDZlRkpHZFdJYnIrZE9LN0NUL2xsclli
        R2RETklBTlowU0FuQXhqYVVmaFhTa1pBUlhHemNNbEZHZnQ2R2lXVXV3TVJIb0JR
        M280S21PN2xMbGhpVmpKV1QwL0tZMm5PRGcrWGpNMndCcGVEQVpsRnNuWFhOL0Yr
        clRlVEFQUzdROHhFM2J3M1JEWEFCVzQ3RjZIUFFNa1JVYnY5SU9XOFZHY2dhNnhQ
        YU5ySUdKbEJlZ3VtbTZmQWNJM0wvQmNnVXNBU3p4U1FiTGx6TER2UmhSVWNUaVRm
        UHl6aTNqSElxSFFLRnkrNzBYUjhiRmpjQkZSUDA2RVpRb3l1b2Y4MkNmV1lWc3FR
        UkpQR2MzSTZuajI4TDhBRldtaENEYVA4M0tiUWVGWnVPY3MycFFaMFkrSzJKcG5I
        VmkzZ3JWQ2ljOEJPNDE4eFVZRnZhcUp5VWJSakQ2Zjg0NmZlVEJvVm5zdnNUL0pu
        QklxUVhJSHNRNytiRU9VYWNwc3VmVlR1MllVemhKSFRnQmRsQ2dxaDcxeDg3NVBo
        bHBGUGpqSXNqcnEzc1grcDRiblp5SjNkSUhzNlQ4cjZHRjRUWnVORHpucXZGWlNz
        TldPVlMwY2YzNjVqdDlyb05kQW9pK1dnL1BpNnEzUkhiS2ZpV1ltcElXS1N6ekVq
        U0VGS0hORCtWRm5mUGxSSXB1WFlaOUtvcW5YM212UlNWZjQyNXhkcWsxRkFFbGlq
        Ums5c0xqM1RhMzNGVkhuUmM0Y2w5Vng3WFZzdTJUc1pzWnRiQmJRUk1JS3RsMUJ2
        cW9ZcjM1d00yM2EwTHprSlNaN3lEMmdnN2pxdUo1SFJmN3VFLzFFTmZXOENxSE45
        Vjc1a3pubUd3WWRYd1VteEJwUDgyZmlEWjVnWXZTRURTYUxYczIvQm9NR3g2ODgw
        bTlXY085aUxqbDhxWTZKWXRLaklyb1BKdXExM0xlRys1YnAxeXBNMDM0RDBvUUdV
        d09hQVQvM0pFcUFjZ3ZrdXdpemJyNGJEeEo2c003YWxjQTM4TjFQcmlhU3RhRG94
        UTNZcjBxbFdQaVBTdE5rVWc3ZmZwNnd5blhkUC9mTWhRa3FCU1lreEsvemlsRjZo
        Y0tPdmlQWm0xUnVxK0swaUJwV09GUGVPTjE5R1hvMURySVpOV21ZK1NkWUFqakJ6
        UmFHbDFYZTZTR2xhUW52VHF4bmdNdW1DVzNGYXlvN2tqNHhuNWJZU05aMjlqUkZF
        YWpoS0xrNWcrR0prWTBrcURQYUVDbEh6RjR1VG04U3JmblhFVm9GNDFTRDl3aFhS
        U0MwQ0N5K2RiS1kyQW1JRDJuTDBHQTJZM3VPVUs5OFBRVXRtTjAwT0VNenh2L253
        YStEcWhHNTNIclpFL2lPdElwK1V3dVo3Y1dnL2Z0TjkvSWgxMGRyTjVnbHBWQUhL
        b1F0ckk1bURXMnA5MldoN0FVdG56djRKZkcvQzl1bnZiSEgyUzVRNW54TnFnTWtk
        OEppMDZXQzIySzhmYm5XMUNLNzNBdEhzaDBpVTB4emFFN3FraGZQam8rbEROM2VZ
        TU4wRkxLclN4L1BhQlNGOXpETTE1QVZmRnZWYWhJUFFiaDRvNXFNU1BSb2VhcUhq
        THBvNGZOZk9HMk1lWUZJNzg3Vlp3UlY2ejdXVmxkN2dIcnNSeFpJWFZPdVhPSDNM
        Wjg2ZFJEakNROGpmZDlucmtSUWFXcGZBRFNMUEFYSU5EcVFXYjF6K1I5REY2UUZi
        a29wT3lSaXlXbGt5Qy9LcUpIK2lsNzA0c1hLbHRuRk4xRlRMWkZtVWgvbElvZDFZ
        SGZKcUJjQjN0SnlSQWk5S0VXVS9HcCtVZlpZMjFxc3pVeFluN0pFQ0xFMTJSODB3
        V3NKS0t6ZmpqUlYvekI3S0hOL1BxRktRUDJoZ0RVcGp3dWVYUFpGWmtHKzJIUQpP
        ODFiOWNDZXgyZUFqeExjVzVMK0RoMENQL2IwUEZDV3FiZjlMM1FyT1g4Ci0tLSBB
        TC9yd3A4b0JpZ3BiRzN5dkc4S3drbUc2am5SM0ZzK0NFUjVXUTJ4NmxFCoKkPvDz
        AAO5Um92AAfnoHbRDJEzs6jY9Jzb6YuXlS+o+VmCvI/BMcy25CPc0kCR0yTDyK5Y
        0/EWcnjCjofPux0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:aADTUzDjWclDzeiEX6YztJd/NRpb9D6qFPqcpUUkWF431ZvkeMfOvXI3LXANz89KrFbOgIO2MdfkXoswTIuh0da1KREfBh5MzjxfQL1Ibgn1p4OXORobkNiW6wSWiwFU8lofDTzxfqGMjLToCkwf+uUgDSBlapYfwWtmbzigm/s=,iv:V2gQX+8LZRl/4ezvaN7kEURdrcYLGtpaM2dwNLCRQM0=,tag:DXoam8GfxvoKGcXiNJo/Iw==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
