# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:4DdnZg8ernrs/q8P//8Rja+uCQwewuRUaP2Hdygd1HM=,iv:IX+ocSwmNGKQQRCUH0lyI+LzepsGFm79vQyklClUGHk=,tag:18USV/0iSXjwXXBn2f4uQg==,type:str]
sops:
  age:
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG5iZVZkMkZs
        UHRTSHVNUUc1N1hvd0VVU1NYVEY0QmNXRmttZVRaQTh6Z1hhNVZOVUt2TGY4ZFcx
        dytTeklWTDl4bzBtb3dDTFZ2VytCWUhHTnExM080K0xySmhHRmJ6eG5jdEFxcmRs
        ZmxvckxZTjJEYndQOGxSYlgxdmZkb05UeWg1b3RjaWdDQTBTTkErYWtQaDNyWXk1
        K08wV1d4ck1pbC9JOTlabzBXSFBzNVM1Y0w0dHJiNDRhSzI4L05vdUd6eldjb1VK
        WjJIcUJ3K0E0bGhIaEpzaEZFaEV2cDRPLzdGdklmZEdDU2Z2MTBuRWwvZjdiZlY1
        QUZuTCtEMG5xdkg4TFBkYWZXMEZXSG1INGJWTFBpTFNiR0syQVVCazBIMG5kQjU1
        Q2xUQ3RYeFFkam1nVjRJTFQ0UG1KWFJqbEYzaXRQMmdCWXVrdjdYTkhVaGVrQUhn
        NTRqNHZTd0tCYk4zS0k2MXJrWW5BeFRUWEczRjRvWkpKaWkycWY0YllmVDg2VUNS
        dVIyWi84NzBWZWxhUXkrcC9GVkw4Y00rSnR1c2VDK2toZmVVNUs5ZHRlazFnK0dB
        UlYyVnpLa0pYTWFKK05McDJZZmRTSldHUmtsRWVpeVJjRkdyamlEaEEydi9yVWNH
        Ykt5YlN1NnVPcTNydklkUnZORjZOUE5NYi84by9CQVVyWUE1dmIrN21odzFNRGxh
        ekVFc1M1UXdZNmcxV1ZZaUVKSjNVWXRNT2paWWlwQ2p4RExWcTdsN3dlYVNvQXlq
        dVpzL3ZOMFhDZ3l4WWRRN2N6MDlIdlhaUHp4YXc1b3hmUHMxaDdGTFBKV1ZLMHJE
        MGVPeWw4cWRSdEJHNzc0MGs0ZWJZS1c5emQ3NnNnMUVFYzBlcVRSNXdSbmJWREcr
        QlNZWG1YdDRKdmZwVVZ4WlJ0WXlmcW0rOExaMVVVUWdJVk5HVVlOaktiMXlzT3Fm
        T09EQWFwbUU1SVJ6alZhSXg5YmlZSlVFdjExaFFlc2JJYVBZdGNZc09wNVZFeEhB
        K3Z0azd4OUxRMkhIdnQvS3l3ZTlQckhKUlNsZEhId3poZFMxNEc0SzVUQVJabEFT
        YWpFMm5lVjRWNU0wTW9SZ21maFFrMG1ZZ0U2dm55Q3RVeTF5ZHhOWmlZbDl0L0tr
        aGZONHk5NWJlRVVHQlVLTUpnVjNna0hXN0oyTXdncUxtU0Myb3BqTWN2c2pqbjVY
        RmVVckFFSVgvWFlNdzd1QzFTSUFJWlhTa0U3ZVFjQ3FXbDVHMnpmN0VON25XaS9O
        N0Q0aWp2amJ2a0wrS2lFTDErak4xeVlhS091U0pab3c1T3VDTXl5V1FaeDBaUDIz
        dWsrS1lHMU9JYjRTWllSS0tPelZMNDhYZnlBT0hzT0ZaUU1vVzRweDJCbDRjdXhz
        b0FySjdhL0xCdE84eXRCQ0hsR1RBb1YzOHBmaXNHeTcwb1VYNitKQmVCWU9hdUQ2
        MlYvd041WGlnbU9Ya2N4Y0JsRUNaM28yNkR4QjV3NEROcU5wT2VhTDhScWw3S0pR
        UThSMzRSZENSOEtkd2pVcmZuckpvcmRBeTc5UXJmSXh5SmJac0t1S1pnb2RYN3Rj
        azduWmVETzNwUHdRVXc3aFRyQWZWMFVqaU5VNEhjU2JHSDFMd2xPNGFZdW5ZZnJ0
        b2t6VGRYdlJXZEovZzJWQU5zK3NDMUVmZzdJKzhTMFA5SkpHREFRbGgxVHZLZldQ
        dkJRL1EvaHVLMVdIaDBMcXF6OXdld05qNEtrSFVyVXZieERHdjJMOTgwNEFXK3Zk
        NmFLUFlOT2dEMVdYajI2ajVqNGdaUE9ORHE5UlM0VW5kQXNFQWI4WnJXZVlhMTZP
        OXk2S3RuNUxBRlhLeUkzT1JEenU0UWJyVVZ6eFVXQy9GcFhaOUR6dWlsVmpoMmVa
        UWV6cHNkU0xtWHNKb3Q4VTk4Z2IxZ3prLzlycTd1Y05lSDdIcGFwY3djWHpWUQpW
        NGJkdXNkRTlKZnNkOXlUY3l5TGpjZGV0QVNXVHdIYjJOdTZKM3hrRWVVCi0tLSBE
        OFA0anlUcXZzb0Z5YTJnb1VIOHVXNi85UnNoWWt0VE1GMTJNVXBQOUVnCpcNRF1Z
        AHmTf7uZcfBJDH3KPd8+B44nhs/MuJRBK4HUpb1NYN9zsGXuPYWH69o41ydTq4Kb
        fNaupVL3LnqhToY=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-25T16:27:30Z"
  mac: ENC[AES256_GCM,data:3TvtgEHUuyxJ2Ksqho2tmb7By1i7WWCalqsazm1aVU68bzjzPR60TqDacow3ynGz0J1wzwzh/ndQtQEkj4SoJ6nduuAiVtlRfYl3G+Y3JUgd5BMEqPsk1Xd4bQuqYhg22+3lxA6WMlzpWIHFyql5RgOFH0NJAF513dz9eTrdAtA=,iv:ZuA71ENpPINn6M+yc5tU0wLv2xOLpjcTwqVn3eo7fYE=,tag:DQJfWbAs7IvaCxLmtnj0QA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
