---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8s-gateway-kubes
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.7.3
    digest: sha256:0e8ab809f4a3d4cd2c009497324c175cfe7bbff31a7f875c5af99c99d893a7ff
  url: oci://codeberg.org/k8s-gateway/charts/k8s-gateway
