# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:lVGfitM0gXw=,iv:ddjdKbFA9rPIvT7BeiCeapCg4caPSk8P32TzIR49ewU=,tag:38K0iiLSfK3cx0jtNwkjfg==,type:str]
  DOMAIN_NAME_COUNTRY: ENC[AES256_GCM,data:eJEuLHkPvZgQM/isIT8rSg==,iv:Pa06+wxXr7c91Wu0jDqqANsRATBNNg/LjaGRBgZy7k0=,tag:QmYFXv79stO8DR3AIldNHw==,type:str]
  DOMAIN_GARBLE_DEV: ENC[AES256_GCM,data:K3tdsRxGcsK1,iv:E7RMm4YD8GCMaslRLDliwEL1y8A6uND/ux2pa2wa7f4=,tag:2P6uSFXkza43+vlk79CeLw==,type:str]
  ENVOY_EXTERNAL_LB_IP: ENC[AES256_GCM,data:KtuDP+TlD3rz6bJx,iv:EEKTyelG3Mvn8zTxza43XKqwuAI4RIjWTySwpxr4MUc=,tag:dHi4FBREBSSgAW7mRdh3Pw==,type:str]
  ENVOY_EXTERNAL_LB_IP_2: ENC[AES256_GCM,data:emaJZfyqmrX+RGDO,iv:OJFNIs68iHnhRxjOxw2MZINXH0M2Upim3iNUF2ZYiR8=,tag:963zQR3K5enwbSG3RMRAtg==,type:str]
  ENVOY_INTERNAL_LB_IP: ENC[AES256_GCM,data:jGgJZDkuXmhS1SXv,iv:f3UahJvf5VsDCH8EwfUoknJpA2OTh9Kkhe7oXjAW0gA=,tag:xKBo3KD61VVRzQnZRMnDtA==,type:str]
  NFS_SERVER_IP_ADDRESS: ENC[AES256_GCM,data:IiLNaDxtoKh//GPq,iv:UMYYZh8qNABW4+f2ykFGlpYgv1ZJUF5Hu0OAXUpjek4=,tag:6wSN17I5Qd81QC1wROaXVA==,type:str]
  MUSIC_ASSISTANT_SERVER_IP_ADDRESS: ENC[AES256_GCM,data:IDULW5T13wDmTR45,iv:fi+OuacNMtxIkdVlvyhDxRNOFv9VK7IRALDCcMJVfR8=,tag:cNFU/FoNhLxr7DbeLnZ93A==,type:str]
  HOME_ASSISTANT_SERVER_IP_ADDRESS: ENC[AES256_GCM,data:qXy5KubHJYRZHfDp,iv:Ci4I8yUupKRMfqGvm6zZBxXepv3Dh4i7KPkuWIDa0Ck=,tag:1HpDO6YBRjmnu9rkfZ55yQ==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:q5v11AwyAJW+t4dNCYAabA==,iv:jO7GU6nJbnL6/wPFN8pf5mFP2A+yacQkKoueoZxt7zY=,tag:wK2diLSOkc50frZjyPmXrw==,type:str]
  BREVO_SMTP_USERNAME: ENC[AES256_GCM,data:PzQSIIHFi86q,iv:Nw1WtLTOkKlaB2MnhDyy/py+2vBWMxJ2S+Z72cJItlw=,tag:Yi1u0g43qFimSZ4GsjVmpQ==,type:str]
  SECRET_HOMELAN_IPV4: ENC[AES256_GCM,data:V1qat956Bg0ThU6+gKKpj1M=,iv:4rg5JEa+2DO0ajo8NiVySq/fd3bi7OZMufvPSm9VmFE=,tag:dLJfiC7qABJ0ywdCZDPxPA==,type:str]
  SECRET_VICTOR_HOME_IP: ENC[AES256_GCM,data:kGZzlwkeg4zawCG2MxzzpRA=,iv:cM1MAZ1a+jiKcynLgFcuHPeJ3Ld0Wph8vI1gzlppTHs=,tag:2PRYrHwyf+Iomw8qKRPOLQ==,type:str]
  SECRET_STIJN_HOME_IPV4: ENC[AES256_GCM,data:QN4a+tQLkaZxlxIhTRHLtg==,iv:N898evH2Biookux9nJPMsVjckTfC5Z4o4SxdVsz7X+A=,tag:oS9EKG+eKCuDx+wy67Mk2w==,type:str]
  SECRET_STIJN_HOME_IPV6: ENC[AES256_GCM,data:0BIEpyBz3C73f9B+RTLvQiCha3dGAJGJQrrjwdquhxtfVt5e,iv:/wyvxkm0eawf7DbAbbAwrfOQuduqUxLFaxRQhB7a5fw=,tag:QBQsyF81R+ZYU31qT4C1zg==,type:str]
  SECRET_J_HOME_IP: ENC[AES256_GCM,data:C1np16JShPeN7SsFM9yUWZ4=,iv:7WdA2BSOQe1ESCMvVYcKFEwzZnH0MTD+6vYYpN89oPI=,tag:J/xmzYGFNcZ9Vtq22h4OZQ==,type:str]
  #ENC[AES256_GCM,data:wr8qqM0olBNVu98j7B9XX4lvSWAuRK1W5anP5Pwvxp0gATSpjTBoCVm6KiWvMvIbP/7bVxdcYHqx6zZO,iv:LB2uvYMLGBjCZMtGcQM9o+D1Z0r2XctQQ0eWbCrifjE=,tag:iy7pZQrz/k4HlzcwC5DxWg==,type:comment]
  STUNNER_SHARED_SECRET: ENC[AES256_GCM,data:nrtlhbZa4OeY4+ArLU4cgeVB8n+Sd69WxOMPOZtq5IPUYU6yHU/3RVAisKu8dJfUD4A426c82H3Nit8EjyjgJSBSbMaEFVuvmWiQvW0MT/AkJufJxUtbILS9p0zxlPvOl996OBVfapCIQ8WCP/aniC3xNVZ1IwE5PdVADh5P6M8=,iv:daQiSUZ0MrrllXqcXJTxrCCa1DNdx0KEXt0LQHYoRAE=,tag:9cFAN98kjSirSNfFif5QSA==,type:str]
  LIVEKIT_API_KEY: ENC[AES256_GCM,data:z/BfDZYP/Ac7D3HZ9gtMvXeR78SuagDcj86YY8o8/cLmBPNMnsuTPSo6hnTuc2m99DaCj0EPXsCgBayfLs4eE4B5ihS5saUGI1Y/duqikRzii6TNFJFUBE73L+Ht8YcOV5oI7uf+zSTBWA2xYcWS15sTKio3B9+iczkzSuzprF0=,iv:Ti4PRrkd5IS+LqhxP8cYTDGA8Y0P4yDAfqC6GrLHSCk=,tag:JyCvBdu9JhYtzeGeQzMtNQ==,type:str]
  LIVEKIT_API_SECRET: ENC[AES256_GCM,data:IRbhutTI6eNTbbSq0FCyXk+P7PPA3u+ygxT/etlBmXhSr7gdJe9UDFEV8GEd6s6ax/B6EJZOLNdQzN64a+mWRYnoN7nmRyD29lxYENl4D9+6OOl/5ZMplz8cI8rrFTlQjMpfeUwaxPBAb0yeJ8Xw/OU8AY9ajwcW4oIlv1wCVow=,iv:kkbbE4LyyGLRSUqPc/A067OmYlBXTLp63EnWcW74FA4=,tag:/SED1nHtNdNaW3f/mbmASQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDRqV2kyZCt2
        V3VMUFFmM1l0M2N5Tk90WUF1Nzl6SWxHKzZYb212azdBWmhVMng2NitLbzd1eHJE
        ZC9kTXpOcjBNWVlVVEphb2NEdVFNNW9mMVBWcTZjOHBZUmZidVFCdXhUbDdQaitJ
        SW84OWdyd3lBcklVdWlUZ1cxRHhyU3U1Y2FuTUc3Mk1pNEZQTlEreXpjVE9jQ0t3
        SitrNFBiSGJxUk9ZVXVxbzJhbC9sdHhSb3gzRWdNMGZIelpqbjJqL0VwZGVmaFd3
        K0lFNCt1cVU2QjF5NTVUWGdPRE5xSnJmRUxsQjgwZThSRldsNXZBTG9EMGRNYkZi
        aEl2OGVRMUYxdnJuSEx1aDhtSG9tN0xrMG1PclBraVBzWXQ3UkpxMmdxTGZ0blRh
        UzhCWU5sTlBFYVVqM2RHamZSWkhJU3hNdnpjWm0rZjlMUnRPaTJIdkh2Q25Ob2l5
        b0IwUS9LVjA5d1dRQ1RVZUM5OWM4SmNVUzdpbzlnK3FEK00wTjN0dGdoZ25kYnR3
        VTZhYmlBaEVsQ3dybFRMQ3pBU21hRzBpWS91WFE5NSs3eVEyQUliRjFSakdaTDgz
        ZGc4NXF5UWRjRGpUbENicEtBQzJLRnVqbGUwelB2UTR6MlZsdXBtNHFRc0phRkJY
        STVDbEdqeHVIcWd4QzRnaU5YSkhlMldKSFg2bVd5T1VER2JSc0pabXcwQXJONTVM
        OUxIZk9LcUREY0w0NFF2VGovK1k3S0hSZFltYlAwS1krMnpmOStFZTNFemVWMGh5
        T2pLY0lxMDR1K1p2b2VxUVd6KzZGbnExOWpHM0dkL0pOcERXdjNwbm5KR0JDZFI0
        UHh2akQzNU9JUnN3TWl2bFgwODVpVTBaOE9oRHFkQTdSdEprKzE1WmVhVFNMSWJy
        SDV3OE42K2lDcmM5RmJYSVBjZVhtOXp6VWVkeGViUU9jdkZVdUFheDdScGZrQWpF
        NXJmY2VtbXhzUDJMZlR4YUt5YVlyTGVBbFpDcVNzSUdLaitGYjhVS0JmOERjSzVx
        Uk9RKzQzUE1ZaUgvc21jYnIvT3NicGRXd2ZURDQ1bjVveHB0NzJrdDZERjdDbndQ
        cDE2V29TOHlRNkJGZUNIQVlQdnlSVXR5ZFNpc3V1TFVUY3hlQ1JkZVdKVFVkQzFE
        N2QvYzREK29pbGpVaHNJRWk0VllxWjR1Tjl1dTJwY09HUng1ZXRVTDhITU5wYlhp
        U2FDNmoxOFNjcDFzc3JjbENEYmgvOUd5ekhBQndJK3Z3RFFRbHpJVmtFbGdObUVI
        WXNLSkFiL3pmTWlCbGgyZDN4RkJJclhOeGJMMGpnN213K0lYOFIyL1ZmeDJRUVhP
        U3VieWxWZnhBWU9GNFJMWGlPWmFsRXNGRWpCTDA2cytEOEJFSllYSmdlSFZmeFVZ
        a1hMUm9QZjcwTVM2eWZUUXMyci9WVmpjbno3TitSK0NSVFN5eWFSSDE4WTJCTk1Z
        SlVlV2hvaEpQMWExOU05RDN3eUN6Z0VvL3BEbXprVEg4YVJlWktlczVjRHMzTG81
        VXQyUUNoRmNUOS81dWc1UDFvOEEvSEJXUzZTMXk0d25jRGdVWlVnUktDWDVtQUJw
        U0Y4TGhncDJKbG1rN0F5UC83eUJ1bDljTFphclBvUUZoY3Q1S2EreXk2SFpNQ29v
        NGZzS29wK3FOV21ubVZVc21XempWRE9JRS9rWjVoWm83dksyTTdIZWxxTlpRbU5q
        TCt4c2ROVXFGc1JZNlUwNU1UQkRnb0p3ZDFFOVQzNVp3RnRoN0JZK2tFQnVFNzJJ
        ekhCYUN0ZXdDKytwYUEyT0tGVjBGOE9vYUl5Y3NkTEREbk5DZU5oU3VnWWhuU05x
        Nlp2OEJSRGFzRGpVYTBvd0krSGs4Ry9GWnIwSS9xdzBreGJSeVcxNC9VVFJvRzd4
        MTloYWwvMzJMNytJYXg0akI4WFRDMmZNNHRpclB5Mmpxcklla2ZVMW5rb2NWUQoz
        WHRjdEwwbDl3MUwxcHJHUVhiMWRsajJSTE1sVlQrWVRIbWUrSlNJUlZ3Ci0tLSBt
        dlMvOGwzUWo5Q2l6c3hjSSswaW5XSk9JZjRDUVJpSFh2cGNseTNKRjZRCqq6vyf/
        GozhJXaIl2R/3g5Rr7TVTUVtuLnG9PABL1pFthXwiJ2jxN6Kkxdg+6/2Sdy2u6nG
        Y4QwRt1lvG2QmKs=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:35Z"
  mac: ENC[AES256_GCM,data:Vc8+pr8Ywv12R7KXVYGYp2WsooXE3MxcIgjuI5hcYyF+4CTFf+Stxu01/8kX2Bqia8bW9AwvyvbHyB/nNQyucmGbYPXounD1AhB9vG7ycW+tSnQSdNf4Ark1TzMJmxoCXtvM9GFypcagjG5hGUGTVabP0qak5aIyYaF4zNljULg=,iv:0/QvFrXrL5h9TPW1Fl/oT6T17eWvnaTyINiAv0F8afY=,tag:KATEE90M1C2jMiZQ+8GXqQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
