---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.0/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-double
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
reclaimPolicy: Delete
provisioner: driver.longhorn.io
parameters:
  dataLocality: best-effort
  numberOfReplicas: "2"
  replicaAutoBalance: least-effort
  staleReplicaTimeout: "30"
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.0/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-snapshot
reclaimPolicy: Delete
provisioner: driver.longhorn.io
parameters:
  # used for volsync to copy from.
  dataLocality: disabled
  numberOfReplicas: "1"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.0/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-cache
reclaimPolicy: Delete
provisioner: driver.longhorn.io
parameters:
  dataLocality: disabled
  numberOfReplicas: "1"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
allowVolumeExpansion: true
volumeBindingMode: Immediate
