# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:z7M4FzFyAxDnIFKXY8Zk+DBhfLgnVw+mV9ZROZ+XQf8wiIyEYmj30Q==,iv:th7KKpZM9w/Py8mrjsF68ff6Q1gRi6C6ya/bs7jbqpc=,tag:9FSjK1ZTzRqQWM6kazzAAQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VlhraG9UOVUybndnUEpj
        dGsweWsvZ3IxTFQxd0xXSmlZYnhLOExaNmljCnRTMHJtSzJ0cGFuYkQrb2pDYWRw
        RVIvUHdLRnF1WFp0dUFUbkxJaW95N1UKLS0tIE8rdTRHMG5pYWJzSzNSeElFamNj
        dVQ0UlduaitXeEE0bklUNmtaUFYvVUUKa7A4lo6rrCZ4IIh5hi7DPQzM4E1n3tTu
        IeLPxFDTbUvDJE/ushhHcDLGFaLDaju5Vubrl8WvPIuR8tFPYvqwJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T13:53:50Z"
  mac: ENC[AES256_GCM,data:coEqX0v2n45w4B0agbPPmitG64E5x72jso1sFkdgl9cGP03HY9Ls3pzGAF2dB2zc7wcAbdr5jx8UsqrpCOm9S7kqKP5BDPWjTiRooXi0GjaIJ52M1RxROIN7tJMa9zNdoxTZzDd+3ZAJotylEL4fUiBCDyvNThoDTDzlSOVGcSE=,iv:BVvonbRg2Wspa+2L0UWOn00bQKdYF+AG5YvJpEbwS8M=,tag:hTbOSSkxcQk9fSe93mBuCg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
