# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:qlgKa2zCsDGl5hWlz61Ii+bsl+lhPEYUT1w+IKbvINcW4URS6+cxwg==,iv:y8Fdmot0343uVu+vGMVP4BurNgMee3gDpLDc70VnYG0=,tag:vJTRqpb79ZQ4PFzuZ1H2Ow==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbDdTd3FXNU14R0ZtN1l4
        ODBHWjZub2M0RURrTGxxYUM5RWd1NWxzVTI0CnJhNmpBZmhZekdsM2VBb2U1eDZU
        SHpXU0owcWhKUDhtQUZjMW4xN2FxWmMKLS0tIDFNLzRsZmsvOVpObDZUVHZ1ZFhi
        L2dCTE9HcG5WUzVRN3pzSmpKRk5yN0UKb5/mSsK/LoHhK+SfHcDB1V8jxUK+fliB
        7B6z7h3M/Sm2cJS2hA7Zo8vkHtfeaTuP3DA3MXbSfr29myfE20IB3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T13:38:34Z"
  mac: ENC[AES256_GCM,data:PYqltMeHCV1l2mC8afS3gY01KbjSZr3g+VxIorLpNLhgSTC+FLxZSzIiXbQNWdh+a6EKBJFI9FtlCcAokVKcXR4YXqURE1e4YHug6CdCzAfsOWLZ3ptcSD62W9x1Lr1mVadB7DbmG5R65ii0+vn626vqkpvOWCThjBM2L8gsyJ0=,iv:Q73jO/+IGEyYvON8iJCJxZJh6F8miCJ+awfwJe0MOMI=,tag:BbJaL/OyC/za8Cw+FqnR/g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
