# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: barman-cloud
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cnpg-barman-cloud
  dependsOn:
    - name: versity
      namespace: storage
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  maxHistory: 2
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    resources:
      limits:
        memory: 32Mi
      requests:
        cpu: 25m
        memory: 32Mi
