apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-auth-secret
type: Opaque
# Authelia env vars. See: https://www.authelia.com/configuration/methods/secrets/#environment-variables
stringData:
  AUTHELIA_SESSION_REDIS_HOST: ENC[AES256_GCM,data:wzqvBSOTd6ncyhM62ktdGWTRUdxcFwOmY3iBxXJKi6YQgeZPJA==,iv:ItfaNge1eMso1Q58CPON0f+a9wNpo7rPaVyYRPv44Kk=,tag:ZZk4z6rdmSrzRvqUfp6p+Q==,type:str]
  AUTHELIA_SESSION_REDIS_PASSWORD: ENC[AES256_GCM,data:z1278FqVNhHZFdStur+78EXiJWZU2gwDDH6+R8jObiT8YCV7sr35cEUzP+MPfRjZyVyMZ7pWics4Mnn4Xue8R02afk2oy4fDEtEEq+YupRqm8ymwPTKunCWwvOntfGiF/sMvWk3xGcqxdijM+S+5mjtW6ZARSje1ed0Yp2Y1MzJeBsmgEj7omIG1e488Wads9VIGUPLfMnele3uZXr33L67p+01BEiiRqKvzEQ8qPy/gT6FNZyJPaRNOHGUlE0EY,iv:4VzaSoZuR4DvC/wU7XuFMbalR7q64AnEEjacqnSBlS8=,tag:JlNklDV/IozT6mNGGKqdqQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEJ0UkhIYmdo
        bS9BTlhIdmZIQ01VRmxEUCthbzBSK3V1S3Y0UHNVaHF4Y1dOODZPQXlyQ3FFaC9w
        dUJmM1RjaFRIU1dPSzNaeStCejVKOGN3VXh0Yzd6TCtQdXBjZmM3bythK1VpTFhl
        Z3NwRXhFNmd2V2FVa01tMVRLTUdNYzI3ZmlGY3YzUU9mSERWVjNhZXhWbVRwS2lx
        OTR0enZ4SjVKSm9uejVNYjlXUjhXZ0RxcHFOT2Zwd2FZNXFRSmMwOG95bnZUSWhl
        WmNBY3lMV3FPWHBlV3NiVmZuUkkzRGtIbjQxN1NRZWtkUW1CTWRyY2hxTStXRk9E
        eUJLeS8xL0srSzFJa3pOdkVURmRFK1BSdnpnNjZHbTFNWHYwWCtrV0QwaVFReFlS
        Q3M2ZDU3aGd4ZWVYUUhWUzk0RHMvSjJKcEYxWXNFY3NxcXk5MzhscGpEMXdKQWo5
        L042N2RTRzZBd0Y2Wk1XNzVXZW53Ynllc1pmdFZJVUFodDJJUGtla1RqNG9TeGkx
        VTFmSCtNKzRXVmN5OTNaVERaK0wyYWFCTFFWalA3aW5mL1NlT3gzQVBpdllSTjNY
        S1NVelhsWVNKTzBoQVlIRkc0YjhvZTc4emRTbHV3NE9wNFdwKzNhVlo5ZDBnKzVw
        RkNpYzVJUXRnelBpMDFpVXI1YTdSLzR2KzBES3JwenV4eGlwelNITXpFNE5pVE8x
        ZGNQMEx2bE9NNitneFRmSDF1Uk1YTDBFWGpIbUdQNzlWQWdPTGRiRzVDUSs0RnZn
        VW1yeERjWGpYYk5ueWw5ZitNNWNKd3NvSzMvRUE5dmtWaEdwZzhaOGdDc1ltbENk
        VU11TDMvWjhJUXlzc1ZqUXExSWZzK0dpVldQWUJNUjVGaGxhVElXUTVib09zZEVw
        M2htL2RFYVVCbzVNVHh5Vk13WUpZdmZoazV6VkY4TU5WRFYzejB3Y1hFVUZWV1BV
        K3dQclhjVWI5bWN2MklFSW5oSjlJa2JCZElFdU5pV0RXZDJnMjQvWEdBemp1bnVL
        azZXVDRPajM2WWNUOTkwQU5ReFNLYStRZzRDV21EQzBuYTM2RGVZVk52eXJ5TFcv
        TUhJZTVWMGlvVmZkeXpsb28yOURCcDFiYnlnRmVWd0tpN0h6RmpoS0FBK0pYcFVS
        Yk9lZVk4SVdKd0xweWJ6VXV3NlJ4YWVRQ3JPZ0NZT2h5S2pOdzVJaU0wK3pBR29T
        NmNqQUY1Mmw2RkFiOGVzZDNuY1FnK0JubjgvdmRWNi92U2lKdVc2S1NaNHFaZ1JC
        c3Z6MEdtaklMd2p0U3pvbjVtd3ZpWks0aS9mZXRnekRmanBKS3gyWUdJdGRrakRL
        SWJFZTJlYlFzRjFJZS96eDdoUGRIWU4wMkdoWVU2cTJsYnkveUNSSnZ4OTdFcHF5
        Z3c2Z1phdjQ5ZGF1MFdPa3FhQ1lDanhrdU0vS2l2TUt0WFpyV093aVhUNVozeGJG
        bmt4QlZmRWxrZ2lmS0RmYjRuZThPVWplN0NxcGRmak9sRnhiVG9xWmpxaWRJanRp
        N3BiNW5FK0kzbzJoL25BV0JuOS95MkdmK0RHdmloNlliUmQ5Q0RESm5ScmxIOTJZ
        UmJwSDd1M1RZUHUxNVdmaU9Ya3lYNG1SYU9UZS9mZTN2RkNVT0hhZDB6VXBEM2lN
        MEQ4Wk55amlhbzc4VFhWemp4MFByc1RkQUUyTklFVWpMMHZCdUVNRFREOFo3VjVZ
        Yll3OGdYMW4rbTBpSUhIQjFVKzViUTRQRHIreGFiTUV1Z0MxTE5zczNxSlFKNVR5
        NzVra2llOGxZNnUwcHZwcTc4UzRIdzFCZ2R3TmdGS0tpWHAwM1lHa1NFRFBzZEpt
        a2pyT3hyNkRhY0ZQWWxWU1Bwdy9YTE9adHFoRTMxRXRZTzZqR2V3RzBtQjZacCsv
        ZU9ia24rQUFxN2RZWDdCQTBSeStEYjFCTFJYYnJIK0VFUE8yVGxRMHFaYTZCdwpK
        TEdtZllHQU83MHZseWlWU1UzZU9FUUE2OGllSWNBWTh3WTdic2F2WnVnCi0tLSBn
        bzRTQktuVWdNQW5BQjUyL3JVRGl0M1RuZWM3Vy9WN2NpV3g5cDY5ZzNBCgiO8IFV
        YTmnGpV6DxJPWeSmnXBLLgPgYUFwTWPEVsGtwh2/QcfkKjrQwpGOaOykpn0zqNQy
        anWmnJdU8hKhDo4=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:bQtLtJVqmevvUg8ajJ3tKPokeOGFa8eikaQwqWDKpB0G5a2E2r33gXu4xkKQtNQof8xNZbfVgXqtXAR4yVU35/aD7AbKXdd3enSDb7hMNr5Dm0BtHTv4S5M3AV8VP8c4gLhc34S0plBvIEuyawefhNz1U/iSS9H3qha9D/X/2Lg=,iv:boUyRKjIhKqg2dyRpuPjjng3EsyugKesZWIxGsCGKO8=,tag:KoagyRzSrf9dBWRvZHL9og==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
