---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager-webhook-ovh
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.9.18
    digest: sha256:955c9751e62d5cc4d54d514b97cc122e38d3ceaca97ba8867827167dd7dc9137
  url: oci://ghcr.io/aureq/charts/cert-manager-webhook-ovh
