# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ovh-issuer-secret
stringData:
  #ENC[AES256_GCM,data:dIHme1XVgvDJIdpKolazAi7aCAQZYONuJdW+5iBmbmrpI3Mxt7910lK2BLGcgFt+xTTPoebKH/9i+zBPeY5xX9rrwg1xSt/qGUJZs8RUdcC+hV3Gshex5+KuYDiF6MA+69fura00Ub9B2aIBt7idC4oBitCAybWzzZ1i1htKZOUnj8iMwX9lvh2jv9c=,iv:h9+dg5sgjBhX/oWNV2pAkHb+S5tow9ubCzDMCNDZjvg=,tag:VV1/9jOcf6Fw+X4tDkHcyw==,type:comment]
  applicationKey: ENC[AES256_GCM,data:yDusO9Mwyvv69b++9I+j9Q==,iv:6VcUqyMroPs4dvlos+bzuG42W47jmhPBe1zAmHYhDdw=,tag:ucI/u+uVF03CkBau+1vqAA==,type:str]
  applicationSecret: ENC[AES256_GCM,data:0L7KcXDjXP49CH733shNbyIUJB0WuewUsZQc9eDm5to=,iv:AnVkD6GWkuSkavToPHC0C+sfIBjXfDHH91waCgbA6x8=,tag:eqq/SCU0V/l3vNHqSDv3Iw==,type:str]
  consumerKey: ENC[AES256_GCM,data:6JsrNfaqHGiCPyEsGb2od669lVYeuq5hoEgOB6S2gdo=,iv:QNEgSZxmS4hNeFOMiPyvvA5FkSciF6qKz3iVjtjTXrM=,tag:omZD/TYZFanNAgMih5r5Mg==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaFViZ0VIeEdtaDU2bldo
        NE5uYWVyN0JOVndFZmpTM0JjVDB3NnNlbG5VCjEzNm9SUE9WZWJVRlkrdVdkVU53
        Ukg4bEpzRk5RRHJ5bDEwUnZjcmN4Y0kKLS0tIFovVktsNUFyUTVHdjBUeE5vS0F4
        V1dUemNveHJhZEdKT042bitUTHN2REkKoSWMdz7CKk3qpBt6uHesTZlQoAx7iWQg
        nFPOWwdFcjAQbmTXp0GNOmNU6t2VOTnjR9VRaXAQeAE5+5CBN5JBsQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFlka1EvY1cy
        MGh6UXJaNFhQbElXL1VBOWxUcmRYSTZTbXlmRDVFc1Y0S21PTmpoTHZXOUpFeklT
        U256T2hMTXZmWnBlcUo5dHp5bngyd3o1Y2cxNDAwNHVPNUg3eitLUFd0S2gvbktt
        bjhKM0RFRURPUmM5dW5mbHlEcWoxWUlmczNvd2oyVnBRdVdZczl5MWJDN2xEeUZI
        NEpqNndlTzdUWW52b09YdEtnNkNpOUpqQnR3S2lGSFNqSFo3UnBKNS9QMkZKN2xG
        WmZWRWlHdlI5d1FtbVFyNFVLUFNaM056Q29hUTJESTdTeThMcWhDZVpsNXZrSUIr
        T2ErNGJJM0FnVG9ZR3VNbkIycTg5d3JHb1I2R3Z2eFdJblYwUXZJZ3FZWFVxbjhn
        bFY5OFNhV0NFWEpzNVQrNndRMGFvazdPcU9Ha0gzYlBUWGdFeHJrTnRWa295a1E2
        c0pyK1F3VXhGOVRSSEVOSktxbkhIUmNXVVpBTVIzMzNkbEY5Q0tTZ2F0R2sxd3Qy
        Y0JrRW9UOFdSWHZhZnFpNkJRVUtjQzJ2NTlYT2RGa0Q1YXl3M2IxalJYTCtVQk5l
        TGg2RE5GaHBKWXZZaUVpbEVaTG8xM0l1TGxqVm1FUW1ZZ0dRWktIeFdQcmdGTVdN
        ZXExTmJKSzJ4UXBBS1Q3bTAvNVpLWG05RjFmeWJXUHpVM0ZJUk43Skk2MEg0cnNx
        eU9XQWlHa0k0ZWZ4VDVoaFNkb0xZWE5Hbk82WFVtZFVTY2pvTm9wUmp4T3Bna1VY
        blhtRERKNTBKZFZDZTFUTDJxdW0veTVOaE9LSEQ2YnBSUzhzOVRKR0wwRFFOc2pK
        VElBN0gwdDhPN2xrMjVvczBESy9scndaVmcxR0V6UlBrNFVEWDZzYWZGeGdPQXlj
        S3FCYkR2Y3oxZGNCUFEyQlYzNWlsQTQ3ZTIzZEhmN1JJbHU1dEUzLzRuVnhIN21X
        R2crRlFsMWNEeFZ6NmRCZUVjVm1JZHUvWXNaUDFIY3lXQUwyUVZJNmx0cGVkcmxq
        L2JmQnQrTEczOUtFK0pYRmxtTXJoUEwxV081SGlBc1ppcHViNDVLZWZTU3JEeG1G
        M1RHSWtmNTdWUTBlZmRCdmY3MVBlRlpqaVFpR0gzN1IxRWJrczdjUVZpbGFJdG1L
        dmhvbW43TVlJYnZETXdDOWpiNHN1NW1zak5pa2JES2tMNHF0aTRXa2p4bjhUSnFu
        ZndxZXF1S280ZHI2cmtjZFRUWmpEeURpQmNkRzBBNUpxYksvdlRFNlp2OWJxV2Fp
        ZElZN1cxdTJZWmhCV1J6ajZVUU81UmhYcjg1K2tnZjNhNzlzR2toZklYOVVxQkZS
        eHRvRnlRd1dSWHlVYUl4Qkl2K2Jwcy8yWU42NjFMN1BjUktiTWhCcllVZWYrQy85
        ckpJU2pSb29tL3dxQm0rQytWUVhVVWY4RUNJQmk3ZkxuMEs0WTVmZU9nbUdtdmNx
        enRTbmppZk9QRkJmK081ODNDNldoampVczRCN0RZTVhGa0RuV09aYldmYXp6RE5C
        R2pweFRxODVDaFhvWG9ZeGVJakhYWmJVb1RLaWgzVHo0Zmg3TG5GWWxwOFZweE8r
        TUoxR3hKQ0hjNFhrM05pdXptQ0txa1JHZEw4Q0JXYXJ3RWJlblRUYzVLRkhZR0g0
        TVV4QkZsTjBHVWpmTGpYQXhhUkdNT0NKRHViSlhZdUJCa1liZ3JRcFBMV2plTXdK
        b05ZOWphZGFzajJXSUFSVUFVVytOcHJFN0wxVm9GdDN1RnZTZVByVytJNVp3b243
        ZmIwbXFsOWp4Y3BvblFlbmNoVXkrODZqbHN1NEVaTlNvSmJFL1YxTmg3bDJVMDE2
        emozVTc0REVaZGZUOEJMTmsrSG81M1gvS08zZEF0SVRscWZ2S3pZNmhERzdXUGVP
        bStZQVNyRnd2MnlFZDV5TTdhdUxFb3pNZ0kyWlRwZ2xIKy9XSUxNTlJXbXhQQQpt
        NTU5S04yM0ZMTnpROXdMczNXSEFkNzhtS3d5czBGSk9zdlR0OGM3Vm1vCi0tLSBu
        NlB0TGZ5OG11cUdBcS9NWmVlVC9jRDVSWE5XMG9qY2NjTTlMbEp6T0FjCimtAHgU
        IFkWMvErpkWJfgl+QnWJIbykqLkB6IP6kKBUrRUhyrFazoYfj2rsz6PffEoJIkPk
        9+P42Qr0vLKZcPU=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T16:14:47Z"
  mac: ENC[AES256_GCM,data:0c8r3uW9CXkW45bubdMkZFJ/23Jq/lPSVGsdGkLOO8IGVrX67MdLp/ohlPUUG6OV+WNSv7d51dzKVS2gzCqwu3fD9G+WuRmrOeNJeBGgNH2z6s0mTtH0azjwbziiHCqbQz3yLaQODKElR68wFDX0pAOFCNQW/L3lhM+Kh/qDBfA=,iv:tIqC/Ti9ywnBvHakAyIqILU7REOOX5UZZ3jhYphqqvA=,tag:ethYq1F5SRZ6TzI718O98A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
