# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ovh-issuer-secret
stringData:
  #ENC[AES256_GCM,data:hUPaCScc0GidyQJwPvSV2L27dOn62hFZOOsEJe+JBb3cmBd+fTJZPBZ2QNHPy4j2VbXWzLYJMAA/7Lq0SqzL6KCw+lmR5nNCecc7ntLHyo2N9wuYdAUs5E0oQmKYHirXF4sIvT5B7PubUebu7WS1dJ/yIrCs1y9QGCwZLfg0lU2NuhiDY6BrWgoPMos=,iv:h9+dg5sgjBhX/oWNV2pAkHb+S5tow9ubCzDMCNDZjvg=,tag:4HetDo0aUv/je7VP+4R4XQ==,type:comment]
  applicationKey: ENC[AES256_GCM,data:EAHEsJtJRJlOEg+pXU7ZuA==,iv:6VcUqyMroPs4dvlos+bzuG42W47jmhPBe1zAmHYhDdw=,tag:NVMkEUF4w1EGkDRMS6vfHw==,type:str]
  applicationSecret: ENC[AES256_GCM,data:ELE7s9V00QFILEOgFIo96W3QeXXhjeHsLzf2O1kGx4s=,iv:AnVkD6GWkuSkavToPHC0C+sfIBjXfDHH91waCgbA6x8=,tag:GOmLAkl8jcUan8oarWakIA==,type:str]
  consumerKey: ENC[AES256_GCM,data:8PO0Yw5yq8xCM4WQpwKlj8r8hywFTtkTqN7s0sgGulc=,iv:QNEgSZxmS4hNeFOMiPyvvA5FkSciF6qKz3iVjtjTXrM=,tag:XmIfgXUR9692sj6ycTRElA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDlnaWwwaWFs
        ZHd4VHlmUnJhZCtLcm45OTJ0bzJvSnFPNzUwZ0RYbytIbTVhSUd2TmxhaDk1R1VO
        OTBNNTRpWFduTDRiOEhnRlZmZlVrbWExSHRlb0JpckdjMFNNZGc0TG5UV0dYNTd3
        d1ZORDNWUEx4emVVTWxGZEI4dWRZMUQ3QVp1ZDgzV3VtTnhXYk55QTQycXd6Q21p
        SHEwcUlzTjA2VXo5SW9rclNXMHJCamNGZEowUHpRK0w4T3ZhYXNYdFNVWW1MY0NP
        VjlQRm1rZ25BVVlUMDkwbERvajRtdmV2dHJHcUdiTml0a3BOazNmaDVZajZXRlR1
        UHYyc2ZJSjNSYThJZkdJTmFFelN2cXU1MlBZV2o2L1oyMFZ4WFExaXpmWHRzNk0w
        dERSaGN2VUVXZ00vSVpJWG1QeFplUHRFK2RmTmJ3K05idXNJb1JFL3MvcDlWUm9l
        RmlETGRiVnhCRUU5aCtTNVVhU1JPcjI0cVk3ZlhqV2hnVXZMYWdoQnl3ams2Vmdp
        TjM5ZldOMEVYZitWWTV2bXI3d1N6KzZBdCt5S2Y1OE82UkFCbzU2bTRmMUNSMzJm
        WlZGUFhtVGdiZ2JGNXk1UGl6SmduTWFyNnlMNmM3Y2diaHFrQ1htUWl2UGRvRkhQ
        MEtydGFJbjlaTFJpMi9KS09YTjlXVFA4MVRsb2E0OThkc1o5dnlsY0RiaHF3VUJZ
        bGdERnFIZVh2MisyMFdxTkhEN3ZXL1RLLzFoUEpYU0s0K1dZR096QWsvQzV4U2ll
        UFhUTllnZk1ZZms5VEhMOTBDb3kwczJaSTRhNHViU2ZheG0wMjd1b1AzbjBhVUhm
        MHRucUM5dXpKb2docmdlWU5TZE1lNW1oT2k2RlREbTJUT0Q2d3JML3hmTWhEN1Fy
        QWJqcjIxazhaS2RyaU0wR1QvZ2ZwNDRBWFg0bXBEamt4d08zWld3S1ZNVXJvZm5S
        dWZWMjU2WjZmUitZMlE2VzJUMUphRE0wMDUvakI5VFFFd2xGYWE4RTNvN0xPaXY1
        ejlxMmFFUVlmVlBJbVc2MkxQMDFhWXlXWmpPVk1kbW91cS9aMytEQlRyQjR1eEpH
        ek1oVzB2WmtTNUNnekJiazZESFNibk9PNWJzZnB1QkdRdGxlWlRoblR4ZDZhdjQr
        dm5EMjd5MGNWZFYxM3R1djRyVmRLTDhERWNsa3phdDJkbkR6MVIrcm1JbFV5eVVo
        ekcyTTZ4a203TjMxb1RrOWptbGxkZDViOUY5dk1GaHUydURZQnJjVVA0b3VXblBn
        Ulg2QXcrRDh0R0ZqMms4c3pkdUlIYVhOMkJWRVRzTERQem5qbkd2WkovQndYS3Nl
        bkdNLzlYeEdXbG1HbmJKMFUyZkRZVlFYcnlNWXJjNFF5NWtyWDk2QXNrOVBwTHcw
        ZmNPUnUyUHplQmxmcEQyMHNoVy9oNWlaZk9rZG9tSFZ3WHR4QjJldm12NWFVTnNP
        TTQ4NDNaWWNKUEFFSnRQZ3Z3TTM5TWVodDNmMUlTemNOWG1hOGRoRjB2U0grRW9K
        cHBrc1p6VVRFWVFXYkpBa1FyVGxrREVDd0RUWWhENjNONFVmcURGVlpHblc3TVBI
        SUQrTVJHM282ei8zRWlkenZiL296R2YrVHNSVzl5WDcwWDlmSlBFMmxzckkweVVI
        Z1Nic3dWSzFKK3htOThvWm4zRDZqbkJ2a3EyWktQRTlRaU1CelViMnRpczFKVUJB
        YVlUS3FXSWNKbkNSQzNCSFJqdFRCQlRmM2R0cjREeklTbDJCcWlZb0d4OGhDMDBx
        a1VITUNHWUUzdkdCQko0Nmt6V1lJMXVRRXpLcEJBOW1sSkhJY3VHR0RaWnFROEhB
        c3lmOXdCRWRoYm1KMmhwaDV0RmR3cGxXY3l5N3MwVkF2VWtNeU9yWjdWYlNIQ3Uw
        eTBOWEZqN283bVp4UERnczJZWUg5MC9hQi9ISmZlbG5FQmNIbXFEN25qN3RadwpV
        ZC9WUmV6VHh1a3RKNjBWLzIxQmFkRERvaDZPUU5rUFB5MDJGQjNYSUhVCi0tLSB1
        d3Vkd0c2bUhkejdubVZKd041ZTgwa01nOGZubVZaanVvS2tKZ2NYYVk4CpttOdP7
        Kh3eSLvfYUyaoW3ULnAf5TvJ0NbnVYBt5/BaZyJGtd9LP3fz6/7b4jwVIDVAuaj5
        +KR6n/d0PYd5DfY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:d0bj4hxOSTnD9Ce8aj6665YhhLzPtIxCyyibl6n5fFpshfG2A7IHSPY98V2nEPRUSqY0Vk5asdtd4YMZRlSsPbVxnsZnSCNPbhfzKM6PGxO57y8pdXrKtcMjUiyA1iaEdWoGTEV5/sNe25wruYtOHE+fSBkXWX1hvyiWSydLDio=,iv:xv3pZSn0ReOFyWM2g02Vwb85GNvGo65pcoVqF+Z0JD8=,tag:K8DPGhYopEb3GnYRAuyWoQ==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
