kind: Secret
apiVersion: v1
metadata:
  name: ferretdb-postgres-pw
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:nAPwwVqPFV4=,iv:g/JcP+hb1YOmmiqRKSMezQgXGNJ6cQwPXiFXXxFfPGA=,tag:EudAHfB/BdR0UKWimxqkaQ==,type:str]
  password: ENC[AES256_GCM,data:4FDqpfxI/GUwtgoog6KhmIuLrSURUXR5wKh3x4RfZpEAfJYKaZqIPoyL/QeKEc0u0rnxiwEB1e8=,iv:47VDMmHoCNn5wEdBPHqYJA3nmn3G3JLcDWA+J96eorI=,tag:1bmcwsfGNdfhuwyw8YaubQ==,type:str]
  uri: ENC[AES256_GCM,data:1WI1H5UVnEBAalwqOErKFZ2UQpDSBkCFMNHrhYfnvKSZCIxyB1t2BMRAhcqDyuw7D7HazF1TY565uZJv0UKYvtdWBRWv3mw83o93pJTipMBnAGeKgi1nvKn0qL8T+j5pBfP6dP2qEPi9dFmLamvToiz1jqRqp40O87HQv1c+Kmu2M1nMkKCGlB0ksTIaHQ==,iv:mzaiq+1QdIXpUdftM0Rth5+gqTfVLXoHFARQPu+BUiU=,tag:Uxfc+VOZmT3wx1MWuJs/gg==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqODNWcW9Jc3NvREMrang4
        U0l5bEpQWDZaODlVSEhyU0ZBNEZHMmZVcHdVClM2TGhEdG4xZ0hodlM2WEplZGRx
        WEE0SWp6aDNyblVmdVptWHBWR2YvTEkKLS0tIEFUUTMrQkVRditXWWcwbGJiNWU1
        OUd6REVEOHRFUmJKSzF2ZnluT2pUVDAKIt6dYA7rvwwVW/3h4m0MKbkYuQhrw09i
        TneOt/Rd1oEuTR2Sl4V6C/ob5+Cb7RSa11HZWHyG3brCmT+5CbL/3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-01T06:32:34Z"
  mac: ENC[AES256_GCM,data:k8k6h/99jJEx5iFmUhqwgI2R36yPYxqBE1aUFvKxLshGM5fah5tI79L4LRYY+igEKC35bgL1/Z2s7f0r7XiSn9OK+873j/N3A/2SDoU1aqu3LLp7/LKoIZ7cesgrktAqIrAz8NInNLfUcW3DyfJNyzTCMXzwkUAUSZtBI8NFGAg=,iv:o6f8pmjx3FZJ+1RxC5FqIPQ3vbQIIt0qcTZTR6sqjVI=,tag:YZRLJQaxxmiv9GBVSKxxaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:qQg/FO1LljxjSy+/walPtY47E6vWlg==,iv:EvugG6+cN9yXEg6fkT7pTXfDadfh28Q0y2rp+kFdjnY=,tag:4cFZW+0+gAzKA+ibhkmQhg==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:69sXwksSbvEsxAFnDwATtacLqWodV/d9u3LrpUR7CBo00jzj5MvpHeG3X4rbapzL,iv:nX2oSbpl+ORA0aOJVPdxW5MfY6HMgF5JuPooB9uq3EI=,tag:dDkHimlDnVSOwCPpp3T1KA==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqODNWcW9Jc3NvREMrang4
        U0l5bEpQWDZaODlVSEhyU0ZBNEZHMmZVcHdVClM2TGhEdG4xZ0hodlM2WEplZGRx
        WEE0SWp6aDNyblVmdVptWHBWR2YvTEkKLS0tIEFUUTMrQkVRditXWWcwbGJiNWU1
        OUd6REVEOHRFUmJKSzF2ZnluT2pUVDAKIt6dYA7rvwwVW/3h4m0MKbkYuQhrw09i
        TneOt/Rd1oEuTR2Sl4V6C/ob5+Cb7RSa11HZWHyG3brCmT+5CbL/3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-01T06:32:34Z"
  mac: ENC[AES256_GCM,data:k8k6h/99jJEx5iFmUhqwgI2R36yPYxqBE1aUFvKxLshGM5fah5tI79L4LRYY+igEKC35bgL1/Z2s7f0r7XiSn9OK+873j/N3A/2SDoU1aqu3LLp7/LKoIZ7cesgrktAqIrAz8NInNLfUcW3DyfJNyzTCMXzwkUAUSZtBI8NFGAg=,iv:o6f8pmjx3FZJ+1RxC5FqIPQ3vbQIIt0qcTZTR6sqjVI=,tag:YZRLJQaxxmiv9GBVSKxxaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
