kind: Secret
apiVersion: v1
metadata:
  name: ferretdb-postgres-pw
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:nAPwwVqPFV4=,iv:g/JcP+hb1YOmmiqRKSMezQgXGNJ6cQwPXiFXXxFfPGA=,tag:EudAHfB/BdR0UKWimxqkaQ==,type:str]
  password: ENC[AES256_GCM,data:4FDqpfxI/GUwtgoog6KhmIuLrSURUXR5wKh3x4RfZpEAfJYKaZqIPoyL/QeKEc0u0rnxiwEB1e8=,iv:47VDMmHoCNn5wEdBPHqYJA3nmn3G3JLcDWA+J96eorI=,tag:1bmcwsfGNdfhuwyw8YaubQ==,type:str]
  uri: ENC[AES256_GCM,data:1WI1H5UVnEBAalwqOErKFZ2UQpDSBkCFMNHrhYfnvKSZCIxyB1t2BMRAhcqDyuw7D7HazF1TY565uZJv0UKYvtdWBRWv3mw83o93pJTipMBnAGeKgi1nvKn0qL8T+j5pBfP6dP2qEPi9dFmLamvToiz1jqRqp40O87HQv1c+Kmu2M1nMkKCGlB0ksTIaHQ==,iv:mzaiq+1QdIXpUdftM0Rth5+gqTfVLXoHFARQPu+BUiU=,tag:Uxfc+VOZmT3wx1MWuJs/gg==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqODNWcW9Jc3NvREMrang4
        U0l5bEpQWDZaODlVSEhyU0ZBNEZHMmZVcHdVClM2TGhEdG4xZ0hodlM2WEplZGRx
        WEE0SWp6aDNyblVmdVptWHBWR2YvTEkKLS0tIEFUUTMrQkVRditXWWcwbGJiNWU1
        OUd6REVEOHRFUmJKSzF2ZnluT2pUVDAKIt6dYA7rvwwVW/3h4m0MKbkYuQhrw09i
        TneOt/Rd1oEuTR2Sl4V6C/ob5+Cb7RSa11HZWHyG3brCmT+5CbL/3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-11T16:04:00Z"
  mac: ENC[AES256_GCM,data:YRdrEb4jH4McH5rTzNMDtLitPeereCs8gG8+vhJe0poZPSYImfl5QZ4Vfrp1Q/IUHCdhtPOI31Wabz4q9E7ut9Pi5CYqjLn9BUfE2Hbf6MAaM+s6Ln0hcxmqFkG4Qu1QgCBW+ZxjmGYF28bGqTzXV7G3Cqt0Yw1IJXiHWiWWK8w=,iv:gZkbBQCFcJF2yExxpBDVB+2sMcpNvZJlft+zW43x4E0=,tag:/FbCkMj1UCgBvHfm28ny8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
