apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:k5D5ZU3KDSs=,iv:73h2VosV6i1mCyv+hFQ8E11psRoVfHlZWf9bSfy/ggY=,tag:G16BBku770+kdxuQlOcYKQ==,type:str]
  password: ENC[AES256_GCM,data:n7by1WMhZfWnliksvj1sGuhxzoMZ89TU+QsoQ+XN5nM=,iv:UgSRP3/X3SZzeZuCSaXPkiJHp2ymRP55s5wKthcQohk=,tag:wTxMYlAEojOTyEbPouFIoA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFRPYU9oaEww
        dThFWFpvTEsvNVpjUWNGc3BGOW5RRkxZRGxnNzhBb0MvTDVDVnM0Tnd5TGVxaWkr
        K0grYW9xUGtmZ1MwL1o3dDNJYnVwZStvU0hzN1FsWkhYNWN5bm1XMUpLS1hneGVp
        WElZMmp1eENaTG5vN3ppcExERHpnYTZJZ0pqNFhNRDFyV0VYSTEzbCtwY25aTWtl
        aTVzRXgyTHlSNWpKTUhhaWxERVpqdEQ3U3NDVW1vam52UXZTSmtURE1CY25XS0FV
        UGMzMkdlY1B4WGdUd3YvbEgvMmo0SjBlSVpTakp2Z1BuOVpjSUpxVWNHbFhrbnpT
        TDkrYi9qamNtVVdIZk1XNmFVekxORkhvSVRRc3JKRC8yRHF5SVc5MGg5V3FvZkFn
        dm5kc0lHZE9EaUdhUHh4Qk4wWU1hZktKdXArblRMS2QyN3hzb0l5dlBQSWJUUWsv
        eDdGNVNSeGtFK2VvZUE2czFaUUxGRmNneVFvc09oV0xVaGgxbzlOOEYzQUtsSjhY
        T0FKRzZCeFRHMEZROExpeHZPNitxNU9zeFpUMWtTaDRaUUx0NkxkbUJXWkRPT2tG
        R05IYnYrdlRnYmpMZGNTbGVnNjlQZFFsSTJDWFk3SDdiNjJpWW1ldnpLWEVGVy9u
        VkRKNHg1dU5qYmdxTUkwS3AvZW9telpTNXZBRDVOZTM2dWVCME5NM0ZmN0IzSkZT
        RTR6Z1NYNFJ1WVdHV3ViaVdUR0E3aVJXY1dDdmdEK01qUUpsVVlBTndESG1ieUJu
        Y2Zvak9VYWRVRWo3MmxKQWNLYlZWT1VQYkN1dUlIS3o4b2greFYvY241WU9ZMFd3
        RU9PZHRZeWZMbjFlNTlHVGhtMjh0QVBaZ21oSXFIWUhERWltWi9PNGs5cCs3RWt1
        SnhaalBjandaaUZxQksrdG1UY09tR2ZMT2M2TkVQTjNmRnFzYW5veGo2RUc3WXho
        Z1NLSjF0YkZNcElFSGNtSGwwb1U1QnJObms1ZXdSWW5saUhocGpzNW1hTDlSYkRu
        TEVWZGU3YlFzRzBpaWVaMm9UWWR1c0NOVEhaSmJzT0VXZmFnc3QrdW14S04ydGx4
        SzhqVC80cmxBTi8ySzVRVFBEbHNEbmpkZkZuRFBFSzRvY2R1V0hYVjhjaHU1aGQ2
        emc5SWp5cEsxYmxhKzY2djFraXNRQ1ZlTUxRbzN4RTFrbnpVM2xQSHJNZ0FValFD
        TFBMM0J3V0Z4dmI4eWgwbXRtV2o0aWdnNkd2dUY1SnJuajNaWWxTQi9oRlR3TDVz
        OG5HcThXS1NEbEx0UmZxOTVGUHFZU3JDdFA0WGdMMzZIbTdzOU9VWDlJL1ZIV0lE
        dGRwNHppUFovQ2ZZNGRxcG5vVHVHb21pZ1hZQjQwNzVIcXY1Y294OU5IQUVvVnFC
        OGk1aGsyaDhtVU41S1dQR0xFbWJGM2pLL3pEbm5Lek9idU5ERStRSWx0UmlERjAr
        eHZXNDhvdUtkakVJUjB5aEsxM0hLWkQydXduNkxlL2ZIQnFrQ21YUjZKbG1veVJl
        amJ1SGZRd3lZc210YVFUTEFHb3l2OXl5U3g1R2JJbzBoU084SFFjVTdPRUxTVHlv
        VWhaMHJKS2tXRmpjdEVjeHJHOFg2Yk8zSmoyd1V3Q1dValM5NGVtUlZUTFJyZWJi
        cWFkM284M3JWVmNNenFmL0R6b3NEOXBERURhTWR4UWk3VTk1K2N5L3AwYzg1NUFH
        eUVDQUlvOUx4a28vczVsRFpjaERDbzNCU0tGdlZXekxzRnQ1Z2p4VThPNDl2dEFF
        NG9qbU1kU21ZR1VpbEhKcjBiVVJyVUJJWFdCSzU2WTFuYVlYcmVxSjZHa2YyK2wr
        eFg0KzRNK0oyWDl4MFdCelpQTUx0Yi8vUTc0M2xEZ0JNMFp0dldYWko2Ykt1eTZk
        Rmt1NTVCbWMyZGl6dlU4Q0xzc2cvS1ovOFU1bjYyTkNXN0ZJcThjemRvekRjUQpj
        NmlHTnBuNlRvN2U0WGdxTlo1TDgyN1B1TldIK1BseXBqU0ZYakVwOG1RCi0tLSBF
        NFlDNktzR2hINmw3bGhDY3RrSXFUNlNVbEpkamtnOVhBMjFva1dGMENVChpFE+xb
        h6jeLroXGGLDeGWyq9exVJuSuAEht2+BPX8XFCn+w1b4etF2nm0I8HbogL1YZyb4
        K6jCX6vGxYXvcAE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:Wsh9NcSb75ddEuMxqHLlS68auC5r7fA/uOwbTorTcOUWfL08LjI0f8yGs803fzVPqUuO8pC1j+V4gAtc1FcKkmSfhhipgKaYZfERKyxDetYBE3BJcbr0zwQHXsIOcsS9zBDwSjVYVfCKqkv4OJt/StXSLmHgPbq8UezpkSjvEKY=,iv:H4rRNA2IupBBfDalSGFpfMy0Xq1TklQ1Owig8oTeWSo=,tag:BvTl1Ud5T2A60zyko5pjJQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:dSI75RR0hdy4EJmi5fICigTgQcSFGQ==,iv:k8Z7Bx5cojxDJAIaUFeo6fg1wwkNI9uESTehoozQOkQ=,tag:gWe6OCs6jD6t5pNqAWMiwQ==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:lttpqgB5PnOXGck61Xrigzt/dezGZU2B52elj+wG3UCnz7E6fTmWumzcC0d4TxJv,iv:raAnSvgp30SSE0PSDsxoCiH6jwrShqH5zwLdLTyYfFc=,tag:zRbliKyJHpZ0PXwLSyC/pg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFRPYU9oaEww
        dThFWFpvTEsvNVpjUWNGc3BGOW5RRkxZRGxnNzhBb0MvTDVDVnM0Tnd5TGVxaWkr
        K0grYW9xUGtmZ1MwL1o3dDNJYnVwZStvU0hzN1FsWkhYNWN5bm1XMUpLS1hneGVp
        WElZMmp1eENaTG5vN3ppcExERHpnYTZJZ0pqNFhNRDFyV0VYSTEzbCtwY25aTWtl
        aTVzRXgyTHlSNWpKTUhhaWxERVpqdEQ3U3NDVW1vam52UXZTSmtURE1CY25XS0FV
        UGMzMkdlY1B4WGdUd3YvbEgvMmo0SjBlSVpTakp2Z1BuOVpjSUpxVWNHbFhrbnpT
        TDkrYi9qamNtVVdIZk1XNmFVekxORkhvSVRRc3JKRC8yRHF5SVc5MGg5V3FvZkFn
        dm5kc0lHZE9EaUdhUHh4Qk4wWU1hZktKdXArblRMS2QyN3hzb0l5dlBQSWJUUWsv
        eDdGNVNSeGtFK2VvZUE2czFaUUxGRmNneVFvc09oV0xVaGgxbzlOOEYzQUtsSjhY
        T0FKRzZCeFRHMEZROExpeHZPNitxNU9zeFpUMWtTaDRaUUx0NkxkbUJXWkRPT2tG
        R05IYnYrdlRnYmpMZGNTbGVnNjlQZFFsSTJDWFk3SDdiNjJpWW1ldnpLWEVGVy9u
        VkRKNHg1dU5qYmdxTUkwS3AvZW9telpTNXZBRDVOZTM2dWVCME5NM0ZmN0IzSkZT
        RTR6Z1NYNFJ1WVdHV3ViaVdUR0E3aVJXY1dDdmdEK01qUUpsVVlBTndESG1ieUJu
        Y2Zvak9VYWRVRWo3MmxKQWNLYlZWT1VQYkN1dUlIS3o4b2greFYvY241WU9ZMFd3
        RU9PZHRZeWZMbjFlNTlHVGhtMjh0QVBaZ21oSXFIWUhERWltWi9PNGs5cCs3RWt1
        SnhaalBjandaaUZxQksrdG1UY09tR2ZMT2M2TkVQTjNmRnFzYW5veGo2RUc3WXho
        Z1NLSjF0YkZNcElFSGNtSGwwb1U1QnJObms1ZXdSWW5saUhocGpzNW1hTDlSYkRu
        TEVWZGU3YlFzRzBpaWVaMm9UWWR1c0NOVEhaSmJzT0VXZmFnc3QrdW14S04ydGx4
        SzhqVC80cmxBTi8ySzVRVFBEbHNEbmpkZkZuRFBFSzRvY2R1V0hYVjhjaHU1aGQ2
        emc5SWp5cEsxYmxhKzY2djFraXNRQ1ZlTUxRbzN4RTFrbnpVM2xQSHJNZ0FValFD
        TFBMM0J3V0Z4dmI4eWgwbXRtV2o0aWdnNkd2dUY1SnJuajNaWWxTQi9oRlR3TDVz
        OG5HcThXS1NEbEx0UmZxOTVGUHFZU3JDdFA0WGdMMzZIbTdzOU9VWDlJL1ZIV0lE
        dGRwNHppUFovQ2ZZNGRxcG5vVHVHb21pZ1hZQjQwNzVIcXY1Y294OU5IQUVvVnFC
        OGk1aGsyaDhtVU41S1dQR0xFbWJGM2pLL3pEbm5Lek9idU5ERStRSWx0UmlERjAr
        eHZXNDhvdUtkakVJUjB5aEsxM0hLWkQydXduNkxlL2ZIQnFrQ21YUjZKbG1veVJl
        amJ1SGZRd3lZc210YVFUTEFHb3l2OXl5U3g1R2JJbzBoU084SFFjVTdPRUxTVHlv
        VWhaMHJKS2tXRmpjdEVjeHJHOFg2Yk8zSmoyd1V3Q1dValM5NGVtUlZUTFJyZWJi
        cWFkM284M3JWVmNNenFmL0R6b3NEOXBERURhTWR4UWk3VTk1K2N5L3AwYzg1NUFH
        eUVDQUlvOUx4a28vczVsRFpjaERDbzNCU0tGdlZXekxzRnQ1Z2p4VThPNDl2dEFF
        NG9qbU1kU21ZR1VpbEhKcjBiVVJyVUJJWFdCSzU2WTFuYVlYcmVxSjZHa2YyK2wr
        eFg0KzRNK0oyWDl4MFdCelpQTUx0Yi8vUTc0M2xEZ0JNMFp0dldYWko2Ykt1eTZk
        Rmt1NTVCbWMyZGl6dlU4Q0xzc2cvS1ovOFU1bjYyTkNXN0ZJcThjemRvekRjUQpj
        NmlHTnBuNlRvN2U0WGdxTlo1TDgyN1B1TldIK1BseXBqU0ZYakVwOG1RCi0tLSBF
        NFlDNktzR2hINmw3bGhDY3RrSXFUNlNVbEpkamtnOVhBMjFva1dGMENVChpFE+xb
        h6jeLroXGGLDeGWyq9exVJuSuAEht2+BPX8XFCn+w1b4etF2nm0I8HbogL1YZyb4
        K6jCX6vGxYXvcAE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:Wsh9NcSb75ddEuMxqHLlS68auC5r7fA/uOwbTorTcOUWfL08LjI0f8yGs803fzVPqUuO8pC1j+V4gAtc1FcKkmSfhhipgKaYZfERKyxDetYBE3BJcbr0zwQHXsIOcsS9zBDwSjVYVfCKqkv4OJt/StXSLmHgPbq8UezpkSjvEKY=,iv:H4rRNA2IupBBfDalSGFpfMy0Xq1TklQ1Owig8oTeWSo=,tag:BvTl1Ud5T2A60zyko5pjJQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
