apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:P8dWbpZLhME=,iv:73h2VosV6i1mCyv+hFQ8E11psRoVfHlZWf9bSfy/ggY=,tag:3Fs+pGgyXyYwNsZwxosdXg==,type:str]
  password: ENC[AES256_GCM,data:klm5kbL26ejCMDn1GhxJLDGnQ3ySGwGdBkBihCwhyGI=,iv:UgSRP3/X3SZzeZuCSaXPkiJHp2ymRP55s5wKthcQohk=,tag:tVLtz1Y5I+ob5dclWchu/w==,type:str]
sops:
  age:
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGgxOWJ6MmhT
        MzVmTjhnc3I4ektzMktyb0E1YnZTNGxxcGJ6T1l3VkxIUHlBRmZHS01JbDlTa3Iy
        akkyMXlWdVA5bnZkb1RuMFJHRXBDeEVlM0d0T0ZqaXROaUNvSUNGaWtHd3A0U1RH
        M3V2aG5UYWJBTkN6ZnlkSFlPeW04RDhuMmgwZGg4NW9DWVgxRWhlQlNXVHFoRitR
        VFlpRFdMYXJXVkl5Y3FPZGFPM3VQZVNUdGxkb3BYWWpJNG9NV0FhV01mc1VZK3hn
        cFhYVnZQNnRuejJzd0ZVQUtmeHFESXJCaXEzdWJ5c29jYzZaQUI1OHIxUElNUG5F
        Nk5va1JoZ2VDdmc1RXF6dEF1N1dGN1JMVEIzOWRGNGpOL2oyYlFPZUxWREJ2emhk
        OHc0aC9MeWZuS2U1b0dsWldsMXlsTFQ1R2RIbmZmcmt1TW1mbDZBQ1A5TEo4cEhI
        Rm1CbVcwS3ZIeDZiWGNPczRrMzBUbWZ2VkZVN255am1lZm9BUUNzZys0K0toNE1G
        U1dvcDNoTWtlMnllZDRRb0pld1ZITEoyTjJNUVp6L21ubnZjbDRJcjlMbU40d0pD
        OTZ4dXdGZDJWNUo3QlhPQzUvcDVvSUxSU1A1blFjUmZDME9lY1dDOXNWbUEza01E
        Mk84SC8veVhVNDIxV1k3cERFVEozbEdhRk83bXJoVzNBaTc3Z01scExBVkhZcTNw
        cy85M2UyMm9GQjNmL21hOCtNM0xEZ0J5WkJwT0E0NnZaN1I2OUdnSUlEWDZTQ0pH
        WkVHaHhEd1ZadGppSVRHQWc0YTdKb2NOZXk3SjRQU3NnaXZDTzAvWFRsUkE5cmNx
        RzZmVFNXYUpXSE1nM09YVmRHVFkya3EvaCs1d2VydFFyT24wdHFGR2s5ZURFMzBV
        eGVBWDFsTVNReGF1ZG9FS3RaZ2FtNkI5ZWFxVlpHVnRVeVF5eUMwdGpyR3lYVW01
        U1o0WE1LTmpGcE1UbndJS2xVTlo2YTJsTnRWRHgrRTkwVFJJQTRtSmc0S2FtNWcx
        L1JZcUUzYlRRTGNVYUI1bk9BQTFUMDVzUm5rMWR3NzJ3U2FLQVJreWFDMXVxczJD
        UmdITXpRcXhjN3g1c29pOGoranUwSHhaY29MN29mL3F2M1dGZ05mcEFhRFhDRnlJ
        YklrckFKejQ1UHNPUUVRY2RnUllhZUN2N1V0M3dIWmFONzZSRUFzWjU2Yjc1NUlw
        Rk5XazJnVDVaNFNKZmVRZHJKYVp1RGE0YlRFdWg4QjhidmVlZy80dC9CR1ZIZE8x
        Sm50cjZna21QZ0oyN3c4M2RTMUFQTlRaNHgxbEh2TjFQVUVjK2p0YTZrUWNVNmx4
        dTM1bnM3dVFydUV0UHJ6NWdaUXUyVFdJT1FpNEFiTGJYOFE2THNUVERWc0tsNWs0
        bFI3UmtCcnhzVlhZN1JpbUcyYklyajFrVkovNTI3blNxQzh1WU5LUTZmL0dtb3BZ
        LzdmQTN4bWlRdk1Uc25URzBOV3V0ZkdPQmhRQ0lCM1pibjUzVC95MWI0d09TaGlW
        OGVEKzdIM0RPUHEzbkl5WVdsM2M3Z2dFWnFKR0F0Z2RTTHZ5a0h1Y2ZTMjh4ZnV5
        T2JWZ1YzU09NeXNsSGRGNUNTeVNPUS9oY2FhajU3Y3RDRVFzdyswdnpsYVQrbnJn
        U0JrWjFxTkc2ZWlXWXRmUXV5QURYZlRZS3d4cWNyQXpSVUxJV0xpeFkyWm16QWE5
        Q0UvcEZSZzlBNUJDekVGdFhzcjExQVJVOXZERk1kUXM5ZXgySWNHaDlubDRqT3Jq
        R0FKdWgwS0EwUXM2TGt5R08zWlk2ZjNRWVhnRDhOQkNENENzdVN6RzdPeXlDdUZk
        YjNLdjVlV1kxQUpQTnpnOUZDR093TWhxejhQaUNVNWdzQjRNaTdDOW80b1JGQkV4
        S212UUUrTmxMNWJFUXRacGQ5V2NwN2dvVFZMVDFtNHFmZkgzb0tjWmc2K0NYdwpr
        S04yVWVDNWVTN0dFbTZmWlBVZzBmQ1JoR3Y3cmxDNUhpZzhLdlUwR3g0Ci0tLSBv
        QzJYWEdqWmhTYXFvU0hWeWZFNEpFOWNGYnA0bU50cTFwb29yVzdydVNVCiYB+hJz
        ktP2fei2X3mN8meBcmWO//iRmg53ZJMA89Ympk2fUSvcKuvpKLX8Mii8ED6VrIPh
        kbh4bebT76VAqr4=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-11T16:04:13Z"
  mac: ENC[AES256_GCM,data:vKlK0j/FqFzr4D7mX1pDMsxp89a7qTdpPC+lU2J0jia9clJqRkpHh6UhmkNWBEaPOzAUWQau26M4wkq6gZ3aKh/5VckzwH6QMpAwDH3etcQzvCsls3NmW6OCKzfK4KD6MtN7sJI/9hRw4p5ltBqpSlT8nTEI03tinifxoqtzcsk=,iv:YxMk8/sT/G7waqSP9Q+iWTdv39izkhNGmdko7GWmf98=,tag:15mk2l9/IU6D2pI3UyjSpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:SvAX3N4dL4+4mAn4kdYv9lo0Wl/cFw==,iv:k8Z7Bx5cojxDJAIaUFeo6fg1wwkNI9uESTehoozQOkQ=,tag:nEcAIrid18f6xX7u5y8xnQ==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:E0XE7QKim5PdWEWaI/6fjhohIC+Zwr+9KCj1WQbUh5bmGAXXY8YvAaNiO5CdspBb,iv:raAnSvgp30SSE0PSDsxoCiH6jwrShqH5zwLdLTyYfFc=,tag:qBPcBt57KPmRY5RCRT0csw==,type:str]
sops:
  age:
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGgxOWJ6MmhT
        MzVmTjhnc3I4ektzMktyb0E1YnZTNGxxcGJ6T1l3VkxIUHlBRmZHS01JbDlTa3Iy
        akkyMXlWdVA5bnZkb1RuMFJHRXBDeEVlM0d0T0ZqaXROaUNvSUNGaWtHd3A0U1RH
        M3V2aG5UYWJBTkN6ZnlkSFlPeW04RDhuMmgwZGg4NW9DWVgxRWhlQlNXVHFoRitR
        VFlpRFdMYXJXVkl5Y3FPZGFPM3VQZVNUdGxkb3BYWWpJNG9NV0FhV01mc1VZK3hn
        cFhYVnZQNnRuejJzd0ZVQUtmeHFESXJCaXEzdWJ5c29jYzZaQUI1OHIxUElNUG5F
        Nk5va1JoZ2VDdmc1RXF6dEF1N1dGN1JMVEIzOWRGNGpOL2oyYlFPZUxWREJ2emhk
        OHc0aC9MeWZuS2U1b0dsWldsMXlsTFQ1R2RIbmZmcmt1TW1mbDZBQ1A5TEo4cEhI
        Rm1CbVcwS3ZIeDZiWGNPczRrMzBUbWZ2VkZVN255am1lZm9BUUNzZys0K0toNE1G
        U1dvcDNoTWtlMnllZDRRb0pld1ZITEoyTjJNUVp6L21ubnZjbDRJcjlMbU40d0pD
        OTZ4dXdGZDJWNUo3QlhPQzUvcDVvSUxSU1A1blFjUmZDME9lY1dDOXNWbUEza01E
        Mk84SC8veVhVNDIxV1k3cERFVEozbEdhRk83bXJoVzNBaTc3Z01scExBVkhZcTNw
        cy85M2UyMm9GQjNmL21hOCtNM0xEZ0J5WkJwT0E0NnZaN1I2OUdnSUlEWDZTQ0pH
        WkVHaHhEd1ZadGppSVRHQWc0YTdKb2NOZXk3SjRQU3NnaXZDTzAvWFRsUkE5cmNx
        RzZmVFNXYUpXSE1nM09YVmRHVFkya3EvaCs1d2VydFFyT24wdHFGR2s5ZURFMzBV
        eGVBWDFsTVNReGF1ZG9FS3RaZ2FtNkI5ZWFxVlpHVnRVeVF5eUMwdGpyR3lYVW01
        U1o0WE1LTmpGcE1UbndJS2xVTlo2YTJsTnRWRHgrRTkwVFJJQTRtSmc0S2FtNWcx
        L1JZcUUzYlRRTGNVYUI1bk9BQTFUMDVzUm5rMWR3NzJ3U2FLQVJreWFDMXVxczJD
        UmdITXpRcXhjN3g1c29pOGoranUwSHhaY29MN29mL3F2M1dGZ05mcEFhRFhDRnlJ
        YklrckFKejQ1UHNPUUVRY2RnUllhZUN2N1V0M3dIWmFONzZSRUFzWjU2Yjc1NUlw
        Rk5XazJnVDVaNFNKZmVRZHJKYVp1RGE0YlRFdWg4QjhidmVlZy80dC9CR1ZIZE8x
        Sm50cjZna21QZ0oyN3c4M2RTMUFQTlRaNHgxbEh2TjFQVUVjK2p0YTZrUWNVNmx4
        dTM1bnM3dVFydUV0UHJ6NWdaUXUyVFdJT1FpNEFiTGJYOFE2THNUVERWc0tsNWs0
        bFI3UmtCcnhzVlhZN1JpbUcyYklyajFrVkovNTI3blNxQzh1WU5LUTZmL0dtb3BZ
        LzdmQTN4bWlRdk1Uc25URzBOV3V0ZkdPQmhRQ0lCM1pibjUzVC95MWI0d09TaGlW
        OGVEKzdIM0RPUHEzbkl5WVdsM2M3Z2dFWnFKR0F0Z2RTTHZ5a0h1Y2ZTMjh4ZnV5
        T2JWZ1YzU09NeXNsSGRGNUNTeVNPUS9oY2FhajU3Y3RDRVFzdyswdnpsYVQrbnJn
        U0JrWjFxTkc2ZWlXWXRmUXV5QURYZlRZS3d4cWNyQXpSVUxJV0xpeFkyWm16QWE5
        Q0UvcEZSZzlBNUJDekVGdFhzcjExQVJVOXZERk1kUXM5ZXgySWNHaDlubDRqT3Jq
        R0FKdWgwS0EwUXM2TGt5R08zWlk2ZjNRWVhnRDhOQkNENENzdVN6RzdPeXlDdUZk
        YjNLdjVlV1kxQUpQTnpnOUZDR093TWhxejhQaUNVNWdzQjRNaTdDOW80b1JGQkV4
        S212UUUrTmxMNWJFUXRacGQ5V2NwN2dvVFZMVDFtNHFmZkgzb0tjWmc2K0NYdwpr
        S04yVWVDNWVTN0dFbTZmWlBVZzBmQ1JoR3Y3cmxDNUhpZzhLdlUwR3g0Ci0tLSBv
        QzJYWEdqWmhTYXFvU0hWeWZFNEpFOWNGYnA0bU50cTFwb29yVzdydVNVCiYB+hJz
        ktP2fei2X3mN8meBcmWO//iRmg53ZJMA89Ympk2fUSvcKuvpKLX8Mii8ED6VrIPh
        kbh4bebT76VAqr4=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-11T16:04:13Z"
  mac: ENC[AES256_GCM,data:vKlK0j/FqFzr4D7mX1pDMsxp89a7qTdpPC+lU2J0jia9clJqRkpHh6UhmkNWBEaPOzAUWQau26M4wkq6gZ3aKh/5VckzwH6QMpAwDH3etcQzvCsls3NmW6OCKzfK4KD6MtN7sJI/9hRw4p5ltBqpSlT8nTEI03tinifxoqtzcsk=,iv:YxMk8/sT/G7waqSP9Q+iWTdv39izkhNGmdko7GWmf98=,tag:15mk2l9/IU6D2pI3UyjSpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
