apiVersion: v1
kind: Secret
metadata:
  name: foundryvtt-secret-victor
stringData:
  FOUNDRY_USERNAME: ENC[AES256_GCM,data:4GCXQMi498x4,iv:JKoUWpAJtkYfsm67YoVCvsytnRGwbtjgZQc8iiWRqcs=,tag:5FbRBy+TPB7du6t9Y9HF3w==,type:str]
  FOUNDRY_PASSWORD: ENC[AES256_GCM,data:TwRl90hSJYktZ7q188PU,iv:uHwI2ZRyTkxYBuuNeVjcvkfULXThVzqpma2D3GK3C8Q=,tag:eKuqnW3rSOr4wnBmSHsN1A==,type:str]
  FOUNDRY_ADMIN_KEY: ENC[AES256_GCM,data:rAWscnRNW9gLa1qxHY6exBZfSY4=,iv:s1KSgeBHgHFWDVJRKUfzxiQYPD61+BCYr3TH63lcnH0=,tag:/S/cCxb3uih0zmqFtuhfNQ==,type:str]
  FOUNDRY_PASSWORD_SALT: ENC[AES256_GCM,data:9JbbT5vZFimWdZJ7PhC5bXsEMwbjL+UvtE4ZoSh2xN0=,iv:AGqK4T9gvEyF0IpSBsvR9dYHj1MnGlAMJHUb+6Vsq0c=,tag:W3tH6Go1TmYQ7ZaoGPsjIw==,type:str]
  FOUNDRY_LICENSE_KEY: ENC[AES256_GCM,data:FIRNuhhPHI/NQSHaSXesYX0mhcGZrtczpZYCjbI=,iv:Iy5a2ofTCLyuJuDQIqsqYM38X9owAFa6w0gUoEINJV8=,tag:Nv4+PSDjU1ihSzmRYe+jGQ==,type:str]
sops:
  age:
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEo4bGYzNDdF
        TFd2K3U2c21vTHpjcDBKT1k1QlV6RnpWcFBVWGJUdHkwWkR0YWJEY3ZpNGxDeGJZ
        UEV4bG9DWVd0Zit3ZnNjYjRjVkV1Mi9IaDdnNlpXVGJaOVZaV0JYQWMzQXJzSmJF
        QTd5ZlpHUVZmSXB4ZCtaNGltUmwxQzNucW1MS29kU0U5c0ZQZWVKbC9KOU1aTE1w
        V2VwQ1FjaTBxU3NsZmJRT3AzN2RWTFFYcWxVcGhFYkF0RTR3WEFEc1JMd3V2V292
        TVRWdUdJbjNOK1BEVzM0UWdMZ1drV3hHWmhtQWVOTllLS3paZHZNMmhKWVVCV1Va
        SVdxMjNyWG10L1RtQjY4QUo0aFRUNzJEdUMzZXNZdjVONDBlcFcrWVZuQy82NCtW
        QWhOczZLeUtBM2Zqb25BbEVFT1FFNU04L25lYy9ObFJyY2JGZm5haE9HN3VaWnRI
        S0lYUlIxUkR6eTcxVTJQRlZLWGNPaS9lUDhaUUpCSHRPRFpnRGIvZlVWV05MQWhp
        amZjcHhUMEpaanJvZ05nM3JLUnpxSGN4TlIyR1BnMkVQM1hXcEJxZ0s3bUlGaFpP
        ajM2aE45S3lUMHY3SXdlZFREaDFFb0p0bXFMbXlEenJrV0NCKy9hMHhCbUxlTEov
        UE5wdk16ellucnZtZnV4KzJKODVLaUZUVkpoMGphTHlEM3ZjUTBiUWdXYy9NZlFV
        aVp5dXJqa3o4aUc5bnZjdzE2aDBIdUdkdzBlOTlBWk9Oa2hjdVdpTk16UTkxUjRZ
        UG56SUlVWWhsejNKUTZKcFRiaG1WcVU2WlhtMkpvNVRSWXNhMktIWUFVNDdheGU4
        bkN5QnVDaWhjMXZ4TXFvUTdnMUdVSFpaaENrT3RsWUc3VkhTakFNTTNDVDl2QVFo
        c3NhM2xuTmRCNUtJK3lDTEdtWmRXMmVqS1E3WWk4bythNFg0RVBzaEExY3JVTTBz
        TUk1N0hlWDdHVmhWRng5NnMvN3NWUmtHcG5kSlVOQkY0bTlhd2J1M3RlVXJMYWs2
        eFh1VSt3bE80ektabEsxQUdIR3FlRzZ4TkplL1lPemt4UmxiL3U5M0lsbGJtOTIy
        Q3k0YVZEUTh6NGJMUklDQUw1S2t4MmNodFNlK0ExK1l1WEdGdWdHMnN0V0RCSzdq
        cVBHa3BULzNrL2FiUHAwOWxLQUNsYzdCenRyR0FXT0d5UXBvVVY1ZE02TS9nanJJ
        Wm5UZ1VpRUJ2eXYra0piNE8zSmNUQ3U3NDFxd0w0VTZQb2NtUEs0c2VLSVgwVVRY
        dEhSUkQrQWhOdW1FZVVkOVR2Y1FnaDdCZzNHYTVIcDBQOXRQSURzRHZPb0I0QVQ1
        QzV6Nm9iKzU3MmU3UDVwZ3JGWTRybDlXUTM1dGZPd2hvZm9rR3l2UG93dDVGZTg5
        VFN5cmp6ajJKTSthKzhNNUxiMG96Ujl2OHB6VjB1T25ocVIvREJSUW9raHUxVXJl
        QXU5WE1sY0FzWStsY3I5NG5lcjZnNUZjYmZaNlY1VnErNVNtRmhYQm1JdVdlT0lr
        Y3ZURXBmOWx3bGRXUmxCazVHekNoNjVYUUk5Rm4zZmN6dkxqTUh4dnVIdE95Q1hD
        ZWwzZjcwRGpCTHl2OWtNOGhlMVJVc2EzSFpMTVFNYm9WRGY0MHNKUkN0M0FkWjVH
        UUYvRmsrZWFsUEFISWFYcys2Zy8wYkRtMC85OVg4MUxXRnZ5UWFsOGZDVWtyTWxq
        b3B1Yk1rRVFmWi9vLzlLb05oNldrcUROb0o1ME1uczVRYUpKaU9kb3djOVNiTGlT
        NUlOZFFNcmJuTDJONGh2TU1jR200cHFVTjUzMktYQmhGN0tid29OSXUyZkJoOGZ2
        UWdTYUt6ZWJQSmxsZEVVSERzMXFhZ3Z4YWErNmo1aTIvMGQyekxRNFZBMmZzbVor
        VUlhamo3UTAzWGpSNEMxSDBzeHp6alkxZkRFZlBib1dCU25idnRxNTlyMlVGZwp5
        SmtyaGowRklXY2NZWDlpUlh5ejBwcmVKOU1TOXZ4S0tyZ2NSYk85TkhVCi0tLSBE
        QjVFTTIrSktoaCt3eUFHYTh3bGhHUGwzQ1NubG5HNkJQV0lvNUZpS3hVCvWdwWw8
        WNc0ZgRB2r+UpaVkbvJdX+Me7xM00laKY8WR78yzAVxhOwCP5STjrl790FQ9CoYT
        6e2D+RDRzjACoAs=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-24T17:01:36Z"
  mac: ENC[AES256_GCM,data:2gL1Ei7tUXKQ6wn7kaQauy+WDsNh08WbPpnIvxnZdZwmWmL7OXH6jpVTbybr4lhZFmR/VosjLGf7c0Z3GjK7TGvf+pUxsOsZG3BrFkjFFFCXIsnOfj//fELBGCMmNbscrXbN7HgIz0NmVWCOwhcrHqUMIX7QlREfPfDlXpswO9U=,iv:D9TWl76hVOCCCjIf2SjSzomBf/oPL7hM+xbgFshNZgs=,tag:L2YkS0r70oN/XGBefE1GxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
