apiVersion: v1
kind: Secret
metadata:
  name: foundryvtt-secret-victor
stringData:
  FOUNDRY_USERNAME: ENC[AES256_GCM,data:4GCXQMi498x4,iv:JKoUWpAJtkYfsm67YoVCvsytnRGwbtjgZQc8iiWRqcs=,tag:5FbRBy+TPB7du6t9Y9HF3w==,type:str]
  FOUNDRY_PASSWORD: ENC[AES256_GCM,data:TwRl90hSJYktZ7q188PU,iv:uHwI2ZRyTkxYBuuNeVjcvkfULXThVzqpma2D3GK3C8Q=,tag:eKuqnW3rSOr4wnBmSHsN1A==,type:str]
  FOUNDRY_ADMIN_KEY: ENC[AES256_GCM,data:rAWscnRNW9gLa1qxHY6exBZfSY4=,iv:s1KSgeBHgHFWDVJRKUfzxiQYPD61+BCYr3TH63lcnH0=,tag:/S/cCxb3uih0zmqFtuhfNQ==,type:str]
  FOUNDRY_PASSWORD_SALT: ENC[AES256_GCM,data:9JbbT5vZFimWdZJ7PhC5bXsEMwbjL+UvtE4ZoSh2xN0=,iv:AGqK4T9gvEyF0IpSBsvR9dYHj1MnGlAMJHUb+6Vsq0c=,tag:W3tH6Go1TmYQ7ZaoGPsjIw==,type:str]
  FOUNDRY_LICENSE_KEY: ENC[AES256_GCM,data:FIRNuhhPHI/NQSHaSXesYX0mhcGZrtczpZYCjbI=,iv:Iy5a2ofTCLyuJuDQIqsqYM38X9owAFa6w0gUoEINJV8=,tag:Nv4+PSDjU1ihSzmRYe+jGQ==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaXRYZlFqaS9nZE9HM01D
        RzZjcTRCM25DRzY2bTZVRWlkVVgyZWhoRldFCnE3azdONDhHUlVsRTN3cEZRQlJF
        RXdSM0xYNkFIUGJqY1BrTFJQU3FVWkkKLS0tIDNwY01Ka1dDeHNidHZuRTRkZzkr
        R1BnVzdjbWI2cVpHTTlBRDBZR3kvWUEK939rru3GWH2B1jtH/zYBhCdzFg2efcQi
        b+DR+/LoN1R0Gwd1OWf82IC5Cgl5mRyBamv5eaw6LPanGeC6uKLsKA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGZhS2dWUE9j
        NVJVRlBxSzcvbExTYzlUekVidE01dWk0QmtoTEZlbWVSU1pJUlNnVC8rMExRVlIw
        M2dtaER2WEx2MGpkNjd6My9sZFYxcXZCMzB5WHN0cEg0NUR6ZGN6ZisrMU1RVkxq
        ZHF1b05BRmtrZkd4S0VBN01hUW9RRzNMcmdJMmFJSFlUOERMRVlBYmo2QVl0SmJN
        dlRiMGpwcHMrNEFabHNnaG15VjRFc05nYi9EamFuMnlQN3VLYjI2S3ZtbkNQdGFw
        L0dINWtDM0hpTit5Snl1dk9HcnkwQlY3bVlwUk5QVExnaE5jUFpCeUhqY3k0dW5t
        NEFVRW54bU1OajUzb0JEL05TK25jbVd1d04xemZUdG4vc0puQkh1Q3UxMzJrUkYr
        aXRmVXQ4b0xtNlZoYXRxNWdSM294aTllTk9aUkRubTlpdWFqZXF0ZzdnYmp2RmFB
        bzJ5QktCSXExbXpLTjlyRU0vNlRacHI2Tm41K2N2anN0UEJjVUZIS1BJN09aTVc4
        N0x6T3AwdjVibXNGSnBHd3hSK2lwZ1kxWVFCcElLN2cyN1VxM0k0anBHbzNJUk4v
        N2lWeTRBN1IvdHM1VVhLSTFGMzRMckQ1ekhCekM4K2lVVGxUZzFGRDBFd0RHR0Rq
        b29UUUwzTmY3TEJZYWNvSnBPaTVveEgydGtINDRLUGoxTDlVbEhsa2ttcEZMUm5O
        elVUcTFicTg4Y0VkSFJOVjlqNzA2N2pxSmMzaDNyK2hCWGh6dXpqNUJScGpEcDZR
        UWprR25RZzZhZ2pDL0dSUEs4d3paZFEwYkNZSnZTOVQ0N0x4eWw4Wkh4MjdqV25M
        dEN3cXpSaEJUcDJGdU91blFsZzZFendPSE9HRk1VMXFKcUFWMlR4TmthUjdDRjhv
        MVVIUWZNcUtHZHY4NmsxbThVREVvS29TMW5kOHpFQldxWm4xVVYwdHpzYisxM25D
        QisvV0tCRzZNcFRYTjZ6NUhJaEFiZ3JKM0ZyVFlBMlFLUUR3cFRjME51TlNua3gz
        czRwMVZ4cDNpc0hxRkNWZmNlWkJ6RE5rZkkzQWZ3Z3hoc1NBVmloeGlSdDFTQnJQ
        VXNMakdIRWd4UXlqZlRQUGN1WmV5aXZCYmFiZzJHcGNZV3FKbzJ5em9xTDZFL3NX
        NUVrQW5jcStmSm40MHQyK0orakRvWVdBbzNVT254WmpYSUhyQWF6Q0V3eE9PRS9i
        VHZ4VWlYaE0xQlJGT1I0YnNiSjNtYzhtcU15VjE2eHRZYkJNY09TQitCVXhLZTgw
        b0NUem1wUzBXU1lJeE1jaEY0UzVOWGpLQ2Z1azVhWmU4aDVKWTBBMDFTaTJscFND
        SUh4RUZZVjFBWHBQUXhlMGwzNmh1WmlmaFhIUk9YQVMxUktjYnI1OEtydnhyQS8r
        RklDUzJEcEpySXZVZjNMTEg4QkhqYXZUK1U0UW5YL1ZCdUgyRlFPTTU2RnNHWCtu
        cjZaUDlQYUZpQVRvTWgxZUN0MXg5eW1KUzhFSGZxQkw1UitLaUUxL01hZ01MNGFP
        VDRhVkM0REQyMFJzUWZoeHE2QUlEeVBNMnBMSGc2MEZnd3RhNHE4bVNwT0liZnlB
        N1dOOG1CTk1HdW1WNG1WV2lyVS9DYW56QnQ4UU9IaUtITzQ1aGhOdWZRQTFldVYx
        WW9FNkg3YTJhd0tYc04velhOMHdaTWdaanJESm01VlRMRzZTYUtsZzdza1J2cWo5
        bVNDYjU4U3Vsa0lJMHlTUnpwK0k3aDJpeFZmYVZJZXcvbm9IY1NzeklmTUF6OHYz
        NVAvT2JwRkhobXcvVGd1aCtXNWN4U1hiZTBGWkxWdXZZc0hmTUVrUDFzVDJPTmd1
        YnpIY09tOWw4V3BtWjNUU3FUL3UrL3NuSDErQ1NON1NUYkxtVzRPRjZLdzZJNkkz
        bzVSb2QrQVBBdktGSmFLbWxLVldSWVpDZ3BCUXV1NUJFOHZKNHlBVjNtdG1Odwpq
        ZkQzanNZWk8vaURHQS9UVmtRbHZlcjMvSWs2bFRYK29Qb3lBZ1JJQlJRCi0tLSBC
        RmtCQVlmZGpUSG41ZDRadU9GUERhU0FEbmpRZzNwSmkwK3RHZGkxR1dJChrb1xih
        BIpue+nItDZevkC/6TJrbeo8G9t8Lnle0CI2BYQLFD+UJo/RgPbu2tqGnIb8Dw4w
        Tjx0nZw8zc6iCdg=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-24T17:01:36Z"
  mac: ENC[AES256_GCM,data:2gL1Ei7tUXKQ6wn7kaQauy+WDsNh08WbPpnIvxnZdZwmWmL7OXH6jpVTbybr4lhZFmR/VosjLGf7c0Z3GjK7TGvf+pUxsOsZG3BrFkjFFFCXIsnOfj//fELBGCMmNbscrXbN7HgIz0NmVWCOwhcrHqUMIX7QlREfPfDlXpswO9U=,iv:D9TWl76hVOCCCjIf2SjSzomBf/oPL7hM+xbgFshNZgs=,tag:L2YkS0r70oN/XGBefE1GxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
