# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nfs-to-volsync-s3
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:aGPKea0hBH9Wa6upsHh34OYoNmy6YGTxaHqYlL3j7mmCHVOiEykevOYBxWr4QQysIGZ3tg==,iv:eFGCMypcP+2WkCu+kTqaR6w7CvCAxohkSS9WGMqLrqM=,tag:CEAUBhODrYpcx2XeyD3qOg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:HdoUfE/I0CVIWCTXUToGanN21DlvGZv+N9XK5xkrtYkpU2U7EaHC0TFsz+tg,iv:KXYOUTusCynTh1SiwoLW6y8EeM7bxOlXEkRi2kuqXUw=,tag:0XrLaQJyM7kaT4zM44dGlw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:FnOZ58kWKQqoKP8U4EZxZkmW2hadGj7I55ZICUhXpHE=,iv:Wco9SWAtSfNGka72ZH49hMIDjWsU6zhKRID3csl7P28=,tag:qHzC8WhbXdhzQzcP1th1oQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zKvjrdBSxfBGR5WPmREuZb250CI/qNqP6+7WRViZCJA=,iv:STBPeOlF0vJEiiJ/h5p5AUWnkTG21wJhq/9NiDHkZJ0=,tag:FsgHQId9PY4bjP54NZg0jQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEFKZlFWRGNy
        N1duSXU2UUpEQ3lvbTh0QldMb2gxOGdnRmVCZGp1SXAzWmVjZGN2V0U2M1UrWVlw
        QnFnYVk0a3IxZjljUE5IVDM0a0pidS9TVzgzYXF3ajlCTmVQQWpmQTFRdDdTMU5H
        dlpsYkdzOWorMVpsOEF5Y056S1VqRy9WNWJkKzE3a0MvTmZCQzk0Zm50bGpqWXdm
        bjVVY0kvMk5QWU4xZXk4KzBEK1EvME0xbklMaUhjSjIwa2MzSjg4UzFhRm5ncDAx
        MXdhU0lvcmM0WUVhcDhETi9NZ0NyWjB1Vnd3UTJNT2s5WjJBWmdCbmJwdVBCQzJo
        Q1VuYTJ6UWR5SzFDRTFlSzRvMEpkcFNva1RJRUd6OGRhaE9FSmJlMHZVVzhWK3RS
        WnIvM243enZCRkVCS1ZQalpuYXp6RUh0dXdiUDF4UXE5dTlrUGNUVC9UTjBPVkRJ
        NFk3Y2lQMTh0QUVVTW1iMGZxRWp1QWdINzZyb29OUGJrQXU4VGtlQlJ1dnVscVRx
        dU1HM3pCWDcvTDV2R0pVRGVDMVUzNHJaWDl3dVM4MGhHSk1uZVFrY205VHJWSFRC
        Q0NaeDgxb2VVSHRDRGZySmJqMW5XTTdEb0wyMkIyQmxQcjlTS0wwZzQwYitCckk0
        WnNia1dyS3ZVajlwMWEvUmpuU2g1WHVrQm1XcEg2QmxuSWdwSHJPL1JpNitnK0E0
        UGRQU2pLU21lV01MeUprOXhCdG5ZeSttbHNHWUQ4RUsySndhTUNqb0FqUXdCZGto
        N3plbjJSeE05TGdESnVlTGIrWER3YkxzZ0hETHUvZFlqYU42Wi95bEg4cVpBcGZr
        Snc5ellQYlVuMzRjcTBzcDhqWWE2WXN2SUh6R2dLWW56aGNkQVV4U0RXR1Z6MDNk
        dzlLbUZkUUptMW53ZFdVU3BkdEgrcVRseEpYak03K3Vvd3F2RkdHR2hyVUxTeHRv
        ZWdsZWlMNmFqb2dTT2FVVjc3Wk0vbEtTWGJ3M1pNTzBGYnZ5MDlLanYrTWphbXB3
        R0xGK2NORFhVVUVLbUppcnhtdkNkN2h5ZkNNb0swNFFkbVY1c0Fud0NmMEpQU01B
        RWJJSXFwbWhjTWVwblBmSi9ZRGpWQ3JjVm8rMklVQWFhVVJCcFVNdkR2TkRpN2l1
        K3ZUQlptMFRuWi9oOHhpSk1GRUZxeU5vNmF2dUhnVEcvNXA4ZWZVQ3JkSVg3REdK
        TFJTelh3Wjh6VGYycXpudEJEYTU2S0VLbHZ6Z0hKM1V4WE1xcXFZRWdtR0NYeStk
        TitYTGdFcVdRRkRrNFR2UjAwYXdRcDVRVlJPeFEvMnJIWDkxUWI5ejRDdFhDc2gz
        eVJRWEJFWWRaQkZQa1lrS1Z0RFQ4cTk2UUlMeGJGeUhySnZhMkdFSTJwUng4eFhl
        dFVub0NMVXlCNjIrWXpKSitibWVTV2N4eHJuNjlER1RIM2M1L29IM3crSEtjR3Ji
        OGptS1I0N0tTY3NqaHB2aTRUYkREL2pZcnBLbjhLYTZLMFRYSFI0blljU0c1RWNm
        QlRJM0prZCswb29CNVhKbkx1L0g2bkoxUFYyRis3U2Z6U1pGMGF2R0l0alRkS3di
        VUJoWU5KMTc4SHhkS3REWktrbjAxQnVLTCtOS21zRFRUWVhRMHI2WGd2L253dVpW
        UzVaVi9uaDFiL2VscWlZRXdCeFpRZmtBNlArbCt4ZGkzNzFkcUVBZGZvRFlzZkc3
        WTdkdkcwZHdvRDRUcFJpUUw3NVhjakhWSUVRbmdQaURWTFdVdHdKK2VSeXp0a0lV
        cHp4THZpdWd1dVdPazZObGhFWXJOWWpRQzdTWnNGNFZYbGVhRUg3Q0MzS1EzSXJJ
        RnRnTlVoVm1SSUJCRHpWeisybi9ycE9Na2c1ZnFSckV2ZWpLeTdFMytPQWZqVlBo
        OUdHcm9BRHlkN0VjR0NFOEJxQmNTdlZlbUdnNUdqNnNpRWhlN09GZ3VzZkpXUQp4
        dUdUMVpZM3lxVG9lbVB1UkhCM0VPVnBaTHJCcVpxbkwrR0NwdktXY2pBCi0tLSAw
        Ni82eW5ZZmdzMmFqdlJ6ZDVyREp6eWZ1YkJYOXlvSy9sT1dnM0hYdCtvCk04xkqb
        Yy5R1leEqppkQuVrUx7TQ6d+nZA1uR/Jg2FQ0aL75xJD24YBYxYEYwenoCpUzdMU
        0K7JtAi4H1MpIIk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:VyU4mdttRXRnjJIbEMZQF3OXLQUxQpA/j2h+EM83ZJ//zU8Szxz24vjSE0Numv0mpsSXgVM5ZmkdivjhRi3/+0gDKOvxXcTTd5MdyXsozxgnbL+HzPGkwn4q51NdXQEQeKkU6y4DkP3YsnrK2h2TJU20cwrhXbiqq8ZtmWV8PSY=,iv:bpz1wRcBIEhSH6eIHvw9pVzina7V/H0rmI2RjD//D5M=,tag:ZLMFn1wviAXPkhII9mYueQ==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
