# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nfs-to-volsync-s3
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:kNa2v4E1p8/nNZM29gzexWQJIIxajZdDcVYCQOq49W/lfz5c2gDJb4Y6VwPnyLaglUmnFg==,iv:eFGCMypcP+2WkCu+kTqaR6w7CvCAxohkSS9WGMqLrqM=,tag:7ofl/HxkusCAwyJf7oX4Sw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:PWZRjwpO+xm6J8FWib/X97SFOSTRQNR715sRp+9xgAnSDKK3adH2QSPgZE3G,iv:KXYOUTusCynTh1SiwoLW6y8EeM7bxOlXEkRi2kuqXUw=,tag:2x8e+BTJrdpvsSpYahVoEQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:o+ClJrTySyI7YGxfH8vO/QECoLABZvg8iX/Ki7Am2oA=,iv:Wco9SWAtSfNGka72ZH49hMIDjWsU6zhKRID3csl7P28=,tag:0RhjOP2tQzxXIedD3Wottw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:r06FTYukXPl0EOAAhdSotULzOpRuZwBKAy7jq/D2sic=,iv:STBPeOlF0vJEiiJ/h5p5AUWnkTG21wJhq/9NiDHkZJ0=,tag:uzsaRuZ9EGW/lq2DacABjA==,type:str]
sops:
  age:
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5ICtpaVFLN2l6
        SWl1Q3FsY0ZiZU9jKzVyQXMzWGRSeXZXaENWSDN3MFFSRkVRNTRLZy9HUHlLcWU2
        aytabWJzaXJ3bGxlUUVNZzhGeDdxbllqaWNYUzBYV1RLU1NvSDVWTTVMTkdjd2l1
        aFpLMkM3dnFRbkYxVzAveEpYZVFVWlpGdy8wY0pjK3lNU0xzRnV5VTJ6d0crdUdH
        M1FBTG9TSHhYNGdRVkd5WnA5bnVsRFlyZXFFc0JBbWpjaFZyZmVwcnpMc0VSVTY5
        eDRDbmRxS0FaYzMwR1JtazBhMWhzZndlbFJLNHVNdVpwR2l4M05XcCtxaVF1QndY
        MHJnY1NUMjR2OEVwYUdHM2xYakN3dkpZc1pGcFJWLzR3dGJUeWpLWUd6YXRUMHRm
        Z0FyazRkS2M4V0pOZHgySjNzRGgzMm5CcjFiZkdmLzFCM202akFISzNUU2tNamRy
        QldRNVpFaWtsZGFpdzdBczJEWEZoRHQ0SFR2bzZ1cG5KQ29lT1hwTXR2K1E1ZlNH
        ZVEwUExsTG1yNXBlRDBiV1lxWXdWUld2R1cvY3hJU1RsMGFSSjdOMVZQMjFRdUxZ
        WUhDbWZZcVN0V1RyZmJrWWlIamVmNWVNWHJXWEx6cTdHSk9FNzVnUkxQbW96UzFT
        UkZBWWdxQVJUb2NHRTJUZ0twTU15N245MFgxMkxBTElOejdmelZHN3hvdDlmVHhH
        eFZIblhSbTEzR0xHRUR6eXpEWjhybWh1MkFYbm1hZkxOWGlXS2pZa2tjdVVWRGtR
        VFBGcVByUXJpNE04R2pXTkMxREJKRExySDhhNnFrM1NlVnRBWHR6YkNJWVpjSE1v
        cDQwelE3cVYrbnVNNjRiWm5laXdzTnpFWW5ZeVAwK2xvQStmU2pyditESlEza0Ro
        WFc0b3Q0QUFuR3hITGM4Vy9ydjcvMGZkZlM4SzRaYzU4NXE2cTVBYzVkSmFFSFlK
        Zk5NVktpUGxWVUdwNkY1UFlxTm5ubU94aWo0a2Rsc1gzSEhtcFYrK3VCVmJJY1Zj
        OEpEMTYxNGNsUHdWbTdSdTBhcWM0U0o4WWNFYmJnMFFuc3lkZWFnQ3BKUk5iVDRF
        aUJQNGgzVTBUOG5ZMVBxcFhSbzdEVlVsL0xMdkdESDVTODc2eGhWaGJTTUxDaDNL
        UFhHdFFEb24vbS9DdDdZZXdGZ095d1BMN3g1U0xMWmtsT1hsanU3VkRySEREenFB
        bGNyZFYzZW1QSVprMklrWmtxTU5DSlJXck1jeGRBUmUrZEFaNFhOOFgxclllTzND
        NE9ZYWRYWXJ3YUJpV1NnY0hHZlRFcTZ4YklLTUVDZlNyRll6dlBuK2Y1QVNqdndK
        SEdvVjRpWmFFYW1TODZIZHpXNHUvNzdPYko3bkR2Wk56YTFpakdaK1psTkdUSmMx
        WFRDc05XSURvRW5JZ1BtaUlaRi9YZk5QbmhCQURkdWkvQXV2LzdXSVlnQWlZbUd0
        TDdxUnJFZ016NldReTBmaUxwQTBlaEVIYkRMYTUyUzI3OGRZSXU1Wng4bSszK1VJ
        SjRwL0JPa2l3V0RrZVVhRm9vV0lWSVdObUQwcjhWbWJUbEtSQitkUHNsTURNU1F5
        bU9CajFuZkdJSmhWTFZoYkZZaWhQdWI0LzFnWDJ6Rmo4NWVCd2ZlbmpVVktYODBH
        azhDeDNSYWRHbkxWUDlvM09ITzRSTEZCSFBWU096MFRFZmd6dXB5ZUxVR3VQc016
        QTZ5dU9QelIwclg5M2dBVllxWkU1RVdTWkt5c1dpeElIUmplM2Rad2JBT0VMb0RE
        T1lJODZ2UURxWCtrNHJoN3o2WndRN2d5OTEzZDBaOXMwNldPY08rdUFicmxybHhK
        Y0RYRjE1RkpvU1JWc1VPU2pidngyUXBHcEpPbTh0UnZpbkpPaVFtMWZwRWI3Rzli
        TFFlNmVLSDhYVmR1N2o3bUVGNDlvTk90Q3MwMk5saERNTnNpMDBJdUtkdzFkQQpD
        cWpCb0R4NXFZajdtcDZPVzhTbnBlbTNOdjgvOGJRNVVZZTRzRXNZYjIwCi0tLSA1
        dU1jVzFHb1VtVFd4UzhnNEZYYzZvUVBDR3MvWTd2WklzYkVWaGwxWjRBCvTD1c4O
        x3h21LmBQUmGkpByBx2tktxZ+00rFW8oB/FuNtrZMIhXu4y7rst2WDJOj36661b8
        4WCxIsU71oCiYU0=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T00:01:26Z"
  mac: ENC[AES256_GCM,data:lE4YwUcnCXVCKln4IZDfMUrqLhM4MX8h3/49UNU0fbOW2HC4L2dhsDGMpgs2D5dJy4DKxU1dnFlY/c9NzpCag04bwX+hJRA/59ESInyQXo8U6keeTKoJoLONd0njgxFSwkxankNC+j/Cdm+0iL0Ld4yHC8sJlK29dJw4n8OCd94=,iv:2LtMx4krHAa5AvhSpe4SoUsQmskDcf2+7aefFudvUR8=,tag:FXgp5sjIYbKH32Y4kzGKzg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
