---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8s-gateway-freek
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.7.4
    digest: sha256:ef9021e3fddb451ed6c3bbddeb0d8cedc6b47030b01292d240db4af78a8afb66
  url: oci://codeberg.org/k8s-gateway/charts/k8s-gateway
