# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: versity-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: database
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: database
type: Opaque
stringData:
  ROOT_ACCESS_KEY_ID: ENC[AES256_GCM,data:vW+7siT18oLm0XiaJS8UwxM7JWnluw==,iv:RJxoag72GrFOoYqWvEW0xpoRMJYF/qMCztZpSGwzcCM=,tag:meI/Ao+GDXMD7wUvvl7spA==,type:str]
  ROOT_SECRET_KEY: ENC[AES256_GCM,data:iGI8gcpMuu7IDGy5ooh/Oy5oaeLwd+6iCGupTLSM27vsyBjOf6KoZ+MdGRetP/JJ,iv:2w3knCFeVIA3ENFY7IvkRQymYo2lYNKx0dm6rzFjAUk=,tag:xOXN5BYANdSiAtn+sEHTYQ==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidkNuSFVVTDBRekdYVm90
        SURkS1RpVHlianFlcHovTmlEYy9kaTM0ZmpvCnVJWTVrVXpSYjFpajdUbHJ0YzFF
        aThNaEFuMWQvRk1RSjR1WTVCVkNhMTQKLS0tIFFyMFZDdExqN1ZwR0wxTHJ0b2VU
        L0FGeU1lSUw2d0lHMGU1VG93aFlwK0UK5qmk3livJkstYXIn4qeBzk6qc1R29xGb
        aYbu5vs1KDtHYbtrRJ5XEwkwvpPwYCVZvOmf3v4bLLSvhOEBG3NiRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-22T20:21:02Z"
  mac: ENC[AES256_GCM,data:B4wbcoBanxwg90W1UIrxUYl4Cr17yKFm3I7j38dRmXsLRBQ3PGrqPMt0hVK2V7q8KwH5K+r651H833Dp8P2E70w4sdWULk9/EAuzKAXh9QoXz6iKViJLGQXQLHMxOw+oytlMHdbOpkM29vMWJ5fXSHacn3x6reIB6nSK8Sb+vA8=,iv:D8zKeb7EQu/CLakvsK4zKJuHO7jIitbwegiJlBqdofM=,tag:WTt4ImkWIoxkOIYXgH4J1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
