---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app alertmanager
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      *app :
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          *app :
            image:
              repository: quay.io/prometheus/alertmanager
              tag: v0.28.1@sha256:27c475db5fb156cab31d5c18a4251ac7ed567746a2483ff264516437a39b15ba
            ports:
              - name: http
                containerPort: 9093
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              limits:
                memory: 100M
              requests:
                cpu: 15m

    service:
      *app :
        ports:
          http:
            port: 9093

    ingress:
      *app :
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${CLUSTER_DOMAIN}"
        hosts:
          - host: "alertmanager.${CLUSTER_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: *app
                  port: *port
    # persistence:
    #   config:
    #     type: configMap
    #     name: alertmanager-configmap
    #     globalMounts:
    #       - path: /etc/alertmanager
    #
    #   secrets:
    #     type: secret
    #     name: alertmanager
    #     globalMounts:
    #       - path: /etc/secrets
