apiVersion: v1
kind: Secret
metadata:
  name: continuwuity
type: Opaque
stringData:
  CONDUWUIT_REGISTRATION_TOKEN: ENC[AES256_GCM,data:bIj0+gg/mFreG4WSK2Q4N43/gUgRHqBYdh8S7GOULmN4uehsRzBHGQjq,iv:bDR54NQECHIftKRhgmfKXUqOHfbukNAibhvxBXdE4mE=,tag:p4jwAuZHPHS1nS/y1/2Kig==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdExxMGpGR1Y0VTAxT0hZ
        RlNiRkt6QkFFRE4vMU5JWWJqak1GblJrcHhBCjdxdDBVQW85emNGMDM1VndLUTZV
        OC9rRHhVelRCT0RwNWZNTWNPZDBVTkEKLS0tIEFiZWpWSC8rTVRWV1JzSVlSYUdB
        T2d3TnpqM3B0bEM1V290YURaaUFhTFEKdZCt2RbvUOHcm1/YtVxZyWYzW3NzftjI
        TWk3nn/HGGPqipJmrOSnxki36082kITrSbb+LrICyfZ8oENl67QZ7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-17T12:06:11Z"
  mac: ENC[AES256_GCM,data:iGcbJv7evP+ccWsezSRkJqG7L7szYfc3l9jBeqIqBsVnk3lpwvfk29g+fYoojUCXvAwGsdQgzoVMTbp+dAXA+8Cq1tFlInKEehvtNmOssyy1Hgvs/ZVFqgwt4SWq4aejgFIUJedO4Xf6gmr06GF3adYVBxxQEomUeycUk6ijGQ8=,iv:8dlRA6BSB16nxv1//X5kpwgwvVf8C64fnxVCmAwD5eM=,tag:Ma1RL2cmwCbknXV0w4RSsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
