identity_providers:
  oidc:
    clients:
      - client_id: |-
          {{- fileContent "/secrets/clients/gotosocial.client-id" | nindent 10 }}
        client_name: GoToSocial (Mastodon-compatible Fediverse server)
        client_secret: |-
          {{- fileContent "/secrets/clients/gotosocial.client-secret-digest" | nindent 10 }}
        redirect_uris: ["https://gts.kubes.cloud/auth/callback"]
        scopes: [openid, profile, groups, email]
        claims_policy: gotosocial

    claims_policies:
      gotosocial:
        id_token: ["preferred_username", "email", "email_verified", "groups"]
