---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/operator.victoriametrics.com/vmalert_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert
spec:
  datasource:
    url: http://vm-local.observability.svc:8429
  evaluationInterval: 1m
  externalLabels:
    cluster: main
  extraArgs:
    external.url: "https://vm-local.${CLUSTER_DOMAIN}"
  notifiers:
    - url: http://alertmanager-operated.observability.svc:9093
  remoteRead:
    url: http://vm-local.observability.svc:8429
  remoteWrite:
    url: http://vm-local.observability.svc:8429
  replicaCount: 1
  selectAllByDefault: true
  useDefaultResources: false
  useStrictSecurity: true
