---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/operator.victoriametrics.com/vmsingle_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vm-local
spec:
  extraArgs:
    maxLabelsPerTimeseries: "40"
    search.maxUniqueTimeseries: "600000"
    search.minStalenessInterval: 5m
    storageDataPath: &path /vmdata
    vmalert.proxyURL: http://vmalert.observability.svc:8080
    dedup.minScrapeInterval: 60s
  replicaCount: 1
  retentionPeriod: "2w"
  volumes:
    - name: &vol vmhostpath-data
      emptyDir:
        sizeLimit: 5Gi
  volumeMounts:
    - name: *vol
      mountPath: *path
  terminationGracePeriodSeconds: 60
  useDefaultResources: false
  useStrictSecurity: true
  resources:
    limits:
      memory: 2Gi
      cpu: 1
    requests:
      cpu: 100m
