---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: &app authelia
spec:
  name: *app
  owner: *app
  cluster:
    name: cluster-shared
  extensions: []
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: &app lldap
spec:
  name: *app
  owner: *app
  cluster:
    name: cluster-shared
  extensions: []
