apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-shared
spec:
  managed:
    roles:
      - connectionLimit: -1
        ensure: present
        inherit: true
        name: authelia
        login: true
        passwordSecret:
          name: authelia-pg-secret
      - connectionLimit: -1
        ensure: present
        inherit: true
        name: lldap
        login: true
        passwordSecret:
          name: lldap-pg-secret
