# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: authelia-pg-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: auth
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: auth
stringData:
  AUTHELIA_STORAGE_POSTGRES_DATABASE: ENC[AES256_GCM,data:L4pmnHwPnEU=,iv:Qr51WoJmfcoYqDzb/GoJiwS7bIyl8R0HlNkHBSqLtro=,tag:8nc2oG7Vj5dJbfkRICWIYA==,type:str]
  AUTHELIA_STORAGE_POSTGRES_ADDRESS: ENC[AES256_GCM,data:0GJFHfsXFw6jHNCriydCzwCE11IvQoA6yPDbz1OLJK6xfWHZAlkRrbJf6Tw=,iv:3PKc9a6K2wYALL1Noe9gU4eD3pgKn8FMgSy1DUXZyl4=,tag:RCS9VjhQhEgDHm+rHnFrkQ==,type:str]
  AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:6EJdBpiobQM=,iv:Uv0lHsUNGuANwZ16MuDf59ja/bF9MMlWLNIrjLHNQsQ=,tag:ewAClzpbyFjcJrYpB1kLnw==,type:str]
  AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:DSRRvpgtcZOYqksran+kz/yz75QBNFu/AgM3MpJD1NQ+bruiSQQzAfbT,iv:Dsaowh2xI9yvSn046MkSoAXrLH3j2dSFCg6QNULtB14=,tag:Io3e65eI2PgoKHPt0LSO4g==,type:str]
  username: ENC[AES256_GCM,data:G+gZSQeFiqE=,iv:rcA17gMXZyPnjczvpu3s1FHGTjvasKA/6FQfrDlG9VE=,tag:s/weiP/r03ZgR2iUzASkVA==,type:str]
  password: ENC[AES256_GCM,data:CpP6n68v1fuh5IkKPuTYfF0zHOnZVDn3EcqfTMttT2aVusF3+tiAoa/U,iv:R32Si5WVvvNFKtUbuAZNZ4ZJ3EEI8PKEnWlNwpnHSig=,tag:RpSJIzoL6hf8t2YdGzQebg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFBBYVhyRThk
        T2NvTXpuTnVBUWtxMUhpU01ScFF2c25KNFF1d1pUbzIrYzFPL1UybFkzaXM5Q21W
        M2hhRG1FYzRYVTViYjR0Z3BDMGYzdEs0VnAxaWVLSWFIUEJxVU91aTR2RlV5cVFt
        b2NEQkROL1B5VUtWdjE3ZGxSUTBldExweDBYVzBjY0EwaWNFcnpXNUNpS0ZmWlNw
        TjkxNmY1eEZjeXNwZXl2QndDdkFFNzBRdHZsUjRJOFlkYVNFSjhCSFU5dDA2bk8w
        dFpBNVpKZTRtZkhOT2xjci9xZ3cvTW40YUs5M3VkdlYyUjZMRjNhYVl2T2tubUVk
        TU9UM0U4Qm9xcU9ObEJ6WkEvbkV5ZjdDVEI3eFpNekVKTVoyZG5sVE42WnY2dXFM
        SG5VQkZzODk2TG1FYjFDM3pnMytUWG4wZzNyUnpZRDZQMHU5YkxJVFRHMlA1WHhy
        cmJTTEIvWUcyWHAwcFJSVlNSYi8yN2dUZEY2QVgreldPWXhONU9hbkxZZjQ3RUxG
        QktmeDBram1CSVhiejkwTFFVMkcvZE1qWC9uOHFOL3F2bkxiQzdaUTJZUG4vNFdM
        UXNzK2liREVsTnF4V0orMjZXZ0FDeEhLbzEyRk4rRXl6VC9CRU12aHlDcFVzWFZu
        WEMrTExHT0lJNTI5a2lNM0xUL216M2wxNGpUbHZhQTZkR0l4OUh1dmgrdzUvN1lx
        ZHdkZkp2WjE5ekJaeXdtbzdMZ1Uxemt0di9UL2VGV2NzWUpnSkg2SUtBMGQ0UnV2
        UGJXd1FBeEgweG4ybVdEdGlUVTFRRFVsazJhSE1HRE9Fd2dNNTM1K2NkeU9qc0x0
        Qms0aVhxVXNmc2p0eWI2bDNzcGcrT0kvUUNnV0xrMzJod05YQWNQakxoVHFFT0FS
        aDN1cnlkeGszSzkzSFE4ZGxuMmVtNjhuOWJlUlZKaWJ6TW13US92ZW9xNGRJN04r
        emtHaitMcm9maTI1TWt2NTRDai8xcFVON3JPKzBSRmdXLzh5Q29sdTlTOGs0YXFy
        amh5K3BSMjdzVlNOVE13eHJoTEpNODZWRjQyYzVqK05rN0FrZ01XTjNtVHhNaEJJ
        ZkQ5YkJ4QnU3MXBTN1RKSFlnWTZCWmpxMnhqakQxRFc1YVFjQ0hUUHdCMEkrT01C
        QmN4eHdRdHJRRkRhSzlTU1lhL3puWnRWeTFzNjNncmMwL1h0ZE12QTFoWFRxZmEy
        NXhzYUVoblVXbzhvRWQ4eHg4UUdyenFkM3RLa1llWjlnQlo5ZXFFa0FYbGpBYysw
        UWc2N2NFYVRLTkFYUmprdWR4OS93TWhhdDFkdVV4QncwY3pNSGVwQzZWZGlBTTJz
        RjcyYVNXdWVWTmdlRGZjSTB2aVBmZmE4ak5sWmRLRzlRRmRJKzBPeTlpenV1bjNI
        V0JzNGY3czlRWk15aERzTG04cnRvLytRcEdFMFRBV3g2UWlQUXJXc2FjN3RnSXBP
        cTZSdTJMRUJVMmFmSzNNRnI2bGUvT2toNTBZbGlINjhRaldYaDBkS0VLNk9abDhT
        MHhkL04zSnBUdk44WEtJZmVEaWh2UjQ1S1ZlMFIxeCtWUDdsMm9nNU8wVk83OURE
        WmMyZTBNbTR0Q2xoNEwxdFlEQm9yaHJEcUNjVis5bzI5V1cwUGV6clpza2Y2UDkx
        djc2aS9tZzJtREhoSkJFeG5QaUo1VERObDR1ZGwzbkR3WHd4V0FCYThCNkFFVTJn
        RU85MW4zQ0JieFBOYTNVb0JOSlJjYThRSTZHU0RnbXhxNVcwckRFZ28rWG9sYU9C
        M1dRT0c4RU1sSnJrMFJocG5rQkZTZ2c3YkRRaXl2bGpjb29XcHNuTDZ6RU4vaWtD
        dTVaYm1Nd2FpUFpYaitmcExoOStaalpldFRqWFg4YUU3YWFQNElNRmN3T2NtRXBG
        bkVERmZqNlZuSVJocUFZR1k4ekVpdFd0cUQ3V3E5QTlzSDdVVDBzWXVHTFZBdwpR
        Q3pLQzA4WE5NN1pNU3NsMHJWSzQ4MGIwTE9LcytuZTExUVBvYTNMM0dRCi0tLSBK
        Q0JGTkZrSE85M05hMXpQS2lpa0lINGZpMHBlN0pJNFVTWDRjdkZlY0FrCn7K2WKb
        NLXjHzeR6dFTU5mVPig2JbTiR9w8WXLc6Vf6p+cxKuB32j3r95jdWawtlGInKbvO
        3TXGuVgX6dQ1i9o=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:7vr/L9WWj+wZ1gIk+EobA6AggaUcMj/MzMpg2MnEcKHI4E/0JoaNTQWOKWj29+08tzh0rNZA6f7N3Y1hfQ+vXQxnIzmuyR5CX3HjYag9XdtgnD1BOtuvYFyWk/K+emyIC1yHeegzh8yruQVGfeKD9hzUwJ2Y1j/10rc1P/39VNg=,iv:jfrVsvH9FD0RpVzdX2VaE3wUBiUpM+Xuec6uaibGFEQ=,tag:V2z0CpRmovOA+5YFPoKHnA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: lldap-pg-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: auth
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: auth
stringData:
  username: ENC[AES256_GCM,data:Erbctyo=,iv:K97PIt79KDFi3lus30hdcNylMtH411NjLLFK7ClM/64=,tag:gtmkkKMtKe/+p9wP40p8wA==,type:str]
  password: ENC[AES256_GCM,data:10tc1/4GpRq898xmxjLRR5CUZK9ch1Urcc0BoeoNXhE=,iv:agkW0419EY9L3r1otPqXgeFnwsJnZf0Bdhtlj71sXyY=,tag:SfvKyNlZNXV7fM/x0Uw3KQ==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:Pk4RJZ5TZ22x4jL9PlKBydKRT0h1ypQGCzd8bTwdrv3EOFxncWRaEspTIu/7d/jb0pUYtq5yp3CtrWVKq22agXMwRyeTzPrv3iy9quaa4RDZ5ChzE7UfsZd/YY68Lx3XUltnbg==,iv:gVk3yKbbRcR830PAPEI4OLtOZGaObhEgAMu9aj4xUs0=,tag:3/RLleaVqWoZHPoS0baB6Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFBBYVhyRThk
        T2NvTXpuTnVBUWtxMUhpU01ScFF2c25KNFF1d1pUbzIrYzFPL1UybFkzaXM5Q21W
        M2hhRG1FYzRYVTViYjR0Z3BDMGYzdEs0VnAxaWVLSWFIUEJxVU91aTR2RlV5cVFt
        b2NEQkROL1B5VUtWdjE3ZGxSUTBldExweDBYVzBjY0EwaWNFcnpXNUNpS0ZmWlNw
        TjkxNmY1eEZjeXNwZXl2QndDdkFFNzBRdHZsUjRJOFlkYVNFSjhCSFU5dDA2bk8w
        dFpBNVpKZTRtZkhOT2xjci9xZ3cvTW40YUs5M3VkdlYyUjZMRjNhYVl2T2tubUVk
        TU9UM0U4Qm9xcU9ObEJ6WkEvbkV5ZjdDVEI3eFpNekVKTVoyZG5sVE42WnY2dXFM
        SG5VQkZzODk2TG1FYjFDM3pnMytUWG4wZzNyUnpZRDZQMHU5YkxJVFRHMlA1WHhy
        cmJTTEIvWUcyWHAwcFJSVlNSYi8yN2dUZEY2QVgreldPWXhONU9hbkxZZjQ3RUxG
        QktmeDBram1CSVhiejkwTFFVMkcvZE1qWC9uOHFOL3F2bkxiQzdaUTJZUG4vNFdM
        UXNzK2liREVsTnF4V0orMjZXZ0FDeEhLbzEyRk4rRXl6VC9CRU12aHlDcFVzWFZu
        WEMrTExHT0lJNTI5a2lNM0xUL216M2wxNGpUbHZhQTZkR0l4OUh1dmgrdzUvN1lx
        ZHdkZkp2WjE5ekJaeXdtbzdMZ1Uxemt0di9UL2VGV2NzWUpnSkg2SUtBMGQ0UnV2
        UGJXd1FBeEgweG4ybVdEdGlUVTFRRFVsazJhSE1HRE9Fd2dNNTM1K2NkeU9qc0x0
        Qms0aVhxVXNmc2p0eWI2bDNzcGcrT0kvUUNnV0xrMzJod05YQWNQakxoVHFFT0FS
        aDN1cnlkeGszSzkzSFE4ZGxuMmVtNjhuOWJlUlZKaWJ6TW13US92ZW9xNGRJN04r
        emtHaitMcm9maTI1TWt2NTRDai8xcFVON3JPKzBSRmdXLzh5Q29sdTlTOGs0YXFy
        amh5K3BSMjdzVlNOVE13eHJoTEpNODZWRjQyYzVqK05rN0FrZ01XTjNtVHhNaEJJ
        ZkQ5YkJ4QnU3MXBTN1RKSFlnWTZCWmpxMnhqakQxRFc1YVFjQ0hUUHdCMEkrT01C
        QmN4eHdRdHJRRkRhSzlTU1lhL3puWnRWeTFzNjNncmMwL1h0ZE12QTFoWFRxZmEy
        NXhzYUVoblVXbzhvRWQ4eHg4UUdyenFkM3RLa1llWjlnQlo5ZXFFa0FYbGpBYysw
        UWc2N2NFYVRLTkFYUmprdWR4OS93TWhhdDFkdVV4QncwY3pNSGVwQzZWZGlBTTJz
        RjcyYVNXdWVWTmdlRGZjSTB2aVBmZmE4ak5sWmRLRzlRRmRJKzBPeTlpenV1bjNI
        V0JzNGY3czlRWk15aERzTG04cnRvLytRcEdFMFRBV3g2UWlQUXJXc2FjN3RnSXBP
        cTZSdTJMRUJVMmFmSzNNRnI2bGUvT2toNTBZbGlINjhRaldYaDBkS0VLNk9abDhT
        MHhkL04zSnBUdk44WEtJZmVEaWh2UjQ1S1ZlMFIxeCtWUDdsMm9nNU8wVk83OURE
        WmMyZTBNbTR0Q2xoNEwxdFlEQm9yaHJEcUNjVis5bzI5V1cwUGV6clpza2Y2UDkx
        djc2aS9tZzJtREhoSkJFeG5QaUo1VERObDR1ZGwzbkR3WHd4V0FCYThCNkFFVTJn
        RU85MW4zQ0JieFBOYTNVb0JOSlJjYThRSTZHU0RnbXhxNVcwckRFZ28rWG9sYU9C
        M1dRT0c4RU1sSnJrMFJocG5rQkZTZ2c3YkRRaXl2bGpjb29XcHNuTDZ6RU4vaWtD
        dTVaYm1Nd2FpUFpYaitmcExoOStaalpldFRqWFg4YUU3YWFQNElNRmN3T2NtRXBG
        bkVERmZqNlZuSVJocUFZR1k4ekVpdFd0cUQ3V3E5QTlzSDdVVDBzWXVHTFZBdwpR
        Q3pLQzA4WE5NN1pNU3NsMHJWSzQ4MGIwTE9LcytuZTExUVBvYTNMM0dRCi0tLSBK
        Q0JGTkZrSE85M05hMXpQS2lpa0lINGZpMHBlN0pJNFVTWDRjdkZlY0FrCn7K2WKb
        NLXjHzeR6dFTU5mVPig2JbTiR9w8WXLc6Vf6p+cxKuB32j3r95jdWawtlGInKbvO
        3TXGuVgX6dQ1i9o=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:7vr/L9WWj+wZ1gIk+EobA6AggaUcMj/MzMpg2MnEcKHI4E/0JoaNTQWOKWj29+08tzh0rNZA6f7N3Y1hfQ+vXQxnIzmuyR5CX3HjYag9XdtgnD1BOtuvYFyWk/K+emyIC1yHeegzh8yruQVGfeKD9hzUwJ2Y1j/10rc1P/39VNg=,iv:jfrVsvH9FD0RpVzdX2VaE3wUBiUpM+Xuec6uaibGFEQ=,tag:V2z0CpRmovOA+5YFPoKHnA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
