# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: authelia-pg-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: auth
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: auth
stringData:
  AUTHELIA_STORAGE_POSTGRES_DATABASE: ENC[AES256_GCM,data:26KDokHYZQ8=,iv:Qr51WoJmfcoYqDzb/GoJiwS7bIyl8R0HlNkHBSqLtro=,tag:By0x45TMLX2cLLzfD+MCWA==,type:str]
  AUTHELIA_STORAGE_POSTGRES_ADDRESS: ENC[AES256_GCM,data:9vYj9G1M0tGr30elJycnXstw7v0S0peQwiHDrshsr5jmKKX/bpFQ5x6W3tE=,iv:3PKc9a6K2wYALL1Noe9gU4eD3pgKn8FMgSy1DUXZyl4=,tag:lMbgOpbqs+Zo1Edg6nrEMA==,type:str]
  AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:BpGaeqEGJlc=,iv:Uv0lHsUNGuANwZ16MuDf59ja/bF9MMlWLNIrjLHNQsQ=,tag:uUB9qH+Wc3nDMKfAlwU2qA==,type:str]
  AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:qDduKDJKXtaHhLu8unNlkidjU8bNOXjJX5iJPbfQb+oH4YwsUVy+/tvH,iv:Dsaowh2xI9yvSn046MkSoAXrLH3j2dSFCg6QNULtB14=,tag:+eUSXhgRuUI0KjFms/j5wQ==,type:str]
  username: ENC[AES256_GCM,data:iY0zveFK4Ew=,iv:rcA17gMXZyPnjczvpu3s1FHGTjvasKA/6FQfrDlG9VE=,tag:rj5j1kqQlpzxtphRmGgrKQ==,type:str]
  password: ENC[AES256_GCM,data:wbaELCK8kPcg1kJ2lVl6QzUnZTBmlD+8wHfFFUPlg0jqfNfcrmZCXmrH,iv:R32Si5WVvvNFKtUbuAZNZ4ZJ3EEI8PKEnWlNwpnHSig=,tag:OY+/7OISFDohV6GNSQjYFQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCamFWTTBZTjh4RlZhSlhN
        VlFiNjRPUzQycGdzdDF4L3hxOEpWclI3blhFCmJ0azB4MkpEbVRDdWpwcTl6UVpW
        bStWZmhvTlc1MmhTa2tnRHBjcXhjYncKLS0tIGhvRmM1eVVXMW14NlVXTUN5YUNj
        UUNKVlZVQ2dvSUNHSnFsUjEwUjlYSG8KU5u9AzHlb/xPAJAJh0MDNvbOF7uEkGm6
        ClrLovzJ6U4gPGlCqpKJ/sg+AaXKP+O0yk/AH+45ErTM75MQuf6mvQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGpodkZMQ0dK
        Z05nN2FzVmNiaEFRTXBZa0ZMSXVPK2F2a1BscDU3cXdPVmxXa0pwNGEyNC9Rb1dv
        ZWJzNG5GTFIyYlZKd0VUN0ZxQlB1eExPU0ZsU0VGdnB3WHlTcDFPd3Z1VkNBRG9G
        eExIWFYzcW5RZHA1c1JSaS9lTk54UG9oMzRQKzJYK3poNW1iQk85Tlc3NFd1Y2hU
        Z1N0QVRqQ0NOVXJSNWgrelVYNXl2VmMrbFp0N0kxUU40bFJaL2cyd2pvaGF1Q0NT
        ZFhma1dCbWp4dUlsYXR6OURGL2VocjlCTUtkTkNWWnJySTlhbUZSUmkvdXc2U21k
        MDRFZ2tTOHRwRzNRb2VGWnJyY2s1dndubi9JamZqbkFObytBMGJmZmFRMWtwTEY4
        WmtmTjRoYUVoNTlVd2F3WXRVcWxRKzRndjRCczByblZEU1NKNURvZ3lTQ0VSNmdB
        M2xWRG80aGhXdHl4SjJHdS9Hb2tRaWg5UTlXTTZLS3VaUkFjRHkrZnNRaVVtOVVV
        Z2lxVXNFOEFWazRWVVFHVCt0bkk1NkpQQm9nY2RwY00zN1ozQUZyVmxIZnJ3S3Zj
        SUtVbUsrOGxiYlRIdFlhelYzdDJUZE9LaEs5N3dFRVQ5WlpTdVY4MnRaSld2ckZ2
        SmRZcGFSek43VXM2ckRoK2VadlNCWVJxdmR1ejM4d0V1L3l3YjhPL2YrVlczTnFV
        NlFkbVR6S08weEJEd3BDWEhQT0NGcS9nVi9oYzlLTFg3T2FtN1dKdVBhRk5zR3Qy
        OXNxcTBhdDQ5YUY0QkllOUE2c1p2d09IK0dXQTJCQ2MwbXJCSXlnYnNGeklyRisz
        eW1ZRDBXc0R4T3c0S1cxNzREalg3b0RHZTNFVEFoL1JjRncyc3JIZlpxdE9DOUNw
        MEdpRjNlQS9NeFhZLzh2WWE4YnhwZmEvWWxneXFTM0pPSm5zNDRnWGpVcDZpL3Q3
        RDVUOGFHRjk0T1JSREhoL1JEY0NPZ3JJQXF4dUR3a3M1bTdQWWpIRGpCcVZsYnls
        YkRnL1BKUDdBb3g0ZXJYVnhUbmd6K3pJYm03cVUvc2UrdSsrNlRiLy9WWFo2b1Uz
        K2RIOGIvTGoxNlh2STFRSTJpY2MyaDhvZzNHNzhTTktuRUplbGViWjA4YkM1UjJK
        T2JZUC9JVGlZQTVuMEhTWmtXY3Y4NkhDaHh1aklscVlMTC9vb0ludjdQSGxWSXIv
        L3k3eHVEWVY5bDZra0FDaWNNUmZwbFdWS3RLWmUzRnl3cDhOcnZGN2N6cHptTys3
        Y2RsVjU2ZTV6UTdCU2I5SHRsM1BxUnYzK3RUMEhjMmVVUEE3YWxsdmh0TlAxeXBB
        djJBd3ZWU1cxT25pOWkzREZ6U0tFcXRyRWgwQ01qZ01vZkR6WFlWQklmeHE4UmZY
        ckxYMDh3Z3cyQVVrTlhQNkJqUHhMT1IzV0N2U3k0YVc2VTYrTEVKeWMvK25VZklS
        VFhTTnJ2c0RLVDAwdFFoSTN0eWZPVDRyVFJMamN4WVR5RHhjRURHL3lub3JkenlF
        djRDdHd0T1hoSFRiamI3VUF3dktnWDJQeDJHTHdvUG90T3lWV0RKSlV2MEc5WTM4
        ZGROS1dMZHhTYkZCYktUZGtLbGZjakxjLzNTeVlZN0NVV0hoQUVRVHk2emxVQ1ps
        akRVdENqTHB5eDA3SlhaeWZPL0Qxd0dVeW9mNGpzb0JPS2ZIcWhRNFVqdzljeTZO
        UjY3amVYMUNzZEw4VW9HUHh6T2JEcmVGalA0VXFnTmpDN2FrRS8wSytoSDFBcExG
        aUcxU1pXRHd2anQ5RmgwWk9US2NsTjMzZHpYOU0wVzdLQUtKeTY1OWZTR1lFQUFL
        Mm5vYnlvblFHSXB2cjY4Y3FKWmtvMkdwU1BFTjNTcWhaY1hPSGxkZno2SWgwMFJK
        clVwMGxDMSt6aFpYbUVlTHhQbjF2YW1kNnRxREJWckwvVzFzbkpNUEZsZEhUQQpZ
        R3ExaVVtTnZENHpYdnRnRkZweHhBZXBvRDJoTlM0RHZ1dkx0QkQ2amFNCi0tLSBP
        M21lS1Y1Rkxqc2Y3Mmd4YklJZHZQay9EdVQyMkI0TXYyMHJ3bVEvSnVZCrrUI3V1
        rNcCzhnckr2sZhdpL/ldi8dpvo+GRVcpvo9zaUf3wQopcZqNXrfxmMGrUsBZKXgu
        hmYwm7iYnuZW6SU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T20:28:40Z"
  mac: ENC[AES256_GCM,data:naG+NMDK5ACvuAIeUvDSnuCNKB9ZnGfGpvASmbprjQwyfgCxEbPJ1VTI1aq4BC17Iy3+30vhI0/gGtlHModC0a3e0fBmJhhedtjeu5ozwpGJxl7I6tsXzGER6Qg2gX0ASmgo0HMG0dRACRZaNDT3ZFLFLGf5/Vbq9FDQS6bDe6w=,iv:Gw1YWic00by2yj0A+wvmo2LBGjpBA8Q4CmRvtDa0bfw=,tag:FUztKGXulMvQ1cKNDV4M6Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: lldap-pg-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: auth
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: auth
stringData:
  username: ENC[AES256_GCM,data:5pMZuVQ=,iv:K97PIt79KDFi3lus30hdcNylMtH411NjLLFK7ClM/64=,tag:zBUR/ZSfikUde1pgME/C5Q==,type:str]
  password: ENC[AES256_GCM,data:i2IpcO2GwuDx8nlutB8x5wCR9jI3NdVKeHezDIQvJJ8=,iv:agkW0419EY9L3r1otPqXgeFnwsJnZf0Bdhtlj71sXyY=,tag:QUBJvVNS6Rvomvhwqr/Esg==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:N5N1KprxYB2Th5NZFr8HjspAiy8KyTsHz5RR1qTfWD0M7adC3dQa8rSB9WE7T/Ks4qPGirinpN0I0E2cdp2qPVdzv4eTSoyV9FmLcqM7Wpc0Do8wL3noeuMvalYTDoWqI+CBTA==,iv:gVk3yKbbRcR830PAPEI4OLtOZGaObhEgAMu9aj4xUs0=,tag:OLTQHGzTeWE+c+wiZtSsdg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCamFWTTBZTjh4RlZhSlhN
        VlFiNjRPUzQycGdzdDF4L3hxOEpWclI3blhFCmJ0azB4MkpEbVRDdWpwcTl6UVpW
        bStWZmhvTlc1MmhTa2tnRHBjcXhjYncKLS0tIGhvRmM1eVVXMW14NlVXTUN5YUNj
        UUNKVlZVQ2dvSUNHSnFsUjEwUjlYSG8KU5u9AzHlb/xPAJAJh0MDNvbOF7uEkGm6
        ClrLovzJ6U4gPGlCqpKJ/sg+AaXKP+O0yk/AH+45ErTM75MQuf6mvQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGpodkZMQ0dK
        Z05nN2FzVmNiaEFRTXBZa0ZMSXVPK2F2a1BscDU3cXdPVmxXa0pwNGEyNC9Rb1dv
        ZWJzNG5GTFIyYlZKd0VUN0ZxQlB1eExPU0ZsU0VGdnB3WHlTcDFPd3Z1VkNBRG9G
        eExIWFYzcW5RZHA1c1JSaS9lTk54UG9oMzRQKzJYK3poNW1iQk85Tlc3NFd1Y2hU
        Z1N0QVRqQ0NOVXJSNWgrelVYNXl2VmMrbFp0N0kxUU40bFJaL2cyd2pvaGF1Q0NT
        ZFhma1dCbWp4dUlsYXR6OURGL2VocjlCTUtkTkNWWnJySTlhbUZSUmkvdXc2U21k
        MDRFZ2tTOHRwRzNRb2VGWnJyY2s1dndubi9JamZqbkFObytBMGJmZmFRMWtwTEY4
        WmtmTjRoYUVoNTlVd2F3WXRVcWxRKzRndjRCczByblZEU1NKNURvZ3lTQ0VSNmdB
        M2xWRG80aGhXdHl4SjJHdS9Hb2tRaWg5UTlXTTZLS3VaUkFjRHkrZnNRaVVtOVVV
        Z2lxVXNFOEFWazRWVVFHVCt0bkk1NkpQQm9nY2RwY00zN1ozQUZyVmxIZnJ3S3Zj
        SUtVbUsrOGxiYlRIdFlhelYzdDJUZE9LaEs5N3dFRVQ5WlpTdVY4MnRaSld2ckZ2
        SmRZcGFSek43VXM2ckRoK2VadlNCWVJxdmR1ejM4d0V1L3l3YjhPL2YrVlczTnFV
        NlFkbVR6S08weEJEd3BDWEhQT0NGcS9nVi9oYzlLTFg3T2FtN1dKdVBhRk5zR3Qy
        OXNxcTBhdDQ5YUY0QkllOUE2c1p2d09IK0dXQTJCQ2MwbXJCSXlnYnNGeklyRisz
        eW1ZRDBXc0R4T3c0S1cxNzREalg3b0RHZTNFVEFoL1JjRncyc3JIZlpxdE9DOUNw
        MEdpRjNlQS9NeFhZLzh2WWE4YnhwZmEvWWxneXFTM0pPSm5zNDRnWGpVcDZpL3Q3
        RDVUOGFHRjk0T1JSREhoL1JEY0NPZ3JJQXF4dUR3a3M1bTdQWWpIRGpCcVZsYnls
        YkRnL1BKUDdBb3g0ZXJYVnhUbmd6K3pJYm03cVUvc2UrdSsrNlRiLy9WWFo2b1Uz
        K2RIOGIvTGoxNlh2STFRSTJpY2MyaDhvZzNHNzhTTktuRUplbGViWjA4YkM1UjJK
        T2JZUC9JVGlZQTVuMEhTWmtXY3Y4NkhDaHh1aklscVlMTC9vb0ludjdQSGxWSXIv
        L3k3eHVEWVY5bDZra0FDaWNNUmZwbFdWS3RLWmUzRnl3cDhOcnZGN2N6cHptTys3
        Y2RsVjU2ZTV6UTdCU2I5SHRsM1BxUnYzK3RUMEhjMmVVUEE3YWxsdmh0TlAxeXBB
        djJBd3ZWU1cxT25pOWkzREZ6U0tFcXRyRWgwQ01qZ01vZkR6WFlWQklmeHE4UmZY
        ckxYMDh3Z3cyQVVrTlhQNkJqUHhMT1IzV0N2U3k0YVc2VTYrTEVKeWMvK25VZklS
        VFhTTnJ2c0RLVDAwdFFoSTN0eWZPVDRyVFJMamN4WVR5RHhjRURHL3lub3JkenlF
        djRDdHd0T1hoSFRiamI3VUF3dktnWDJQeDJHTHdvUG90T3lWV0RKSlV2MEc5WTM4
        ZGROS1dMZHhTYkZCYktUZGtLbGZjakxjLzNTeVlZN0NVV0hoQUVRVHk2emxVQ1ps
        akRVdENqTHB5eDA3SlhaeWZPL0Qxd0dVeW9mNGpzb0JPS2ZIcWhRNFVqdzljeTZO
        UjY3amVYMUNzZEw4VW9HUHh6T2JEcmVGalA0VXFnTmpDN2FrRS8wSytoSDFBcExG
        aUcxU1pXRHd2anQ5RmgwWk9US2NsTjMzZHpYOU0wVzdLQUtKeTY1OWZTR1lFQUFL
        Mm5vYnlvblFHSXB2cjY4Y3FKWmtvMkdwU1BFTjNTcWhaY1hPSGxkZno2SWgwMFJK
        clVwMGxDMSt6aFpYbUVlTHhQbjF2YW1kNnRxREJWckwvVzFzbkpNUEZsZEhUQQpZ
        R3ExaVVtTnZENHpYdnRnRkZweHhBZXBvRDJoTlM0RHZ1dkx0QkQ2amFNCi0tLSBP
        M21lS1Y1Rkxqc2Y3Mmd4YklJZHZQay9EdVQyMkI0TXYyMHJ3bVEvSnVZCrrUI3V1
        rNcCzhnckr2sZhdpL/ldi8dpvo+GRVcpvo9zaUf3wQopcZqNXrfxmMGrUsBZKXgu
        hmYwm7iYnuZW6SU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T20:28:40Z"
  mac: ENC[AES256_GCM,data:naG+NMDK5ACvuAIeUvDSnuCNKB9ZnGfGpvASmbprjQwyfgCxEbPJ1VTI1aq4BC17Iy3+30vhI0/gGtlHModC0a3e0fBmJhhedtjeu5ozwpGJxl7I6tsXzGER6Qg2gX0ASmgo0HMG0dRACRZaNDT3ZFLFLGf5/Vbq9FDQS6bDe6w=,iv:Gw1YWic00by2yj0A+wvmo2LBGjpBA8Q4CmRvtDa0bfw=,tag:FUztKGXulMvQ1cKNDV4M6Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
