---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      tailscale:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        serviceAccount:
          identifier: tailscale
        containers:
          app:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.82.5@sha256:9a1f2640beecac3ad42ed8ef03d75adcb7165600f5131b17f9a2a3da68505928
            env:
              HOME: /tmp
              NO_AUTOUPDATE: true
              TS_ENABLE_HEALTH_CHECK: true
              TS_ENABLE_METRICS: true
              TS_EXTRA_ARGS: >-
                --advertise-connector
                --advertise-exit-node
                --advertise-tags=tag:k8s
                --advertise-routes=192.168.1.0/24
              TS_STATE_DIR: /tmp
              TS_USERSPACE: true
            envFrom:
              - secretRef:
                  name: tailscale-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 9002
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
    persistence:
      tmp:
        type: emptyDir
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
    serviceAccount:
      tailscale:
        forceRename: tailscale
        enabled: true
