# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-secret
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:dWsueGw77tLWxJ1Jl3AHcrhwkdCzBaTNc+BGnH31CuEviVoXz9a6vURuuDAS82OEMvHIpTzFuhbhNDxmWg==,iv:dguDqJWwEIVYiIO85KGcCt/zYy4zZ4A8aruI4Y+NFG4=,tag:bOVjgt7JcBMETHR/Muw2Tg==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UWVudk4reVpIT3VDSXFl
        aFJ0bzNmdHJTa0N2RmhYcTRJd01vK29DSFNzClpiR09oQjNsZFhDV1RUUXpONnI5
        eWNXU0xlbzUyMXhnbzFod0hxWG9YaE0KLS0tIE5jN0I3bDdxODE5UmUzT1Q2YnFV
        NCs5ODkvN2VlS3dEbEZ2aDJiWVFxc0UKasABkWCcSM89TZ3JrGRVCWGtyGXaGP5D
        imHFMt4wsz6sD9fFU5+SRAxXQkhF0flyEBIfNxxVsfbzjvVNY09TCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T21:00:41Z"
  mac: ENC[AES256_GCM,data:ieQoRrK68Q7N8ID85B7mmdVpuNEbUhSANFppf0V6Y/zdjB88AJ5qBU9sBP+joJAL4yAA1vCon8kC+o+Fci7v8/3V05P08gy5XtidU/hNPXj0t1Nf2lNrNfhSJKkw7Tbw8H2WiYCWxMZPO2IunFc1//cqTu+qsNEbgqByA7DP/B0=,iv:Lbc6j8W2d9MucazOK+zMzoKxNPPeXf7SaztC49EKKws=,tag:TJ8PeksRyBDb7dCv80+SHw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
