# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:U1G68B51Z6i0WnyHDPbc2gitMwBeKL1iwlCQYUn2+l8=,iv:bh8KGytXBW7lvE6hcA/HV6WBn0w902ByBNbnDEJsSm4=,tag:QCxfCXE3sB63YzG4pb9X9Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDg4THhhMnpz
        b2hTSFFRaEF4NkdwRWlrSmdQWlZqNVBneTdZOUhNenBxZGJQUmZYWlFMcEZySE5Y
        N0VtVnFGajF5bm9BVlN3SEVaK29EWGNrR0JKZFUrOThoMUROYXBrMHpHTkZtYVBq
        UE1Mbm9EV21JUE5COXlkeDJGcW1FRzZlOTBUVXZCSWVpZVJLR1FsaWV0aW53ZGJa
        YUlXMkQ2TjA4QzgreTZ0VFBqbzlVckROMTVJOXZZL08xdklzNW1rYWFHcVFLb05V
        SWFQa296Nnd2akxpdTFNNzBEZHBUMGl5TkhxVHNRUkx6eHBENzc4VTNEZGx6anlX
        R1lLaHZYM1NlWmZwQkFveFo1Snl5TXdYei82MnRNeXFFMlYvc2NNbVRFbEZMU1Bm
        aEJISjJud01xL1ZvTzZpanVHVkF3aHRLMXBSL2ZZRmhDaXJ0Q1BSSTN4TUY1Q1dm
        T09BaTRnZVNtc0pleG5ZWHVjbHQwVEpIdHVrQm5mSEVRRk16V1ArRURmbTZyK0d2
        ZWFOL2NvQTFnM3RoZzBiTWlqOWQ4aEdDM1JMcVl3a2paR0dXMXJNL0xKblBJbmoy
        eWplcitOcmpMVWVNSloxTVcxTWJzUFN4RThRMkNxejcyMFF1dlZldXEvMnBBbmZH
        VTJyQnNxc3lKaForYlltdVhlODFUNXJmdlRVZVlqOUo3VC9ZNXFSUk4xK3ErZWp0
        a1E4YitqcDdRMjhzVUEwWkl3amF3RU5CMGk4ZGJFYk53SHZCL05vYlF3eTIvTDZN
        citiZHBnRHZVYUN2T3NlRnJMMzNlUG5zU1I5d1phVmZFVFA0UFZHd0hMTmhmZ2tz
        RWpqSUZ5YjhUWnYyVldxVXN3SXVhcWFNbEkwdnFYK2tjSnhFU1hLQklia0MzUE5R
        WWdITGhSS1ZXaXl4c3pGZk9OazIwSHd0MWZWRld2b2JkcjR5cHdVZUZVaXJGWk45
        dWhKdlpvK09ka0QzR1Zod1VTTEZ2SldPK3l6SkQ3UUlYemloZG8rMmNlWjU0Nmt2
        b3dSbVh1MFBFUmthMFlaSFpjZGJwNFZZWHZ6SUlGcDRndFdNSkVqK3p5UnZIZWFL
        TXl0MUIwR0pOYUhaVDlOdWJCQkVlQ1JBSDF3T0hXclppMkU0VFNyUG9BZEdtTURC
        aUhpVk9YZVc0dnRPSW83NzlnWkxLc2NxVWdyWkh6cWMxOFVKdkQwWVordVdPYlJP
        TUgyem5UUHZyZmg4TS9lZkNxSFMvdHNRS2FjU29GalQvNzh2VUlYcmNmRTBKSTl6
        eWErRFVIUFdmOHVoTVd1RGFYTDd2K3hMNFlFeDdLUDZQemlxa25aTnNrb1hpQVlD
        bSt4RU8rbmhpU0wvNDNDWnRYRjlxalVwVU5VTVJIeXhmTzd6UXc4QmpCZGkwcU0z
        T2dobnROaEdjb2tZQW1TVjBKbFJoaWNJR0JiaFpuVDNuMWxsZ0oxWHRpSjFKSVdt
        alRXN0lSc21zRDk3TVhsSTE0YmpBZjZGcXJtb2JiVE5FWER3WWZhQVNJZDVQSmVQ
        Y1l0NmpVQjhuSlVmVkR1eUV5UUJJRmI2VnpRZmR3Unp5NlF1b0ZrOFRQdU0rV3pN
        V0VXTDQ2M0dEbFZBNmpJNEQ4MFVrb1F1RG5GL3UvRGJtS0VwUDNrRzBZZnBOOVAy
        QnlrOXFZcnJNbS96S3VCcE1adXpLRUMwdys4THcxZk5LbS94QXlvTmRZYnZxUE9R
        VXdBNm9iQ0NkZjBGRFZWSGEzOXVCZ2pOTjFjN2FrTkNuMEFGTXI2NE1HZEdNS0pP
        NktFVktlMENVNmhmQTczZWd2S0tFRTMxR0hDdTdzT0JjZ2ZJdjB3VkM0dEtJT20v
        L3JoWnNjNzdndHp3OXZvVTc4VFVndlJEemFlM0FFWDBWSW1hYTliNTNzVERONkZN
        RkFrNlRPcUVhNEFjOHZsMlk3a0tQM2FOTWZCNnpEODc4Tm43ZDZpQXlrdHlCZwpp
        TVdsbTRmZ21ncGRHc2pUbjNnMHE1SkxhRXBuOHZFaldQS3czZ3Z1cFZBCi0tLSBB
        QWg0am1NQVYxUzRFUWI1UzdSZWRXaXpVNmh6bVNCaGtNZnJzdVA0ODlJCn242EJn
        yUsMqlwpPUB/klNyJDFKXMv9t6zTlrolA3Du0nQEEG6r7MYrFwxatKFVSiEzKBQb
        PhfD7xL6u8VWYYo=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T20:08:34Z"
  mac: ENC[AES256_GCM,data:ATJre8KspgPQIMke/MoGit7nnFQUwT/REYolzyNUep8RieT8FpImworFsHbupJZ/wTsnp/QRETdxIiS92677rzOtYdpkHvPhRMiqjLNW5FWaFWS8k2GUw/T1abQhopdcEvhjSrvrZFT5Dr9F0nLHHWP8QcaqpF85s3B0MUsMoOU=,iv:b3BZtl9ouizpFFlgtdWkVkqv6J4gq69OXXDgMe7XX2M=,tag:7LFrCb1hi7S4gyPmabJv4A==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
