---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app matrix-continuwuity
  namespace: flux-system
spec:
  targetNamespace: social
  components:
    - ../../../../components/volsync/cold
  postBuild:
    substitute:
      VOLSYNC_CRON_LOCAL: "10 23,3,9 * * *"
      VOLSYNC_CRON_REMOTE: "40 3 * * *"
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: rook-ceph-cluster
      namespace: flux-system
  path: ./kubernetes/apps/social/matrix/continuwuity
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app matrix-livekit-jwt
  namespace: flux-system
spec:
  targetNamespace: social
  postBuild:
    substitute:
      APP: *app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: matrix-continuwuity
  path: ./kubernetes/apps/social/matrix/lk-jwt-service
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app matrix-livekit
  namespace: flux-system
spec:
  targetNamespace: social
  postBuild:
    substitute:
      APP: *app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: stunner-config
      namespace: flux-system
  path: ./kubernetes/apps/social/matrix/livekit
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sable
  namespace: flux-system
spec:
  targetNamespace: social
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/social/matrix/sable
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  timeout: 5m
