---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ocis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      ocis:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.2.0
            command:
              - /bin/sh
              - -c
            args:
              - |
                if [ ! -f /etc/ocis/ocis.yaml ]; then ocis init; else exit 0; fi
            env:
              OCIS_INSECURE: true

        containers:
          ocis:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.2.0
            env:
              # DEMO_USERS: true
              # IDM_CREATE_DEMO_USERS: true
              OCIS_INSECURE: true
              OCIS_LOG_COLOR: true
              OCIS_LOG_LEVEL: info
              OCIS_LOG_PRETTY: true
              OCIS_URL: https://files.${CLUSTER_DOMAIN}
              # PROXY_DEBUG_ADDR: 0.0.0.0:9205
              # PROXY_HTTP_ADDR: 0.0.0.0:9200
              PROXY_TLS: false
              # STORAGE_USERS_OCIS_ROOT: /data
              # TZ: ${TIMEZONE}
              # Authelia OIDC
              # Auto role assignment:
              # docs: https://doc.owncloud.com/ocis/next/deployment/services/s-list/proxy.html#automatic-role-assignments
              # OCIS_OIDC_ISSUER: https://auth.${CLUSTER_DOMAIN}
              # PROXY_AUTOPROVISION_ACCOUNTS: true
              # PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none
              # PROXY_OIDC_REWRITE_WELLKNOWN: true
              # PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
              # PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: groups
              # PROXY_USER_OIDC_CLAIM: "preferred_username"
              # WEB_OIDC_CLIENT_ID: ocis
              # WEB_OIDC_METADATA_URL: https://auth.${CLUSTER_DOMAIN}/.well-known/openid-configuration
              # WEB_OIDC_SCOPE: "openid profile email groups"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: ocis
        ports:
          http:
            port: &port 9200
            primary: true
          metrics:
            port: 9205
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: metrics
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${CLUSTER_DOMAIN}"
        hosts:
          - host: files.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
    persistence:
      # config:
      #   type: configMap
      #   name: ocis
      #   globalMounts:
      #     - path: /etc/ocis/web.yaml
      #       subPath: web.yaml
      #       readOnly: true
      data:
        # existingClaim: ocis
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: local-hostpath
        globalMounts:
          - path: /etc/ocis
            subPath: config
          - path: /var/lib/ocis
            subPath: data
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
