---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ocis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cloudflared
      namespace: network
  values:
    controllers:
      ocis:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.1.1
            command:
              - /bin/sh
              - -c
            args:
              - |
                if [ ! -f /etc/ocis/ocis.yaml ]; then ocis init; else exit 0; fi
            env:
              OCIS_INSECURE: true

        containers:
          ocis:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.1.1
            env:
              DEMO_USERS: true
              # NOTIFICATIONS_SMTP_HOST: smtp.${CLUSTER_DOMAIN}
              # NOTIFICATIONS_SMTP_INSECURE: true
              # NOTIFICATIONS_SMTP_PORT: "25"
              # NOTIFICATIONS_SMTP_SENDER: "ocis@${CLUSTER_DOMAIN:=fnord}"
              OCIS_INSECURE: true
              OCIS_LOG_COLOR: true
              OCIS_LOG_LEVEL: info
              OCIS_LOG_PRETTY: true
              OCIS_URL: https://files.${CLUSTER_DOMAIN}
              PROXY_DEBUG_ADDR: 0.0.0.0:9205
              PROXY_HTTP_ADDR: 0.0.0.0:9200
              PROXY_TLS: false
              STORAGE_USERS_OCIS_ROOT: /data
              TZ: ${TIMEZONE}
              # Authelia OIDC
              # Auto role assignment:
              # docs: https://doc.owncloud.com/ocis/next/deployment/services/s-list/proxy.html#automatic-role-assignments
              # OCIS_OIDC_ISSUER: https://auth.${CLUSTER_DOMAIN}
              # PROXY_AUTOPROVISION_ACCOUNTS: true
              # PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none
              # PROXY_OIDC_REWRITE_WELLKNOWN: true
              # PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
              # PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: groups
              # PROXY_USER_OIDC_CLAIM: "preferred_username"
              # WEB_OIDC_CLIENT_ID: ocis
              # WEB_OIDC_METADATA_URL: https://auth.${CLUSTER_DOMAIN}/.well-known/openid-configuration
              # WEB_OIDC_SCOPE: "openid profile email groups"
            envFrom:
              - secretRef:
                  name: ocis-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: ocis
        ports:
          http:
            port: 9200
            primary: true
          metrics:
            port: 9205
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: metrics
    ingress:
      app:
        className: internal
        hosts:
          - host: files.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      storage-users:
        type: nfs
        server: &nfsServer ${NFS_SERVER_IP_ADDRESS}
        path: &nfsPath /mnt/nfs/backups/data/k8s/ocis
        globalMounts:
          - path: /data
            subPath: storage-users
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 20Gi
        storageClass: openebs-hostpath
        globalMounts:
          - path: /etc/ocis
            subPath: config
          - path: /var/lib/ocis
            subPath: data
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
